### ISSUE TITLE
GUI doesn't support Edge Actor in VTK 6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#174]
```
In vtk6.x SetInput should be replaced by SetInputDataObject in gui.py

see

http://www.vtk.org/Wiki/VTK/VTK_6_Migration/Replacement_of_SetInput



```

Original issue reported on code.google.com by `mesheb82` on 11 Feb 2015 at 9:13

**Comment by SteveDoyle2** [comment]
The code doesn't crash anymore with VTK 6, so the ticket is closed, but we're opening new ticket in for the edge actor in #187
