### ISSUE TITLE
Support for OUGV2

### ISSUE THREAD

**Issue by nilswagner** [SteveDoyle2/pyNastran#185]
NotImplementedError: 'OUGV2'

**Comment by SteveDoyle2** [comment]
The issue is due to using SORT2 instead of SORT1, so switching your result to SORT1 will make it work.  From all the models I've seen Nastran puts op2 data in SORT1 format regardless of if you requested SORT2 or not.  

Can you attach an OP2 and the corresponding BDF?

**Comment by nilswagner** [comment]
I'm sorry. The op2 file is confidential.

**Comment by SteveDoyle2** [comment]
Can you make a 2 element OP2 problem with the table.  I don't want one over 50 KB.

**Comment by SteveDoyle2** [comment]
this has been added to v0.8
