### ISSUE TITLE
Surface normals of elements?

### ISSUE THREAD

**Issue by Ravi2015** [SteveDoyle2/pyNastran#191]
Hi Steve & others!

I was wondering if there's any builtin function in pyNastran that gives the surface normal of a 2D element, such as CQUAD4?

Thanks in advance :)

**Comment by SteveDoyle2** [comment]
Yes, 

Also, in order to help others (since I'm closing this), please see

https://groups.google.com/forum/#!topic/pynastran-discuss/52RMXtTxq7Y
