### ISSUE TITLE
Grid Point Forces Issue

### ISSUE THREAD

**Issue by Buran1988** [SteveDoyle2/pyNastran#192]
Hello Steve,

I was wondering what happened with the feature that fetchs grid point forces data from OP2 in version 0.7. I was using that feature in pyNastran 0.6 release where it worked pretty good. I've got sample op2 file that is generated by MSC Nastran with GPFORCE=ALL option, but pyNastran parser can't find any grid point forces data in it . 

Could you please advice if there has been changed something in handling of grid point forces data so I could update my end-user code?

Many thanks in advance,
Nikita

**Comment by SteveDoyle2** [comment]
It should work.  Can you attach your bdf and op2 model?

**Comment by SteveDoyle2** [comment]
ohh...I see the problem.  The variable name got changed.  I'll push a bug release soon.

**Comment by SteveDoyle2** [comment]
the bug is fixed in v0.7.2
