### ISSUE TITLE
PSHELL zero thickness issue

### ISSUE THREAD

**Issue by Ravi2015** [SteveDoyle2/pyNastran#193]
Hello again!

I'm getting an error from pyNastran (v0.6.1) when reading a FE model which has a few PSHELL cards with thickness =0!
PyNastran seems to want a thickness value>0

Luckily, my model had only two such cards and it was simple to correct by giving a very small positive value (0.000001)

For sure, this is not a major issue, but would it be ok to just check that the thickness value is greater than OR equal to 0 instead of strictly greater than zero.

**Comment by SteveDoyle2** [comment]
That is the intended behavior.  The requirements for read_bdf are such that you have a valid nastran deck.  The reasoning being that errors like this is error messages are poor at least with MSC Nastran and it's a lot easier to find errors by forcing these.

If you have a BDF that shows the PSHELL thickness of an element as 0.0 that runs (e.g. the solid_shell_bar example), I have no problem changing the requirement.  I made a quick test and it failed.

**Comment by SteveDoyle2** [comment]
pyNastran no longer requires thickness>0.  However, if a thickness is defined, it must be >0.  Leave it blank if you don't want that check.

This behavior is necessary for when you have thicknesses defined on an element-basis (e.g. CQUAD4) instead of the PSHELL.
