### ISSUE TITLE
All cards of a particular type

### ISSUE THREAD

**Issue by Ravi2015** [SteveDoyle2/pyNastran#194]
Hi,

I'm using pyNastran v0.6.1 on Windows 7.

In my code, I have to find all RBE2 elements and check whether they are connected to a CBUSH element, etc.

Currently, the way I find all the RBE2 elements is to loop over model.rigidElements items and then check if the element type == RBE2

However, I was wondering if there are already some lists that contain all the cards of a particular type (in my case, I would be interested in all RBE2 cards/ elements). If such lists exist, then I could just use those lists directly instead of searching through all the model.rigidElements or model.elements items.

By the way, congratulations on releasing pyNastran v0.7!!

Thanks in advance and kind regards,
Ravi

**Comment by SteveDoyle2** [comment]
There is no way to do what you're after other than what you're already
doing.

That's been asked for multiple times.  It needs a better solution.  I'll
figure it out.

**Comment by Ravi2015** [comment]
Ok, thanks for the clarification Steve :)

**Comment by SteveDoyle2** [comment]
In the master branch there is now a function:

card_dict = model.get_cards_by_card_types(card_types, reset_type_to_slot_map=False)

where card_dict's key=card_name; value=list of cards of that card.type.  It stores the IDs as part of the setup step and shouldn't impact memory much, so it will be fast calling it once or in a loop,

It may change slightly (e.g. API), but should be more or less done.

**Comment by Ravi2015** [comment]
Excellent!
