### ISSUE TITLE
renumbering entities: false unassociated properties and RBE 

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#196]
renumbering entity IDs has two problems:

1) RBE2 and RBE3 elements do not reflect changed grid numbers

2) after changing property & element IDs, in the output cbf file, these properties and elements are grouped under "ELEMENTS_WITH_NO_PROPERTIES" and "UNASSOCIATED_PROPERTIES", even though the cards reflect the correct numbering.

I attached an example file. The script renumber_test.py reads in the bdf file "before.bdf", renumbers the grids, elements, properties, materials, and coordinate systems, and writes out "after.bdf". The desired result is that only the entity numbers would change. However, diffing the files shows that the two RBE elements did not get the updated grid numbers, and the elements and properties are put under sections indicating that they are unassociated.

I did not check MPC cards for updationg, but I expect them to fail as well given the RBE behavior.

**Comment by SteveDoyle2** [comment]
Are you referring to the pyNastran.bdf.bdfInterface.dev_utils.bdf_renumber function?  That's a known deficiency, but I can certainly add them.  Also, the script and example are not attached.

**Comment by jeffrey-guy-lyon** [comment]
Sorry I will attach the example when I get to work Tuesday. 

I was renumbering entities by directly setting the id like (in this case for a grid):

GridObject.gid = 12345

This seemed to correctly update the associated elements, but not rigid elements.

**Comment by jeffrey-guy-lyon** [comment]
Steve,

Attached is the example that goes with issue #196 (renumbering entities).

Thanks,
Jeff


------------------------------------------------------------------------------

Notice: This e-mail is intended solely for use of the individual or entity to which it is addressed and may contain information that is proprietary, privileged and exempt from disclosure under applicable law. If the reader is not the intended recipient or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. This communication may also contain data subject to U.S. export laws. If so, that data subject to the International Traffic in Arms Regulation cannot be disseminated, distributed or copied to foreign nationals, residing in the U.S. or abroad, absent the express prior approval of the U.S. Department of State. If you have received this communication in error, please notify the sender by reply e-mail and destroy the e-mail message and any physical copies made of the communication. Thank you. 
********** **********

**Comment by jeffrey-guy-lyon** [comment]
github stripped the attachment in the comment above. How can I get you the example files?

**Comment by SteveDoyle2** [comment]
Just email it to me :)

I'll add it as a test.

**Comment by SteveDoyle2** [comment]
I updated the rigid elements the other day to cross reference nodes, so if you pull from the master, the node ids on the RBEx will update properly.  I still need to update the SPCs and MPCs to cross reference, but your example works as is.

In terms of writing the BDF, you should be using:

    mesh.write_bdf('after.bdf', interspersed=False)

to not get a confusing output file (e.g. a PROD associated with a CTRIA3 element or missing properties).

**Comment by SteveDoyle2** [comment]
see #199 and #200
