### ISSUE TITLE
CONM2 card error

### ISSUE THREAD

**Issue by 4evar** [SteveDoyle2/pyNastran#201]
If I pass in a list to BDF() to generate a CONM2 it skips 9th item in the provided list for example ['CONM2', 11, 12, 13, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0]

test = BDF()
test.add_card(['CONM2', 11, 12, 13, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0], 'CONM2')

The printed card is:
CONM2         11      12      13     14.     15.     16.     17.
                      19.     20.     21.     22.     23.

I was expecting something like this
CONM2         11      12      13     14.     15.     16.     17.
                      18.     19.     20.     21.     22.     23.
Is this the correct behavior?

**Comment by SteveDoyle2** [comment]
Yes.  Per the QRG, the CONM2 card looks like:

        +-------+--------+-------+-------+---------+------+------+------+------+
        |   1   |    2   |    3  |   4   |    5    |  6   |  7   |   8  |  9   |
        +-------+--------+-------+-------+---------+------+------+------+------+
        | CONM2 | EID    | NID   |  CID  |  MASS   |  X1  |  X2  |  X3  |      |
        +-------+--------+-------+-------+---------+------+------+------+------+
        |       |   I11  |   I21 |  I22  |   I31   |  I32 |  I33 |      |      |
        +-------+--------+-------+-------+---------+------+------+------+------+

As you can see, the first line of the card has a blank in it.  That is where your 18 is.  You need to call it like:

test.add_card(['CONM2', 11, 12, 13, 14.0, 15.0, 16.0, 17.0, 18.0, None, 19.0, 20.0, 21.0, 22.0, 23.0], 'CONM2')

**Comment by 4evar** [comment]
Ah understand now! Thanks for the help and great job with the library.

**Comment by SteveDoyle2** [comment]
Just a note.  This didn't exist at the time, but there's a much better way to create a CONM2, which is:

    test.add_conm2(eid, nid, massi, cid=0, X=None, I=None, comment='conm2')

This sort of capability exists for almost every card.

**Comment by SteveDoyle2** [comment]
not an error; changing the "milestone"
