### ISSUE TITLE
NX Nastran has differences with MSC Nastran

### ISSUE THREAD

**Issue by SteveDoyle2** [SteveDoyle2/pyNastran#202]
There are cards/formatting rules in Nastran's BDF and OP2 that differ across Nastran versions.  Per dev discussion with Jeff, the API has been hashed out:

    model = BDF()
    model.set_as_nx()
    model.set_as_msc()  # the default
    assert model.nastran_format in ['nx', 'msc'] == True
    model.read_bdf()

Alternatively, in the BDF at the top, set:

    $ pyNastran: version=NX
    $ pyNastran: version=MSC

which are case/space insensitive

For the OP2:

    model = OP2()
    model.set_as_nx()
    model.set_as_msc()
    model.read_op2()  # if nothing is set, it will default to msc, but try nx if it fails

ONLY NX and MSC are supported as they're the standards.  Radioss and smaller distributions are explicitly not supported, though they could be wrapped such that they'll work.  Radioss is a alternative that could be added, but until I have access to 1) the QRG and 2) an executable, it will not be in the official code.

**Comment by saullocastro** [comment]
@SteveDoyle2 Is this the last issue in the milestone for v0.8?

**Comment by SteveDoyle2** [comment]
It's not perfect, but is fairly good.  This ticket wasn't about perfection though, so I'm closing it.

Really this issue was me being lazy :)  With the latest DMI/DMIG fixes, I'm fairly happy with where it's at.  I'll work on a last push of the BDF/OP2 (running `bdf_test.py` and `op2_test.py`) and finally release it.
