### ISSUE TITLE
attempting to write a bdf created from scratch with no case control fails due to undefined encoding

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#205]
Attempting to run the code:

from pyNastran.bdf.bdf import BDF

mesh = BDF()
mesh.add_card(['GRID', 100000, 0, 43.91715, -29., .8712984], 'GRID')
mesh.write_bdf('out.bdf')

produces the exception:

DEBUG:     fname=bdf_writeMesh.pyc         lineNo=83     ***writing out.bdf
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    mesh.write_bdf('out.bdf')
  File "C:\Anaconda\lib\site-packages\pynastran-0.8.0_dev_no_checksum_error-py2.7.egg\pyNastran\bdf\bdfInterface\bdf_writeMesh.py", line 109
, in write_bdf
    outfile = open(out_filename, 'wb', encoding=self._encoding)
AttributeError: 'BDF' object has no attribute '_encoding'

When defining the bdf, is there a way to define the encoding explicitly?

This is on Python 2.7.9 & the latest dev version of pyNastran.

Thanks!

**Comment by SteveDoyle2** [comment]
write_bdf now has an additional encoding option.  The default=None option will grab the system encoding.  If you just put a utf-8 marker at the top of your python file, then it'll use utf-8 and you won't need to worry about the encoding.  If your encoding is different than that (e.g. latin1), you'll need to specify it explicitly.

**Comment by SteveDoyle2** [comment]
Correction.

he default=None option will grab the system encoding or self._encoding if it was set.
