### ISSUE TITLE
different error now produced when running test case from #204

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#206]
When running the code from issue #204, I'm now getting a different exception:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    mesh.write_bdf('out.bdf')
  File "C:\Anaconda\lib\site-packages\pynastran-0.8.0_dev_no_checksum_error-py2.7.egg\pyNastran\bdf\bdfInterface\bdf_writeMesh.py", line 121
, in write_bdf
    self._write_header(outfile)
TypeError: _write_header() takes exactly 3 arguments (2 given)

**Comment by jeffrey-guy-lyon** [comment]
I think the fix is to change line 121 of bdf_writeMesh.py from:

self._write_header(outfile)

to:

self._write_header(outfile, self._encoding)

**Comment by jeffrey-guy-lyon** [comment]
Sorry, this bug was due to a local change I made. Your code works fine!

**Comment by SteveDoyle2** [comment]
I was very confused for a second :)
