### ISSUE TITLE
writing MPCs using long fields broken

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#207]
Writing MPCs in long field format produces invalid formatting. This worked at some point. Previous revs of pyNastran were tried to see where the breakage occured. It worked at rev 2340, nut not at 2469 (I did not dive deeper than that).

Example:

Desired MPC output (written using pyNastran rev 1993):

MPC*                   1            1000               1              1.
*                      3               1      -90000000.
*                                      2               1       11614000.
*                      3               2  -.000000003885
*                                      2               2       82906000.
*                      2               3       33040000.
*                                      6               1       15917000.
*                      5               1      -22160000.
*                                      6               2       18800000.
*

Output from latest rev:

MPC*                   1            1000               1              1.               3               1      -90000000.
       *                               2               1       11614000.               3               2  -.000000003885
       *                               2               2       82906000.               2               3       33040000.
       *                               6               1       15917000.               5               1      -22160000.
       *                               6               2       18800000.

**Comment by jeffrey-guy-lyon** [comment]
Markdown messed up the example formatting. I emailed you the examples though.

**Comment by SteveDoyle2** [comment]
Thanks for that.  I thought I had the MPCs working with the faster method.
