### ISSUE TITLE
Skip unrecognized datablocks in OP2 reader

### ISSUE THREAD

**Issue by ryakoub** [SteveDoyle2/pyNastran#229]
OP2 file may have a user-defined matrices.  Currently the OP2 reader quits if it counters unrecognized datablocks.  It might be a good idea to just skip them.

**Comment by SteveDoyle2** [comment]
Without knowing it's a matrix, it cannot be skipped.

**Comment by ryakoub** [comment]
can't we assume if it is not one the Nastran datablock it is most likely a matrix?

**Comment by SteveDoyle2** [comment]
That probably makes sense.

**Comment by SteveDoyle2** [comment]
matrices are skipped; we no longer assume they're standard tables

While, this is the same problem, but with the opposite choice made, I'm calling this closed for now.
