### ISSUE TITLE
Fatal error while reading OP2 table

### ISSUE THREAD

**Issue by ryakoub** [SteveDoyle2/pyNastran#234]
Getting the following Fatal error while reading OP2.  The op2 file only includes OES1 table that is written by a DMAP output2 module.

"op2_scalar.py", line 981, in read_table_name
    raise FatalError('last table=%r' % self.table_name)
FatalError: last table='OES1'

**Comment by SteveDoyle2** [comment]
DMAP generated tables are not supported.  Can you post the BDF and OP2?

**Comment by ryakoub** [comment]
how to attach a file?

**Comment by SteveDoyle2** [comment]
It looks like you can only attach images.  Can you email it to me?

**Comment by ryakoub** [comment]
what is your email?

**Comment by SteveDoyle2** [comment]
It's in the setup.py file.

**Comment by SteveDoyle2** [comment]
Nastran is consistently inconsistent.  All standard solutions (e.g. SOL 101, 145, 200) have a trailing marker.  The parser can fairly reliably use that information to determine if a run has crashed (it cannot detect parsing errors, just results).

This deck doesn't have a trailing 0 marker indicating that it finished successfully.  What you can do is:

    from pyNastran.op2.op2 import FatalError, OP2
    model = OP2()
    try:
        model.read_op2('oes1.op2', vectorized=False)
    except FatalError:
        model.combine_results()
    model.write_f06('oes1.f06')

and all your data will be there.  You can't get the data in vectorized format though.

Alternatively, you can create the trailing block.  I don't know DMAP, but all you should need to do is add either a 0 to the end or a 4,0,4.

**Comment by ryakoub** [comment]
what is the vectorized results?

**Comment by SteveDoyle2** [comment]
It's a way of organizing the data into numpy arrays that takes 5x less memory with a ~10% input/output speed hit.  You get the same information.

**Comment by ryakoub** [comment]
Thanks for the hint.  I added EOF in DMAP, now it is reading it fine.

**Comment by SteveDoyle2** [comment]
Can you post how you updated the model?

**Comment by ryakoub** [comment]
add another (final) output2 statement with ITAPE=-9 which instructs Nastran to add an EOF marker, 

OUTPUT2  ,,,,//-9/IUNIT
