### ISSUE TITLE
Error from BDF DMIG card

### ISSUE THREAD

**Issue by ryakoub** [SteveDoyle2/pyNastran#235]
### Error from BDF DMIG card

The BDF issues an error that cj (field 4) can't be blank.  According the QRF from NX Nastran , cj can be blank, i.e. something like:

|  1  |  2  |  3  |  4  |  5  |  6  | 7  | 8  |  9  | 10|
| --- | --- | ---  | --- | --- | --- | --- | --- | --- |--- |
| DMIG | A  | 0    |  9  | 1 |1 | ||1||
| DMIG | A  | 1    |     |   |2 | 1|1.0|||
| DMIG | A  | 1    |     |   |2 | 2|1.0|||
| DMIG | A  | 1    |     |   |2 | 3|1.0|||
is accepted by _Nastran_ but _pyNastran/BDF_ issues an error.  I believe this is a bug.

**Comment by SteveDoyle2** [comment]
Per the QRG:

Cj : Component number for grid point GJ. (0 < Integer < 6; blank or zero if
GJ is a scalar or extra point.)

I read that as Ci / Cj is required if you have a GRID point because if 6 is valid, then 1, 2, 3, 4,5, and 6 are valid (despite them saying 0 < C < 6 because GRIDs have a 6 DOF).  Thus, it only defaults to 0 for an EPOINT/SPOINT.  Is that how you interpret it?

**Comment by ryakoub** [comment]
But given Remark 6.a
If NCOL is not used for rectangular matrices, two different conventions are available: 

◦If IFO = 9, GJ and CJ will determine the sorted sequence, but will otherwise be ignored; a rectangular matrix will be generated with the columns submitted being in the 1 to N positions, where N is the number of logical entries submitted (not counting the header entry). 

I understand it that they can be ignored.  So I see it as a different way the grids can be entered using scalar points if this makes sense at all.

**Comment by SteveDoyle2** [comment]
That's so cryptic.  If I understand that right and I probably don't, the order of the matrix will be the same as the order that was entered, such that if you have two entries that are the same, it'll be written twice (currently it's overwritten, which may be a bug).

Also, does that mean a value of 0 and 7 and 999999 is allowed for a GRID/SPOINT?

**Comment by ryakoub** [comment]
For the first part, yes the order of the matrix is defined by the sequence of the non-header data.  But Nastran doesn't allow repeated rows with the same values.

I am not sure about the second part.

**Comment by SteveDoyle2** [comment]
How about the code requires 1-6 for GRID points and 0/None for SPOINTs/EPOINTs.  I don't think anything needs to be do for the IFO statements as order is preserved.

**Comment by ryakoub** [comment]
yes this is I believe the way it should be

**Comment by SteveDoyle2** [comment]
Oh my mistake from before.  If you have two identical entries, you'll get both, so no overwriting.  I said both options previously...

So, I think this issue is clear now.
