### ISSUE TITLE
OP2 reader should include moments as well as forces for CBUSH elements

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#236]
As far as I can tell, only the force components are read in.

I'm looking in op2.cbush_forces[subcase]

Are the moments somewhere else?

Thanks,
Jeff

**Comment by SteveDoyle2** [comment]
No.  The RealCBushForce and the ComplexCBushForce objects contains a
self.force and self.moment data member.  The op2 attribute
(op.2cbush_force) and class names (e.g. RealCBushForce) refer to the force
table (e.g. FORCE=ALL).

**Comment by jeffrey-guy-lyon** [comment]
Ok! Sorry to open a ticket for a non-existing problem.

**Comment by SteveDoyle2** [comment]
No worries.
