### ISSUE TITLE
Syntax errors in op2_paul.py, test_op4_nose.py, op2.py, painter.py, mathFunctions.py

### ISSUE THREAD

**Issue by nilswagner** [SteveDoyle2/pyNastran#242]
Extracting pyNastran-0.8.0_dev_407f8a4-py2.7.egg to /home/nils/local/lib/python2.7/site-packages
  File "/home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg/pyNastran/op2/dev/op2_paul.py", line 2089
    op4names, op4vars, *_ = o4.listload(op4file)
                       ^
SyntaxError: invalid syntax

  File "/home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg/pyNastran/op2/dev/original/test_op4_nose.py", line 61
    name, mat, *_ = o4.listload(filename, [nm2])
               ^
SyntaxError: invalid syntax

  File "/home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg/pyNastran/op2/dev/original/op2.py", line 2088
    op4names, op4vars, *_ = o4.listload(op4file)
                       ^
SyntaxError: invalid syntax

  File "/home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg/pyNastran/gui/menus/painter.py", line 2
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file

  File "/home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg/pyNastran/applications/cart3d_nastran_fsi/mathFunctions.py", line 2
    fom six import string_types
          ^
SyntaxError: invalid syntax

pyNastran 0.8.0-dev-407f8a4 is already the active version in easy-install.pth
Installing format_converter script to /home/nils/local/bin
Installing test_bdf script to /home/nils/local/bin
Installing test_f06 script to /home/nils/local/bin
Installing test_op4 script to /home/nils/local/bin
Installing test_op2 script to /home/nils/local/bin
Installing run_nastran_double_precision script to /home/nils/local/bin

Installed /home/nils/local/lib/python2.7/site-packages/pyNastran-0.8.0_dev_407f8a4-py2.7.egg
Processing dependencies for pyNastran===0.8.0-dev-407f8a4
Searching for six==1.9.0
Best match: six 1.9.0
Processing six-1.9.0-py2.7.egg
six 1.9.0 is already the active version in easy-install.pth

Using /home/nils/local/lib/python2.7/site-packages/six-1.9.0-py2.7.egg
Searching for Pillow==3.1.0.dev0
Best match: Pillow 3.1.0.dev0
Processing Pillow-3.1.0.dev0-py2.7-linux-x86_64.egg
Pillow 3.1.0.dev0 is already the active version in easy-install.pth
Installing pildriver.py script to /home/nils/local/bin
Installing viewer.py script to /home/nils/local/bin
Installing gifmaker.py script to /home/nils/local/bin
Installing pilconvert.py script to /home/nils/local/bin
Installing pilfont.py script to /home/nils/local/bin
Installing pilfile.py script to /home/nils/local/bin
Installing createfontdatachunk.py script to /home/nils/local/bin
Installing explode.py script to /home/nils/local/bin
Installing pilprint.py script to /home/nils/local/bin
Installing player.py script to /home/nils/local/bin
Installing thresholder.py script to /home/nils/local/bin
Installing painter.py script to /home/nils/local/bin
Installing enhancer.py script to /home/nils/local/bin

Using /home/nils/local/lib64/python2.7/site-packages/Pillow-3.1.0.dev0-py2.7-linux-x86_64.egg
Searching for docopt==0.6.2
Best match: docopt 0.6.2
Processing docopt-0.6.2-py2.7.egg
docopt 0.6.2 is already the active version in easy-install.pth

Using /home/nils/local/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
Searching for scipy==0.15.1
Best match: scipy 0.15.1
Processing scipy-0.15.1-py2.7-linux-x86_64.egg
scipy 0.15.1 is already the active version in easy-install.pth

Using /home/nils/local/lib/python2.7/site-packages/scipy-0.15.1-py2.7-linux-x86_64.egg
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using /usr/lib64/python2.7/site-packages
Finished processing dependencies for pyNastran===0.8.0-dev-407f8a4

**Comment by SteveDoyle2** [comment]
There is not a syntax error, nor is there any plan to fix it.  It is a Python 3-only code that I was given (and the syntax error refers to the backup version), but there is a Python 2 compatible version that works.  It's only a development code anyways and should not be used.

**Comment by SteveDoyle2** [comment]
You shouldn't be using setup.py install on a dev version, which is why you're getting an error.
