### ISSUE TITLE
CBEAM Card has an illegal field

### ISSUE THREAD

**Issue by ryakoub** [SteveDoyle2/pyNastran#243]
the BDF writer writes the CBEAM as

CBEAM      10000   10000  197523  197537     -1.      0.      0.     GGG

which is not accepted by NX Nastran and a a FATAL error is issued.  I have to remove the characters at the end in order for the model to run.  I am not sure if this is a bug.

**Comment by SteveDoyle2** [comment]
It should be fixed as of the latest version.  The default is hackish because the NX/MSC defaults are different, but since nobody uses p-elements, I'm not concerned.  Offt now defaults to GGG for CBAR/CBEAM which is correct and is hidden when writing.  NX just doesn't have other options for GGG.
