### ISSUE TITLE
OP2 readers works in 0.7, doesn't work in 0.8

### ISSUE THREAD

**Issue by ssssOO** [SteveDoyle2/pyNastran#264]
Dear Steve,

I have one OP2 file which is well read in pyNastran 0.7 using test_op2. However I am looking forward to use the export_to_vtk OP2 function in pyNastran 0.8, but when I try to tun test_op2 with my OP2 file I receive the following error message

NotImplementedError: displacementes; table_name=OUGV1PAT

Do you know if there is a way of using the export_to_vtk funciontality right now?

Thank you very much for your work

**Comment by SteveDoyle2** [comment]
I re-added support for OUGV1PAT

Regarding export_to_vtk, I'd use export_to_vtk_filename as that's the one I just looked at and tested.  It only supports models with GRID points (so no SPOINTs/EPOINTs).  I'd aslo be careful about using 0-d elements.  Finally, it only supports real OUG tables (eigenvector, displacement, velocity, acceleration) right now.  

Getting other things like stress or SPOINTs/CAERO panels in there isn't really the highest priority.  There's a loss of information when you change the data format, so I'm not the biggest fan of doing that.  I typically just use the pyNastran GUI and Patran when I'm forced to.

**Comment by SteveDoyle2** [comment]
Additionally, I'm not really sure how to write a VTK file that only applies results to some elements, which is necessary for things like Bar Forces.
