### ISSUE TITLE
op4 sparse real binary reader - reading stiffness matrices

### ISSUE THREAD

**Issue by wrtc90** [SteveDoyle2/pyNastran#266]
I'm trying to read the (l-level) stiffness matrix in linear statics KLL (pull out right before the SSG3 call as sparse unformatted) from an .op4. While loading the associated force vector PLI via op4 read_real_sparse_binary works flawlessly, reading this matrix via

from pyNastran.op4.op4 import OP4
op4rd = OP4()
KLL = op4rd.read_op4('KLL.op4','KLL','double')

yields:

Traceback (most recent call last):
    KLL = op4rd.read_op4('KLL.op4','KLL','double')
  File "C:\Python27\lib\site-packages\pyNastran\op4\op4.py", line 115, in read_op4
    return self.read_op4_binary(op4_filename, matrix_names, precision)
  File "C:\Python27\lib\site-packages\pyNastran\op4\op4.py", line 488, in read_op4_binary
    (name, form, matrix) = self._read_matrix_binary(f, precision, matrix_names)
  File "C:\Python27\lib\site-packages\pyNastran\op4\op4.py", line 611, in _read_matrix_binary
    A = self._read_real_binary(f, nrows, ncols, Type, is_sparse, is_big_mat)
  File "C:\Python27\lib\site-packages\pyNastran\op4\op4.py", line 687, in _read_real_binary
    A = self._read_real_sparse_binary(f, nrows, ncols, Type, is_sparse, is_big_mat)
  File "C:\Python27\lib\site-packages\pyNastran\op4\op4.py", line 753, in _read_real_sparse_binary
    valueList = unpack(strValues, data[0:nValues * NBW])
struct.error: unpack requires a string argument of length 16

Reading a formatted sparse KLL output works flawlessly as well. I gather there's something going wrong with the word size determination during unpacking which I could not fix with my limited knowledge. I'm happy to provide the data if necessary.

**Comment by SteveDoyle2** [comment]
Yeah, I'm not sure.

Ideally what would help me the most is a small test problem, with an included BDF (one of the example models like the solid_shell_bar would be fine), such that I can edit it as well as the OP4 in both ASCII and binary format.

**Comment by SteveDoyle2** [comment]
If it wasn't obvious, I'm bad at DMAP, so making matrices print out is hard for me :)

**Comment by wrtc90** [comment]
Ok, I will try to reproduce it with one of the examples soon! :)

**Comment by wrtc90** [comment]
Here the _static_solid_shell_bar_ bar example from _pyNastran/models/sol_101_elements/_ with DMAP statements for matrix op4 output. The formatted and unformatted matrices are included as well:

[static_solid_shell_bar.zip](https://github.com/SteveDoyle2/pyNastran/files/110782/static_solid_shell_bar.zip)

**Comment by SteveDoyle2** [comment]
That was harder than it should have been.  You had a small-form binary sparse matrix, which apparently hadn't been tested.  I've pushed an update to the latest master.

**Comment by wrtc90** [comment]
Awesome, thank you so much!
