### ISSUE TITLE
add MONPNT1 visualization

### ISSUE THREAD

**Issue by SteveDoyle2** [SteveDoyle2/pyNastran#286]
A vertex for the summation point and AECOMPs that point to AELISTs would work

**Comment by alby3z** [comment]
Is the op2 output read of the MONITOR points supported?

**Comment by SteveDoyle2** [comment]
No.  I'm not sure how to make the MONITOR table show up in the op2.  If you have an example (it's a lot easier to make tables show up in the F06 than the OP2), it'd be easy to add.

**Comment by alby3z** [comment]
@SteveDoyle2 

I am about to contact MSC support to have information about monitor points op2 output.

**Comment by SteveDoyle2** [comment]
You could probably do it with an ALTER; not that I can write them.

**Comment by alby3z** [comment]
I have received the final sentence from MSC support: obtain the monitor points output in the op2 is not possible at the moment in NASTRAN, neither through case commands nor through ALTERs.

I have officially asked to consider the implementation of this feature in the future NASTRAN releases.


Is there any possibility to read the monitor points output by parsing the f06 file with pyNastran?

**Comment by SteveDoyle2** [comment]
I know that one of the Nastran's can do SOL 200 with MONITOR points.  Maybe it's NX Nastran?  It seems like it'd be trivial.

> Is there any possibility to read the monitor points output by parsing the f06 file with pyNastran?

Not with pyNastran.  F06s are just too complicated and are far more than the OP2.  Nastran frequently writes incorrect case information and these errors are different depending on the solution number, and if you have xy plots.  It's 100x worse for SOL 200.  The OP2 is excessively verbose, so you can kind of correct for that.  I gave up parsing the F06 because of that.

**Comment by SteveDoyle2** [comment]
Well I said F06s are too complicated, so I simplified the problem.  There's a trim parser (SOL 144) only.  Structural monitor point loads are supported.

Only took 6.5 years!
