### ISSUE TITLE
OP2: Missing get_stress_mapper table for OES1X (CBUSH)

### ISSUE THREAD

**Issue by watkinrt** [SteveDoyle2/pyNastran#287]
I'm currently using NX nastran to run simulations using CBUSH elements. When I try to read in the OP2 file from these simulations, the oes_stressStrain get_stress_mapper throws a KeyError saying that it cannot find the key (102, 1, 7, 'OES1X'). In looking at the get_stress_mapper method, four keys currently exist for cbush element (lines 610-614 of oes_stressStrain.py): (102, 1, 7, b'OES1X1'), (102, 1, 7, b'OES1'), (102, 2, 13, b'OES1X'), (102, 3, 13, b'OES1X'). I simply added in the line (102, 1, 7, b'OES1X') : ('cbush_stress', RealBushStressArray) to fix the problem.

**Comment by SteveDoyle2** [comment]
Can you push that?

Also, if anybody knows what the difference between an OES1X1, OES1, OES1X, etc. are I'm all ears.  Originally, I thought it was a 2-noded CBAR element vs. an 11-noded CBAR element (or something similar for other cards), but from what I can tell there is no logic.  a I'll leave this an open issue.

**Comment by watkinrt** [comment]
How do I get permission to push changes to the GitHub repository? Currently, I'm getting a permission denied error.

**Comment by SteveDoyle2** [comment]
You need to issue a pull request.
