### ISSUE TITLE
Consider changing op2 reader pandas DataFrame API for static displacement and gridpoint force results to be consistent with transient results

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#292]
Please consider using pandas MultiIndex for op2 static displacement and gridpoint force results. Presently the dataframes for these results are flat and cannot be meaningfully manipulated (added, compared). 

I will email you example code.

**Comment by SteveDoyle2** [comment]
closing due to email discussion
