### ISSUE TITLE
OP2: Reading PSDF table from random analysis

### ISSUE THREAD

**Issue by watkinrt** [SteveDoyle2/pyNastran#295]
How hard would it be to add in reading of the PSDF XY table? Currently, I get the following error:

```
 C:\Users\...\pyNastran\pyNastran\op2\op2_scalar.pyc in _read_tables(self, table_name)
   1251                     msg += 'If you have matrices that you want to read, see:\n'
   1252                     msg += '  model.set_additional_matrices(matrices)'
-> 1253                     raise NotImplementedError(msg)
   1254 
   1255             table_name = self._read_table_name(rewind=True, stop_on_failure=False)

NotImplementedError: geom/results split: 'PSDF'

If you have matrices that you want to read, see:
  model.set_additional_matrices(matrices)
```

I'm not quite sure were to start in implementing something like this.

**Comment by SteveDoyle2** [comment]
I do not currently have examples for that table for PSDF.  Random tables are harder than static/transient tables and pyNastran currently very poorly supports them.

**Comment by watkinrt** [comment]
How do you go about reading in the binary .op2 file to interrogate the table structure? Can you point me to a locating in the existing code that does this?

> Random tables are harder than static/transient tables and pyNastran currently very poorly supports them.

What makes them harder than transient tables? Isn't the main difference just being in the frequency domain instead of the time domain (or am I missing something)? If you output both RMS and frequency response data, I suppose that complicates things.

Thanks again for you help.

**Comment by SteveDoyle2** [comment]
> Can you point me to a locating in the existing code that does this?

I assume that's not a table and not a matrix, so you open up pyNastran/op2/op2_scalar.py and add the table to global variables NX_RESULT_TABLES (line 81) and MSC_RESULT_TABLES (line 118).  Then on line 476 (_get_table_mapper), add **'PSDF': [self._read_psdf_3, self._read_psdf_4]**.

The self._read_psdf_3 and self.read_psdf_4s functions should look similar to pyNastran/op2/tables/oug/oug.py.  The OUG table handles displacement/velocity/acceleration/eigenvectors/temperature, anything with node_id, grid_type, tx, ty, tz, rx, ry, rz. There are plenty of examples (e.g. forces/stresses) so find the one that fits your data the best.  The 3rd record of a results table (self._read_psdf_3) defines the macro parameters (e.g. subcase number, time step, analysis code, variable name (e.g. time, modes, load_step), heat transfer, etc.  

The 4th record reads the actual data.  You need to handle file streaming (e.g. for a displacement/OUG table, if you have 1,000 nodes, you have 1,000*8=8,000 floats.  If the record size is 1000, you'll split nodes exactly.  If the record size is 250, you're going to occasionally get a few entries of the next node on the current block).  The best way is to just kinda look at the code around it, but it's important that you get your record size right by looking at the data and making sure you don't get crazy numbers for something like the node id.

The first step in reading is to size the data (auto_return=True during sizing), so you'll need a results class.  There are many examples (see pyNastran/op2/tables/oug/oug_displacements.py).  The second time through, the data is actually read using numpy.fromstring.

> What makes them harder than transient tables? 

The definition of Record 3 and Record 4 for the OUG/OES/OEF/etc. tables is in the DMAP guide.  I looked in a version of the DMAP guide and PSDF was referenced, but not discussed in detail in the Data Block Descriptions section.  This is where self.show_data(data, type='ifs') is useful.  Nastran also lies about the values for some very important parameters (e.g. the format_code and the device_code) depending on how you wrote your case control deck (e.g. DISP = ALL vs. DISP(PLOT,PRINT)=ALL or DISP(PHASE)=ALL for a static case).  Those parameters are important for identifying what kind of data you have and I've had at least some trouble for every random table I've tried to read.  I'm also not totally clear on the thermal value, which is a series of bitwise flags defining different parameters regarding random response (e.g. ABS vs. SRSS vs. NRL vs. NRLO).  I haven't figured that out yet.

> If you output both RMS and frequency response data, I suppose that complicates things.

It shouldn't if you get your format code and variable storage slots set right.

**Comment by SteveDoyle2** [comment]
closed due to inactivity
