### ISSUE TITLE
First line after BEGIN BULK not read?

### ISSUE THREAD

**Issue by magnus187** [SteveDoyle2/pyNastran#299]
Hi,

I think that the first line after BEGIN BULK is not properly read, at least in case of no executive control section and no case control section in the input file.
I commented line 897 and then it works for my models.
Please, investigate.

        if 'CEND' in lineUpper[:4]:
            self.has_case_control_deck = True
        else:
            self.has_case_control_deck = False
# line commented  in order to read the first line after BEGIN BULK correctly...
#            (i, line, comment) = self._get_line()   # BEGIN BULK

Thanks,
Magnus

**Comment by SteveDoyle2** [comment]
You need to call read_bdf with punch=True.  Also, if you label your file a *.pch, it will automatically apply punch=True (and you can't disable that).  

The variable name (punch) sucks if you don't run optimization (SOL 200), which outputs a *.pch file of your design variables.  The confusion comes in when a *.pch file is also used for an output, which is a different type of pch file.  Sadly, I can't think of a better name.
