### ISSUE TITLE
Node numbers eigenvectrors

### ISSUE THREAD

**Issue by Thomas-van-Dijk** [SteveDoyle2/pyNastran#302]
Is it possible to have the node numbers of the eigen eigenvectors like element numbers at strains?

Stress:
```
import pyNastran
from pyNastran.op2.op2 import OP2
model = OP2()
model.read_op2(op2_filename)
print(model.get_op2_stats())
stress = model.ctetra_stress[1]
stress.element_node
```
Eigenvectors:
`model.eigenvectors.node`

Thanks for pyNastran!

**Comment by SteveDoyle2** [comment]
You're after `nids = model.eigenvectors[1].node_gridtype[:, 0]`

**Comment by Thomas-van-Dijk** [comment]
Thank you, spot on.
