### ISSUE TITLE
fiber distance is sometimes labeled as fiber curvature on plate elements

### ISSUE THREAD

**Issue by Thomas-van-Dijk** [SteveDoyle2/pyNastran#303]
Looks like the same issue, wrong label, not top/bottom

**Comment by SteveDoyle2** [comment]
Nastran uses an overly complicated series of bits to give the information for fiber distance, curvature, von mises, shear.  It's also easy to get wrong, but it's also easy to tell what the data really should be based on the numbers.  This information is based on what the user requests (so you can't get max shear and von mises at the same time).  

Can you attach an example of the bug?

**Comment by Thomas-van-Dijk** [comment]
Hi Steven,

Thanks for your reply,
I attached a small model, two input files with difference:


   - taperedtowerV2Curve.dat
   -    STRAIN(SORT2,PRINT,STRCUR) = 2
   - taperedtowerV2.dat
   -   STRAIN(SORT2,PRINT,FIBER) = 2


 pyNastran gives result with top bottom, labels for taperedtowerV2.dat
and curvature, mean for taperedtowerV2Curve.dat

Greetz,
Thomas
[image: Inline afbeelding 1]

2016-05-09 17:36 GMT+02:00 SteveDoyle2 <notifications@github.com>:

**Comment by SteveDoyle2** [comment]
The files are not attached.

**Comment by Thomas-van-Dijk** [comment]
Here it is
https://drive.google.com/file/d/0BzFDEEVlTjP0TzFZcUlRVlJocUQ5WTd5aUxsS01HTHJWZWdJ/view?usp=sharing

2016-05-10 18:44 GMT+02:00 SteveDoyle2 <notifications@github.com>:

**Comment by SteveDoyle2** [comment]
Everything should work now.  Let me know if you find anything else.  It's always what's there, but it's not always what it says...

**Comment by Thomas-van-Dijk** [comment]
Hi Steve,
It works like a charm now.
Thank you!


2016-05-11 8:47 GMT+02:00 SteveDoyle2 <notifications@github.com>:
