### ISSUE TITLE
extending the pyNastran.bdf.cards.elements.shell.CQUAD4 class

### ISSUE THREAD

**Issue by Thomas-van-Dijk** [SteveDoyle2/pyNastran#304]
Hi I want to extend the CQUAD4 class with the element coordinate system:
```
class coord(object):
    """ class defining the element coordinate system.
    go = gridpoint 0
    g1 = gridpoint 1
    etc.

    g0g2 = linepiece from gridpoint 0 to grid point 2
    g3g1 = linepiece from gridpoint 3 to grid point 1

    using definition of coordinate system of element
    reference manual. implemented as follows:

        vx, unit vector in x direction  equal to the
        average  of diagonal g0-> g2 and g3->g1

        vy, unit vector in ydirection is average of diagonal
        g0->g2 and g1->g3

        vz, unit vector in z direction is perpendicular to
        both vx and vy.

        Note vx and vy are always perpendicular due to the
        definition.

    """

    def __init__(self, element):
        g0g2 = element.get_node_positions()[2] - element.get_node_positions()[0]
        g3g1 = element.get_node_positions()[1] - element.get_node_positions()[3]
        g1g3 = element.get_node_positions()[3] - element.get_node_positions()[1]

        vx = g0g2/norm(g0g2)+g3g1/norm(g3g1)
        vx = vx/norm(vx)
        vy = g0g2/norm(g0g2)+g1g3/norm(g1g3)
        vy = vy/norm(vy)

        vz = np.cross(vx, vy)
        vy = np.cross(vz, vx)
        vx = np.cross(vy, vz)

        self.vx = vx/np.linalg.norm(vx)
        self.vy = vy/np.linalg.norm(vy)
        self.vz = vz/np.linalg.norm(vz)
        self.matrix = np.array([vx,vy,vz])
    def __repr__(self):
        string = 'vx = ' + str(self.vx)\
                +'\nvy = ' + str(self.vy)\
                +'\nvz = ' + str(self.vz)
        return string

class test1(pyNastran.bdf.cards.elements.shell.CQUAD4):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.Coord = coord(self)
pyNastran.bdf.cards.elements.shell.CQUAD4 = test1
```
This gives me the following error:
```
AttributeError: 'test1'object has no attribute 'nodes_ref'
```
Any comments welcome!
Thomas

**Comment by SteveDoyle2** [comment]
Thomas,

Nodes_ref is created during the cross-reference step.  Until then, you can't get the location of the nodes, only the node IDs.

Also, I believe the projection of the material coordinate system should be used if the value is any integer >= 0 (so not None) and not -1 (which is a valid coordinate system).  If it's a float, I think the coordinate system should be rotated by that angle.

I believe vx is the primary and correct direction, and vy is a rough guess (vy is found from a cross with the normal), so something like:
      4    3
      +---+
       |    |
      +---+
      1    2

    g21 = g2 - g1
    g43 = g4 - g3
    g41 = g4 - g1
    g32 = g3 - g2
    vx = 0.5 * (g12 + g43)
    vy = 0.5 * (g41 + g32)
    vz = np.cross(vx, vy)
    vx /= np.linalg.norm(vx)
    vz /= np.linalg.norm(vz)
    vy = np.cross(vz, vx)
    if theta_mcid is None:
       self.matrix = np.array([vx,vy,vz])
       return
    elif isinstance(theta_mcid, int):  # not handling the -1 case
        i = coord.i # mag=1
        # a x b = a*b*sin(theta)
        theta = np.asin(np.cross(i, vx))
    else:
        theta = np.radians(theta_mcid)

    mtheta = np.eye(3)
    mtheta[0,0] = mtheta[1,1] = cos(theta)
    mtheta[0,1] = -sin(theta)
    mtheta[1,0] = sin(theta)
    self.matrix = np.dot( np.array([vx,vy,vz]), mtheta)

Steve

**Comment by SteveDoyle2** [comment]
closing due to innactivity
