### ISSUE TITLE
frequency response op2 table reading broken

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [SteveDoyle2/pyNastran#306]
Trying to read an OP2 with frequency response table throws NotImplemented exception. This used to work (at the master on or around 3/11/2016; I'm not sure which revision).

For example, with the deck:

```
SOL 111
CEND
  TITLE = sine
  ECHO = NONE
  SUBTITLE = 1 G
  ECHO = NONE
  ACCE(PLOT,SORT1,PHASE)=ALL
  DISP(PLOT,SORT1,PHASE)=ALL
  FORCE(PLOT,SORT1,PHASE)=ALL
  METHOD= 200
  FREQ = 100
  SDAMP = 20
  SPC = 1
  $MPC = 1
SUBCASE 1
  DLOAD = 1
SUBCASE 2
  DLOAD = 2
SUBCASE 3
  DLOAD = 3
BEGIN BULK
PARAM,PRGPST,NO
PARAM,POST,-1
PARAM,OGEOM,NO
PARAM,AUTOSPC,YES
PARAM,GRDPNT,0
PARAM,WTMASS,.00259

EIGRL,200,,200.,,,,7.77

FORCE,1,1,0,4.E9,1.0,0.0,0.0
FORCE,2,1,0,4.E9,0.0,1.0,0.0
FORCE,3,1,0,4.E9,0.0,0.0,1.0

RLOAD1,1,1,,,1
RLOAD1,2,2,,,1
RLOAD1,3,3,,,1

$ damping Q=20
TABDMP1,20,CRIT,
+,0.0000,0.02500,1.+6,0.0250,ENDT

TABLED1,1
,0.0,1.0,100.0,1.0,ENDT

$ one sample at low frequency for static check
FREQ1        100      .1      1.       1

$ linear spacing across band 10 Hz to 140 Hz
FREQ1        100     10.      1.     140

$ bunched around modes 
$ y = [2**(x-1) for x in [1., .5, .6, .7, .8, .9, .95, .98, .99, 1.01, 1.02, 1.05, 1.1, 1.2, 1.3, 1.4, 1.5]]
FREQ5        100      1.    150.      1.  0.7071  0.7578  0.8122  0.8705        +
+         0.9330  0.9659  0.9862  0.9930  1.0069  1.0139  1.0352  1.0717        +
+         1.1486  1.2311  1.3195  1.4142

SPC1           1     456       1
SUPORT,1,123

CONM2,100,1,0,4.E9

$ Femap with NX Nastran PropOrient 1 : 1,0,0.,1.,2.,3.,4.,-1.,0.,0.
PBAR           1       1  .001252.6042-76.5104-81.7888-7      0.        +       
+          -.025  -.0125    .025  -.0125    .025   .0125   -.025   .0125+       
+        .849928 .850704      0.
$ Femap with NX Nastran Material 1 : ISOTROPIC Material
MAT1           19900000.3778626.     .31    .098      0.      0.        
GRID           1       0      0.      0.      0.       0
GRID           2       0     2.5      0.      0.       0
GRID           3       0      5.      0.      0.       0
GRID           4       0     7.5      0.      0.       0
GRID           5       0     10.      0.      0.       0
SPOINT       100                        
CBAR           1       1       1       2      0.      1.      0.
CBAR           2       1       2       3      0.      1.      0.
CBAR           3       1       3       4      0.      1.      0.
CBAR           4       1       4       5      0.      1.      0.
ENDDATA
```

Running this through NX Nastran produces frequency response table FRL in the OP2. Trying to read it with pyNastran 0.7.2 using the code below:

```python
from pyNastran.op2.op2 import OP2

op2 = OP2(debug=False)
op2.read_op2('sine.op2')
```

Throws exception:

```python
INFO:      fname=op2.pyc                   lineNo=107    vectorized=True combine=True
INFO:      fname=op2.pyc                   lineNo=111    -------- reading op2 with read_mode=1 --------
DEBUG:     fname=op2_scalar.pyc            lineNo=482    op2_filename = 'sine.op2'
INFO:      fname=op2_scalar.pyc            lineNo=595      table_name='PVT0'
INFO:      fname=op2_scalar.pyc            lineNo=595      table_name='CASECC'
INFO:      fname=op2_scalar.pyc            lineNo=595      table_name='EQEXINS'
INFO:      fname=op2_scalar.pyc            lineNo=595      table_name='OGPWG'
INFO:      fname=op2_scalar.pyc            lineNo=595      table_name='FRL'
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-9cff7b5e262a> in <module>()
      1 op2 = OP2()
----> 2 op2.read_op2('sine.op2')

pynastran-0.7.2-py2.7.egg\pyNastran\op2\op2.pyc in read_op2(self, op2_filename, vectorized, combine)
    114 
    115             # get GUI object names, build objects, but don't read data
--> 116             OP2_Scalar.read_op2(self, op2_filename=op2_filename)
    117 
    118             # TODO: stuff to figure out objects

pynastran-0.7.2-py2.7.egg\pyNastran\op2\op2_scalar.pyc in read_op2(self, op2_filename)
    535             raise FatalError('no tables exists...')
    536 
--> 537         table_names = self._read_tables(table_name)
    538         if self.debug:
    539             self.binary_debug.write('-' * 80 + '\n')

pynastran-0.7.2-py2.7.egg\pyNastran\op2\op2_scalar.pyc in _read_tables(self, table_name)
    701                     self._read_results_table()
    702                 else:
--> 703                     raise NotImplementedError('%r' % table_name)
    704 
    705             table_name = self.read_table_name(rewind=True, stop_on_failure=False)

NotImplementedError: 'FRL'
```

**Comment by SteveDoyle2** [comment]
I cannot reproduce the error.  My error is:

     *** USER FATAL MESSAGE 4405 (PRTPRN)
         NO EIGENVECTORS COMPUTED FOR COMPONENT MODE SYNTHESIS OR SYSTEM     SOLUTION.
    1    SINE                                                                      JUNE   8, 2016  MSC.NASTRAN  6/17/05       PAGE     8
          1 G                                                                                                                           
    0                                                                                                            SUBCASE 1              
    0                                                                                                                                   
                                                                                                                                    
                                                                                                                                    
     *** USER INFORMATION MESSAGE 4425 (PRTPRN)
         ONE OR MORE FATAL ERRORS HAVE OCCURRED.  THERE MAY BE MORE ERROR MESSAGES IN THE PRECEDING OUTPUT

The following is correctly spit out in that case:

    pyNastran.f06.errors.FatalError: There was a Nastran FATAL Error.  Check the F06.

Onepossibility is you're not up to date.  The sine examples I have do not crash on the FRL table. 

The output of models/freq_sine/good_sine.op2 is:

    >>> test_op2 -ct good_sine.op2

    OP2_FILENAME = 'good_sine.op2'
    isubcases = []
    DEBUG:     fname=op2_scalar.pyc            lineNo=465    set_subcases - subcases = []
    DEBUG:     fname=op2_scalar.pyc            lineNo=465    set_subcases - subcases = []
    DEBUG:     fname=op2.pyc                   lineNo=365    combine=True
    DEBUG:     fname=op2.pyc                   lineNo=366    -------- reading op2 with read_mode=1 --------
    INFO:      fname=op2_scalar.pyc            lineNo=1100   op2_filename = 'good_sine.op2'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='PVT0'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='CASECC'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='EQEXINS'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='FRL'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='BHH'
    ----------------------------------------------------------------
    INFO:      fname=op2_scalar.pyc            lineNo=1541   name='BHH' matrix_num=103 form=6     mrows=11 ncols=11 tout=2 nvalues=2 g=909
    INFO:      fname=op2_scalar.pyc            lineNo=1618   created BHH
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='KHH'
    ----------------------------------------------------------------
    INFO:      fname=op2_scalar.pyc            lineNo=1541   name='KHH' matrix_num=104 form=6     mrows=11 ncols=11 tout=2 nvalues=2 g=909
    INFO:      fname=op2_scalar.pyc            lineNo=1618   created KHH
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='LAMA'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='OUGV1'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='OEF1X'
    DEBUG:     fname=op2.pyc                   lineNo=378    -------- reading op2 with read_mode=2 --------
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='PVT0'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='CASECC'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='EQEXINS'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='FRL'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='BHH'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='KHH'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='LAMA'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='OUGV1'
    DEBUG:     fname=op2_scalar.pyc            lineNo=1288     table_name='OEF1X'
    DEBUG:     fname=op2.pyc                   lineNo=495    combine_results
    DEBUG:     fname=op2.pyc                   lineNo=385    finished reading op2

It's just strange because the FRL table is not that complicated...

**Comment by jeffrey-guy-lyon** [comment]
Thanks. It might be an NX vs. MSC thing, as that deck runs on NX. I will try it with MSC when I get to work tomorrow.

**Comment by jeffrey-guy-lyon** [comment]
Steve,

I have no idea what was wrong with my environment, but I cleaned out all pynastran files and reinstalled and the problem went away. Sorry for the false alarm!

-Jeff

**Comment by SteveDoyle2** [comment]
No worries!
