### ISSUE TITLE
PBEAM "SO" field

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#321]
I have encountered a syntax error when reading a PBEAM card:

```
SyntaxError: c1 1 = 'YESA' (field #25) on card must be a float or blank (not a string).
card=['PBEAM', '23001', '4340', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', '0.0', '0.00', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', 'YESA', '0.49', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', 'YESA', '0.60', '0.8226', '0.9216', '0.9216', '0.0', '1.8432', '0.0', 'YESA', '0.71', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', 'YESA', '0.89', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', 'YESA', '1.00', '0.8226', '0.9216', '0.9216', '0.0', '1.8432', '0.0']
```

Is it possible that only one continuation is allowed?

Apparently the first "YESA" has been parsed with no issues.

Thanks a lot

EDIT: I've also tried to write YESA only in the field corresponding to X/XB = 1.0 (leaving the other lines with a None instead) as reported in the NASTRAN qrg. Also in this case pyNastran gives me an error:

`SyntaxError: SO1 = None (field #17) on card must be an string (not blank).
card=['PBEAM', '23001', '4340', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', '0.0', '0.00', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', None, '0.49', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', None, '0.60', '0.8226', '0.9216', '0.9216', '0.0', '1.8432', '0.0', None, '0.71', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', None, '0.89', '1.9250', '2.3255', '2.3255', '0.0', '4.6510', '0.0', 'YESA', '1.00', '0.8226', '0.9216', '0.9216', '0.0', '1.8432', '0.0']`

**Comment by SteveDoyle2** [comment]
You need to use the master (v0.8).  v0.7.2 does not support that kind of PBEAM. The API on the card changed pretty significantly.

**Comment by alby3z** [comment]
Using master the pbeam is correctly parsed.
