### ISSUE TITLE
BDF long fields parsing

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#323]
I got an error when parsing a bdf file containing a CORD2R defined with fields of 16 characters. Is this expected?

The bdf card is the following:

```
CORD2R*              311             310      0.00000000      0.00000000       
*CS311A       0.00000000      1.00000000    -90.44467000      0.00000000       
*CS311B       1.00000000   -180.44467000      0.00000000                        
```

The error is the following:

bad fields = ['CORD2R*', '2303', '2302', '46.7084608', '178.0713037', '101.8000000', '47.4366979', '-169.7660133', '101.8000000', '36.7156684', '177.5460922', '101.8000000']

RuntimeError: field='46.7084608' is not 8 characters long...rawValue='46.7084608'

**Comment by SteveDoyle2** [comment]
That is not valid Nastran syntax.

**Comment by alby3z** [comment]
Actually the bdf card was the following:

```
CORD2R*              311             310      0.00000000      0.00000000 CS311A
*CS311A       0.00000000      1.00000000    -90.44467000      0.00000000 CS311B       
*CS311B       1.00000000   -180.44467000      0.00000000                        
```

**Comment by SteveDoyle2** [comment]
I'd need to see a full problem.  That coord is fine and should work.

**Comment by alby3z** [comment]
Using master v0.8 everything is fine.
