### ISSUE TITLE
Read bdf with duplicate properties' ID

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#324]
Is it possible to force the reading of the bdf in the case of duplicated card IDs?

**Comment by SteveDoyle2** [comment]
No.  You can disable reading of specific cards though.

I know Patran (I'm not sure about Femap) will renumber elements/properties, so you can use that to avoid duplicate ids.

**Comment by SteveDoyle2** [comment]
see #188

**Comment by SteveDoyle2** [comment]
Closing because duplicate/wont/cantfix.
