### ISSUE TITLE
Question on Geometry

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#327]
I have successfully loaded a bdf file then I used the command:
'''i_transform, transforms = bdf_model.get_displacement_index_transforms()"'

Followed by:

'''op2_model.transform_displacements_to_global(i_transform, transforms)'''

But after that honestly I didn't understand how to query the position of the nodes in the transformed coord sys.

**Comment by SteveDoyle2** [comment]
It doesn't transform a position.  It transforms a result (e.g. displacement, velocity, acceleration, eigenvector, spc_foces, mpc_forces, applied_loads) to the global frame only.  You access it with:

    op2_model.displacements[subcase].data

If you're after a node in the global frame:

    bdf_model.nodes[nid].get_position()

For a local frame:

    bdf_model.nodes[nid].get_position_wrt(bdf_model, cid)

**Comment by alby3z** [comment]
When invoking the command to get the position in the global frame, an error occurs:

bdf_model.nodes[67111].get_position()
Traceback (most recent call last):

  File "<ipython-input-312-7b78d8113b30>", line 1, in <module>
    bdf_model.nodes[67111].get_position()

  File "C:\Users\10758\AppData\Local\Continuum\Anaconda3\lib\site-packages\pynastran-0.8.0+dev.no.checksum.error-py3.5.egg\pyNastran\bdf\cards\nodes.py", line 1058, in get_position
    xyz = self.cp_ref.transform_node_to_global(self.xyz)

AttributeError: 'GRID' object has no attribute 'cp_ref'

**Comment by SteveDoyle2** [comment]
You need to cross reference the model.  By default, cross referencing is enabled.

So:

    model = read_bdf(bdf_filename, xref=True)

or

    model = read_bdf(bdf_filename, xref=False)
    model.cross_reference()

**Comment by alby3z** [comment]
I successfully run "test_bdf" on my bdf with -x option, I only get a couple of rejected cards:

'
   key=CONM2   value1=20852   value2=20852
   key=CORD1R  value1=2       value2=2
   key=CORD2C  value1=20      value2=20
   key=CORD2R  value1=51      value2=51
   key=EIGRL   value1=1       value2=1
   key=ENDDATA value1=1       value2=1
  -key=GENEL   value1=4       value2=4
   key=GRID    value1=14906   value2=14906
   key=MAT1    value1=119     value2=119
   key=MAT2    value1=1490    value2=1490
   key=MAT8    value1=22      value2=22
   key=MAT9    value1=1       value2=1
   key=PARAM   value1=5       value2=5
   key=PBAR    value1=1810    value2=1810
   key=PBARL   value1=12      value2=12
   key=PBEAM   value1=254     value2=254
   key=PBEAML  value1=6       value2=6
   key=PBUSH   value1=90      value2=90
   key=PCOMP   value1=191     value2=191
   key=PELAS   value1=43      value2=43
   key=PROD    value1=76      value2=76
   key=PSHEAR  value1=512     value2=512
   key=PSHELL  value1=1197    value2=1197
   key=PSOLID  value1=1       value2=1
   key=RBE2    value1=432     value2=432
   key=RBE3    value1=387     value2=387
  -key=RSPLINE value1=6       value2=6
   key=SPCADD  value1=1       value2=1
'

But when I use the cross-referencing, the test_bdf function breaks and gives a (probably) unreliable error on a coordinate system:

RuntimeError: Local unit vectors haven't been set.
Type='CORD2R' cid=321 rid=CORD2C       323         222.919 185.412 198.925233.343986.26359191.1203
        309.1199190.5056249.3577

I say that it is unreliable because the COORD system  has been succesfully tested with -x option.

**Comment by SteveDoyle2** [comment]
I've never seen that error unless I don't have a cross referenced deck.  

I'd suggest running with:

    test_bdf bdf_filename -e 0

By default it suppresses errors so you can get a mass of errors in one go.

**Comment by SteveDoyle2** [comment]
CORD2s are incredibly robust.  CORD1s, I have much less faith in.

**Comment by alby3z** [comment]
I think I have found the possible issue:

>>> coord321 = bdf_model.coords[321];
>>> coord321.beta()

array([[None],
       [None],
       [None]], dtype=object)

The coord sys 321 has an array of non in the beta attribute.

**Comment by alby3z** [comment]
I have modified the bdf leaving only a couple of coord system, including the same coord 321 of the comment above.

In this case the beta is defined:

>>>coord321.beta()
 
array([[-0.49605689, -0.11985282,  0.85997841],
       [ 0.104249  , -0.99148415, -0.078047  ],
       [ 0.86200911,  0.05093614,  0.50432708]])

**Comment by alby3z** [comment]
Attached the bdf file that returns the xref error when trying to load it with pyNastran:

[test_coord_xref.txt](https://github.com/SteveDoyle2/pyNastran/files/403904/test_coord_xref.txt)

**Comment by alby3z** [comment]
Erroneously closed.

**Comment by SteveDoyle2** [comment]
I'll take a look

**Comment by SteveDoyle2** [comment]
This bug is fixed.  I'm closing this just to simplify issues...one thing per ticket.
