### ISSUE TITLE
Random tables TABRND1

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#328]
[test_tabrnd1.txt](https://github.com/SteveDoyle2/pyNastran/files/399530/test_tabrnd1.txt)
I have read the attached bdf file (taken from NASTRAN QRG) that defines a TABRND1.

Then if I ask for the random tables loaded, pyNastran return an empty dictionary:

>>> bdf_model.random_table
{}

**Comment by SteveDoyle2** [comment]
I recommend running:

    test_bdf bdf_filename

on any problem deck.  It's basically a read/write and does some checks on the deck.  Just doing an IO will produce an output deck that looks like:

    BEGIN BULK
    $      ><      ><      ><      ><      ><      ><      >
    TABRND1        3
                 2.5  .01057     2.6  .01362   ENDT
    ENDDATA
    BEGIN BULK
    ENDDATA

It got very confused.  You need to add an executive control deck to the top.
