### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by yellowhat** [SteveDoyle2/pyNastran#336]
Hi all,
I am trying to install pyNastran on a Windows machine and a Anaconda 4.1.1.
I have tried:
- ```pip install pyNastran```
- ```python setup_no_gui.py install``` from git master

In both case I am able to import pyNastran module without any error, but there are no functions like bdf or op2.

Infact `dir(pyNastran)` returns:
```['__author__',`
 '__builtins__',
 '__copyright__',
 '__desc__',
 '__doc__',
 '__email__',
 '__file__',
 '__license__',
 '__name__',
 '__package__',
 '__path__',
 '__pyqt_copyright__',
 '__releaseDate2__',
 '__releaseDate__',
 '__version__',
 '__website__',
 'is_pynastrangui_exe',
 'is_release',
 'os',
 'sys']```

Thanks.

**Comment by SteveDoyle2** [comment]
Importing pyNastran only gets you very basic package info.  

If you want the bdf, you need to import the `pyNastran.bdf` module.  The same thing goes for `pyNastran.op2`.  That allows you to load a bdf without also loading an op2 (and vice versa) and waste time/memory importing lots of things you don't need.  Here's a good place to start:

http://pynastran-git.readthedocs.io/en/v0.8/quick_start/bdf.html
http://pynastran-git.readthedocs.io/en/v0.8/quick_start/op2.html

**Comment by yellowhat** [comment]
OK. Thanks
