### ISSUE TITLE
pyNastranGUI does not work on Windows

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#339]
pyNastranGUI does not work on windows due to the following error:

`ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support`

**Comment by SteveDoyle2** [comment]
I don't know what that means and I don't know how to reproduce it.

I run the GUI on Windows, so I suspect something is wrong with your Python installation.  In the past I've used:

1.  base Python + numpy/scipy/vtk from http://www.lfd.uci.edu/~gohlke/pythonlibs/

2.  Anaconda Python https://www.continuum.io/downloads

While it *should* work on Python 3, Python 2 support is better.

**Comment by SteveDoyle2** [comment]
Thinking more about the problem, I suspect you're running the program differently than how I do.  Can you explain your process for running it?

Also, can you put the full traceback?  pyNastran doesn't use use pbs, but something like PyQt might.

**Comment by alby3z** [comment]
Sorry for the late answer.

I installed anaconda 3 that is based on python v 3.5. Then I installed the latest release (7.0.0) of the vtk libraries with the standalone installer for windows 64 bit found on http://www.vtk.org/download/

Then I simply open a command window and run the command:
'pyNastranGUI'

**Comment by SteveDoyle2** [comment]
No worries.  I just got back from my trip.

Can you type "conda list" from the command line and send me the output?

**Comment by SteveDoyle2** [comment]
Ok.  I figured out the issue.  Python-coveralls is used for getting the coverage and doesn't like Windows apparently.  It's now disabled for Windows.
