### ISSUE TITLE
SET3 continuation "THRU" appears in Fields 2 or 9

### ISSUE THREAD

**Issue by empennage** [SteveDoyle2/pyNastran#340]
pyNastran.__version__ = .9.0+dev.no.checksum.error
Python 2.7.10 | Anaconda 2.3.0 (64-bit)
Windows 7 SP1 ver 12.9
NX Nastran v8.5

The SET3 card was written to the BDF file with the continuation "THRU" in fields 2 or 9. Note 5, of the NX Nastran 8.5 Quick Reference Guide says:

> 5. “THRU” cannot appear in Field 4 or 9. For continuations, “THRU” cannot appear
in Fields 2 or 9.

The following Nastran fatal message was received:

>  *** USER FATAL MESSAGE 316 (IFPDRV)
     ILLEGAL DATA ON BULK DATA ENTRY SET3    
     User information:
     See Bulk Data entry description in Section 5 of the NX NASTRAN
     Quick Reference Guide. If you are using the large field format make
     sure the number of entries is even.
 SET3           1    GRID 1000000    THRU 1000016 1000022    THRU 1000028 0000007
 +0000007 1000034    THRU 1000082 1000090 1000091 1000099    THRU 1000257 0000008
 +0000008 1000259    THRU 1002744 1002748    THRU 1002994 1003000    THRU 0000009
 +0000009 1003188 1003190    THRU 1003769 1003771    THRU 1003787 1003796 000000A

The following code replicates the issue:

```python
import pyNastran
from pyNastran.bdf.bdf import BDF

print(pyNastran.__version__)

model = BDF()

# List of grid IDs
grid_list = [1, 2, 3, 4, 5, 6, 7, 13, 15, 20, 21, 22, 23, 30, 31, 32, 33]

# Define the card lines
card_lines = ['SET3', 1, 'GRID']
card_lines = card_lines + grid_list

# Add nastran card to BDF object
model.add_card(card_lines, 'SET3', comment='', is_list=True)

# Write to bdf file using PyNastran
model.write_bdf('set3.bdf')
```

A work-around that worked for me is to update SetIDs function in bdf_sets.py:
```python
def SetIDs(self):
        """gets the IDs of the SETx"""
        #return collapse_thru(self.ids)
        return self.ids
```

**Comment by SteveDoyle2** [comment]
I just checked the MSC 2005 QRG.  There is no note about the THRU field.  However, the MSC 2016 QRG does have the note.  Nastran is annoying sometimes :)

**Comment by empennage** [comment]
No worries. A colleague and I were joking that it's probably a hold-over from the punch card days in the 1960's.  :)

**Comment by SteveDoyle2** [comment]
You only know the half of it.  It's worse than you can even imagine.  The OP2 is bad and the F06 is even worse.  The PBEAM is probably the worst card in Nastran.

Anyways, SET3s now look like the following.  I think it's right...

    SET3, 1, GRID, 3, THRU, 7
    SET3, 1, GRID, 20, THRU, 30
    SET3, 1, GRID, 9, 11, 33

Also, what references a SET3?  I've only ever used a SET1 for SPLINEx cards.

**Comment by empennage** [comment]
It looks like the SET3 format does not work in NX Nastran 8.5. From what I can tell, Nastran requires a unique ID on each SET3 card. 

```
 *** USER FATAL MESSAGE 311 (IFPDRV)
     NON-UNIQUE FIELD 2 ON BULK DATA ENTRY SET3               1           SORTED ENTRY COUNT =         49
     User information:
     Sorted Bulk Data entry type indicated must have a unique integer
     in field 2. An error in the input has been detected. Two or more
     grid points, elements,  or properties have the same id.  (For example,
     you may not use two GRID  entries with the GID=2 in the same run.)
 *** USER FATAL MESSAGE 6151 (IFS1P)
     SET1/SET3 ID =       1 IS NOT UNIQUE.
     USER ACTION:            MAKE ALL SET1/SET3 ID NUMBERS UNIQUE.
```

Below is an example model that produces the fatal error shown above:
``` 
INIT MASTER(S)
NASTRAN SYSTEM(442)=-1,SYSTEM(319)=1
ID F2,Femap
SOL SEMODES
TIME 10000
CEND
  TITLE = Bar
  ECHO = NONE
  DISPLACEMENT(PRINT) = ALL
  METHOD = 1
  SPC = 1
BEGIN BULK
$
SET3, 1, GRID, 3, THRU, 7
SET3, 1, GRID, 20, THRU, 30
SET3, 1, GRID, 9, 11, 33
$
$
PARAM,POST,-1
PARAM,OGEOM,NO
PARAM,AUTOSPC,YES
PARAM,GRDPNT,0
PARAM,WTMASS,.00259
$
$
SPC1, 1, 123456, 3 
$
$
EIGRL          1                      10       0                    MASS
$ Femap with NX Nastran Property 1 : Bar
PBARL          1       1 MSCBML0     ROD                                +       
+             .5      0.                
$ Femap with NX Nastran Material 1 : Al 6061-T651
MAT1           19900000.             .33    .098 2.286-5     20.        
MAT4           1    13.5      .4    .098                              0.+       
+       -17.7778      0.      0.
GRID           3       0      3.      0.      0.       0
GRID           4       0      4.      0.      0.       0
GRID           5       0      5.      0.      0.       0
GRID           6       0      6.      0.      0.       0
GRID           7       0      7.      0.      0.       0
GRID           9       0      9.      0.      0.       0
GRID          11       0     11.      0.      0.       0
GRID          20       0     20.      0.      0.       0
GRID          21       0     21.      0.      0.       0
GRID          22       0     22.      0.      0.       0
GRID          23       0     23.      0.      0.       0
GRID          24       0     24.      0.      0.       0
GRID          25       0     25.      0.      0.       0
GRID          26       0     26.      0.      0.       0
GRID          27       0     27.      0.      0.       0
GRID          28       0     28.      0.      0.       0
GRID          29       0     29.      0.      0.       0
GRID          30       0     30.      0.      0.       0
GRID          33       0     33.      0.      0.       0
CBAR           1       1       3       4      0.      0.      1.
CBAR           2       1       4       5      0.      0.      1.
CBAR           3       1       5       6      0.      0.      1.
CBAR           4       1       6       7      0.      0.      1.
CBAR           5       1       7       9      0.      0.      1.
CBAR           6       1       9      11      0.      0.      1.
CBAR           7       1      11      20      0.      0.      1.
CBAR           8       1      20      21      0.      0.      1.
CBAR           9       1      21      22      0.      0.      1.
CBAR          10       1      22      23      0.      0.      1.
CBAR          11       1      23      24      0.      0.      1.
CBAR          12       1      24      25      0.      0.      1.
CBAR          13       1      25      26      0.      0.      1.
CBAR          14       1      26      27      0.      0.      1.
CBAR          15       1      27      28      0.      0.      1.
CBAR          16       1      28      29      0.      0.      1.
CBAR          17       1      29      30      0.      0.      1.
CBAR          18       1      30      33      0.      0.      1.
ENDDATA 

```

The SET3 cards are being used by another subsystem engineer to map grids into sets using AutoCAD software. This way we can associate specific grid IDs to separate parts of the model based on physical geometry.

Hope this helps.

**Comment by SteveDoyle2** [comment]
Attempt #2:

THRU will only be used if there will be one SET3 card.  Otherwise, it will write the full list as integers.

Since that's a silly format and because pyNastran is useful for fixing/debugging decks, it handles reading in SET3 cards with duplicated IDs.

**Comment by empennage** [comment]
Thanks for the quick response time. I ran my script with the updated PyNastran, and it appears to work as expected.

**Comment by SteveDoyle2** [comment]
Sounds good.  It will probably need to change again.  Apparently, SETs in Nastran aren't actual sets (e.g. unordered list of points).  On certain cards, I think order actually matters.

What do you use the SET3 cards for?  I'd like to make sure the case people actually use them for actually works right.

**Comment by empennage** [comment]
We are using SET3 cards to break the model into separate components for importing into the Autocad software. For example, a car chassis could be set ID 1, and the door set ID 2. 

The SET3 cards are strictly for the external Autocad processing. In other words, the Nastran results would not change if the cards were deleted.

**Comment by SteveDoyle2** [comment]
OK, that makes more sense.  Closing...
