### ISSUE TITLE
Create/modify groups

### ISSUE THREAD

**Issue by nickersonbm** [SteveDoyle2/pyNastran#346]
Hi,

With regards to the GUI I'm having issues trying to create and modify groups, specifically that the menu options under 'View' aren't there.  I'm using version 0.8 of the GUI.  Not sure what is causing the issue, just wanted to see if it has been encountered before.

Thanks

**Comment by SteveDoyle2** [comment]
you need to call the gui from the command line with the `--groups` flag, e.g.,

    pyNastranGUI --groups solid_bending.bdf solid_bending.op2

**Comment by nickersonbm** [comment]
Perfect, that's got it working.  Thanks for the help.  I've got a few solid elements that I'm applying .csv results to to visualize in the GUI, but the elements I needed to see were hidden within the others.  So I know which elements I want to view, and this command works perfectly to hide the others.

Thanks for a great library, has made my work a lot easier.
