### ISSUE TITLE
Unable to read bdf file

### ISSUE THREAD

**Issue by ironexmaiden** [SteveDoyle2/pyNastran#348]
Hello Steve

I use the above code to read the pyramid.bdf but the read procedure fails

from pyNastran.bdf.bdf import BDF
model = BDF(debug=False, log=None)
model.cardsToRead = set(['GRID','CQUAD4','CTRIA3'])
model.read_bdf('/home/dio/pyramid.bdf')
print(model.get_bdf_stats())

Pyramid File
$ Created by Gmsh
GRID    1       0       0.00E+000.00E+000.00E+00
GRID    2       0       1.0000000.00E+000.00E+00
GRID    3       0       1.0000001.0000000.00E+00
GRID    4       0       0.00E+001.0000000.00E+00
GRID    5       0       0.5000000.5000001.600000
CTRIA3  1       1       2       1       4
CTRIA3  2       1       2       4       3
CTRIA3  3       1       1       2       5
CTRIA3  4       1       1       5       4
CTRIA3  5       1       4       5       3
CTRIA3  6       1       2       3       5
ENDDATA

The output I took is:

---BDF Statistics---
SOL None

bdf.coords
  CORD2R   : ???

**Comment by SteveDoyle2** [comment]
That's not a valid deck (a deck capable of running Nastran).  That's a punch file.  Punch files (*.pch) get look like standard decks, but they don't have Executive Control or a Case Control Decks.  They are created from SOL 200 (optimization) runs and have information like the final design variables & updated PSHELL cards.  They are not the same thing as *.pch files that store results like an F06/OP2.

You can:
  1 . call read_bdf(...) with `punch=True`
  2. Add '$ pyNastran : punch=True' to the top of the main file.
  3. Name your file *.pch

**Comment by ironexmaiden** [comment]
Thank you Steve it worked with xref = False.
