### ISSUE TITLE
OP2: reading OELOP1 table

### ISSUE THREAD

**Issue by quantic-cloud** [SteveDoyle2/pyNastran#349]
Is it possible to read the OELOP1 table "Summation of element oriented forces on adjacent elements" in the OP2 file?

The table looks like this in the .f06 file,

    1234567       
 
         S U M M A T I O N   O F   E L E M E N T   O R I E N T E D   F O R C E S   O N   A D J A C E N T   E L E M E N T S
                                             ( ONE AND TWO DIMENSIONAL ELEMENTS ONLY )
                                              POINT-ID     ORIENT-ID      TENSION =(+)
                                               1100000       1200000      1.161508E+04

and like this in the .pch file,

    $TITLE   =                                                                102016
    $SUBTITLE=                                                                102017
    $LABEL   =                                                                102018
    $ELEMENT ORIENTED FORCES                                                  102019
    $REAL OUTPUT                                                              102020
    $SUBCASE ID =     1234567                                                 102021
    1100000           1200000              1.161508E+04                       102022

**Comment by SteveDoyle2** [comment]
What version of Nastran are you running?  Do you have a small example with the bdf, f06, and op2?

**Comment by quantic-cloud** [comment]
Nastran 2012. I attached a very simple example. The table appears at the bottom of the .f06, I assume it will be in the .op2. But if I do this :

    from pyNastran.op2.op2 import OP2
    model = OP2()
    model.read_op2('beam_2d.op2')

and look at `model`'s attributes, I can't find the values.

[beam_2d.zip](https://github.com/SteveDoyle2/pyNastran/files/653467/beam_2d.zip)

**Comment by SteveDoyle2** [comment]
The example does not contain the OELOP1 table in the OP2.  I cannot create it either as NX 10.1 crashes on the deck with:

     *** USER FATAL MESSAGE 4291 (SHELL_GMGD)
     FOR ELEMENT WITH ID =        19
     THE MATERIAL ROUTINE -MAT- RETURNS A 2X2 J-MATRIX FOR MATERIAL ID =         1 WHICH IS SINGULAR.

 Also, who creates the version of Nastran are you running?  MSC, NX, Autodesk, etc.

**Comment by quantic-cloud** [comment]
I did some tests over the weekend and I came to the conclusion that OELOP1 table is not in the OP2 file. Requesting to compute the table yields the same OP2 file size as requesting not to compute it. Also Patran does not list the table in the available results when I read the OP2 file. But the table does appear in the .pch and .f06 files. Which way do you think would be easier to parse it? 

In the attached zip file, there are 2 bdf and associated result files: one set requesting to compute and print the OELOP1 table (NOELOP,1), the other requesting nothing (NOELOP,-1). Also I fixed the material properties that was possibly causing the error on your NX 10.1. I was using MSC Natran. 

[beam_2d_2016-12-20.zip](https://github.com/SteveDoyle2/pyNastran/files/665446/beam_2d_2016-12-20.zip)

**Comment by SteveDoyle2** [comment]
The PCH file is significantly easier to parse than the F06.  Parsing either file isn't really a goal of the project because it's a nightmare to get it to work with SOL 200/superelements/poorly defined decks.  It's also orders of magnitude slower.

I guess I would talk to your NX technical rep and see if there's a way to get the data into the OP2.  Often there's a secret flag.  Alternatively, you can probably just take the grid point forces and transform them.
