### ISSUE TITLE
Reading .op2 data from Matlab

### ISSUE THREAD

**Issue by BobGordon** [SteveDoyle2/pyNastran#351]
I have a need to read Nastran eigenvectors for post-processing in Matlab.  Until now, I have been reading them from the .pch file using Matlab code.  I would like to be able to read them from the .op2 file since it is much smaller and reads/writes much faster.  After discovering pyNastran, I have been able to read the eigenvectors successfully from a command prompt.  However, I can't read the .op2 from Matlab as described in the documentation and issue #338 in this project by user alby3z.  I am running Window 10, Matlab R2015a, Python 2.7.12 (Anaconda) and pyNastran 0.8.0.

I've tried the example posted by alby3z.  When I type the following at the Matlab prompt I get an error
>> import py.pyNastran.op2.op2.OP2
Error using import
Import argument 'py.pyNastran.op2.op2.OP2' cannot be found or cannot be imported.

Could this be a path issue?  Any suggestions would be greatly appreciated.

**Comment by SteveDoyle2** [comment]
It's sounds like it, but I haven't used Matlab in about 10 years, so I'm probably not the one to ask.

I guess I'd start by going through a Matlab-Python tutorial and how to set the PYTHONPATH and call `setup.py develop` on a package, so it's in your `easy_install.pth` file or use `setup.py install` so it's in site-packages.

**Comment by alby3z** [comment]
If I start my Matlab (R2015A like yours) I get the same error:

`>> import py.pyNastran.op2.op2.OP2
Error using import
Import argument 'py.pyNastran.op2.op2.OP2' cannot be found or cannot be imported.`

If I write the following commands, then everything works fine:

`>> import py.pyNastran.op2.op2.OP2.*
>> clear import
>> import py.pyNastran.op2.op2.OP2 %now everything works fine`

I have asked for support to Mathworks (Italy) without receiving an answer, so I am still using this as a workaround.

**Comment by BobGordon** [comment]
Now I get:
```
>> import py.pyNastran.op2.op2.OP2.*
>> clear
>> import py.pyNastran.op2.op2.OP2.*
>> clear import
>> import py.pyNastran.op2.op2.OP2
>> op2_results = OP2();
>> op2_results.read_op2('s1_notemp.op2')
DEBUG:     fname=op2.py                    lineNo=365    combine=True
Error using log>stderr_logging (line 99)
Python Error: AttributeError: MexPrinter instance has no attribute 'flush'

Error in log>msg_typ (line 159)
        self.log_func(typ, '   fname=%-25s lineNo=%-4s   %s\n' % (fn, n, msg))

Error in log>debug (line 145)
                                                    for line in lines[1:]]))

Error in op2>read_op2 (line 365)
        self.log.debug('combine=%s' % combine)
```

Getting close, any ideas?

**Comment by alby3z** [comment]
Yes, sorry I forgot the other workaround that I took in place.

I found that Matlab has a script inside the installation folder that needs to be modified in order to get pyNastran working. Basically I add a couple of empty function declaration that are needed to make it work properly. It took me hours to find the bug in Matlab.

I'll send you as soon as I find it on my pc.

**Comment by alby3z** [comment]
Replace the file:

`C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\matlab\external\interfaces\python\+python\+internal\redirectstdout.m`

with the one attached below:

[redirectstdout.zip](https://github.com/SteveDoyle2/pyNastran/files/653609/redirectstdout.zip)

**Comment by BobGordon** [comment]
No change when I substitute the new file.  It looks identical to the one I replaced.

**Comment by alby3z** [comment]
I put the original file instead of the modified one, below you find the correct one (just rename it as .m and replace to the original one):

[redirectstdout.txt](https://github.com/SteveDoyle2/pyNastran/files/654895/redirectstdout.txt)

**Comment by BobGordon** [comment]
It works now with the new file.  Many thanks @alby3z .  This will speed up reading Nastran modes shapes greatly.  Also thanks to @SteveDoyle2 for pyNastran.  It will be a big benefit to my work.

**Comment by SteveDoyle2** [comment]
I have added the info to the example.

Closing.

**Comment by alby3z** [comment]
You're welcome @BobGordon, happy to hear that it could be useful!

**Comment by Wentiing0421** [comment]
I met the same problem and I replaced the redirectstdout.m you mentioned before. But no change when I substitute the new file. It looks identical to the one I replaced.

**Comment by SteveDoyle2** [comment]
I don't have access to Matlab anymore, so I'd suggest googling a workaround or because it's a Mathworks bug, they should be able to tell you how to fix it.

At this point though, I'd suggest calling python from the command line and not using the Matlab interface.  From what I understand, it's much faster to dump the output to an HDF5 file and read that into Matlab than reading a large OP2.
