### ISSUE TITLE
How to read the subcase number from OP2 with mode shapes

### ISSUE THREAD

**Issue by BobGordon** [SteveDoyle2/pyNastran#355]
I have successfully used pyNastran to read a large (8 Gb) OP2 containing mode shapes, save it in Matlab format and read it with Matlab.  Wow is it fast!  It took about 15 s for the entire process.  My current method of reading a PCH file from Matlab takes over 200 s.

My question: How to I query the OP2 to determine the subcase number for the eigenvalues/vectors?  Here's a portion of my script:
```
...
import pyNastran

from pyNastran.op2.op2 import read_op2
model = read_op2(op2_filename, debug=False)

eig1 = model.eigenvectors[3]
...
```
The subcase number seems to vary from one model to another.  If I specify the wrong subcase I get:
```
Traceback (most recent call last): 
  File "K:\pyN_scripts\run_op2b.py", line 24, in <module> 
    eig1 = model.eigenvectors[2] 
KeyError: 2 

```
I'm new to python so please excuse my ignorance.
Bob

**Comment by SteveDoyle2** [comment]
Binary is awesome, but 200 seconds to read the PCH is still pretty impressive!

If you only have one case, you can do:

    all_subcases = list(model.eigenvectors.keys())
    isubcase = all_subcases[0]
    eig = model.eigenvectors[isubcase]

It gets significantly more complicated than that if you're doing buckling/optimization, but that should work for what you want.

BTW, how is the Matlab/pyNastran integration?  I'm scared to even try it.

**Comment by BobGordon** [comment]
When I use your suggestion I get:
```
Traceback (most recent call last): 
  File "K:\pyN_scripts\run_op2b.py", line 24, in <module> 
    all_subcases = list(model.eigenvectors.keys()) 
TypeError: 'list' object is not callable 

```

The process is much slower running directly from Matlab.

**Comment by SteveDoyle2** [comment]
This is being called from python right?  That works in Python 2.7 and 3.5.

I would try it on `pyNastran/models/beam_modes/beam_modes_m1.op2`.  It should work.

**Comment by BobGordon** [comment]
Python 2.7 and pyNastran 0.8.0.  When I try your example:
```
>> !python K:\pyN_scripts\run_op2b.py beam_modes_m1.op2 shapes
INFO:      fname=op2_scalar.py             lineNo=1176   op2_filename = 'beam_modes_m1.op2' 
Traceback (most recent call last): 
  File "K:\pyN_scripts\run_op2b.py", line 24, in <module> 
    all_subcases = list(model.eigenvectors.keys()) 
TypeError: 'list' object is not callable 
```

**Comment by SteveDoyle2** [comment]
Can you run:

    type(model.eigenvectors)

    type(model.eigenvectors.keys())

**Comment by BobGordon** [comment]
Found the problem.  I was using 'list' as a variable name to pass the op2 filename.  Changed that name and now it works fine.  Many thanks for the assistance and a great product.
Bob G

**Comment by SteveDoyle2** [comment]
Glad you like it :)
