### ISSUE TITLE
Read OP2 geometry: error querying node position

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#363]
I have encountered an issue querying the position of a node (ID = 103048) from an op2:
```
from pyNastran.op2.op2_geom import read_op2_geom
op2_geom = read_op2_geom('nasrot_sol103.op2')
op2_geom.nodes[103048].get_position()

Traceback (most recent call last):

  File "<ipython-input-10-3df5a98c5408>", line 1, in <module>
    op2_geom.nodes[103048].get_position()

  File "C:\Users\10758\AppData\Local\Continuum\Anaconda3\lib\site-packages\pynastran-0.9.0+dev.no.checksum.error-py3.5.egg\pyNastran\bdf\cards\nodes.py", line 1087, in get_position
    xyz = self.cp_ref.transform_node_to_global(self.xyz)

AttributeError: 'GRID' object has no attribute 'cp_ref'
```

If I ask for another node (ID =  105200) everything works fine:

```
op2_geom.nodes[105200].get_position()
Out[11]: array([ 1.,  0.,  0.])

```

Below you find the zip file containing the model and the op2.

[Blade_Test.zip](https://github.com/SteveDoyle2/pyNastran/files/707989/Blade_Test.zip)

**Comment by SteveDoyle2** [comment]
You need to call:

    op2_geom.cross_reference()

before accessing anything that is cross referenced (e.g., `cp_ref`).  Nodes that have cid=0 don't need to be transformed and do not require cross referencing.

I probably should set xref as a parameter on the read_bdf method for the OP2Geom class.

**Comment by alby3z** [comment]
It works great, thanks!

Yes, probably it would be simpler to have it as a parameter.
