### ISSUE TITLE
Mass Properties for Beams with NSM

### ISSUE THREAD

**Issue by hurlei** [SteveDoyle2/pyNastran#373]
`BDFMethods.mass_properties` does not correctly account for beams with nonstructural mass offsets in calculating CG and inertia.

I'll look into this when I get a chance.

**Comment by SteveDoyle2** [comment]
Per google:

In physics, the center of mass is the arithmetic mean of all points weighted by the local density or specific weight. If a physical object has uniform density, then its center of mass is the same as the centroid of its shape.

Centroid is for uniform density, while center of mass is for nonuniform density.  We care about the nonuniform density, so:

All (it should be all) cards now have a Centroid() method and a center_of_mass() method.  Most of the time, they are just the same.

**Comment by SteveDoyle2** [comment]
To be clear:

All elements that have a mass should have a Centroid() and a center_of_mass() method. Most of the time, they are just the same.  CELASx/CDAMPx/CBUSH/etc. may not even have a physical location, so they don't have a centroid or center of mass.
