### ISSUE TITLE
Write op2

### ISSUE THREAD

**Issue by cthelin7** [SteveDoyle2/pyNastran#374]
Maybe I have missed it in the documentation, but I am looking for a way to write op2 files. I see pyNastran currently can open them, edit the information, and then write a f06 file, but if it could also write an op2 file, that would be an incredibly useful feature.  The only place I saw any op2 writing occurs in the test classes and in the oug package. I recommend adding this feature to the op2() class, so one can easily open, edit, and thus "save" the changes to the op2 file for later use in a post-processor.

**Comment by SteveDoyle2** [comment]
There is currently no way to write an OP2 for any object.  The OUG table
has a preliminary writer, but it doesn't work.  Unfortunately, the OP2
reader is so abstracted that it's non-trivial to write an OP2.

What's your use case?  A large part of the reason there is no support for
it is I couldn't think of a decent use case.  As far as I know, people
aren't using pyNastran to write a solver.

**Comment by cthelin7** [comment]
Thank you for the super fast response! I have results that I created for nodes in a mesh. and I want to visualize these new stresses on a mesh in a post-processor, as if NASTRAN had created the results.  As far as I can see, post-processors like NX require an op2 file to generate the visualization.  So, I was trying to open an op2 file with pyNastran, edit the results, and then write the op2 file so I could load that into a post-processor. I was just about to check out your GUI to see if it would help.

**Comment by SteveDoyle2** [comment]
Yeah.  I would do it in the GUI.

The GUI supports OP2s as well as custom CSV elemental/nodal results that are defined in the same order as the mesh (e.g., minimum node/element is the first line in the CSV).  It also supports deflections/modes/frequencies, though I suspect it only supports a single time/frequency/mode.

**Comment by cthelin7** [comment]
Thank you! I will try that! You have been incredibly helpful, and have saved us a lot of trouble with your library.

**Comment by SteveDoyle2** [comment]
Glad you like it!

**Comment by Vybornak2** [comment]
Hello, I wanted to ask if this still holds true. There have been quite a few contributions, so I am wondering whether this has changed.

Is there a way to write new OP2? Optionally is there a way how to modify existing OP2?

**Comment by SteveDoyle2** [comment]
I think it was added around 2019. You can write an op2 using
op2_model.write_op2. It supports the vast majority of results.

**Comment by Vybornak2** [comment]
Hello, thank you for a quick response!

Is it possible to somehow include some custom results? I thought it should be the case, what you are mentioning. But I am not sure, how would I do it since I did not see it in the documentation.

I mean if it is possible to create new op2 from scratch, save some data into it (computed utilization, for simplicity lets say something like SVM/Yield strength).

I actually do not know what are boundaries of OP2 format here.

**Comment by SteveDoyle2** [comment]
Results have to go in an existing result. You could call pretend margin is
temperature, but other than that, no.

**Comment by Vybornak2** [comment]
Thank you, I thought as much.
