### ISSUE TITLE
reading huge op2 file

### ISSUE THREAD

**Issue by BobGordon** [SteveDoyle2/pyNastran#375]
I am trying to read a 60Gb op2 file and save it to a Matlab .mat file.  I have done this successfully with a 2Gb op2 file, but when trying to read the 60Gb file I get the following:
```
>> !python C:\Users\bgordon\pyN_scripts\run_op2.py modes1000c.op2 shapes
INFO:      fname=op2_scalar.py             lineNo=1176   op2_filename = 'modes1000c.op2' 
Traceback (most recent call last): 
  File "C:\Users\bgordon\pyN_scripts\run_op2.py", line 35, in <module> 
    sio.savemat('op2_shapes.mat', {var_name:eig1.data}) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio.py", line 211, in savemat 
    MW.put_variables(mdict) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 846, in put_variables 
    self._matrix_writer.write_top(var, asbytes(name), is_global) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 587, in write_top 
    self.write(arr) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 626, in write 
    self.write_numeric(narr) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 652, in write_numeric 
    self.write_element(arr) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 493, in write_element 
    self.write_regular_element(arr, mdtype, byte_count) 
  File "C:\ProgramData\Anaconda2\lib\site-packages\scipy\io\matlab\mio5.py", line 507, in write_regular_element 
    tag['byte_count'] = byte_count 
OverflowError: Python int too large to convert to C long 
```
Can this be fixed?
Bob G

**Comment by SteveDoyle2** [comment]
That looks like a scipy issue to me.  I'm more than a little surprised that
pyNastran didn't crash on that.  How much RAM do you have?

Also, for my own curiosity, what was your peak RAM and how long did it take?

**Comment by BobGordon** [comment]
The machine has 256 Gb RAM.   Nastran writes the op2 file to a RAID0 array of SSDs.  It took about 15 minutes to write the file.

**Comment by SteveDoyle2** [comment]
That seems like it's a lot slower than it should be.  I don't have many
data points that are that big, but I expect 2 GB in ~4 seconds, 8 GB in ~15
seconds.  That's should be linear and it appears to be.  60 GB in 15
minutes seems like a bug.  I'd expect 1 minute, 2 tops.

I assume that's a frequency solutions (vs. say modes or transient) and
you're just parsing the displacements.  About how many nodes, elements, &
frequency steps?  Anything special about your case?

**Comment by BobGordon** [comment]
It's a normal modes solution.  About 3800 modes of a 3.5M dof model.  I'm writing out the mode shapes for post-processing in Matlab.

**Comment by SteveDoyle2** [comment]
That's a lot of modes and probably 50x what I'd expect.  You are using
EIGRL to calculate the modes correct?  EIGRL is far faster and just as
accurate as EIGR or EIGB.  Is there any reason you have so many modes?

**Comment by BobGordon** [comment]
I'm using RDMODES, a parallel modal solver in NX Nastran.  The modes are used to run a modal frequency response in Matlab.  It's a custom solution with multiple, frequency dependent materials.  All the modes are needed for an accurate solution.

By the way, I write the mode shapes uisng PARAM.POST,-1, for general post processing.  Is there a faster way write the modes to an op2?

**Comment by BobGordon** [comment]
I am running pyNastran with python v2.7.  The comments at this URL, http://bugs.python.org/issue21816, lead me to believe that upgrading to v3.4 (or higher) might solve the problem.  What do you think?

**Comment by SteveDoyle2** [comment]
That looks like it would work.  3500*3.5 million is really big.

I would suggest trying h5py to save the data in hdf5 format instead of MAT
format though.  Matlab supports it natively and it's a superior format for
read access.  It can even handle problems outside of RAM limits and has
superseded the MAT format in Matlab.  My one question would be does Matlab
also support the standard HDF5 format vs. their slightly tweaked format?

**Comment by BobGordon** [comment]
I loaded python 3.6.  I still get the same error.

So, to try h5py, do I read the op2 with pyNastran then write with h5py?

**Comment by SteveDoyle2** [comment]
That's odd.  I guess, first I would try h5py just on something small.  If
that doesn't work, I'd split your matrix to be something like 100 modes
each and save that.

I would also report the error to scipy.  You could probably create a zeros
matrix of the same size and get the same error.

**Comment by BobGordon** [comment]
H5PY works on the big problem!  It takes 2 minutes or so to read the op2 and write the hdf5 file.  And another couple of minutes to read the hdf5 into Matlab.  Thanks for all you help.
Bob

**Comment by SteveDoyle2** [comment]
Nice!  It's good to know.
