### ISSUE TITLE
Read OP2 geometry ref  issue #322

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#378]
With reference to closed issue #322 I've modified the ept.py file, in order to exclude PBUSH from the op2 geometry parsing.

Everything worked fine, except that I can't xref the model, see the error below when I input `op2_geom.cross_reference()`:

`KeyError: 'cid=CORD2R         0              0.      0.      0.      0.      0.      1.\n              1.      0.      0.\n not found which is required by GRID nid=655360.  Allowed Cids=dict_keys([0, 1, 2, 3, 4, 5, 230150, 352001, 10, 11, 12, 130190, 301, 16, 20, 21, 22, 32, 33, 932, 933, 40, 41, 300, 178, 1201, 1202, 1203, 352051, 310, 311, 1592, 1593, 6, 321, 322, 323, 324, 2501, 2502, 2503, 201, 202, 1102, 1101, 78, 207, 208, 14, 999001, 1103, 1594, 101, 102, 230250, 107, 108, 110, 111, 112, 114, 116, 1401, 1402, 2301, 2302, 2303])`

The grid 655360 is defined as follows:

`GRID      655360         518.557 2.23374 196.412`

that is with respect to the basic coordinate system (unfortunately the font here does not allow a fixed width characters).

The point is that the CORD2R ID = 0 shouldn't exist in the model, because it is the basic NASTRAN coordinate system. I've checked and in the bdf this ID = 0 CORD2R has not been defined.

**Comment by SteveDoyle2** [comment]
Do you have an example BDF and OP2 of that?

I know there is some oddity with the coordinate system.  In a BDF, cid=0 for a CBUSH is different than cid=blank.  It's very possible that Nastran writes the blank out as 0 to the OP2.

**Comment by alby3z** [comment]
I would really like to share an example, the point is that I cannot reproduce the error because I don't know where it comes from and I can't share the original bdf and op2...

**Comment by SteveDoyle2** [comment]
Is the problem not the CBUSH with a cid=0 when it's supposed to be blank?

**Comment by alby3z** [comment]
I have modified the ept.py file, in order to exclude PBUSH from the op2 geometry parsing. Do I have to do the same thing for the CBUSH?

**Comment by alby3z** [comment]
I think to not having fully understood your last comment...

**Comment by SteveDoyle2** [comment]
What I was trying to say is there is good test coverage over most things
related to a GRID, CQUAD4, MAT1, PSHELL, etc. cards.  The PBUSH cards have
oddities about them (e.g., cid=0 vs. blank mean different things).
Additionally, Nastran uses 0 for blank node IDs (e.g., on a CTETRA10)
instead of NANs.  All that points me to think that the problem is probably
with the CBUSH.

**Comment by SteveDoyle2** [comment]
I think this is fixed due to some fixes in the OP2 reading.  Feel free to reopen if it's not.
