### ISSUE TITLE
CQUAD4 Loads Extraction from OP2.

### ISSUE THREAD

**Issue by upendra117** [SteveDoyle2/pyNastran#386]
Hi Developers,
I am having trouble in following items. 

- Can some one help me extracting CQUAD4 Element IDs from OP2?
- Would like to request for help with a code to extract CQUAD4 loads (Such as  EID, Nx, Ny, Nxy, Mx, My, Mxy).

Really appreciate your help.

**Comment by SteveDoyle2** [comment]
Please post in the discussion forum.  It helps to show that the project is alive and acts as a reference.  Having it in a close issue doesn't.
