### ISSUE TITLE
Unable to pickle BDF object

### ISSUE THREAD

**Issue by saullocastro** [SteveDoyle2/pyNastran#389]
When trying to use 

```
from multiprocessing import Pool
from functools import partial

from pyNastran.bdf.bdf import read_bdf

def do_something(x, mesh):
    pass

if __name__ == '__main__':
    mesh = read_bdf('dummy.bdf') 
    p = Pool(8)
    xs = [1, 2, 3, 4, 5]
    p.map(partial(do_something, mesh=mesh), xs)
```

We get an error which is related to `cPickle` not being able to `pickle.dump()` pyNastran BDF.

Have you already seen this?

Thanks

**Comment by SteveDoyle2** [comment]
Perfect timing!  I was just about to send you an email.  I was really bad at licenses when I started pyNastran.  First it was GPL and then I learned what GPL actually meant.  

Now it is LGPL, which means that if you make modifications to the library, you are required to publish them.   It gets more complicated for binaries, so if you ever make a pyInstaller executable as a single file means you have to open source your code.  You also have to provide instructions on how to change out the library to a different version.  I didn't know about that part when I chose LGPL.  The goal was always to make it just a library that you can include and that you were encouraged/forced to commit to if you modified it.  

I was planning on relicensing pyNastran to BSD, so people can include pyNastran into executables without jumping through hoops.  There are a lot of licenses, but there is not any in-between BSD/LGPL licenses, so I figured just go with what numpy, scipy, and matplotlib use.  As you wrote code, I need to get your approval to include your code as BSD.  Thoughts?

Here is the current license:
https://github.com/SteveDoyle2/pyNastran/blob/master/LICENSE.md

Here is scipy's license.  I was planning on using the same thing.
https://www.scipy.org/scipylib/license.html

#-------------------------------------------------
 
Regarding your error, I've done work on previous versions regarding pickling, but it generally doesn't function well.  What I've seen when using pyNastran with the multiprocessing module is that you actually run slower, though obviously that depends on your problem.

To actually pickle the bdf, you need to NOT have a cross-referenced model.  If you do, call:
    bdf.uncross_reference()

which is implemented for most objects.  Can you provide a model?

**Comment by saullocastro** [comment]
@SteveDoyle2  thank you for the concern regarding licensing. For me it is perfect to have PyNastran with BSD license. Despite the new licensing scheme, I intend to continue submitting to the main PyNastran repository  any significant improvements that eventually comes.

**Comment by saullocastro** [comment]
@SteveDoyle2  I will try to find a model that I can send to you in order to reproduce this error...

**Comment by saullocastro** [comment]
@SteveDoyle2  I got the following error when trying `uncross_reference()`

```
In [5]: model.nastran.bdf.uncross_reference()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7d786a6490b5> in <module>()
----> 1 model.nastran.bdf.uncross_reference()

C:\repositories\trunk\structmanager\pyNastran\bdf\bdf_interface\uncross_referenc
e.pyc in uncross_reference(self)
     22         self._uncross_reference_elements()
     23         self._uncross_reference_properties()
---> 24         self._uncross_reference_materials()
     25         self._uncross_reference_masses()
     26         self._uncross_reference_aero()

C:\repositories\trunk\structmanager\pyNastran\bdf\bdf_interface\uncross_referenc
e.pyc in _uncross_reference_materials(self)
     68         """cross references the material objects"""
     69         for material in itervalues(self.materials):
---> 70             material.uncross_reference()
     71
     72     def _uncross_reference_masses(self):

C:\repositories\trunk\structmanager\pyNastran\bdf\cards\materials.pyc in uncross
_reference(self)
    618
    619     def uncross_reference(self):
--> 620         self.matt2 = self.Matt2()
    621         del self.matt2_Ref
    622

AttributeError: 'MAT2' object has no attribute 'Matt2'
```

**Comment by SteveDoyle2** [comment]
Do you have the model?

**Comment by saullocastro** [comment]
@SteveDoyle2 I would have to prepare a new model because the one that generated this error cannot be disclosed

**Comment by SteveDoyle2** [comment]
Could you disclose it if you delete the xyz locations of all the grids (the Nastran default for an x/y/z coordinate is 0.0)?

**Comment by saullocastro** [comment]
I'll do that tomorrow, thanks

**Comment by saullocastro** [comment]
@SteveDoyle2 I attached to this comment a zipped "dummy.bdf" file where you can reproduce this error.

[dummy.zip](https://github.com/SteveDoyle2/pyNastran/files/1028667/dummy.zip)


Thanks!

**Comment by SteveDoyle2** [comment]
Do you have a script that demonstrates the error?

**Comment by compmech** [comment]
@SteveDoyle2  I don't and the script is part of a bigger package that we have. The example I have at the issue description is very representative of what we are doing.

**Comment by saullocastro** [comment]
@SteveDoyle2 I don't and the script is part of a bigger package that we have. The example I have at the issue description is very representative of what we are doing.

**Comment by SteveDoyle2** [comment]
My mistake.  I forgot about that.  I'm a bit frazzled today.

**Comment by SteveDoyle2** [comment]
Give it a shot.  I think it's largely fixed.

**Comment by saullocastro** [comment]
I'll try it tomorrow Steve, thanks!

**Comment by saullocastro** [comment]
Hi @SteveDoyle2  sorry I forgot to get back to you regarding this issue. Thanks for fixing it!

**Comment by SteveDoyle2** [comment]
No worries :)  To be fair, I just fixed a Python 3 pickling bug.  You can do bdf_model.save() and .load() now.
