### ISSUE TITLE
When I try to read a particular bdf file get an Error

### ISSUE THREAD

**Issue by b1a2b3c4d** [SteveDoyle2/pyNastran#390]
File "C:\Users\\pyNastran\bdf\cards\elements\bars.py", line 417, in __init__
    self._validate_input()
  File "C:\Users\\pyNastran\bdf\cards\elements\bars.py", line 429, in _validate_input
    raise RuntimeError(msg)
RuntimeError: G0=23 cannot be GA=23 or GB=15

 [here is the bdf file](https://drive.google.com/open?id=0BxaMFoAUrxpBeTQ5bmJkTk16eW8)

**Comment by SteveDoyle2** [comment]
What is the problem?  When I run it in NX Nastran 10.1 I get the following Fatal Error:

     *** USER FATAL MESSAGE 350 (IFS350)
         THE FOLLOWING GRID OR SCALAR POINTS ARE SPECIFIED MORE THAN ONCE ON THE BULK DATA     ENTRY SHOWN BELOW:
             23
     *** USER FATAL MESSAGE 316 (IFPDRV)
         ILLEGAL DATA ON BULK DATA ENTRY CBAR    
     CBAR     13      5       23      15      23

**Comment by b1a2b3c4d** [comment]
I have know where the problem is. The bdf is builded in a wrong way, so it caused an error.
