### ISSUE TITLE
Difference in "def cross_reference(self, model) " between classes in shell.py and solid.py. 

### ISSUE THREAD

**Issue by qqnzhyxxx** [SteveDoyle2/pyNastran#396]
Dear Mr. Steve:
       At first ,Thanks for you open source project.
       Today, I pull you newest project from here. Finded you have restructure some class in  pyNastran/pyNastran/bdf/cards/elements. when I work with it, my codes get some bugs.Through debug，I find there have some difference in "**def cross_reference(self, model)** " between class CTRIA3(TriShell) in shell.py and others. 
       The issue cause the element in model has different struction. e.g. Originally , **self.model.element[i].pid** is an object of class PSHELL/PSOLID... Now , for solid element this member variables changed to type int, but it not change for shell element.  **self.model.element[i].pid.mid** has same problem.Could you tell me the purpose of doing so?
       Thank you for your reading and I look forward to hearing from you soon.

**Comment by SteveDoyle2** [comment]
As you said, it looks like the PSHELL/PCOMP hasn't been updated.  I thought I got all the main group (elements/properties/materials).  There are a few other stragglers as well in the optimization and thermal cards.

What should work currently in the master, in v1.0, and work once everything is migrated over is anything that is cross-referenced will have an _ref attribute that you access, so **self.model.elements[i].pid_ref.mid** (for a PSHELL to get the mid1/mid2 integer id) or **self.model.elements[i].pid_ref.mids_ref[0]** for a PCOMP.

**Comment by qqnzhyxxx** [comment]
Thank you very much for your reply！
 I'll be patient and wait for the project to be updated. I hope to have the opportunity to contribute to the project.

**Comment by SteveDoyle2** [comment]
Niu,

The bug should be fixed now.
