### ISSUE TITLE
Fonction PositionWRT in pyNastran\bdf\utils.py don not work

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#400]
When i use the function PositionWRT(xyz, cid, cid_new, model, is_cid_int=True): , i have the error : 
   AttributeError: 'CORD2R' object has no attribute 'transformToLocal'

I looked for this function(transformToLocal), but it does not exist

**Comment by SteveDoyle2** [comment]
That has been broken for quite a while then...

The old code block is:

        # a matrix global->local matrix is found
        matrix = coord_to_ref.beta()
        xyz_local = coord_to_ref.transform_node_to_local(xyz_global, matrix)

You can correct it with:

        # a matrix global->local matrix is found
        matrix = coord_to_ref.beta()
        xyz_local = coord_to_ref._transform_node_to_local(xyz_global, matrix)

Or:

        xyz_local = coord_to_ref.transform_node_to_local(xyz_global)

I've updated the code to use the 2nd option.

Alternatively, you can just call:

    node.get_position_wrt(model, cid)
