### ISSUE TITLE
INCLUDE with environment variable

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#401]
The INCLUDE written with environment variables is not recognized.

See NASTRAN COG
Using Filenames and Logical Symbols
Several of the parameters used by MSC Nastran, including command line arguments, initialization and 
RC file commands, and statements within MSC Nastran input files, specify filenames. The filenames 
must follow your system’s standard filename conventions, with the addition that filenames can include 
a “logical symbol” component, i.e., the filename can be specified in either of the following forms:
         logical-symbol:filename

My nastran file (bdf_demo_ACA.dat) is in : 
     D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL\VERIF\RL

I have an environment variable : 
     model_test_bddm_LOCAL = D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL/MATERIAUX

I have an INCLUDE in my "bdf_demo_ACA.dat" file : 
     INCLUDE 'model_test_bddm_LOCAL:ACA_Mat.blk'
      
When i read my "bdf_demo_ACA.dat" file with pyNastran, i have the error : 
Traceback (most recent call last):
  File "M:\Utilisateur\Carlina\SIMXPERT_Carlina\TEMPLATE\Template_2\pyNastran\bdf_demo_ACA.py", line 271, in <module>
    model_bdf.read_bdf(bdf_filename, xref=False , encoding='latin1')
  File "\\castore02\data8\structure\PyNastran\pyNastran-master_22062017\pyNastran\bdf\bdf.py", line 1079, in read_bdf
    bulk_data_lines = self._get_lines(self.bdf_filename, self.punch)
  File "\\castore02\data8\structure\PyNastran\pyNastran-master_22062017\pyNastran\bdf\bdf.py", line 3475, in _get_lines
    return self._lines_to_deck_lines(lines, punch=punch)
  File "\\castore02\data8\structure\PyNastran\pyNastran-master_22062017\pyNastran\bdf\bdf.py", line 3543, in _lines_to_deck_lines
    self._open_file_checks(bdf_filename2)
  File "\\castore02\data8\structure\PyNastran\pyNastran-master_22062017\pyNastran\bdf\bdf.py", line 3652, in _open_file_checks
    raise IOError(msg)
IOError: No such bdf_filename: u'D:\\Temp_DEMO\\Model_TEST_VarEnv_LOCAL\\VERIF\\RL\\model_test_bddm_LOCAL\\ACA_Mat.blk'
cwd: 'M:\\Utilisateur\\Carlina\\SIMXPERT_Carlina\\TEMPLATE\\Template_2\\pyNastran'
include_dir: 'D:\\Temp_DEMO\\Model_TEST_VarEnv_LOCAL\\VERIF\\RL'
failed: D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL\VERIF\RL\model_test_bddm_LOCAL\ACA_Mat.blk
failed: D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL\VERIF\RL\model_test_bddm_LOCAL
passed: D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL\VERIF\RL
passed: D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL\VERIF
passed: D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL
passed: D:\Temp_DEMO
passed: D:\

PyNastran does not convert environment variable . He concatene simply the path of the nastran  file with the include value.
The good value of the include shall be : 
     D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL/MATERIAUX/ACA_Mat.blk

It is possible that pyNastran reads the INCLUDE with the environment variable format ?

Thanks

**Comment by SteveDoyle2** [comment]
Expanding environment variables isn't hard, but I've always been confused on what the format is.  Much of tbe Nastran path capability is undocumented, which makes things tricky.  Unless I missed something, I don't see any special character to indicate an enviironment variable.

Do you have an example deck?  

Also, maybe I shouldn't ask this, but can you use two wnvironment variables in Nastran?  Can you use an environment variable and a driver letter?

**Comment by PabloBeranger** [comment]
I wrote a paasage of the COG (NASTRAN Installation and Operations Guide) in the beginning of my first message.
logical-symbol:filename
NASTRAN Installation and Operations Guide : 
   paragraph "Using Filenames and Logical Symbols"
   paragraph "Using the INCLUDE Statement"

Here is an example : 
NASTRAN FILE : 
############################################################################
SOL 103
$
GEOMCHECK NONE
ECHOOFF
$
CEND
$
ECHO = NONE
$
AUTOSPC(NOPRINT)=YES
GROUNDCHECK(SET=ALL)=YES
METHOD = 34
DISP(PLOT)=ALL
$
BEGIN BULK
$ ------------
PARAM,K6ROT,10.
PARAM,SNORM,0.
$
EIGRL,34,,,7
$
$----------------------
$ 1 - Reperes 
$----------------------
$
$INCLUDE './COORD/ACA_Coord_01.bdf'
$
$ ------------------------------
$ 2 - Base De Donnees Materiaux
$ ------------------------------
INCLUDE 'model_test_bddm_LOCAL:ACA_Mat.blk'
$
$ ------------ PROPRIETES
$INCLUDE './C1/PROPRIETE/ACA_Prop_C1.blk'
$INCLUDE './S1/PROPRIETE/ACA_Prop_S1.blk'
$
$ ------------ MODELE S1
INCLUDE 'model_test_sm_st_LOCAL:ACA_Modele_S1_VarEnv_LOCAL.bdf'
$
$ ------------ MODELE C1
INCLUDE 'model_test_CM_st_C1_LOCAL:ACA_Modele_C1_VarEnv_LOCAL.bdf'
INCLUDE 'model_test_CM_st_C1_BIS_LOCAL:ACA_Modele_C1_BIS_VarEnv_
          LOCAL.bdf'
$
$ ------------
ENDDATA
############################################################################


**Batch file with environment variables** : 
############################################################################
@ECHO off

ECHO.
ECHO %INDENT_ECHO_05%   *****************************************************
ECHO %INDENT_ECHO_05%   *** Chargement Variable Environnement LOCAL MODEL Test  ***
ECHO %INDENT_ECHO_05%   *****************************************************
ECHO.

SET model_test_base_LOCAL=D:\Temp_DEMO\Model_TEST_VarEnv_LOCAL
  ECHO %INDENT_ECHO_05%      model_test_base_LOCAL = %model_test_base_LOCAL%
REM
REM
SET model_test_bddm_LOCAL=%model_test_base_LOCAL%/MATERIAUX
  ECHO %INDENT_ECHO_05%      model_test_bddm_LOCAL = %model_test_bddm_LOCAL%
REM
REM =================================
REM ----------- FEM_model_test_SM -----------
REM =================================
REM
SET model_test_sm_base_LOCAL=%model_test_base_LOCAL%/PROGRAMME_SM_GEN
  ECHO %INDENT_ECHO_05%      model_test_sm_base_LOCAL = %model_test_sm_base_LOCAL%

REM
SET model_test_sm_st_LOCAL=%model_test_sm_base_LOCAL%/STRUCTURE/S1
  ECHO %INDENT_ECHO_05%      model_test_sm_st_LOCAL = %model_test_sm_st_LOCAL%
  
SET model_test_sm_st_BULK_LOCAL=%model_test_sm_st_LOCAL%/BULK
  ECHO %INDENT_ECHO_05%      model_test_sm_st_BULK_LOCAL = %model_test_sm_st_BULK_LOCAL%
  
SET model_test_sm_st_COORD_LOCAL=%model_test_sm_st_LOCAL%/COORD
  ECHO %INDENT_ECHO_05%      model_test_sm_st_COORD_LOCAL = %model_test_sm_st_COORD_LOCAL%
  
SET model_test_sm_st_LINK_LOCAL=%model_test_sm_st_LOCAL%/LINK
  ECHO %INDENT_ECHO_05%      model_test_sm_st_LINK_LOCAL = %model_test_sm_st_LINK_LOCAL%
  
SET model_test_sm_st_PROP_LOCAL=%model_test_sm_st_LOCAL%/PROPRIETE
  ECHO %INDENT_ECHO_05%      model_test_sm_st_PROP_LOCAL = %model_test_sm_st_PROP_LOCAL%


REM
REM ===============================
REM ----------- FEM_model_test_CM -----------
REM ===============================
REM
SET model_test_CM_base_LOCAL=%model_test_base_LOCAL%/PROGRAMME_CM
  ECHO %INDENT_ECHO_05%      model_test_CM_base_LOCAL = %model_test_CM_base_LOCAL%
REM
SET model_test_CM_st_C1_LOCAL=%model_test_CM_base_LOCAL%/STRUCTURE/C1
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_LOCAL = %model_test_CM_st_C1_LOCAL%
  
SET model_test_CM_st_C1_BULK_LOCAL=%model_test_CM_st_C1_LOCAL%/BULK
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_BULK_LOCAL = %model_test_CM_st_C1_BULK_LOCAL%
  
SET model_test_CM_st_C1_COORD_LOCAL=%model_test_CM_st_C1_LOCAL%/COORD
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_COORD_LOCAL = %model_test_CM_st_C1_COORD_LOCAL%
  
SET model_test_CM_st_C1_LINK_LOCAL=%model_test_CM_st_C1_LOCAL%/LINK
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_LINK_LOCAL = %model_test_CM_st_C1_LINK_LOCAL%
  
SET model_test_CM_st_C1_PROP_LOCAL=%model_test_CM_st_C1_LOCAL%/PROPRIETE
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_PROP_LOCAL = %model_test_CM_st_C1_PROP_LOCAL%

SET model_test_CM_st_C1_BIS_LOCAL=%model_test_CM_base_LOCAL%/STRUCTURE/C1_BIS
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_BIS_LOCAL = %model_test_CM_st_C1_BIS_LOCAL%
  
SET model_test_CM_st_C1_BIS_BULK_LOCAL=%model_test_CM_st_C1_BIS_LOCAL%/BULK
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_BIS_BULK_LOCAL = %model_test_CM_st_C1_BIS_BULK_LOCAL%
  
SET model_test_CM_st_C1_BIS_LINK_LOCAL=%model_test_CM_st_C1_BIS_LOCAL%/LINK
  ECHO %INDENT_ECHO_05%      model_test_CM_st_C1_BIS_LINK_LOCAL = %model_test_CM_st_C1_BIS_LINK_LOCAL%
############################################################################

**Comment by SteveDoyle2** [comment]
I think, I was unclear:

1.  Does the environment variable syntax support drive letters?
2.  Does the environment variable syntax support multiple environment variables?
3.  Please attach a working example and all include necessary files for each case.  Please do not just copy and paste the into the ticket.

Thanks

**Comment by PabloBeranger** [comment]
Yes, the environment variable syntax support drive letters and UNC path : 
Yes, the environment variable syntax support multiple environment variables : 
      for Windows : SET toto=D:\dir_BulkAA
                            SET tata=%toto%\dir_Models01

The environment variablee syntax support WINDOWS and LINUX path.

The environment variables allow to read the same file under Windows and Linux. It is enough to load the file containing the definition of the environment variables corresponding to the system.

Here is an example.
     In the directory Satellite_V02 there is the file In the file "satellite_V02_Variable_Env_SimX.bat" containing the definition of environment variables. In this file you can define the variable "Satellite_V02_base" to a local path or a network path. 
You have to load this file. 

I modified the python function "get_include_filename" to get back the value of the environment variable.

You have all files in the archive.
[Satellite_V02.zip](https://github.com/SteveDoyle2/pyNastran/files/1137984/Satellite_V02.zip)

**Comment by SteveDoyle2** [comment]
Thank you for those tests.  I'll take a look.

I was previously unaware there was documentation regarding the INCLUDE file syntax in the COG guide.  There are some odd rules regarding INCLUDE files that should at least crash gracefully.  

It turns out there is also some odd rules regarding paths and python that need to be handled.  `os.path.join('dir', '/dir2', 'model.bdf')` outputs `/dir2/model.bdf'

**Comment by PabloBeranger** [comment]
I forgot to specify that the NASTRAN file to be selected are in the directory JOBS\QS. 
You can test the INCLUDE with a relative path : "satellite_V02_ACA_QS_SOL101_RELATIF_Path.dat"
and with an environment variables path : "satellite_V02_ACA_QS_SOL101_VarEnv.dat"

**Comment by SteveDoyle2** [comment]
I'm making progress, but it's not quite ready yet (even with ignoring the `C:\*\model.bdf` functionality).  there are a few odd path edge cases to handle.

Anyways, do you have an example of the syntax for multiple environment variables?

**Comment by SteveDoyle2** [comment]
As a bonus, UNC paths work.

**Comment by PabloBeranger** [comment]
That you mean by :  syntax for multiple environment variables ?

When you define an new environment variable, you can use other variables already defined.
It is what I'm doing in my file "satellite_V02_Variable_Env_SimX.bat"
   SET Satellite_V02_base=M:\ACA\Satellite_V02SET Satellite_V02_base=M:\ACA\Satellite_V02
   SET Satellite_V02_bddm=%Satellite_V02_base%/BULK/MATERIAUX

For the definition of the NASTRAN INCLUDE, he can have only a single variable by INCLUDE.
    INCLUDE 'Satellite_V02_bddm:Satellite_V02_Materiaux.blk'

This example answers your question ?

**Comment by SteveDoyle2** [comment]
Yes that is helpful.  I think for now that two environment variables is not going to be supported.

It's done though.  Not sure why the tests are failing, but they're out of date somehow.  They should all pass on all platforms.  You'll need pathlib2 if you're on Python 2.7.

**Comment by PabloBeranger** [comment]
I am sorry, but the reading of the INCLUDE  with environment variables does not work. This below the image of the error.
![pynastran_17072017_error_include](https://user-images.githubusercontent.com/19569215/28270400-9f11d4b2-6b05-11e7-8dd7-19782386f589.jpg)
