### ISSUE TITLE
INCLUDE with environment variable V02

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#405]
I am sorry, but the reading of the INCLUDE with environment variables does not work. This below the image of the error.
![pynastran_17072017_error_include](https://user-images.githubusercontent.com/19569215/28271655-739f7ef2-6b09-11e7-8809-a7e1d563ced1.jpg)

**Comment by SteveDoyle2** [comment]
I'm sorry, I didn't realize Nastran supported sane syntax for environment variables :)  Your include statement uses a $ sign.  

Includes should be specified as:

    INCLUDE ‘TPLDIR:model.inc'
    INCLUDE ‘TPLDIR:/
                dir2/model.inc'

Per the COG manual:

   1, Environment variables are only recognized within the context of a logical symbol definition

Reading further:

2.  A logical symbol can be defined using any environment variable or previously defined
symbol. 

3. Use the standard environment variable reference convention, i.e., “$name” or
“${name}” on Linux and “%name%” on Windows.

Since you're on Windows, the 3rd note is a bit confusing.  It's not documented that Windows supports $'s (not that %'s are supported).

**Comment by PabloBeranger** [comment]
$name is the standard definition for LINUX variable environment ( see LINUX ksh).
     EXAMPLE : export Satellite_V02_base=/data/struture/ACA/Satellite_V02
                       export Satellite_V02_bddm=$Satellite_V02_base/BULK/MATERIAUX
                       echo     Satellite_V02_bddm = $Satellite_V02_bddm

%name%  is the standard definition for WINDOWS variable environment ( see WINDOWS Batch File ).
     EXAMPLE :  SET Satellite_V02_base=M:\ACA\Satellite_V02
                       SET Satellite_V02_bddm=%Satellite_V02_base%`\BULK\MATERIAUX
                       echo     Satellite_V02_bddm = %Satellite_V02_bddm%

When NASTRAN have an INCLUDE with environment variable like this : 
    INCLUDE 'Satellite_V02_bddm:Satellite_V02_Materiaux.blk'
     
    NASTRAN replaces the word before the colon (:) by the value of the environment variable and add the string after the colon (:) . What gives as result for the path of the file : 
        For WINDOWS : 
            Satellite_V02_bddm = M:\ACA\Satellite_V02\\BULK\MATERIAUX
            FINAL PATH = M:\ACA\Satellite_V02\\BULK\MATERIAUX\Satellite_V02_Materiaux.blk

        For LINUX        : 
            Satellite_V02_bddm = /data/struture/ACA/Satellite_V02/BULK/MATERIAUX
            FINAL PATH =    /data/struture/ACA/Satellite_V02/BULK/MATERIAUX/Satellite_V02_Materiaux.blk

With the environment variables the same nastran file can be loaded under PATRAN Windows or PATRAN Linux.

That is why, in the code which I modified, I replace simply the word before the colon (:) by the environment variable , Independently of the path of the nastran file.
        # Récupération Valeur Variable Environnement Projet
        if nt.environ.has_key(ifilepaths[0].strip()) :
          
          currVarEnv = nt.environ[ifilepaths[0]]
        
          filename = os.path.join(currVarEnv , ifilepaths[1])
          filename_FINAL_02 = currVarEnv + '/' + ifilepaths[1]

**Comment by SteveDoyle2** [comment]
As I said previously, nested environment variables are not supported.  Your fix would result in the same behavior as what currently exists.  Instead of using:

> simply the word before the colon (:) by the environment variable

the recommended way to expand environment variables in Python is to use:

    os.expandvars(path)

Using the Windows case:

    # doesnt work
    SET Satellite_V02_base=M:\ACA\Satellite_V02
    SET Satellite_V02_bddm=%Satellite_V02_base%`\BULK\MATERIAUX
    echo Satellite_V02_bddm = %Satellite_V02_bddm%

    # works
    SET Satellite_V02_bddm=M:\ACA\Satellite_V02\BULK\MATERIAUX
    echo Satellite_V02_bddm = %Satellite_V02_bddm%

for the INCLUDE:

    INCLUDE 'Satellite_V02_bddm:Satellite_V02_Materiaux.blk'
