### ISSUE TITLE
Model NASTRAN with NSML1 , NSMADD

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#406]
I use a model NASTRAN with NSML1 and NSMADD and NSM in the properties. When I calculate the masses and the inertia with pyNastran(model.mass_properties() AND model.get_mass_breakdown([pid] ), the NSML1 is not taken into account in the masses and inertia resulting.

Is PyNastran take the NSML1 in the calculation of the masses and the Inerties

**Comment by SteveDoyle2** [comment]
No, the mass properties methods do not consider NSM/NSM1/NSML/NSML1/NSMADD cards.  They were added fairly recently.

**Comment by PabloBeranger** [comment]
Have you planned a date for the implementation of the NSML in the calculation of the total masses and the inertias ? Thanks

**Comment by SteveDoyle2** [comment]
No.  There are currently no plans for adding NSM cards to the `mass_properties` function.  There are a lot of other issues that are higher priority.

**Comment by SteveDoyle2** [comment]
merging with #416
