### ISSUE TITLE
sum_forces_moments error

### ISSUE THREAD

**Issue by subbu124** [SteveDoyle2/pyNastran#408]
Code seems (v 1.1.0+Dev) to be not working correctly while calculating the sum of applied forces and moments, I dug a bit into this and found out that, if in bdf load collection is defined not in order ( like 14 after 17), the code is sorting/ starting loads in ascending order (like 14 then 17) but scale factors collected are not aligned with this newly ordered loads. So if -1.,17,1.,14 is there in load combination, sum is done like -1*14+1*17. Please try to address this

**Comment by SteveDoyle2** [comment]
Please provide an small example,

**Comment by subbu124** [comment]
[Doc4.docx](https://github.com/SteveDoyle2/pyNastran/files/1178850/Doc4.docx)

Please go through above file

**Comment by SteveDoyle2** [comment]
That's not an example.

I need LOAD cards, some loads (e.g., FORCE, PLOAD), the expected result, and the actual result.

**Comment by subbu124** [comment]
Ok,I will try to create a simple example, and get back to you.

**Comment by subbu124** [comment]
[FILENAME.docx](https://github.com/SteveDoyle2/pyNastran/files/1179046/FILENAME.docx)

Please find the example

**Comment by SteveDoyle2** [comment]
Thank you for that.  The bug should be fixed.

**Comment by subbu124** [comment]
And though ordering in ascending seems to be working , in other case as in doc4.docx I sent you, even though I put things in order, scale factors and loads are jumbling out. Please also check that, also. I will try to find why that is happening and get back to you if I find anything useful

**Comment by SteveDoyle2** [comment]
Again, I need a BDF.  A picture of a load card is not helpful

**Comment by SteveDoyle2** [comment]
To be clear, I don't need you figure out why it's happening, just if it is, what you expect, and then reproducing it with a non-proprietary example.  Having a deck is useful because Nastran is so complicated, but presumably it can get the answer right.

**Comment by subbu124** [comment]
OK, I understand, I will try to create bdf which can replicate the said error

**Comment by SteveDoyle2** [comment]
Were you able to find another error?  I'd like to close this if it's done.

**Comment by subbu124** [comment]
Sorry for busy with some other work, anyways if you fixed the one in the bdf I sent, close this.

**Comment by subbu124** [comment]
Sorry for busy with some other work, anyways if you fixed the one in the bdf I sent, close this.

**Comment by subbu124** [comment]
Sorry got busy with some other work, anyways if you fixed the one in the bdf I sent, close this.

**Comment by SteveDoyle2** [comment]
No worries.
