### ISSUE TITLE
mass_properties for ELEMENT MASSE

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#409]
When i use the function : 
    mass_CONM2 , cg_CONM2 , I_CONM2 = bdf2.mass_properties(mass_ids = [IDS Element MASSE] )  
i receive the error message : 
  Traceback (most recent call last): .....
  pyNastran-master_17072017\pyNastran\bdf\methods\mass_properties.py", line 88, in _mass_properties_elements_init
    assert len(model.mass_ids) > 0
  AttributeError: 'BDF' object has no attribute 'mass_ids'
  
I think there is an error in the function : 
  def _mass_properties_elements_init(model, element_ids, mass_ids): of the module mass_properties.py

  assert len(model.mass_ids) > 0 will be > assert len(model.masses) > 0 
    similar of the ELEMENT > assert len(model.elements) > 0
When I modify the code in this way, I have no more the error.
 
Do you think the same thing as me ?
Thanks

**Comment by SteveDoyle2** [comment]
You're correct.  The mass_ids attribute was removed.

The bug is now fixed.
