### ISSUE TITLE
GUST add_card wrong reference to velocity field

### ISSUE THREAD

**Issue by jbussemaker** [SteveDoyle2/pyNastran#413]
First of all, thanks for the awesome package, saves me lots of time!

I just ran across the following bug: in the add_card method of the GUST class (pyNastran.bdf.cards.aero), the field index of the velocity (V) field should be 5, not 4 as it is now.

Would be nice if that could be fixed!

**Comment by SteveDoyle2** [comment]
Yeah for B-list cards on B-list solutions.  The funny thing is I use that solution...odd.

It's fixed!
