### ISSUE TITLE
NASTRAN BULK CARDS : NSM , NSM1 , NSML , NSML1

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#416]
The version of pyNastran reads cards NASTRAN NSM, NSM1, NSML, NSML1 of the bulk.   
Then pyNastran record all these cards under the format of Class NSM1.

But for NSM  and NSM1  The value type is Surface Mass Kg / m ²
and for NSML and NSML1 The value type is Mass Kg .

Thus to be able to calculate the good mass, it is necessary to be able 
  to get back the good type of NSM.
  
Is it possible to have the good type for every NSM?  
  BDF.nsms['ID NSMx'][0].type = NSM   pour carte NSM
  BDF.nsms['ID NSMx'][0].type = NSM1  pour carte NSM1
  BDF.nsms['ID NSMx'][0].type = NSML  pour carte NSML
  BDF.nsms['ID NSMx'][0].type = NSML1 pour carte NSML1

**Comment by SteveDoyle2** [comment]
> Then pyNastran record all these cards under the format of Class NSM1.

I guess I don't follow what you mean by that.  NSM and NSM1 inherit from Property,  NSML inherits from NSM and NSML1 inherits from NSM1.  Inheritance is used for the NSML and NSML1 cards because the format of the cards are the same (e.g., the readers and writers).

All of the cards in pyNastran (including those), have a self.type attribute, which is correct.

> Is it possible to have the good type for every NSM?

No.  The cards in pyNastran (attempt to) follow the QRG as closely as possible.

Per the QRG, the NSM and NSM1 cards supports nonstructural mass on a Surface Mass (kg/m^2) or Surface Length (kg/m) basis.  It should be exactly the same for NSML and NSML1.

That math though, is not currently done in pyNastran.

**Comment by PabloBeranger** [comment]
The NSM can be defines in property card or by the specific BULK CARD NSM NSM1 NSML and NSML1(see QRG)

For BULK CARD NSM NSM1 NSML and NSML1 the value of NSMx can be applied on PROPERTY oe ELEMENT :
  PROPERTY( PSHELL, PCOMP, PCOMPG, PBAR, PBARL, PBEAM, PBEAML, PBCOMP, PROD, 
            CONROD, PBEND, PSHEAR, PTUBE, PCONEAX, and PRAC2D)
  

For NSM defined in property card the unit value is Kg/m² or Kg/m
  In this case the MASS = NSM x Area of Elements property OR
                   MASS = NSM x Length of Elements property
 
For NSMx defined by BULK CARD NSM NSM1, the unit value is Kg/m² or Kg/m
  In this case the MASS = NSM x Area of Elements property if TYPE = PROPERTY
                   MASS = NSM x Area of selected Elements if TYPE = ELEMENT
                   MASS = NSM x Length of Elements property if TYPE = PROPERTY
                   MASS = NSM x Length of selected Elements if TYPE = ELEMENT
                   
                   
For NSMLx defined by BULK CARD NSML and NSML1 the unit value is Kg
  
  For NSML1 : the MASS for every PROPERTY or ELEMENT(depending of TYPE) is in proportion to the 
              total surface of properties or elements.
              
    In this case the MASS = NSML1 x Area   of Elements property / Area of ALL Elements properties
                     MASS = NSML1 x Length of Elements property / Length of ALL Elements properties
    
    Example :
    NSML1   420     PSHELL  20.0    20000   20010   20001   20011   40001                     
    +       40011                    
    
    Tha MASS for the property 20000 is :
      20(Kg) * (Area of Property 20000) / (Areas of Properties 20000 20010 20001 20011 40001 40011)
      
      
  For NSML : the MASS for the property in simple it is egual at the value.
    Example :
    NSML,300,PSHELL,20000,10.0,20010,20.0
    
    Tha MASS for the property 20000 is : 10.0Kg
    
It is the same philosophy of calculation if the type is ELEMENT  instead of PROPERTY.
  
You can use the NASTRAN CARD     "ELSUM (EIDSUM, PIDSUM,,SUMMARY) = ALL"  to see in the f06 the result off the differents NSMx.


[TEST_NSMx.zip](https://github.com/SteveDoyle2/pyNastran/files/1291970/TEST_NSMx.zip)

**Comment by PabloBeranger** [comment]
Do you think you can integrate the calculation of the TOTAL mass with the addition of the mass 
coming from the bulk cards NSM , NSML , NSM1 , NSML1 ?

Today, pyNastran calculates the mass of an ELEMENT with:
    MASS ELEMENT = (Area ELEMENT x Thickness x Rho) + (Area ELEMENT x NSM Property)
    
But the mass coming from the other bulk cards(NSM , NSML , NSM1 , NSML1) is not taken.
The bulk cards NSM , NSML , NSM1 , NSML1 add MASS on Elements and/or Properties (it depends of the field TYPE see QRG) 

The total mass should be for ELEMENT :
  MASS ELEMENT = (Area ELEMENT x Thickness x Rho) + (Area ELEMENT x NSM Property) + (Area ELEMENT x NSMx ELEMENT(NSM and/or NSM1 and/or NSML and/or NSML1)
  
  MASS PROPERTIES = (Area ELEMENT x Thickness x Rho) + (Area ELEMENT x NSM Property) + (Area Property x NSMx Property(NSM and/or NSM1 and/or NSML and/or NSML1)

**Comment by SteveDoyle2** [comment]
I'll have to take a look.  My computer is having problems right now, so I can't promise when.

Those formulas are very helpful though.

**Comment by SteveDoyle2** [comment]
I've got I think the first attempt at this.  It only supports CQUAD4/PSHELLs at the moment, but I given my confusion, I think that's enough.  

The function is currently:

    _mass_properties_new(model, element_ids=None, mass_ids=None, nsm_id=None)

which is found in `bdf/mesh_utils/mass_properties`

My understanding for NSM is:

    mass = (element.area x element.thickness x element.rho) + (element.area x element.nsm) + (element.area x nsm.value)

Thus, for 2 elements, it's a simple sum, regardless of what's on the NSM/NSM1/NSML/NSML1 card.

Similarly, for a line element, it's:

    mass = (element.length x element.area x element.rho) + (element.length x element.nsm) + (element.length x nsm.value)

Furthermore, there is no support for NSM on a solid element.

The example you provided is too complicated for me to really understand effectively (id=20000 is used repeatedly across multiple NSMx cards; multiple ids are used on multiple cards; too many elements, complicated numbers).   I think to really get this right, I need a simple example with a few elements (no more than 10) with simple numbers and documented (e.g., with areas tabulated).

**Comment by SteveDoyle2** [comment]
Alright...those NSM formulas are actually more complicated:

There are multiple parts.  The elemental part:

    mass = (element.area x element.thickness x element.rho) + (element.area x element.nsm)

The NSM/NSM1 part.  The nsm for each element adds as similar to the standard NSM/area as follows:

    mass = (element.area x nsm.value)

The NSML1 part.  The nsm is the total nsm on the card(so not applied to each element).  The mass simplifies to the NSM/NSM1 for a single element:

    total_area = sum([element.area for element in elements])
    mass = (element.area x nsm.value) / total_area

That leaves the NSML, which all the documentation points to it being the same as the NSML1.  However, it always degenerates to the NSM card, making me a bit confused on why it has a separate card.  Any ideas?

**Comment by PabloBeranger** [comment]
is the mass coming from the NSM, NSM1 NSML MSML1 cards included in the mass of the associated properties and associated elements ?
Otherwise how to calculate the overall mass of a property or a element on which NSMx is applied ?

is the module _mass_properties_new functional because it is written "don't use this" in mass_properties.py ?

**Comment by SteveDoyle2** [comment]
I guess my answer is I think so.  I was baviv trouble understanding the
output because there were multiple NSM cards, so I wasn't sure what to look
at.  The tests in bdf/cards/test/test_nsm.py all pass, but might not all be
logically correct.

Regarding the don't use note, that should be removed.  There are a few tpl
models that get a different answer than the other method, which doesn't
consider nsm/differential shell thickness, but that is expected.  I would
compare with the f06 though at lesst for now.

**Comment by PabloBeranger** [comment]
NSM: Writing on 1 Line
          For each ID PROPERTY, Take ID Area PROPERTY / ELEMENT
          For each ID retrieve the value of NSM
          Value NSM = ValueID * Area of ​​ID PROPERTY
          Value NSM = ValueID * Length of the ID PROPERTY
          MASS Value NSM = ValueID * ELEMENT ID Area
          MASS value NSM = ValueID * Length of the ELEMENT ID

      NSML: Writing on 1 Line
          For each ID PROPERTY, Take ID Area PROPERTY
          For each ID retrieve the value of NSM
          NSML MASS Value = ValueID * ID Area PROPERTY

          
      NSM1: Writing on 1 Line OR Multiple Lines
          For each ID PROPERTY, Take ID Area PROPERTY
            Value MASSE NSM1 = Value * Area of ​​the ID PROPERTY
      

      NSML1: Write on 1 Line OR Multiple Lines
          Calculate the TOTAL AREA of Aires IDs PROPERTY
            Value MASSE = Value * Area of ​​the ID PROPERTY / TOTAL AREA
          
        (Same if Type ELEMENT)

With the line ELSUM in your NASTRAN JOB, you have the output in the f06 : 
    
![image](https://user-images.githubusercontent.com/19569215/36644920-7d007f16-1a61-11e8-866f-cf7e8a14867a.png)

f06 : 
![image](https://user-images.githubusercontent.com/19569215/36644955-eaeca040-1a61-11e8-93a3-ea38f769deb3.png)

Here in an example : 
[TEST_NSM_SOL101.zip](https://github.com/SteveDoyle2/pyNastran/files/1756576/TEST_NSM_SOL101.zip)


The test I did with NSM ID 100 does not give the right result
 ![image](https://user-images.githubusercontent.com/19569215/36645020-fb36d366-1a62-11e8-8bce-c980728b7182.png)
 
Result pyNastran
![image](https://user-images.githubusercontent.com/19569215/36645047-50679078-1a63-11e8-8030-60bef04e1c2c.png)

the result should be 2Kg

**Comment by PabloBeranger** [comment]
the result should be 0.2Kg

**Comment by SteveDoyle2** [comment]
Where do you see 0.2 kg?  The answer I see is 424.3234 from the OGWPG
table.  Also, this is non-dimensional right?

**Comment by PabloBeranger** [comment]
In the file TEST_NSM_SOL101.dat , the NSM ID 100 is : 
![image](https://user-images.githubusercontent.com/19569215/36660324-0fe4cd0c-1ad8-11e8-9d4c-4c32022928da.png)
That means : 
    10Kg/m2 for PSHELL ID 20000 
    10Kg/m2 for PSHELL ID 20010
     The AREA of ELEMENT with PSHELL ID 20000 = 0.01m2
     The AREA of ELEMENT with PSHELL ID 20010 = 0.01m2
      So the mass defined by the NSM 100  card for PSHELL ID 20000 is : 10Kg/m2 x 0.01m2 = 0.1Kg
      So the mass defined by the NSM 100 card for PSHELL ID 20010 is : 10Kg/m2 x 0.01m2 = 0.1Kg
          Thre TOTAL mass defined by the NSM 100 = 0.1Kg + 0.1Kg = 0.2Kg

This is the result that gives nastran in the f06 : 
   
![image](https://user-images.githubusercontent.com/19569215/36660960-284249d6-1ada-11e8-849c-a99b09826c29.png)

**Comment by PabloBeranger** [comment]
For the nsm there are several cases:
  > the nsm defined in the property CARDS like PSHELL, PBAR .... more see NASTRAN QRG

   > The NSM bulk card see NASTRAN QRG 
        the NSM , NSM1, NSML, NSML1 cards define different ways of distributing the surfacing mass value                       or linear mass value (depend of TYPE).

In addition these cards can be assigned on different types of entities (PROPERTY, ELEMENT)
![image](https://user-images.githubusercontent.com/19569215/36714481-bf38665a-1b92-11e8-8901-f5bd3bc0aaa3.png)

The NSMADD card sum the mass of the different cards NSM , NSM1, NSML, NSML1

But I think you have to know all this for writing the code in pyNastran. Is not it ?

**Comment by SteveDoyle2** [comment]
I do.  I've just never used the builtin mass breakdown table.  I prefer to
develop on small problems so it's obvious what is going on.  Once that
works, I do a big problem.  The nsm from the PSHELL card is just obscuring
the answer I care about.

**Comment by SteveDoyle2** [comment]
I've got the NSM PSHELL/PCOMP case fixed.  There was an issue with the area not being computed correctly (all the elements were used).  I'm sure there are other issues, so there is still more work.

Also, I think you misunderstood how the mass properties function is working.  You implicitly specified all the element ids (so CQUAD4s, so implicitly the  area*(NSM + t*rho)) and the conm2s and all the NSM=100 data.  The expected answer for just the NSM=100 info is 0.2 kg, but your expected answer is calculated as: 

    mass_properties() - mass_properties(nsm=100) = 0.2

As a similar side effect, if you limit the element ids that are passed in and request nsm=100, if you didn't specify all the ids used by in nsm=100, the mass won't be distributed to all the elements in that set.

**Comment by SteveDoyle2** [comment]
errr...with positive mass...

mass_properties(nsm=100) - mass_properties()

**Comment by PabloBeranger** [comment]
It is true that it is difficult to know and understand the functioning of the different functions of pyNastran for a person who has not written the code.

Also how do you test the NSM with test_bdf.py?

How do you test the NSM, NSM1, NSML, NSML1, NSMADD?

How do you check the results of these cards with the results given by NASTRAN ?

How do you check the TOTAL mass when the mass : 
   > comes from the density of the material 
   > comes from the NSM defined by the PROPERTY 
   > comes from NSM, NSM1, NSML, NSML1 if there is any
??

mass_properties(nsm=100) is it possible because I did not find this option for this function ????

**Comment by SteveDoyle2** [comment]
I testthe nsm using 1 and 2 element probems found in
bdf/cards/test/test_nsm.py.

I don't need to consider material density or property nsn because it gets
the right answer to numerical precision as long as the element does not
havea centroid at 0,0,0. Lines use L*(nsm+A*rho).  Shells use A*(nsm+t*rho)
and solids use rho*V.  I have various tests for things like area of a quad,
thickness of a pcomp, etc.  Then I do the full mass test.

I prefer to just compare to the OGPWG table, but to actually see the
contribution to a single element, I need to not mask the numbers with
other, much larger values.  I also look at the inertia.

In regards to understanding the functionality, you gotta do your due
dillegence on real problems usually with the qrg handy, as well as
occasionally look through the code.  Nastran is huge and there is no way
around that.  Most functions that do anything complicated are documented,
but with a lot of code, now you have a lot of documentation, so it's hard
to find.  Looking at the code is usually just easier.

If you're not very familar with python or using an IDE, you'll probably
have a tough time.  Then it's just understanding the organization, so you
know where to look.

**Comment by SteveDoyle2** [comment]
In regards to:

> How do you check the TOTAL mass when the mass...

I make a separate model for each, so the same way you'd do it with Nastran.  I look at the OPGWG table, so:

         O U T P U T   F R O M   G R I D   P O I N T   W E I G H T   G E N E R A T O R
                                    REFERENCE POINT =        0
             DIRECTION
        MASS AXIS SYSTEM (S)     MASS              X-C.G.        Y-C.G.        Z-C.G.
                X            1.773637E+00      1.744462E-17  1.249067E-02 -2.010698E+01
                Y            1.773637E+00     -7.539155E-02  1.746754E-17 -2.010698E+01
                Z            1.773637E+00     -7.539155E-02  1.249067E-02  0.000000E+00

If I'm trying to add functionality (e.g., to support NSM cards), then I want the mass to only be coming from NSM cards.  If I'm testing NSMADDs, I'll use a different model.  If I'm testing CBEAMs (the result is known to be not quite right if you have nsm offsets), I use a different model.

When I'm working with a new model, I also validate the loads and mass properties.  I can't commit them though.

Unit tests (so tiny tests that run instantly that test something very small) are easier to debug and don't timeout the build.  I don't want to commit a test problem that uses 100 quads if I don't have to, when 3 will do.

**Comment by PabloBeranger** [comment]
I just did a test of the _mass_properties_new function with an NSM assigned to a PBARL :
![image](https://user-images.githubusercontent.com/19569215/36860455-92aebf94-1d81-11e8-819a-8cd5e55b69ec.png)

mass, cg, I = _mass_properties_new(bdf2 , nsm_id =1000 , dev=False)

The mass of the NSM 1000 is not added at the model mass
![image](https://user-images.githubusercontent.com/19569215/36860834-b0384c1e-1d82-11e8-87dc-cba06dc6d7c5.png)

[TEST_NSM_MODEL_BARRES_SOL103_N2014_SP_V01.dat.zip](https://github.com/SteveDoyle2/pyNastran/files/1772236/TEST_NSM_MODEL_BARRES_SOL103_N2014_SP_V01.dat.zip)

**Comment by SteveDoyle2** [comment]
I've updated a few things to clean things up and better test some of the capability (e.g., actually support NSM,PSHELL,1.0,ALL).  It should be much more correct.

I get the following:

    mass = 18.57602875205866
    cg   = [0.3172265  0.1088072  0.16459938]
    Ixx=0.8518654078441317, Iyy=2.6945079955294053, Izz=2.4111248878499802
    Ixy=0.7663617188235192, Ixz=0.9492808625617597, Iyz=0.3221205737811732

    nsm_id=1000
      mass = 19.776028752058597
      cg = [0.3172265  0.1088072  0.16459938]
      Ixx=0.8518654078441317, Iyy=2.6945079955294053, Izz=2.4111248878499802
      Ixy=0.7663617188235192, Ixz=0.9492808625617597, Iyz=0.3221205737811732

    nsm_id=30
      mass = 19.776028752058597
      cg = [0.3172265  0.1088072  0.16459938]
      Ixx=0.8518654078441317, Iyy=2.6945079955294053, Izz=2.4111248878499802
      Ixy=0.7663617188235192, Ixz=0.9492808625617597, Iyz=0.3221205737811732

which is consistent with:

         MASS     
     1.977603E+01 
     1.977603E+01 
     1.977603E+01 

The inertia is slightly inaccurate due to the mr^2 approach, but that's expected.

**Comment by SteveDoyle2** [comment]
What I did notice is you didn't request any NSM in the deck, so it won't match the results I showed.

**Comment by SteveDoyle2** [comment]
For the other test problem, the results I've got are:

    nsm_id mass      nsm
    30     385.9     367.5
    100    18.65     0.2
    110    18.69     0.24
    200    22.45     4
    210    21.45     3
    220    36.45     18
    300    48.45     30
    310    107.5     89
    400    43.45     25
    410    53.45     35
    420    38.45     20
    430    48.45     30
    500    18.45     0.00135
    510    18.45     0.0008924
    600    18.46     0.005001
    610    18.46     0.007499
    620    18.47     0.015
    700    19.95     1.5
    710    19.95     1.5
    800    43.45     25
    810    53.45     35
    820    38.45     20
    830    48.45     30

**Comment by SteveDoyle2** [comment]
Here you go:

    def test_nsm():
        """tests a complete nsm example"""
        bdf_filename = os.path.join(MODEL_PATH, 'nsm', 'nsm.bdf') # nsm.bdf
        bdf_filename = os.path.join(MODEL_PATH, 'nsm', 'TEST_NSM_SOL101.bdf') # nsm.bdf
        model = read_bdf(bdf_filename)
        from itertools import chain
        print('    %6s %-9s %s' % ('nsm_id', 'mass', 'nsm'))
        mass0 = model._mass_properties_new(debug=False)[0]
        for nsm_id in sorted(chain(model.nsms, model.nsmadds)):
            mass, cg, I = model._mass_properties_new(nsm_id=nsm_id, debug=False)
            print('    %-6s %-9.4g %.4g' % (nsm_id, mass, mass-mass0))

**Comment by PabloBeranger** [comment]
Hello ,
I have the following error for calculating CDG and inertias with NSM, NSM1, NSML, NSML1 on 1D ELEMENT : 
![image](https://user-images.githubusercontent.com/19569215/36966900-912472b0-205e-11e8-9fd9-c9a459fc2ed0.png)


Herewith the model and the script : 
[NSM_ELEMENT_1D.zip](https://github.com/SteveDoyle2/pyNastran/files/1780210/NSM_ELEMENT_1D.zip)

**Comment by SteveDoyle2** [comment]
The check for were any elements found was incorrect leading to the arrays coming out of the setup method being lists leading to the error you saw.  It incorrectly assumed that you had at least 1 area element.  That wasn't intentional, but was just a way to check that any elements were found.
