### ISSUE TITLE
CLASS NSM and NSM1 does not take into account the writing on several lines

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#418]
The CLASS NSM and NSM1 return only the value for the first line.

$..1....$..2....$...3...$...4...$...5...$...6...$....7..$...8...$...9...$..10...
NSM     301     PSHELL  20000   10.0    30000   10.0    30001   10.0  
+       50000   10.0    99995   10.0    99995   10.0

pyNastran return : 
 Num NSM 8 / 10 : ID = 301 Val = [$..1....$..2....$...3...$...4...$...5...$...6...$....7..$...8...$...9...$..10...
                                      NSM          301  PSHELL   20000     10.
                                      , $..1....$..2....$...3...$...4...$...5...$...6...$....7..$...8...$...9...$..10...
                                      NSM          301  PSHELL   30000     10.
                                      , $..1....$..2....$...3...$...4...$...5...$...6...$....7..$...8...$...9...$..10...
                                      NSM          301  PSHELL   30001     10.
                                      ] ; type Val = <type 'list'> ; NB Val = 3 

The same thing for NSM1.

You can see example nsmadbig.dat  from NASTRAN tpl

**Comment by SteveDoyle2** [comment]
Do you have an an example that loads in?

pyNastran does not support:


    >>> test_bdf nsmadbig.bdf

    pyNastran.bdf.errors.DuplicateIDsError: self.elements IDs are not unique=[25
    old_element=
    CSHEAR        25       1     111     121     181     171

    new_elements=
    CBAR          25      22       1       2      0.      1.      0.

The element/property ids have to be unique.

**Comment by SteveDoyle2** [comment]
At least some of the NSM bugs are fixed.  Inherited and overwritten class variables don't actually overwrite, so at least some things were going to the wrong classes.

Do you have documentation on the NSM card supporting more than 1 line?  It's not in the QRG.

**Comment by PabloBeranger** [comment]
No i do not have the documentation.
But when i run a job with NSM and NSML writing on more than 1 line, i do not have fatal and with the card ELSUM (EIDSUM, PIDSUM,SUMMARY) = ALL i retrieve in the f06 the good value.

I ask the question to the MSC support .

You can indicate me how to run, >>> test_bdf XXXX.dat ,because I always have an error ?

**Comment by PabloBeranger** [comment]
MSC confirms that we cannot write on several lines the card NSM and NSML.
With NASTRAN 2012 and above, the job has no FATAL because the IFPSTAR = YES. If IFPSTAR = NO then the job has a FATAL.
With nastran version lower at 2012 the job has a FATAL

**Comment by SteveDoyle2** [comment]
What is probably happening is they're just dropping the secondary lines.

A similar thing happens (at least up to NX 10) with what happens to the
LOAD card.  In NX (and I thought it used to be the case in MSC, but I'm not
100%) is that if you reference a LOAD card with another LOAD card, it
doesn't complain, but it drops the LOAD.

PyNastran is designed to work on well formatted decks.  So things like
missing nodes or duplicate element ids or MPC=5 in the case control that
doesn't reference an MPC are assumed to be error rather that intended, but
depending are all totally fine in Nastran.  'test_bdf' is designed to test
different issues and it very useful when debugging a deck.  It catches many
things Nastran does not.  It's my go to thing for understanding a model as
well as I know what cards it uses, that it doesn't have missing cards, etc.

**Comment by SteveDoyle2** [comment]
I think this is a non-issue; closing
