### ISSUE TITLE
Question on test_bdf.py

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#419]
Can you explain me how work test_bdf.py, because i have always error?
Look at what I'm doing on the image.
![pynastran_test_bdf_](https://user-images.githubusercontent.com/19569215/30398225-e9979646-98cf-11e7-9902-17d60ad7875e.jpg)

And in a general way all test_xxx.py.

Thanks

**Comment by SteveDoyle2** [comment]
I'd run it outside of ipython like in cmd/powershell

> And in a general way all test_xxx.py

See the docs.  It's linked right near the top of the main page in the
Version/Docs/Status table.

http://pynastran-git.readthedocs.io/en/latest/?badge=latest
