### ISSUE TITLE
BUG : Write ACCEL1 card with THRU and THRU BY

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#420]
Writing of the card ACCEL1 with the format:
   > IdGRID1 THRU IdGRID10
   > IdGRID1 THRU IdGRID10 BY 2 (or X Value and if the X value correspond at an ID GRID)

test_bdf or bdf.write_bdf(path_File) do not write correctely the ACCEL1 card when theris the
  syntax THRU or THRU BY :
    > pyNastran add the number of BY (in this case 2) to the list of GRID.
    > py Nastran does not take the LAST GRID defined by THRU is not on the step

Example : 
  Read BDF
![accel1_input](https://user-images.githubusercontent.com/19569215/30519141-e4a0d1cc-9b8e-11e7-9905-493d353a1394.jpg)

  Write by pyNastran or test_bdf
![accel1_output_pynastran](https://user-images.githubusercontent.com/19569215/30519152-142bc51e-9b8f-11e7-83d2-5c172109b988.jpg)
       The value of BY is added and then last ID of THRU is missing (10 for ACCEL1 4 and 24 for ACCEL1 5)

  Output From PATRAN
![accel1_output_patran](https://user-images.githubusercontent.com/19569215/30519187-c137ddec-9b8f-11e7-9e37-86881af31f9b.jpg)

Here is my test file 
[accel1qr_ACA.zip](https://github.com/SteveDoyle2/pyNastran/files/1308941/accel1qr_ACA.zip)

**Comment by SteveDoyle2** [comment]
Thanks.

I'll take a look

**Comment by SteveDoyle2** [comment]
The two issues are fixed.  The BY issue was just an off-by-1 error.  I thought it was tested before (it is now).

The 1,THRU,10,BY,2 is a bit odd, but Nastran is full of undocumented oddities.
