### ISSUE TITLE
BUG When bdfXX.write_bdf with NSM in PSHELL card : the NSM IS NOT WRITING

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#421]
When i write the BDF with (bdfXX.write_bdf) with NSM in PSHELL card the NSM is NOT WRITING.
I have a script pyton which simply read the bdf and write the bdf.
My bdf file in input has : 
      ![bug_write_pshell_01](https://user-images.githubusercontent.com/19569215/30707731-b6c7ffca-9efc-11e7-9cfd-75d2726a08b2.jpg)

The bdf in output : 
     ![bug_write_pshell_02](https://user-images.githubusercontent.com/19569215/30707764-d54f2054-9efc-11e7-86b0-7cb4ce8db6e7.jpg)

My script : 
[PSHELL.zip](https://github.com/SteveDoyle2/pyNastran/files/1322094/PSHELL.zip)

Does this error  also present in the other cards which have NSM ?

**Comment by SteveDoyle2** [comment]
> Does this error also present in the other cards which have NSM?

Just PSHELLs.  It's the ts/t field, not NSM.

The bad line was:

        if tst or tst2 is None:
            tst = None

And should be:

        if tst is None or tst2 is None:
            tst = None
