### ISSUE TITLE
Not able to read neutral nastran binary result file (*.neut)

### ISSUE THREAD

**Issue by belzedar64** [SteveDoyle2/pyNastran#428]
PyNastran OP2 module is not able to read neutral binary file format (Nastran result file *.neut)

Is there a way to read them without making a 'rcout2' transformation ?
In pyNastran, is there a way to convert them before read OP2 tables ?

**Comment by SteveDoyle2** [comment]
I guess I'm not at all familiar with the *.neut file.  I assume it's an output file, but I'm not aware of the flag to create it.  What does it do differrently from an OP2 (e.g., different results)?  Also, do you know where the format is documented?

**Comment by SteveDoyle2** [comment]
closing due to innactivity
