### ISSUE TITLE
Question: Read bdf and simply INCLUDE files

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#431]
Is there a simple way to read a bdf (.read_bdf) without perform any other operation except insert the INCLUDE files in the bdf? I have tried to disable the checks and xref (validate=False,xref=False) but it crashes because I've many "NASTRAN accepted" errors in my model.

**Comment by SteveDoyle2** [comment]
Not explicitly no  If you look at the top of the ``read_bdf`` method, you'll see what you need:

    def read_bdf(self, bdf_filename=None,
                 validate=True, xref=True, punch=False, read_includes=True, encoding=None):
        """
        Read method for the bdf files

        Parameters
        ----------
        bdf_filename : str / None
            the input bdf (default=None; popup a dialog)
        validate : bool; default=True
            runs various checks on the BDF
        xref :  bool; default=True
            should the bdf be cross referenced
        punch : bool; default=False
            indicates whether the file is a punch file
        read_includes : bool; default=True
            indicates whether INCLUDE files should be read
        encoding : str; default=None -> system default
            the unicode encoding

        .. code-block:: python

          >>> bdf = BDF()
          >>> bdf.read_bdf(bdf_filename, xref=True)
          >>> g1 = bdf.Node(1)
          >>> print(g1.get_position())
          [10.0, 12.0, 42.0]
          >>> bdf.write_card(bdf_filename2)
          >>> print(bdf.card_stats())

          ---BDF Statistics---
          SOL 101
          bdf.nodes = 20
          bdf.elements = 10
          etc.
        """
        self._read_bdf_helper(bdf_filename, encoding, punch, read_includes)

        self._parse_primary_file_header(bdf_filename)

        self.log.debug('---starting BDF.read_bdf of %s---' % self.bdf_filename)
        system_lines, executive_control_lines, case_control_lines, \
            bulk_data_lines = self._get_lines(self.bdf_filename, self.punch)

**Comment by alby3z** [comment]
I have written a simple script to do this task based on your suggestion:

```
# -*- coding: utf-8 -*-
"""
This script takes a NASTRAN exec file and replace INCLUDE statement with the
INCLUDEd file.
This is useful to create a single file to be submitted on the cluster

Created on Tue Oct 17 07:46:34 2017

@author: Alberto Trezzini
"""

import os
from pyNastran.bdf.bdf import BDF

# Set the working path where the executive BDF file is located,
# due to the fact that the INCLUDE path are written relatively to this folder

exec_path = '' # Here goes the path
os.chdir(exec_path)

#Instantiate a BDF object

bdf = BDF()

# Select the executive bdf file
exec_file = '' # Here goes the executive bdf path

# Perform bdf parsing
bdf._read_bdf_helper(bdf_filename=exec_file,read_includes=True,encoding=None,punch ='False')
bdf._parse_primary_file_header(bdf_filename=exec_file)
system_lines, executive_control_lines, case_control_lines,bulk_data_lines = bdf._get_lines(bdf.bdf_filename, bdf.punch)


outbdf = open('test.txt', 'w+', newline='')

for item in bulk_data_lines:
  outbdf.write(item) #print('.', end='')
  
outbdf.close()
```

**Comment by SteveDoyle2** [comment]
Oh I forgot to mention, there's a new function that should be way easier to use...

   lines = model.include_zip(bdf_filename=None, encoding=None)

**Comment by alby3z** [comment]
Very good! In which version did you put this function?

**Comment by SteveDoyle2** [comment]
New features always go into the master.  New features are not allowed in
old (e.g., 1.0) versions.  I keep meaning to to bug releases, but it's a
lot of extra work to port them over.
