### ISSUE TITLE
Error with RIGID=LAGRAN

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#432]
The code in case_control_deck.py don't take the value for LAGRAN.
     
![image](https://user-images.githubusercontent.com/19569215/31781720-73807b12-b4f9-11e7-9fb5-bab9abebcc89.png)

Nevertheless this value is the default value .
  
![image](https://user-images.githubusercontent.com/19569215/31781787-9cc30a1c-b4f9-11e7-89d8-3f93c2845504.png)

**Comment by SteveDoyle2** [comment]
LAGR was supported in addition to 'LGELIM', 'LAGRANGE', 'STIFF', 'LINEAR'.  LAGRAN has been added.  Everything is converted to long form (e.g., DISP -> DISPLACEMENT).

The code could check the first 4 character thing, but that's bad practice for things like STRE.
