### ISSUE TITLE
Question : Read individual INCLUDE 

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#435]
I have several INCLUDE.
I would like to read only a file at the same time with pyNastran to have the detail of the INCLUDE.
 I have a file which contains only cards SET and pyNastran return the error message : 
      
![image](https://user-images.githubusercontent.com/19569215/31826127-82968342-b5b4-11e7-81d8-cae39a158caa.png)

To do that , i execute this
   
![image](https://user-images.githubusercontent.com/19569215/31826254-d1617f5e-b5b4-11e7-8bde-fb8dcc0a2980.png)

or by the Class BDF()
   
![image](https://user-images.githubusercontent.com/19569215/31826292-eefcbc22-b5b4-11e7-93c9-1daa024804e0.png)

Here is my INCLUDE
  
[INCLUDE_SET.txt](https://github.com/SteveDoyle2/pyNastran/files/1402309/INCLUDE_SET.txt)

It is possible to read only this type of INCLUDE ?
Thanks

**Comment by SteveDoyle2** [comment]
That's not a valid nastran deck.  That's part of a case control deck.  You
told it to read the bulk data section with punch=True.  The punch name
comes from SOL 200, where you get a *.pch file that looks like a valid bdf,
but has no system/executive/case header.

Pass the lines into CaseControlDeck.
