### ISSUE TITLE
PyNastranGUI.exe crashes with DLL error when loading nastran model

### ISSUE THREAD

**Issue by SteveDoyle2** [SteveDoyle2/pyNastran#436]
This is a continuation of #429

> It looks like there's a DLL error. I'm on a different system (that's also been updated since I built the exe, but it used to work), but I'm getting:

    Intel MKL FATAL ERROR: Cannot load mkl_avx2.dll or mkl_def.dll

> That occurs after the gui launches and right after opening a file or just calling:
pyNastranGUI.exe geometry.bdf

> I really need a VM to test the gui on, but that's harder to get than it should be.

This goes away depending on how you have your environment set up.  Can you just delete out your PATH to test this?

**Comment by dmap-guru** [comment]
I got this error when trying the executable in pyNastranGUI_v1.0.0_2017-5-25.zip but not with the executable in pyNastranGUI_v0.9-dev_2017-2-25.zip.

When you run the either executable, a temporary directory is created in your %TEMP% directory.  With v0.9-dev, the 2 files mkl_avx2.dll and mkl_def.dll are copied to this directory, presumably as they are packaged in the v0.9-dev executable.  These DLLs are at version 2017.  With the v1.0.0 executable, a temporary directory is created in your %TEMP% directory, but this time, neither the file mkl_avx2.dll nor mkl_def.dll appears in the temporary directory.  If you don't have these DLLs on your system pyNastranGUI stops with the error when you try to load a Nastran input file.  If you do have these files on your system (e.g. from an Anaconda installation) these may not be the same version; on my Anaconda installation, the DLLs are at version 2018, so pyNastranGUI stops with the error when you try to load a Nastran input file.

A workaround to confirm the DLL version issue was to run v0.9-dev to let it create the temporary directory in %TEMP% and then copy the mkl_avx2.dll and mkl_def.dll files to where the v1.0.0 executable is located.  Quit v0.9-dev and start v1.0.0.  Now you can load a Nastran input file without the error.

It looks like mkl_avx2.dll and mkl_def.dll were not packaged with the v1.0.0 executable.

**Comment by mjredmond** [comment]
I have these kinds of problems all the time... if possible, you could use something like VirtualBox and a vanilla windows installation to test the program on.

**Comment by SteveDoyle2** [comment]
I dont have a spare Windows install disc though.  I want to use VMWare
player or Docker or whatever, but you need the VM/image.

**Comment by mjredmond** [comment]
You might be able to do it in linux with wine... [https://milkator.wordpress.com/2014/07/19/windows-executable-from-python-developing-in-ubuntu/](url)

**Comment by SteveDoyle2** [comment]
That actually sounds like it will work!  Great suggestion!

**Comment by SteveDoyle2** [comment]
There is is new pyNastranGUI dev version up on sourceforge now.  It's 99.9% the 1.1 release, which should be coming very soon.
