### ISSUE TITLE
Read BDF echo during parsing

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#439]
I notice that when `read_bdf ` parses the model, it outputs on the screen the echo of the process (in my humble opinion) slowing down the process:

![read_bdf](https://user-images.githubusercontent.com/20402436/32066048-8d74f7f2-ba4c-11e7-92e7-258208b374c1.png)

Is it possible to remove/change this?

**Comment by SteveDoyle2** [comment]
That's a result of the ECHOOn you have in your deck.  There was an error with how it was set that I've fixed.  That will not suppress messages though.

I've added a ``self.force_echo_off = False`` parameter to quiet the deck.

**Comment by SteveDoyle2** [comment]
closing; reopen if issues
