### ISSUE TITLE
GUI doesn't start with The 'vtk>=5.10.1' distribution was not found and is required by pyNastran

### ISSUE THREAD

**Issue by sovsep** [SteveDoyle2/pyNastran#443]
Hi,
when try to start GUI with "pyNastranGUI" I get a missing vtk library, but the python-vtk v.5.10.1 package is installed.

 `pyNastranGUI 
Traceback (most recent call last):
  File "/usr/local/bin/pyNastranGUI", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vtk>=5.10.1' distribution was not found and is required by pyNastran`

**Comment by SteveDoyle2** [comment]
So that looks like a setuptools bug.  So there are a few possibilities.

1.  You don't have vtk on your PYTHONPATH variable.  So if you load python and try `inport vtk`, that needs to run.  I'm a Windows guy, so I'm not really sure where things get installed to on Linux.

2.  Another option is that setuptools just has a bug and updating it might help.

3.  Install from source instead of from pip/pypi and use `python setup_no_reqs.py install`.  You can just bypass that setuptools check.

Hope one of those works!

**Comment by sovsep** [comment]
Ok, solved.
The problem was slightly different. Ubuntu python-vtk package is for python 2.7.
So I have installed vtk with pip3. By default it is in version 8.0. So far seems to work.

But, there is another issue. If using "load geometry" in the dialog window no bdf files or any other file is shown and can not be selected. Only option how to load a bdf is from the command line, when executing pyNastranGUI yournastran.BDF.

**Comment by SteveDoyle2** [comment]
The name loader might be case sensitive on linux.  I've never actually
tried the gui on Linux, so I'm not sure.

Try making it filename.bdf instead of filename.BDF.

**Comment by SteveDoyle2** [comment]
The vtk issue was an issue .  If there's another bug, please make a new ticket.
