### ISSUE TITLE
Error in PBARL with NSM(NSM are not taken into account)

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#446]
I think there is an error for the NSMs properties PBARL.
I have a model with PBARL and NSM.
After reading the model with read_bdf, I browse the properties and the NSM are at 0 ??

Likewise with the test_bdf script, the NSMs are set to 0
        test_bdf nas101_PBARL_NSM.dat > nas101_PBARL_NSM.out
        
Is there the same problem with other 1D properties?

Here are my test files :
        my python script = ACA_Test_BDF_Envoie.py
        my NASTRAN file  = nas101_PBARL_NSM.dat
                reuly from my script = nas101_PBARL_NSM_Out_PyNastran_TestBDF.dat
                
        test_bdf command output = nas101_PBARL_NSM.out   
        test_bdf file output    = nas101_PBARL_NSM.test_bdf.dat  

[Envoie.zip](https://github.com/SteveDoyle2/pyNastran/files/1484002/Envoie.zip)

**Comment by SteveDoyle2** [comment]
I'm a bit surprised by that.  It's fixed though and only affects the PBARL.

I added some rod/bar/beam nsm tests.  No other issues.

**Comment by SteveDoyle2** [comment]
Thanks by the way!
