### ISSUE TITLE
Question : is it normal to have self.bdf_filename in _get_lines function ?

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#449]
In the bdf.py the function  _get_lines function the line(3745) : 
     main_lines = self._get_main_lines(self.bdf_filename, self.punch)
contain self.bdf_filename while the line(3721) is def _get_lines(self, bdf_filename):

**Comment by SteveDoyle2** [comment]
Maybe I'm not following the question.  _get_main_lines needs to check the header for the encoding.

Is there an issue?

**Comment by PabloBeranger** [comment]
Yes I think it's an issue. When I execute the script I have an error : 
![image](https://user-images.githubusercontent.com/19569215/33040249-c0e70ae2-ce3a-11e7-9741-b40c02299209.png)

If i replace the line : 
   main_lines = self._get_main_lines(self.bdf_filename, self.punch) 
by
   main_lines = self._get_main_lines(bdf_filename, self.punch)
I have no more . 
bdf_filename  corresponds to the bdf_filename that is transmitted by the function _get_lines

[Envoie_V02.zip](https://github.com/SteveDoyle2/pyNastran/files/1489085/Envoie_V02.zip)

**Comment by SteveDoyle2** [comment]
That was easy enough.  A variable wasn't being used.  It's fixed now.

You needed to set model.bdf_filename:
model = BDF()
model.bdf_filename = bdf_filename   # no longer required
model.get_lines(bdf_filename)
