### ISSUE TITLE
Error when i test H5 Nastran Example

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#463]
I have this e
![image](https://user-images.githubusercontent.com/19569215/34319095-2c61c9b2-e7d9-11e7-8e70-8216ff948cd9.png)
rror :

**Comment by SteveDoyle2** [comment]
I think that just needs the chr part removed.  @mjredmond  Thoughts?

**Comment by mjredmond** [comment]
This is likely a python 2 issue.  I use python 3, so I need to use chr to convert the first character in the line from integer to string to check for '$'.  I'll change it to be python2 compatible.  @PabloBeranger can you confirm that you're using python 2?  There's probably some other python 2 gremlins lurking in the code that I'll have to fix.

**Comment by mjredmond** [comment]
I got it working for me on python 2.7.14.  @PabloBeranger can you confirm that it works?  Thanks.

**Comment by PabloBeranger** [comment]
Yes i works with python 2.7.11

**Comment by mjredmond** [comment]
Thanks!
