### ISSUE TITLE
Issue with PBEAML having multiple cross-sections

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#464]
Hi,

While reading this PBEAML with few cross-sections, getting mentioned error. This format is expected to work. Any suggestions?

Regards,
Ravi

![image](https://user-images.githubusercontent.com/34907733/34404336-10e382ea-ebd3-11e7-9b2b-68b5f61f982f.png)

  File "F:\Program Files\Ansconda3\lib\site-packages\pyNastran\bdf\bdf_interface\assign_type.py", line 335, in double
    'card=%s' % (fieldname, svalue, ifield, dtype, card))
SyntaxError: dim_n=7_ii=0 = None (field #44) on card must be a float (not blank).
card=['PBEAML', '622', '623', None, 'BAR', None, None, None, None, 
'.238', '.238', None, 'NO', 
'.166', '.238', '.238', None, 'NO', 
'.510', '.126', '.126', None, 'NO', 
'.565', '.117', '.117', None, 'NO', 
'.619', '.126', '.126', None, 'NO', 
'.963', '.238', '.238', None, 'NO', 
'1.0', '.238', '.238', None, 'NO']

**Comment by SteveDoyle2** [comment]
Wow that's a really bad error message....at least that part looks like a version issue.  In the master it says:

    SyntaxError: istation=7; ndim=2; dim1 = None (field #44) on card must be a float (not blank).

It looks like the 'NO' on the second line is associated with station A, which should not have a SO field defined.  If that's valid in Nastran, it's either not defined in the QRG or the QRG is just confusing :)

The code also looks like it's expecting more dimensions after the final NO.  It looks like at least that part is an error.  So it looks like Remark 5 `If any of the fields NSM(B), DIMi(B) are blank on the continuation entry for End B, the values are set to the values given for end A.` is not supported.

**Comment by SteveDoyle2** [comment]
Remark 5 `If any of the fields NSM(B), DIMi(B) are blank on the continuation entry for End B, the values are set to the values given for end A.` is now supported.  The following card now works:

        fields = [
            'PBEAML', '623', '623', None, 'BAR', None, None, None, None,
            '.238', '.238', None,
            'NO', '.166', '.238', '.238', None,
            'NO', '.510', '.126', '.126', None,
            'NO', '.565', '.117', '.117', None,
            'NO', '.619', '.126', '.126', None,
            'NO', '.963', '.238', '.238', None,
            'NO', '1.0', '.238', '.238', None,
            'NO']

The next part of remark 5 `A. For the continuation entries that have values of X(j)/XB
between 0.0 and 1.0 and use the default option (blank field), a linear interpolation between the
values at ends A and B is performed to obtain the missing field.` is **NOT** supported.

**Comment by SteveDoyle2** [comment]
self.dim is now a numpy array as well.

**Comment by raviraj3997** [comment]
Thanks for the update! It helps a lot
I have downloaded latest pyNastran Master.
The cast mentioned in the query works now.!
