### ISSUE TITLE
 issue with CELAS2 which defines the stiffness between two DOFs of Same node.

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#465]
Hi,

Nastran allow to define spring elements (CELAS2) which input the stiffness between two DOFs of Same node.

We get below error when try to read such CELAS2 elements.

Any suggestions on reading this type of cards using pyNastran?

Thanks
Ravi

Element CARD:
![image](https://user-images.githubusercontent.com/34907733/34404304-e0939b0c-ebd2-11e7-8bb3-83fe9940b69b.png)

Error:
  File "F:\Program Files\Ansconda3\lib\site-packages\pyNastran\bdf\cards\elements\springs.py", line 303, in _validate_input
    assert len(set(self.nodes)) == 2, 'There are duplicate nodes=%s on CELAS2 eid=%s' % (self.nodes, self.eid)
AssertionError: There are duplicate nodes=[613, 613] on CELAS2 eid=615

**Comment by SteveDoyle2** [comment]
What version are you using?  In the master version, that error doesn't occur.  I don't think it has changed recently.

        fields = ['CELAS2', '615', '-7.39E6', '613', '1', '613', '5', '0.01']
        model = BDF()
        model.add_card(fields, fields[0])
        model.pop_parse_errors()
        e = model.elements[615]
        print(e)

    CELAS2       615 -7.39+6     613       1     613       5     .01

**Comment by raviraj3997** [comment]
Thanks for the quick help.
I am using pynastran 1.0.0
How do I download the master version?

Thanks
Ravi

**Comment by SteveDoyle2** [comment]
You just go to the github page and click on the green Clone button.
That'll give you the url to clone it with using git (so you can just pull
whenever you want) or you can download a zip.  If you do the first option,
there is some additional setup, but it's more convenient if you pull
regularly.

**Comment by raviraj3997** [comment]
Thanks for your help! I have downloaded the pyNastran-Master. that resolves my issue.
