### ISSUE TITLE
Question: Simple example to scale/shift/rotate a bdf file

### ISSUE THREAD

**Issue by georgehandrew** [SteveDoyle2/pyNastran#466]
Dear Developer,

Would you please provide a simple example on how to do a scale/shift/rotation on a bdf model after it is loaded.
If you can provide some further examples on how to remove part of the model and how to merge two models, etc. are also very much appreciated. I have tried to find from documents, but it seems I have to understand  lots of details before I can do the operations by myself.

Thanks!

**Comment by SteveDoyle2** [comment]
Please post questions to the discussion forum.  If you find a bug, then by all means.

**Comment by georgehandrew** [comment]
thanks for reminding. I have asked the question at the discussion forum. Sorry for inconvenience.

**Comment by SteveDoyle2** [comment]
No worries, just nobody else checks the issues and questions get repeated a lot.
