### ISSUE TITLE
Wrong behabiour of __str__ method of pyNastran.bdf.cards.loads.static_loads.LOAD

### ISSUE THREAD

**Issue by EVillarrealJ** [SteveDoyle2/pyNastran#470]
The \_\_str\_\_ method fo **pyNastran.bdf.cards.loads.static_loads.LOAD** class does not work properly.
For Example, a typical NASTRAN LOAD card:
![load_card_bug](https://user-images.githubusercontent.com/35369480/34877395-28d80ed2-f7a6-11e7-8289-6d264fcf18a0.jpg)

however when you print that card, it is showed like this:
![load_card_bug2](https://user-images.githubusercontent.com/35369480/34877466-76928c56-f7a6-11e7-8fa3-bc7c25343d6b.jpg)

As it can be seen, aparently the Scale factors are located in their position but the LIDs are mixed erroneously.

**Comment by EVillarrealJ** [comment]
Thank you very much, I will try to update the last MASTER branch.

**Comment by SteveDoyle2** [comment]
closed due to innactivity and I think it's fixed
