### ISSUE TITLE
RSSCON card is being rejected

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#471]
Hi 
My Nastran model has RSSCON cards, It seems currently it is not supported.

CARD: 
RSSCON   2348    GRID    2331    2332    2333

It gives info:
INFO:    bdf.py:2304                      rejecting card_name = RSSCON

Is there any way to get it read?

Thanks

**Comment by SteveDoyle2** [comment]
That's a rigid element, correct?

**Comment by raviraj3997** [comment]
Yes, This is rigid element. 

It generates a multipoint constraint that models a clamped connection between a shell and
a solid element.

**Comment by SteveDoyle2** [comment]
Give the new RSSCON a shot.  No xref quite yet, but you can access the data.  The data depends on self.rigid_type=GRID/ELEM.

**Comment by raviraj3997** [comment]
Thanks Steve!

I gave it a try. I could read the RSSCON with rigid_type = GRID/ELEM, could access all data on card.

Thanks

**Comment by SteveDoyle2** [comment]
I'm glad it works.  Let me know if it doesn't make sense.  I was struggling a bit to make it clear.
