### ISSUE TITLE
Issue in reading PBEAML with multiple cross sections

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#475]
Hi I am trying to read below PBEAML

![image](https://user-images.githubusercontent.com/34907733/35979456-69c5d33e-0d0e-11e8-9956-77e42fb150ce.png)

It is being read as image below
![image](https://user-images.githubusercontent.com/34907733/35979566-a8229c16-0d0e-11e8-9979-03ce8876ad96.png)

Seems like SO entry after length X/XB = 1.0 is not valid (as per our last discussion). it should through error. 

Could you please check if this can be done?

Thanks

**Comment by SteveDoyle2** [comment]
I'm think a bit confused.  Is the first example you showed correct or incorrect?

Can you also provide an example?  Typing out fixed width cards is very error prone.

**Comment by raviraj3997** [comment]
Sorry for the confusion.

The first image is an example of the wrong format.  but pyNastran reads it and shows two cross sections at X/XB = 1.0 (in the second image).

**Comment by SteveDoyle2** [comment]
This should be corrected now.  The issue was you had a duplicate station defined (station 1.0 is the default) and if no dimensions are defined, station 0.0 values are used if it's station 1.0.

I added a check during the validate step to prevent duplicate station definitions (all values of x/xb must be unique).

**Comment by raviraj3997** [comment]
Hi, I get the below error when reading the same PBEAML shown in the image below:

This is now as expected. 
In addition, would it be possible to write PBEAML ID in error? Thanks for your help!

![](https://user-images.githubusercontent.com/34907733/35979456-69c5d33e-0d0e-11e8-9956-77e42fb150ce.png)

ERROR:
raise ValueError('xxb=%s unique(xxb)=%s' % (self.xxb, uxxb))
ValueError: xxb=[ 0.     0.166  0.51   0.565  0.619  0.963  1.     1.   ] unique(xxb)=[ 0.     0.166  0.51   0.565  0.619  0.963  1.   ]

**Comment by SteveDoyle2** [comment]
This should be 1 step better.  You get the card print out.  Validate now
stores up the errors in a single block (e.g.,. properties).  It still needs
some more work, but it's a lot better.

**Comment by raviraj3997** [comment]
That helps!
Thanks
