### ISSUE TITLE
Getting grid point singularity table

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#480]
Hi Steve, 
I want to access grids with singularity. 

Below code can write grid point singularity table in F06 file, however, I am not sure what arguments I need to use in the last line of below code.

```
from pyNastran.op2.op2 import OP2
model_op2 = OP2()
model_op2.read_op2(op2Filename)
model_op2.make_grid_point_singularity_table
```

Instead of writing these nodes on F06 file, I want to access it in array. Is it possible?

Thanks

**Comment by SteveDoyle2** [comment]
That is a programmatic way to create the grid point singularity table that
works for simple problems, but is not the real singularity table.

I'm not sure if it's possible to get the table easily.  If you contact your
sales rep and they tell you how, I can add it, but I think it requires an
alter.

There is a way to get the mass matrix and the eigenvalue tables from the
OP2, so it might not.

I guess the bigger question is what's your end goal? The singularity table
is only really useful in debugging and only if you can sift throught the
1000s of errors.

**Comment by raviraj3997** [comment]
I am reading NASTRAN files and writing this information for simulation in another software. This information is crucial to that. 

Is there any workaround?

**Comment by SteveDoyle2** [comment]
You could make an alter to export KGG if I'm not mistaken and find all the
0s in the matrix.  I forget exactly what the ratios are (it's something
like KGGmax/min on a per DOF basis), but you may not need that. I'd also
get very worried if I started messing around with contact/muti-subcase.

You could also look through the DIAG 14(???) DMAP output and find where
GPST is written (it's in the GPSP module).  It might just be in the OP2,
but be unparsed.  Presumably MSC/NX sales or the external code you're using
could help.  There is also a DMAP yahoo group.  It might just be the EXQUIS
(I'm sure that's spelled wrong) table, but I don't have the docs for it.

The other option is for you to write an F06 parser to get that info.  F06
parsers work well on a single problem, but are harder to generalize to
mult-time step/subcase/preload other solutions.

**Comment by SteveDoyle2** [comment]
closing due to no takeable action
