### ISSUE TITLE
Error when i run HDF5 Example

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#481]
When i run the example.py hdf5 in the directory h5Nastran , i have this error : 
![image](https://user-images.githubusercontent.com/19569215/36352626-1e31078a-14bc-11e8-96d0-6cba1d4d1bcd.png)

My python version is 2.7.11

MappingProxyType is for python 3

Is the package compatible h5Nastran compatible with python27 ?

**Comment by SteveDoyle2** [comment]
PyNastran now requires the typing module.  For Python 2, it was backported and works with mypy (if you follow the much less nice syntax). My first guess is you either don't have the package or are using an old version.

@mjredmod is that right?

**Comment by SteveDoyle2** [comment]
@mjredmond thoughts?

**Comment by PabloBeranger** [comment]
I installed the latest version of pyNastran and i have the typing 3.6.4 .

I run the exemple.py and i still have the same error : ImportError: cannot import name MappingProxyType

**Comment by mjredmond** [comment]
Sorry I just saw this issue, I think my phone is full and can't download new emails.... anyways, I'll look into this and get back to you.

**Comment by mjredmond** [comment]
I just made a workaround to catch the ImportError... the example should work now.  As to why you don't have that module in python 3, the types module might be python 2 only.  I'll have to figure that out.

**Comment by mjredmond** [comment]
I reimplemented ImmutableDict.  @PabloBeranger , would you please confirm that it works for you?  Thanks.

**Comment by PabloBeranger** [comment]
Hello ,
I tested the version of this day and I have the following error : 
   
![image](https://user-images.githubusercontent.com/19569215/36563316-0672ce10-181a-11e8-966f-1be1de1f58c4.png)

**Comment by PabloBeranger** [comment]
It's OK the example.py script works
Are all new developments tested in Python 2 and 3?
This would allow for a more robust pyNastran code.
Thank you.

**Comment by mjredmond** [comment]
They should be but generally aren't.  In the future it will be, but everything is still pretty preliminary.
