### ISSUE TITLE
Issue related to "BEGIN BULK" when it is in comment

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#482]
Hi Steve

I have below lines in my Nastran input files

![image](https://user-images.githubusercontent.com/34907733/36464053-936fd4b6-16f3-11e8-8cae-a5a25716e571.png)

It gives me the ERROR below:

![image](https://user-images.githubusercontent.com/34907733/36464106-f09ddafc-16f3-11e8-9959-8e9c451ea29d.png)

Seems like pyNastran looks for the keyword "BEGIN BULK" and first "BEGIN BULK" occurs in the commented line, so, throws an error.

Would it be possible to ignore the content in commented line for begin bulk?

Thanks

**Comment by SteveDoyle2** [comment]
That's not the issue.  It is finding the BEGIN BULK correctly.  There are 3/4 decks (the system/executive is kinda strange):

 - System/Executive (ends with a CEND)
 - Case Control (ends with a BEGIN BULK)
 - Bulk Data (ends wtih an ENDDATA/end of file)

By default, all sections must be read.  That is what defines a "valid Nastran deck" or a deck capable of running a Nastran solution.  Alternatively, you can read just the bulk data section using the `punch=True` flag.  You're trying to read starting from the case control, which is not supported.

Removing the comment will not fix it.  Removing the `BEGIN BULK` line will.

**Comment by raviraj3997** [comment]
I think I have confused you. I understand about decks you mentioned and used all decks.

I have attached the working example form "pyNastran-master\models\cbush" without comments and other with comments (with begin bulk). It might help you understand my issue.

file: cbush.dat - can read correctly
file: cbush_changed.dat (with comment) - gives error. 

Please have a look at files and let me know if you understand my point.

Thanks


[cbush.zip](https://github.com/SteveDoyle2/pyNastran/files/1743585/cbush.zip)

**Comment by SteveDoyle2** [comment]
Ah, you're correct.  I got confused by the overly simplified header.  I've heard of that error so many times that I sort of have a stock response.

It's fixed now, but needs a test.

**Comment by raviraj3997** [comment]
Thanks for fixing!

I tested it, look good now!
