### ISSUE TITLE
Error while reading SET

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#483]
Hi Steve,

Nastran can handle the SET definition shown below without any error.

![image](https://user-images.githubusercontent.com/34907733/36542582-3b1ca432-1807-11e8-8a24-56a3c49f0b73.png)

However, pyNastran gives error while reading it.

ERROR:
![image](https://user-images.githubusercontent.com/34907733/36542691-8cf5e99e-1807-11e8-9ce7-24bf907d3876.png)

Can we handle this kind of SET definitions?

Thanks

**Comment by raviraj3997** [comment]
Yes, I understand your point.

Instead of giving the RuntimeError for the SET cards, it would be helpful if we can give the warnings for unsupported SET cards and continue to read Bulk data. Since we generally use the SET card for output requests. So it won't affect bulk data.

Would it be possible?
Thanks

**Comment by SteveDoyle2** [comment]
I'll have to think about it and get a better list of cards that run through that function first.  My concern is by try-excepting things, invalid data will get through.  Is there a reason it's difficult to write the card in the nicer form?

**Comment by SteveDoyle2** [comment]
I learned a bit more about sets recently.  They're more complicated than I always thought, so this is on tap for the next version (not 1.2).

**Comment by SteveDoyle2** [comment]
It's done now.

Also, this wasn't going to be backported since it's a new feature, but given how bad what it's replacing is (see #560), it kind of should be.
