### ISSUE TITLE
Warning message instead of Error in reading some cards like MPCADD and LOAD

### ISSUE THREAD

**Issue by raviraj3997** [SteveDoyle2/pyNastran#484]
Hi Steve,

I have two cases where Nastran doesn't give the error and works fine. However, when I read the same input file in pyNastran, it throws an error.

Case 1 - MPCADD: I have card specified below, where MPCADD uses two sets of MPCs with set ID 10 and 100. one of them is specified bulk abut other is not. Nastan takes care of this situation without error. Currently, pyNastran gives the error. Is it possible to give the warning instead of error and proceed to read other bulk data?
MPCADD  1001    10      100

Case 2 - LOAD: LOAD card here used load set identification number 71 which is not defined in the bulk data, and Nastran doesn't give the error for this case as well. pyNastran throws an error saying "can not find LOAD ID=71 which is required by LOAD=5100008". Instead of giving error can we give the warning and read the all bulk data?
LOAD     5100008      1.      1.      71

Please let me know your thoughts.

Thanks

**Comment by SteveDoyle2** [comment]
`xref=Trus` or `model.cross_reference()` requires all cards are found, even if they are unused.  It makes for cleaner code and is good practice.

`model.safe_cross_reference()` is much more lax, even more lax than Nastran.  It still does require a few cards (not all methods are fully implemented and are just a repeat of cross reference) and error messages could be more consistently handled, but is probably what you want.
