### ISSUE TITLE
read OGS1 and other tables

### ISSUE THREAD

**Issue by vanpaemel** [SteveDoyle2/pyNastran#487]
Hi Steve,

First of all, thank you for the good work on pyNastran.

I want to read the OGS1 table which is written in an OP2 file.  

I use the matlab-python interface to read results into matlab. In the figure below I copied the output of the matlab command window. It can be seen that the table OGS1 (which are grid point stresses) has been read. 
![image](https://user-images.githubusercontent.com/36950521/36834317-d0224200-1d32-11e8-8db8-74f696e5053e.png)
However, when I try to access the grid point stresses, it is empty.
![image](https://user-images.githubusercontent.com/36950521/36834681-ebc71174-1d33-11e8-8055-97917bb3bf8a.png)

I want to do the same for other tables, e.g.  with the RASCONS table. (note that this is not in the written in the op2 file for this example)

I also tried to export the OP2 file to a hdf5 file ( but using Python, not Matlab). But the function was not defined. 
![image](https://user-images.githubusercontent.com/36950521/36834822-66f132ee-1d34-11e8-929d-03e9790c579c.png)

Thank you for any help

**Comment by SteveDoyle2** [comment]
I think the OGS table got disabled for some reason.  I think it was when I first added vectorization.  I just don1 see it often.  

For the RASCONS, I think that was trying to overwrite a stress result, so it just didn't get added.

I think it's probably just time to hange the op2 combine format agin to add the table to the output key if there is a conflict.

I also haven't seen that hdf5 error before.  The object might be in an incomplete state.

Do you have a bdf/f06/op2 example?  Also, this is MSC 2017 correct?

**Comment by vanpaemel** [comment]
Hi Steve,

Thanks for your reply.

I'm using NX nastran 11.0 , is this a problem?
See below the bdf file (as a .dat file) , f06 , f04 and op2 file.
[bdf_op2_f06_f04.zip](https://github.com/SteveDoyle2/pyNastran/files/1770787/bdf_op2_f06_f04.zip)

The objective is to output the grid point stresses in the coordinate system of the GRID card.

Thanks for your help

**Comment by SteveDoyle2** [comment]
Yeah, that was a very old part of the code.  I thought that was all turned on.  It was all disabled.  It can be tough to find that stuff.

There are still some issues if you run test_op2 with the diff resulting in a failure and the pandas stuff not working, but it works fine.  I still need to update the other ones as well.

**Comment by vanpaemel** [comment]
Hi Steve,

I pulled the last changes from github. But I don't find any OGS table created , the grid_point_stresses and grid_point_volume_stresses seem to be empty. Or did I interpret it wrong that it was fixed? 

I ran the op2 file I've sent to you.

Thanks for all your efforts

**Comment by SteveDoyle2** [comment]
There were no grid_point_volume_stresses results in the OP2 that you provided.  There was data in grid_point_stresses.  You see it if you run:

    test_op2 .\ogs.op2 -tc

    ---stats for .\ogs.op2---
    displacements[1]
    spc_forces[1]
    cquad4_stress[1]
    grid_point_stresses[1]

ogs.op2 is just the renamed model you sent, also located here:
https://github.com/SteveDoyle2/pyNastran/tree/master/models/ogs

As well as looking at the updated block of code inside https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/op2/tables/ogf_gridPointForces/ogs_surface_stresses.py

    class GridPointStressesArray(ScalarObject):
        """
        '                                  S T R E S S E S   A T   G R I D   P O I N T S   - -     S U R F A C E       5\n',
        '0                       SURFACE X-AXIS X  NORMAL(Z-AXIS)  Z         REFERENCE COORDINATE SYSTEM FOR SURFACE DEFINITION CID        0\n',
        '     GRID      ELEMENT            STRESSES IN SURFACE SYSTEM           PRINCIPAL STRESSES            MAX             \n',
        '     ID          ID    FIBRE   NORMAL-X   NORMAL-Y   SHEAR-XY     ANGLE      MAJOR      MINOR      SHEAR     VON MISES\n']
        '0     13683          3736    TRIAX6         4.996584E+00   0.0            1.203093E+02   0.0            0.0            0.0'
        '      13683          3737    TRIAX6        -4.996584E+00   0.0           -1.203093E+02   0.0            0.0            0.0'
        '      13683                  *TOTALS*       6.366463E-12   0.0           -1.364242E-12   0.0            0.0            0.0'
        """
        def __init__(self, data_code, is_sort1, isubcase, dt):
            ScalarObject.__init__(self, data_code, isubcase, apply_data_code=True)
            self.ntotal = 0
            self.ntimes = 0
            self.nelements = 0
            self.itotal = 0
            self.ielement = 0
            self.data = None
            self.itime = None
            self.node_element = None

It should just work.

Regarding grid_point_volume_stresses, they are currently still disabled.  I was unaware they were disabled (along with 2 other OGS results) and it'll take a bit of time to vectorize them.

**Comment by vanpaemel** [comment]
Hi Steve,

Indeed, it works like it should be! I needed to restart my Matlab to make it work.

Thanks again!

**Comment by SteveDoyle2** [comment]
Gettin closer.  GridPointVolumeStresses object (stored in grid_point_volume_stresses) has been working for a while and is vectorized.  There's a third type (grid_point_max_stresses I think) that still needs work before this is closed.

Additionally, the op2 "case" key has been updated to include the ogs id.  If you have multiple ogs results, instead of just being by subcase, you'll need to use the full `combine=False` option.  This may be collapsed in the future, but is not totally terrible.  It's better than crashing.

**Comment by SteveDoyle2** [comment]
pushing to 1.2 because I'm having trouble finding an example of:

Grid point stress discontinuities (plane strain)

**Comment by SteveDoyle2** [comment]
Nm.  i'll close this and make a new one.  See #498
