### ISSUE TITLE
Add function for Length of PROPERTY 1D(PBAR, PBARL,...)

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#488]
Is it possible to add the "get_length_breakdown" function for the length of 1D PROPERTY (similar to the "get_area_breakdown" function for areas)?

**Comment by SteveDoyle2** [comment]
This is added.  CONRODs are not supported because they don't have a property.  They will probably be added in the future with a property id of -10 (corresponding to the DMAP id).

I also renamed stop_if_no_eids in get_mass_breakdown and added stop_if_no_length/area/volume

**Comment by PabloBeranger** [comment]
I tested the function. It does not return the total length of the property but the length of the last element treated.

There is no append in the list lengths as there is in the calculation of the volume for example.

I think there is an error

**Comment by SteveDoyle2** [comment]
You are correct.  It's fixed now.

**Comment by PabloBeranger** [comment]
Ok Thanks
