### ISSUE TITLE
NLPARM: pyNastran defaults wrong when gap is present for SOL 106

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#489]
I can't share the bdf, but here's the original NLPARM card.  All I did was read in the original bdf and write it back out with no changes....
```
NLPARM         1      10            ITER       1      25      PW      NO+       
+           .001     .01    1.-5       3      25       4      .2      .5+       
+              5                             20.             20.
```

Here's what pyNastran writes out

```
NLPARM         1                    ITER       1
            .001          .00001
```

With the original card, Nastran sol 106 starts at subcase 1 load factor 0.1, as intended.  With the card written out by pynastran, it starts at subcase 1 load factor 1.0.

After looking in the QRG, here's what I found for NLPARM in comment 16

```
The default for NINC is 10, except if there is a GAP, Line Contact, Heat Transfer or
PARAM,NLTOL,0, in which case the default is 1.
```

I have gaps present, so if NINC is blank, it gets set to 1 instead of 10.  pyNastran thinks default is always 10.

I don't think the card objects have access to the model instance, so it would currently be impossible to check for gaps.  The easiest thing to do in the meantime is to just write out the full card instead of wiping defaults.

**Comment by SteveDoyle2** [comment]
I think that also means you can't set a default.  That message is not listed in the first qrg I loaded, so more inconsistencies...

It's updated though.

**Comment by mjredmond** [comment]
Thanks!
