### ISSUE TITLE
CGAP cid default incorrect when reading from bdf

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#493]
In the CGAP.add_card method, there's a line for cid as follows that sets cid to 0 if blank.

```
cid = integer_or_blank(card, 8, 'cid', 0)
```

The default should be None, otherwise, the basic coordinate system will always be used for the CGAP, which is incorrect.  In my bdf this leads to repeated bisections, and eventually to an excessive pivot ratio error.  When I change the 0 to None, the bdf runs correctly.

Thanks.

**Comment by SteveDoyle2** [comment]
So this gets and stays right, my understanding of the CGAP/CBUSH is:
 - If the nodes are **not** coincident, the i/x direction is defined by the vector defined by node 2-1.  The vector v is defined similar to how the CBAR/CBEAM vector v is defined to define the y/z vectors.
 - If the nodes are coincident, a coordinate system must be defined.  The vector v is ignored and the y/z vectors are taken from the coordinate system.
 - If the nodes are **not** coincident and a coordinate system is defined, the axes will be the same as the coordinate system.

Things I'm unclear on:
 - If CID is being used to define the element coordinate system and the CID refers to either a cylindrical or spherical coordinate system then grid GA will be used to locate the system. If grid GA lies on the z-axis of the cylindrical or spherical coordinate system it is recommended that a different coordinate system be used for this element.  **Does this mean that cid defines the stiffness, but the vector v is defined by GA?**
 - If the vector v is ignored, does that mean that you can not define the vector v?

This will also take me a couple days.  I'm pretty busy right now and have an update I'm working on to fix multiple OGS outputs that I'm not ready to push.

**Comment by mjredmond** [comment]
My understanding is about the same as yours.  Is there more to simply changing that 0 to a None in the code?  Thanks.

**Comment by SteveDoyle2** [comment]
No that's it.   It probably makes sense just to pull out the cid line entirely from the if-elif-else statement.  I checked and it looks like that's the only spot that needs to be updated.  You're more than welcome to update it.  Otherwise, I won't be able to get to it until next week.
