### ISSUE TITLE
PBEAM - C1 and C2 defaults not correct for 106 non linear material runs

### ISSUE THREAD

**Issue by mjredmond** [SteveDoyle2/pyNastran#503]
The following 2 cards yield different Nastran results (for my case a 106 non-linear material run).  The only difference is the second one doesn't define C1 and C2.  The QRG suggests the defaults are always 0., but Nastran must use different defaults than 0. for these values and probably D-F as well.

```
PBEAM          1       1    .085   .0061   .0061              .1
 
            YESA      1.    .085   .0061   .0061              .1
              0.      0.
```

```
PBEAM          1       1    .085   .0061   .0061              .1
 
            YESA      1.    .085   .0061   .0061              .1
```

**Comment by SteveDoyle2** [comment]
I've run into things like that before.  I'm pretty sure those are K1/K2
instead of C1/C2.




Looking at the code, I see:

    if i == 0:  # the first 2 fields aren't written
        list_fields += [A, i1, i2, i12, j, nsm,
                        c1, c2, d1, d2, e1, e2, f1, f2]
    else:
        if so in ['YES']:
            list_fields += ['YES', xxb, A, i1, i2, i12, j, nsm,
                            c1, c2, d1, d2, e1, e2, f1, f2]
        elif so in ['NO']:
            list_fields += ['NO', xxb, A, i1, i2, i12, j, nsm]
        elif so in ['YESA']:
            list_fields += ['YESA', xxb, A, i1, i2, i12, j, nsm]
        else:
            raise RuntimeError('so=%r type(so)=%s' % (so, type(so)))

as well as:

        footer = [k1, k2, s1, s2, nsia, nsib, cwa, cwb,
                  m1a, m2a, m1b, m2b, n1a, n2a, n1b, n2b]

It appears your k1 and k2, are both be 1.0 in the second example.

**Comment by SteveDoyle2** [comment]
The missing figure...

![image](https://user-images.githubusercontent.com/1059417/38823322-f1a20d74-415a-11e8-89c3-7f0ee6421e6d.png)

**Comment by mjredmond** [comment]
You're right, that was the issue.  I was reading the bdf wrong.  Setting K1/K2 to 0. fixed the issue.  Thanks!
