### ISSUE TITLE
bdf renumber using CBEAM alternate format

### ISSUE THREAD

**Issue by a-deblois** [SteveDoyle2/pyNastran#507]
Hi,

With all reserve, when using "bdf renumber" on a CBEAM entry with alternate format, the G0 grid number is not updated. Let me know of you want an example, but it should be easy to reproduce.
Thank you for your help,
Antoine

**Comment by SteveDoyle2** [comment]
It should be fixed now.

**Comment by a-deblois** [comment]
Hi,
thanks for the prompt response. Just to clarify, in what branch is the problem solved? Should I pull the dev version? FYI, I am using 1.0.0

**Comment by SteveDoyle2** [comment]
The master.

v1.1 is being released in ~2 weeks and releases are kind of a pain (e.g., get the docs working).

**Comment by a-deblois** [comment]
Great. I also just realized that this issue is also present when using `bdf merge`. Hoping that the fix you made also fixes the merge tool.
Regards.
