### ISSUE TITLE
Is pyNastran capable of writing OUT2 file format?

### ISSUE THREAD

**Issue by ahojukka5** [SteveDoyle2/pyNastran#508]
Is it possible to write Nastran OUT2 file format or ASCII tables (.DOFT, .GEOM, etc.)?

**Comment by SteveDoyle2** [comment]
I'm not familiar with that format, so no.  Is that a format supported by Nastran natively?

**Comment by ahojukka5** [comment]
I think it's the same than OP2. It contains the table of DOFs, geometry, element dictionary table, element stiffness matrices, element information table. I also need to write "OUT4", which, I think, is same than OP4. And eigenvectors, again in OUT2 (binary) format.

**Comment by SteveDoyle2** [comment]
> I think it's the same than OP2. It contains the table of DOFs, geometry, element dictionary table, element stiffness matrices, element information table.

I'm definitely not familiar with the DOF or element stiffness matrices data format.  That data is rarely stored in the OP2.  Geometry and results are pretty straightforward though assuming you know what version of Nastran you're targeting.  OP2 writing is not an option though (see #472).  I just haven't found a good use case for it and with the HDF5 export option, there's even less of a reason (e.g., you can modify your eigenvectors and load them into the GUI).

> I also need to write "OUT4", which, I think, is same than OP4. 

That is supported, though only in ASCII, unless they're all dense matrices.

> Also, a PUNCH file containing table of DOFs, geometry, mass-, stiffness- and damping matrices would be good.

pyNastran does not support writing to a PUNCH file.  You can write to a BDF and F06 from an OP2Geom object.

**Comment by ahojukka5** [comment]
I'm trying to write superelement data. I'm not writing the results for the use of Nastran, but the other software, which is capable taking input in Nastran format.

I think I have a sort of plan now. I can write DOFT, GEOM, KDIC files in ASCII format. They are tables / matrices. As far as I understand, OP2 is just a generic format to store "datablocks" (https://vibrationdata.wordpress.com/2012/09/18/nastran-notes/), like dof map, geometry and element information. Condensed matrices are dense and they can be written to OP4 using `pyNastran`.

What is left, I somehow have to write eigenvectors in a binary format, and because software taking them as input require that they are in OP2 format and not OP4 format, I have to figure out a way to write binary OP2 containing vectors. I think I could study a little bit of that option. Do you have any references to the subject I could take a look at?

**Comment by SteveDoyle2** [comment]
The dmap guide describes the OP2 format.
