### ISSUE TITLE
pyNastranGUI and Xserver

### ISSUE THREAD

**Issue by a-deblois** [SteveDoyle2/pyNastran#512]
Hi,

I am trying to launch pyNastranGUI though an exported display (Hummingbird Exceed), I get the following error message. I searched the pyNastran discussion and the github but could not find a similar issue. 

Is the error related to 

- Qt: Failed to compile a keymap!" or

- TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType?

Please advise,
thanks,
Antoine

$ pyNastranGUI 
Using PyQt5
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Qt: Failed to compile a keymap!
Current XKB configuration data search paths are: 
/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/lib
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
vtk_version = [8]
supported_formats = [u'nastran', u'nastran', u'cart3d', u'panair', u'shabp', u'usm3d', u'tecplot', u'surf', u'ugrid', u'lawgs', u'stl', u'fast', u'bedge', u'tetgen']
Traceback (most recent call last):
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/bin/pyNastranGUI", line 11, in <module>
    load_entry_point('pyNastran==1.0.0', 'console_scripts', 'pyNastranGUI')()
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/lib/python2.7/site-packages/pyNastran-1.0.0-py2.7.egg/pyNastran/gui/gui.py", line 31, in cmd_line
    MainWindow(inputs)
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/lib/python2.7/site-packages/pyNastran-1.0.0-py2.7.egg/pyNastran/gui/main_window.py", line 152, in __init__
    self.setup_gui()
  File "/gpfs/fs1/app/python/Anaconda-5.1/Anaconda/lib/python2.7/site-packages/pyNastran-1.0.0-py2.7.egg/pyNastran/gui/gui_common.py", line 3199, in setup_gui
    self.restoreGeometry(settings.value("mainWindowGeometry"))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType'

**Comment by SteveDoyle2** [comment]
There is an initialization bug in v1.0.  It was recently fixed in the master.

For 1.0, you either need to use PyQt4 to launch the GUI at which point you can switch to PyQt5.
