### ISSUE TITLE
Add read_op2_geom to OP2 class

### ISSUE THREAD

**Issue by AlejandroStewart** [SteveDoyle2/pyNastran#519]
It may be interesting ( I don´t know if possible) to add **_read_op2_geom_** method to OP2 class. Specially since you can skip or read your own tables with methods such as **_set_additional_result_tables_to_read_** but This capability is lost when also interested in extracting geometry data form the OP2.

Alejandro

**Comment by SteveDoyle2** [comment]
There is a separate class pyNastran.op2.op2_geom.OP2Geom that should work.

**Comment by AlejandroStewart** [comment]
Thank you. This tool is soo big it is impossible to know it all!

**Comment by SteveDoyle2** [comment]
Yeah...I don't know if I can fix that!
