### ISSUE TITLE
Subcase reading

### ISSUE THREAD

**Issue by Pascal3100** [SteveDoyle2/pyNastran#520]
Hi,

it crashes on readeaing subcases like :

SUBCASE=20197

Can you fix it?

**Comment by SteveDoyle2** [comment]
You can now use `SUBCASE 1`, `SUBCASE = 1`, and `SUBCASE=1`.  This is now fixed in master.

Your subcase id is very large.  I thought the max was 1000...

**Comment by Pascal3100** [comment]
Hi Steve! 
First of all, thanks a lot for this beautifull and very usefull package!
Thanks for your fix too! 
How to just update it with pip?
Ids go to 99999999 for max id.

Pascal 

-----Message d'origine-----
De : "SteveDoyle2" <notifications@github.com>
Envoyé : ‎03/‎07/‎2018 18:31
À : "SteveDoyle2/pyNastran" <pyNastran@noreply.github.com>
Cc : "Pascal Lopez" <lopez.pascal.pro@gmail.com>; "Author" <author@noreply.github.com>
Objet : Re: [SteveDoyle2/pyNastran] Subcase reading (#520)

You can now use SUBCASE 1, SUBCASE = 1, and SUBCASE=1. This is now fixed in master.
Your subcase id is very large. I thought the max was 1000...

**Comment by SteveDoyle2** [comment]
You cannot update it with pip at the moment.  It'll probably be up a few weeks.  If you want it now, check out the code with git.

**Comment by SteveDoyle2** [comment]
done
