### ISSUE TITLE
Problem reading Eigenvalues in Linux

### ISSUE THREAD

**Issue by AlejandroStewart** [SteveDoyle2/pyNastran#522]
When reading Eigenvalues from a modes analysis, in Windows I see the first mode in  a list (starting at0) while in linux I see a dictionary that starts with 1

Linux:

![image](https://user-images.githubusercontent.com/14002967/42633133-cb4a6710-85df-11e8-83d7-3dd3793c03ef.png)

Windows:

![image](https://user-images.githubusercontent.com/14002967/42633078-a389c590-85df-11e8-9ef8-aa9bbf9e6223.png)

**Comment by SteveDoyle2** [comment]
You're using two different versions of the code.  The Eigenvalue table was changed to be a numpy array to make it easier to work with.
