### ISSUE TITLE
Question about large FEM model (> 1,000,000 GRID and ELEMENT)

### ISSUE THREAD

**Issue by PabloBeranger** [SteveDoyle2/pyNastran#529]

**Comment by PabloBeranger** [comment]
When you have loaded a large FEM model with pyNastran, is it possible to save the result so that it can be recharged more quickly.
This would be comparable to saving a MATLAB project in .m format

**Comment by SteveDoyle2** [comment]
There is, but you should post questions in the discussion forum.  It helps
to show the project is alive and helps others.

**Comment by SteveDoyle2** [comment]
It's linked off the main page

https://groups.google.com/forum/#!forum/pynastran-discuss

**Comment by PabloBeranger** [comment]
I put the question in the forum..... What is the solution of my question ?

**Comment by SteveDoyle2** [comment]
You're fine.  I wasn't feeling well today.
