### ISSUE TITLE
"Comment" in cards visualisation 

### ISSUE THREAD

**Issue by DomePezz** [SteveDoyle2/pyNastran#530]
Hello everyone,

I have found a bug when I read a bdf/dat file and visualise the elements in "Console". Some comments are still in the visualisation of elements. I have found the issue in the _clean_comment. 

Thank you 
Domenico

**Comment by SteveDoyle2** [comment]
Can you provide an example that demonstates the error?

Can you also describe in mote detail what you mean by the following?

> ... visualise the elements in "Console".

Console is just the command line/terminal right?   Or is that short for Patran/Femap/Simcenter?

>

**Comment by DomePezz** [comment]
Hello,

I checked better. The logic is one that to keep comments of files. Sorry, it is my mistake. You can delete my issue. Congratulation for the work that you are making 

Domenico

**Comment by SteveDoyle2** [comment]
Glad it works.  I'll double check the docstring (assuming it has one).

I'm Lso glad you like it! Thanks!
