### ISSUE TITLE
Missing nodes in geometry 

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#531]
Parsing the op2 with op2_read_geom (xref=false) apparently loads only a subset of the grids of the model.

By using xref=True the parsing crashes because some of the grid are not defined. I load the model in hyperview and the grids are there.

Is there a possibility that some of the nodes defined in the op2 are stored in different table rather than GEOM and as consequence are not imported by pyNastran?

**Comment by SteveDoyle2** [comment]
Xref=True/False will load in the same nodes.  The op2 parser does not use xref.  Xref cross-references or links up the model and is a post step.  It lets you call `element.nodes_ref[0].get_position()`

  I suspect Hyperview is ignoring the nodes and that your missing nodes are associated with an SPC, MPC, load, others?, but not a coordinate system or element.  Patran will also ignore missing elemental nodes and just set the xyz to 0,0,0 and gives you wacky geometry.  Nastran will crash though.

You can try loading it into the gui, which uses `safe_cross_reference`.  It more lenient.

Beyond that, I need an example to debug it.

**Comment by alby3z** [comment]
Ok, got it.

Unfortunately I can load and see the nodes in hyperview.

I will do some more tests in the nexts days and report any outcome.

What I can definitely see is that there is a sort of threshold on the node numbering (e.g. ID 90000000 or whatever high number) stored in the .nodes class.

**Comment by SteveDoyle2** [comment]
As long as the IDs are less than 9 digits, I wouldn't expect a problem.  Depending on the version of Nastran, they reserve values over 9 digits for internal usage.  For example, PBCOMPs are turned into PBEAMs that share the same property ID despite both being beam properties (which is not allowed in the input file).  It's just an oddity of the code structure.

The intention is that internal IDs are not saved, though it's possible there is an issue.

**Comment by SteveDoyle2** [comment]
Any news on this issue?  It seems important, so I'd like to get it solved.

**Comment by alby3z** [comment]
Unfortunately I wasn’t able to solve the issue, but I spent just a day and then I moved on, so the problem is still there unresolved.
I wasn’t able to create a shareable model that mimic the issue so I don’t know how to submit an example for you to look at.

**Comment by SteveDoyle2** [comment]
closing due to lack of test problem & innactivity
