### ISSUE TITLE
attach results from text file

### ISSUE THREAD

**Issue by cristipurdel** [SteveDoyle2/pyNastran#533]
Is is possible to attach results for elements based on smth like an els file and visualize them in pyNastran?

**Comment by SteveDoyle2** [comment]
I'm not sure what you mean by "smth like an els file"?

So my guess is no.  Results may be attached depending on the format (e.g., Nastran can attach op2 files, Cart3d can attach triq files) and all formats may attach custom csv node/element results.

**Comment by cristipurdel** [comment]
els files can hold up to 6 variables (this is as much as I managed to load) for each element
I have not seen the "Load Custom Results" button, which is what I was interested in.
As a feature request, maybe it would be helpful to load more than 2 variables or make it compatible with els files.
I believe the format of a els*.res.res_tmp is:

```
/* modified ansys_els_stress.res_tmpl */
/* PATRAN 2.5 results file template  */

KEYLOC = 0

TYPE = scalar
Column = 1
PRI = RESERVE FACTOR1
Sec = Scalar

TYPE = scalar
Column = 2
PRI = RESERVE FACTOR2
Sec = Scalar

TYPE = scalar
Column = 3
PRI = RESERVE FACTOR3
Sec = Scalar

TYPE = scalar
Column = 4
PRI = RESERVE FACTOR4
Sec = Scalar

TYPE = scalar
Column = 5
PRI = RESERVE FACTOR5
Sec = Scalar

TYPE = scalar
Column = 6
PRI = RESERVE FACTOR6
Sec = Scalar

TYPE = END
```

while the els file is:

```
title header for els files
    6
!
!
 1110001
         4.93         5.45         4.93     2592007.     1161055.          31.  
 1110002
         4.05         4.87         4.05     2592007.     1161050.          31.  
 1110003
         3.75         4.91         3.75     2592007.     1162157.          31.  
```
You can leave open or close the issue as you wish

**Comment by SteveDoyle2** [comment]
Do you have a reader for this or can you write a reader for this?  To me that's just as easily written as:

    # eid, RESERVE FACTOR1, RESERVE FACTOR2, RESERVE FACTOR3, RESERVE FACTOR4, RESERVE FACTOR5, RESERVE FACTOR6
     1110001,         4.93,         5.45,         4.93,     2592007.,     1161055.,          31.  
     1110002,         4.05,         4.87,         4.05,     2592007.,     1161050.,          31.  
     1110003,         3.75,         4.91,         3.75,     2592007.,     1162157.,          31.

**Comment by cristipurdel** [comment]
I thought you had a limitation on 2 cases, but if it's working with more, better to highlight this in the docs

**Comment by SteveDoyle2** [comment]
I guess don't just assume at limitations.  You gotta try it first.  The docs should describe limitations when they exist.

There are limitations regarding transients and deflections, but that's not this case and they're not specified by the format/in the menu.
