### ISSUE TITLE
Read OP2 to get nodes displacement

### ISSUE THREAD

**Issue by nekcorp** [SteveDoyle2/pyNastran#540]
Hi,

Thanks for your job it is awesome.

I would like to know what I need to read an op2 file to get displacement of nodes.

I work to a python script to automate a Matrix reduction, and in the process I need to check the displacement of nodes.

I do not know how I can do it with pyNastran, I want to know the part of code I can use.

Thanks for your help.

**Comment by SteveDoyle2** [comment]
Also, questions should be asked in the discussion forum.  The issue tracker is for bugs and features.
