### ISSUE TITLE
AssertionError: nelements=0

### ISSUE THREAD

**Issue by yellowhat** [SteveDoyle2/pyNastran#543]
Hi,
I would like to read an `op2` file but I am getting this error:

```
from pyNastran.op2.op2 import read_op2

op2_filename = r'Crankshaft_cond_OPT_COND_MGPS.OUT2'
op2 = read_op2(op2_filename)

DEBUG: op2_scalar.py:743 set_subcases - subcases = []
DEBUG: op2.py:547 combine=True
DEBUG: op2.py:548 -------- reading op2 with read_mode=1 (array sizing) --------
INFO: op2_scalar.py:1291 op2_filename = 'Crankshaft_cond_OPT_COND_MGPS.OUT2'
DEBUG: op2_scalar.py:1537 table_name=b'OGS1'
DEBUG: op2.py:560 -------- reading op2 with read_mode=2 (array filling) --------
DEBUG: op2_scalar.py:1537 table_name=b'OGS1'

...

C:\Miniconda3\lib\site-packages\pyNastran\op2\tables\ogs_grid_point_stresses\ogs_surface_stresses.py in build(self)
    232 
    233         assert self.ntimes > 0, 'ntimes=%s' % self.ntimes
--> 234         assert self.nelements > 0, 'nelements=%s' % self.nelements
    235         assert self.ntotal > 0, 'ntotal=%s' % self.ntotal
    236         #self.names = []

AssertionError: nelements=0
```

This is file that I am trying to open: [Crankshaft_cond_OPT_COND_MGPS.zip](https://github.com/SteveDoyle2/pyNastran/files/2729644/Crankshaft_cond_OPT_COND_MGPS.zip) 

In my opinion the problem is that it contains only the results not the mesh.
Infact to visualize it in HyperView I have also to load the model file `.fem`.
My aim is to just read the results, is there a way to avoid that assertion?

Thanks

**Comment by SteveDoyle2** [comment]
It looks like the GridPointStressesVolumeArray had a bug making it not work with transient/modal/frequency results.  That's been fixed and incorporated into the master.

There is no workaround other than updating.

**Comment by SteveDoyle2** [comment]
The model is not required to read in results and will be ignored by the read_op2 method (uses the OP2 class).  It's only read when using read_op2_geom method (calls the OP2Geom class).

**Comment by yellowhat** [comment]
Perfect. Thank you very much for the explanation

**Comment by SteveDoyle2** [comment]
To maybe be more clear., using a simpler result as an example, a transient displacement result has a shape that is (ntimes, nnodes, 6).  Ntimes and nnodes are calculated from the data size.  It doesn't make sense to have a result with no nodal output (or elemental output in the above example), there is a check.  Similarly, for a static result, you'll have 1 time, so ntimes > 0.  It's just an indication that there is a major error.  Also, the error message is a lot better than what numpy will give you.

It's simply to size the output array and has nothing to do with geometry.
