### ISSUE TITLE
Memory usage keeps rising

### ISSUE THREAD

**Issue by yellowhat** [SteveDoyle2/pyNastran#546]
Hi,
I have noticed that if I try to reload multiple times the same op2 file, memory usage continue to rise up.
For example if I have:

```python
from numpy import ones

for i in range(3):
    m0 = psutil.Process(os.getpid()).memory_info().rss/1024/1024/1024

    arr = ones([10**6, 1000], dtype='f8')

    m1 = psutil.Process(os.getpid()).memory_info().rss/1024/1024/1024
    print(f'{m0:6.4f}|{m1:6.4f}')
```
I can see that the memory usage is always the same, because will delete the old `arr` and replace with the new one.
Instead if I do the same using `pyNastran`:

```python
from pyNastran.op2.op2 import read_op2

op2File = r'hm14.op2'

for i in range(3):
    m0 = psutil.Process(os.getpid()).memory_info().rss/1024/1024/1024

    op2 = read_op2(op2File, build_dataframe=False, debug=False, skip_undefined_matrices=True)

    m1 = psutil.Process(os.getpid()).memory_info().rss/1024/1024/1024
    print(f'{m0:6.4f}|{m1:6.4f}')
```
I can see that the memory usage continue to rise up.

I have the same behavior if I delete the `op2` object before:

```python
del op2
op2 = read_op2(op2File, build_dataframe=False, debug=False, skip_undefined_matrices=True)
```

### UPDATE
I can see that there is a `close_op2` method but I get:

```python
>>> op2.close_op2()
Traceback (most recent call last):

  File "<ipython-input-4-043f0e5ed512>", line 1, in <module>
    op2.close_op2()

  File "C:\Miniconda3\lib\site-packages\pynastran-1.2.0+dev.no.checksum.error-py3.7.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1478, in close_op2
    if self.f is not None:

AttributeError: 'OP2' object has no attribute 'f'
```

Thanks

**Comment by SteveDoyle2** [comment]
I’m not sure why or how to find it.  I’ve tested it previously, but didn’t see any issue.  Test_op2 has a memory profiler graph code that works on Windows and Linux, so it’s worth checking if.  Are we talking a few MB on a 2 GB file?  It used to be really bad.

The close_op2 method is called automatically.  It’s to do things like close the op2 file (f) and delete struct objects that can’t be pickled.  You shouldn’t be calling it.

**Comment by yellowhat** [comment]
Seems that every time I call `read_op2` it will reload from scratch without overwriting the previous `op2` object.
If you are reading a small `.op2` file is fine, but if the `.op2` file is several GB, every time I reread it:


```python
from pyNastran.op2.op2 import read_op2

for i in range(2):
    m0 = psutil.Process(os.getpid()).memory_info().rss/1024**3

    op2 = read_op2(op2File, build_dataframe=False, debug=False, skip_undefined_matrices=True)

    m1 = psutil.Process(os.getpid()).memory_info().rss/1024**3
    print(f'{m0:6.4f}|{m1:6.4f}|{id(op2)}')
```

The result is:
```python
<IPython.core.display.HTML object>
7.5966|16.5824|204017280
<IPython.core.display.HTML object>
16.5824|25.5636|204094768
```
It is a different object but the previous one is not deleted.

**Comment by yellowhat** [comment]
If I use (from command line):
```sh
test_op2 -c test.op2
```

I can see that the `op2` file is read correctly, but it reads it just 1 time, so the occupied memory is what I expect.

Thanks

**Comment by yellowhat** [comment]
Another way to test is to `read_op2` and delete the object:

```python
from pyNastran.op2.op2 import read_op2
op2 = read_op2(op2File, build_dataframe=False, debug=False, skip_undefined_matrices=True)
del op2
```
The memory usage is always the same

**Comment by SteveDoyle2** [comment]
I took a look at the memory.  I'm on Windows, so I'm using wmi vs. resource (or psutil), but I'm a bit confused by the graph.  The x-axis is iterations of the loop and the y-axis is memory usage.  It looks like this might be related to the garbage collector?

![image](https://user-images.githubusercontent.com/1059417/52308026-1d2ba480-2951-11e9-8e5f-1b149fe9e5ff.png)

**Comment by SteveDoyle2** [comment]
Additionally, if you zoom in, it gets even weirder...

![image](https://user-images.githubusercontent.com/1059417/52308169-86131c80-2951-11e9-9a9a-c5dd109123f1.png)

**Comment by yellowhat** [comment]
Even forcing the garbage collector:

```python
import psutil
import gc
from pyNastran.op2.op2 import read_op2

op2File = '190130_TM01_X1_Crankshaft_MGPS.OUT2'

for i in range(2):
    m0 = psutil.Process(os.getpid()).memory_info().rss/1024**3

    op2 = read_op2(op2File, build_dataframe=False, debug=False, skip_undefined_matrices=True)

    m1 = psutil.Process(os.getpid()).memory_info().rss/1024**3
    print(f'{m0:6.4f}|{m1:6.4f}|{id(op2)}')

    print('Unreachable objects:', gc.collect())
    del gc.garbage[:]
    print('Unreachable objects:', gc.collect())
```

The memory usage keeps rising:

```python
<IPython.core.display.HTML object>
0.1175|9.1010|154570368
Unreachable objects: 14
Unreachable objects: 0
<IPython.core.display.HTML object>
9.1010|18.0843|119329512
Unreachable objects: 145
Unreachable objects: 0
```

**Comment by SteveDoyle2** [comment]
Adding in that garbage collection makes me think there is no issue (a memory leak).  I've added the code (that should work on Linux as well using a different method).  I ripped that off of test_op2.  It was in a disabled section and was used in the past to test memory leakage.

I also found this article...

> Therefore, if a long-running Python process takes more memory over time, it does not necessarily mean that you have memory leaks. If you are interested in Python's memory model, consider reading my article on memory management.

It seems like there may be internal references, which it are periodically cleaned up, so it could potentially be better in terms of making use of reference counting, but not actually being a leak.  Still, reducing that factor of 8 on memory before the garbage collector is automatically called would be nice.

> In the example above, the del statement removes the references to our objects (i.e., decreases reference count by 1). After Python executes the del statement, our objects are no longer accessible from Python code. However, such objects are still sitting in the memory, that's because they are still referencing each other and the reference count of each object is 1. You can visually explore such relations using objgraph module.

> Unlike the reference counting, the cyclic GC does not work in real-time and runs periodically. To reduce the frequency of GC calls and pauses CPython uses various heuristics.

https://rushter.com/blog/python-garbage-collector/

![image](https://user-images.githubusercontent.com/1059417/52363723-35a2ca00-29f8-11e9-8356-b213b675c9b6.png)


    import os
    import psutil
    import gc
    from pyNastran.op2.op2 import read_op2
    
    # we need to check the memory usage
    is_linux = None
    is_memory = True
    try:  # pragma: no cover
        if os.name == 'nt':  # windows
            windows_flag = True
            is_linux = False
            import wmi
            comp = wmi.WMI()
    
            """Functions for getting memory usage of Windows processes."""
            __all__ = ['get_current_process', 'get_memory_info', 'get_memory_usage']
    
            import ctypes
            from ctypes import wintypes
    
            GetCurrentProcess = ctypes.windll.kernel32.GetCurrentProcess
            GetCurrentProcess.argtypes = []
            GetCurrentProcess.restype = wintypes.HANDLE
    
            SIZE_T = ctypes.c_size_t
    
            class PROCESS_MEMORY_COUNTERS_EX(ctypes.Structure):
                """
                Windows memory tool that has the same interface as
                `resource` on Linux/Mac.
                """
                _fields_ = [
                    ('cb', wintypes.DWORD),
                    ('PageFaultCount', wintypes.DWORD),
                    ('PeakWorkingSetSize', SIZE_T),
                    ('WorkingSetSize', SIZE_T),
                    ('QuotaPeakPagedPoolUsage', SIZE_T),
                    ('QuotaPagedPoolUsage', SIZE_T),
                    ('QuotaPeakNonPagedPoolUsage', SIZE_T),
                    ('QuotaNonPagedPoolUsage', SIZE_T),
                    ('PagefileUsage', SIZE_T),
                    ('PeakPagefileUsage', SIZE_T),
                    ('PrivateUsage', SIZE_T),
                ]
    
            GetProcessMemoryInfo = ctypes.windll.psapi.GetProcessMemoryInfo
            GetProcessMemoryInfo.argtypes = [
                wintypes.HANDLE,
                ctypes.POINTER(PROCESS_MEMORY_COUNTERS_EX),
                wintypes.DWORD,
            ]
            GetProcessMemoryInfo.restype = wintypes.BOOL
    
            def get_current_process():
                """Return handle to current process."""
                return GetCurrentProcess()
    
            def get_memory_info(process=None):
                """Return Win32 process memory counters structure as a dict."""
                if process is None:
                    process = get_current_process()
                counters = PROCESS_MEMORY_COUNTERS_EX()
                ret = GetProcessMemoryInfo(process, ctypes.byref(counters),
                                           ctypes.sizeof(counters))
                if not ret:
                    raise ctypes.WinError()
                info = dict((name, getattr(counters, name))
                            for name, _ in counters._fields_)
                return info
    
            def get_memory_usage(process=None):
                """Return this process's memory usage in bytes."""
                info = get_memory_info(process=process)
                return info['PrivateUsage']
    
        elif os.name in ['posix', 'mac']:  # linux/mac
            import resource
            windows_flag = False
            is_linux = True
        else:
            raise NotImplementedError('os.name=%r and must be nt, posix, mac' % os.name)
    except:
        is_memory = False
    
    #--------------------------------------------------------------------------------------------
    
    check_memory = True
    op2_filename = 'bwb_saero.op2'
    #exclude_results = ['displacements', 'stress', 'strain']
    ntimes = 1000
    m_init = []
    m_final = []
    for i in range(ntimes):
        if check_memory:
            if is_memory:  # pragma: no cover
                if is_linux: # linux
                    kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
                else: # windows
                    kb = get_memory_usage() / 1024
                mb = kb / 1024.
                print("Memory usage start: %s (KB); %.2f (MB)" % (kb, mb))
            else:
                raise RuntimeError('wmi (for Windows) or resource (for Linux/Mac) cannot be found')
            m_init.append(mb)
    
        #m0 = psutil.Process(os.getpid()).memory_info().rss/1024**3
    
        read_op2(op2_filename,
                       build_dataframe=False, debug=False,
                       #exclude_results=exclude_results,
                       skip_undefined_matrices=True)
    
        print('Unreachable objects:', gc.collect())
        #del gc.garbage[:]
        #print('Unreachable objects:', gc.collect())
    
        #--------------------------------------------------------------
        if is_memory and check_memory:  # pragma: no cover
            if is_linux: # linux
                kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
            else: # windows
                kb = get_memory_usage() / 1024
            mb = kb / 1024.
            m_final.append(mb)
            print("Memory usage   end: %s (KB); %.2f (MB)" % (kb, mb))
    
        #m1 = psutil.Process(os.getpid()).memory_info().rss/1024**3
        #print(m0, m1)
        #print(f'{m0:6.4f}|{m1:6.4f}|{id(op2)}')
    
    import matplotlib.pyplot as plt
    plt.plot(m_init, '-o', label='init')
    #plt.plot(m_final, '-o', label='final')
    plt.legend()
    plt.grid(True)
    plt.show()

**Comment by SteveDoyle2** [comment]
I was playing around with the objgraph module and managed to cut down the memory usage by deleting no longer relevant data members (so ~400 MB to 140 MB peak).  It looks as if it's methods that werent being cleaned up, but there is more.  I could actually get it to be ~75 MB peak and climb less by deleting **fewer** data members, but that makes no sense, so I think I'm just going to pretend it's some circular reference garbage collection oddity.  It's all done automatically in close_op2 and is pushed.

![image](https://user-images.githubusercontent.com/1059417/52371044-54f62300-2a09-11e9-9ee5-4ce60e4028bb.png)

**Comment by yellowhat** [comment]
Hi,
I have just tried your last commits:

```python
<IPython.core.display.HTML object>
0.1174|9.1023|184199992
<IPython.core.display.HTML object>
9.1023|18.0842|184188712
<IPython.core.display.HTML object>
18.0842|18.0856|192773592
<IPython.core.display.HTML object>
18.0825|18.0870|184188712
<IPython.core.display.HTML object>
18.0824|18.0860|192773592
```

The memory usage is much better now.

Thank you very much

**Comment by SteveDoyle2** [comment]
I think about the only thing I understand about memory inter-object references is that it's confusing.  There are 2 steps more than I'd like, which is a bit better than 26 there originally was.

![image](https://user-images.githubusercontent.com/1059417/52434909-584ee480-2ac5-11e9-9caa-14f964b6e980.png)

It's also possible that there is only 1 extra step (e.g., step ~500) given this graph...

![image](https://user-images.githubusercontent.com/1059417/52435028-9ba95300-2ac5-11e9-9075-8144384720b2.png)

**Comment by yellowhat** [comment]
Thank you very much, not the memory usage has much more sense:

```cmd
> test_op2 190130_TM01_X1_Crankshaft_MGPS.op2 --memory
binarydebug  = False
disablecompare = False
exclude      = []
geometry     = False
help         = False
is_mag_phase = False
is_sort2     = False
load_hdf5    = False
memory       = True
nx           = False
post         = None
profile      = False
quiet        = False
safe         = False
short_stats  = False
skip_dataframe = False
subcase      = None
version      = False
write_bdf    = False
write_f06    = False
write_op2    = False
write_xlsx   = False
OP2_FILENAME = '190130_TM01_X1_Crankshaft_MGPS.op2'
DEBUG:   test_op2.py:346              subcases = []
DEBUG:   op2_scalar.py:733            set_subcases - subcases = []
DEBUG:   op2_scalar.py:733            set_subcases - subcases = []
Memory usage start: 90284.0 (KB); 88.17 (MB)
DEBUG:   op2.py:589                   combine=True
DEBUG:   op2.py:590                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1448           op2_filename = '190130_TM01_X1_Crankshaft_MGPS.op2'
DEBUG:   op2_scalar.py:1601             table_name=b'OGS1'
DEBUG:   op2.py:608                   -------- reading op2 with read_mode=2 (array filling) --------
DEBUG:   op2_scalar.py:1601             table_name=b'OGS1'
DEBUG:   op2.py:877                   combine_results
DEBUG:   op2.py:621                   finished reading op2
DEBUG:   op2.py:589                   combine=True
DEBUG:   op2.py:590                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1448           op2_filename = '190130_TM01_X1_Crankshaft_MGPS.op2'
DEBUG:   op2_scalar.py:1601             table_name=b'OGS1'
DEBUG:   op2.py:608                   -------- reading op2 with read_mode=2 (array filling) --------
DEBUG:   op2_scalar.py:1601             table_name=b'OGS1'
DEBUG:   op2.py:877                   combine_results
DEBUG:   op2.py:621                   finished reading op2
---stats for 190130_TM01_X1_Crankshaft_MGPS.op2---
grid_point_stresses_volume_direct[(1, 2, 1, 0, 0, '', '')]
  type=GridPointStressesVolumeDirectArray ntimes=581 nelements=258788
  data: [ntimes, nelements, 8] where 8=[ox, oy, oz, txy, tyz, txz, pressure, ovm]
  node.shape = (258788,)
  location.shape = (258788,)
  data.shape = (581, 258788, 8)
  sort1
  modes = [  1   2   3 ... 579 580 581]
  eigns = [-1.808e-01 -5.654e-02 -2.533e-02 ...  3.024e+13  3.140e+13  3.146e+13]
  mode_cycles = [6.768e-02 3.784e-02 2.533e-02 ... 8.751e+05 8.918e+05 8.927e+05]

grid_point_stresses_volume_direct[(1, 2, 1, 0, 2, '', '')]
  type=GridPointStressesVolumeDirectArray ntimes=581 nelements=257891
  data: [ntimes, nelements, 8] where 8=[ox, oy, oz, txy, tyz, txz, pressure, ovm]
  node.shape = (257891,)
  location.shape = (257891,)
  data.shape = (581, 257891, 8)
  sort1
  modes = [  1   2   3 ... 579 580 581]
  eigns = [-1.808e-01 -5.654e-02 -2.533e-02 ...  3.024e+13  3.140e+13  3.146e+13]
  mode_cycles = [6.768e-02 3.784e-02 2.533e-02 ... 8.751e+05 8.918e+05 8.927e+05]

grid_point_stresses_volume_direct[(1, 2, 1, 0, 3, '', '')]
  type=GridPointStressesVolumeDirectArray ntimes=581 nelements=558
  data: [ntimes, nelements, 8] where 8=[ox, oy, oz, txy, tyz, txz, pressure, ovm]
  node.shape = (558,)
  location.shape = (558,)
  data.shape = (581, 558, 8)
  sort1
  modes = [  1   2   3 ... 579 580 581]
  eigns = [-1.808e-01 -5.654e-02 -2.533e-02 ...  3.024e+13  3.140e+13  3.146e+13]
  mode_cycles = [6.768e-02 3.784e-02 2.533e-02 ... 8.751e+05 8.918e+05 8.927e+05]

grid_point_stresses_volume_direct[(1, 2, 1, 0, 4, '', '')]
  type=GridPointStressesVolumeDirectArray ntimes=581 nelements=339
  data: [ntimes, nelements, 8] where 8=[ox, oy, oz, txy, tyz, txz, pressure, ovm]
  node.shape = (339,)
  location.shape = (339,)
  data.shape = (581, 339, 8)
  sort1
  modes = [  1   2   3 ... 579 580 581]
  eigns = [-1.808e-01 -5.654e-02 -2.533e-02 ...  3.024e+13  3.140e+13  3.146e+13]
  mode_cycles = [6.768e-02 3.784e-02 2.533e-02 ... 8.751e+05 8.918e+05 8.927e+05]


INFO:    op2.py:1085                  ---self.subcase_key---
INFO:    op2.py:1090                  subcase_id=1
INFO:    op2.py:1092                    (1, 2, 1, 0, 0, '', '')
INFO:    op2.py:1092                    (1, 2, 1, 0, 2, '', '')
INFO:    op2.py:1092                    (1, 2, 1, 0, 3, '', '')
INFO:    op2.py:1092                    (1, 2, 1, 0, 4, '', '')
Memory usage     end: 18958468.0 (KB); 18514.13 (MB)
build_dataframe is not implemented in GridPointStressesVolumeDirectArray
build_dataframe is not implemented in GridPointStressesVolumeDirectArray
build_dataframe is not implemented in GridPointStressesVolumeDirectArray
build_dataframe is not implemented in GridPointStressesVolumeDirectArray
Memory usage cleanup: 18958468.0 (KB); 18514.13 (MB)
dt = 935.893000
```
