### ISSUE TITLE
Set cannot be found

### ISSUE THREAD

**Issue by wolof2008** [SteveDoyle2/pyNastran#547]
when I run my code:
from pyNastran.bdf.bdf import BDF
model = BDF()
model.read_bdf("test.bdf", xref=True,encoding='latin1')
model.Set(3)

it return  'sid=3 not found.  Allowed SETx=[]' error, but my BDF file has the following case card:
SOL 101
CEND
SET 3 = 311,316,317,324
SET 99 = 1 THRU 10

I cannot figure out the issue, please help me!

**Comment by SteveDoyle2** [comment]
The Set function refers to set cards in the bulk data deck (e.g., SET1,
SET3), not the case control.  This is the same as how Element/Property/etc.
work.  You need to access the case control deck data, and specifically from
subcase 0 (the global subcase data that is not explicitly in a subcase).
This lets you access data that is potentially overwritten in SUBCASE 1.

case_control = model.case_control_deck
subcase = case_control.subcase[0]
values, set_id = subcases['SET 3']

**Comment by wolof2008** [comment]
Thank you very much, it works!
one thing should be take care is:
"subcases = case_control.subcases[0]" instead of "subcase = case_control.subcase[0]"
