### ISSUE TITLE
Way to ask for .OP4?

### ISSUE THREAD

**Issue by TomDeWeer** [SteveDoyle2/pyNastran#548]
Is there a way to ask nastran, via pyNastran, to generate a .OP4 file containing mass and stiffness matrices? It should create a file management section if the following form: 

ASSIGN OUTPUT4  'filename_kgg.op4' UNIT = 45 FORM = UNFORMATTED

**Comment by SteveDoyle2** [comment]
I'd ask the DMAP group over on yahoo.  I'm far from an expert on how to
pull matrices, but that line will only open the file vs. writing the
matrix.  If you plan on reading the matrix using pyNastran, I'd dump it to
the OP2 as it's faster to read.

If your goal is just writing that assign line, you can do:

model = read_bdf(bdf_filename)
model.system_command_lines = ['ASSIGN OUTPUT4 'filename_kgg.op4' UNIT = 45
FORM = UNFORMATTED']

**Comment by SteveDoyle2** [comment]
Please ask this over on the discussion forum.  This is for bugs/new features, not questions.  There are also people better at DMAP over there.
