### ISSUE TITLE
Reading small .OP4 matrix raises AssertionError

### ISSUE THREAD

**Issue by TomDeWeer** [SteveDoyle2/pyNastran#549]
In pyNastran.op4.op4, get_markers_sparse(): an AssertionError is raised when reading out a matrix with 150 rows, contained in an .OP4 file (see attachment [small_matrix.zip](https://github.com/SteveDoyle2/pyNastran/files/2897991/small_matrix.zip)). Debugging shows that it crashes after all the matrix elements have been read out.

When reading out a larger matrix, is_big_mat becomes True and the error is not raised.

Is there a quick way to solve this issue?

**Comment by SteveDoyle2** [comment]
Do you have the ASCII version of that matrix?

**Comment by TomDeWeer** [comment]
Of course, here it is: [small_matrix.zip](https://github.com/SteveDoyle2/pyNastran/files/2899522/small_matrix.zip)

**Comment by TomDeWeer** [comment]
I found the error. I requested the matrix via OUTPUT4 KGG//0/-45/2/FALSE/ $ . Changing the FALSE to TRUE solves the problem. I think it's because it asks nastran to output a large matrix in small matrix format.

**Comment by SteveDoyle2** [comment]
Nastran will automatically switch from a small matrix to a large matrix.  That was a small matrix, but there was a bug.  It's fixed now.
