### ISSUE TITLE
Problem with reading Eigenvectors from op2

### ISSUE THREAD

**Issue by Farzadtb** [SteveDoyle2/pyNastran#553]
Hello dear Steve and thank you for adding me to your group.
Sorry for the lengthy question, please tell me if I need to correct it ;

I just started using your tool and I just could not get over a problem, actually , I was running a 
displacement imposed SEMFREQ analysis , and 
I use FEMAP v10.3 , not Nastran but I think it's all the same about op2

I get this description when I insert  the following:
https://gist.github.com/Farzadtb/6e7989e14ab65a6e8d53773cfd84b108

I get this Output:
https://gist.github.com/Farzadtb/a7ae5e59c29c292ccb290ede36a3b0f0

but when I do 

print("loadcases = %s" % op2.eigenvectors.keys())

I get :

print("loadcases = %s" % op2.eigenvectors.keys())
loadcases = dict_keys([])

so I can not proceed with the modes etc

Could you please help me with this ?

Thank you very much

**Comment by SteveDoyle2** [comment]
That is expected.  You need to include the eigenvector request in your case control deck.  Currently, you've requested the complex displacement (frequency response) as output.  The eigenvectors are not included by default during a frequency analysis.  I'm not really a FEMAP or NX expert, but there are NX experts in the discussion forum.  It's located at:
https://groups.google.com/forum/#!forum/pynastran-discuss

Alternatively, run modes.
