### ISSUE TITLE
Reading OP4 with the Same Matrix Names

### ISSUE THREAD

**Issue by ratalex** [SteveDoyle2/pyNastran#559]
I would like to employ op4.read_op4 to read a stack of matrices from an OP4 NASTRAN output file. The problem is that all my matrices in the op4 have the same name. The code seems to read all of them but overwrites at every loop.
Would it be possible to append my matrices of the same name to a list (like a 3rd dimension of the matrix)
Thanks for your time and help.
Alex

**Comment by SteveDoyle2** [comment]
Why do your matrices have the same name?  How is that even possible?  Do you have an example?

**Comment by ratalex** [comment]
The matrix output is the Generalized Aerodynamics Matrix (QHH) within the aeroelastic solution sequences. For example the sol145 or sol146. It loops on the number of Mach number & reduced frequency pairs (from the MKAERO1 card) and stacks the QHH. The dimension of a single QHH is [nModes,nModes] and NASTRAN outputs each QHH one after another in a loop of number of Mach (outer loop) and reduced frequency (inner loop). Therfore, the size of the stacked-up QHH is QHH(M,K) = QHH[nModes,nModes].

The stacked matrices (with the same name) can be outputted at the sequence line number 203 from the Nastran 2008 sol146 SEAERO subDMAP for example. Here is an extract of the NASTRAN cards outputing the QHH matrices.

assign output4='QHH.ft94',unit=94,form=formatted,status=unknown
SOL 146
$ NASTRAN VERSION 2008
COMPILE SEAERO,SOUIN=MSCSOU,LIST,NOREF
ALTER 203
OUTPUT4 QHH//0/94
CEND
$
MKAERO1 0.2500  0.6000                                                  +MK
+MK     0.1000  0.2000  0.4000

**Comment by SteveDoyle2** [comment]
Alters are notoriously not compatible, so that doesn't run in my version of Nastran.

Can you make an small complete example and include the OP4 as well?  The bah plane model that's in the models directory is fine.

**Comment by ratalex** [comment]
assign output4='QHH.ft94',unit=94,form=formatted,status=unknown
ID BAH WING
SOL 145
TIME 100
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$ DMAP - OUTPUT4 QHH
COMPILE FLUTTER,SOUIN=MSCSOU,LIST,NOREF 
ALTER 'AMP   '
OUTPUT4 QHH//0/94
CEND

[bah_plane.zip](https://github.com/SteveDoyle2/pyNastran/files/3208728/bah_plane.zip)

Please find attached the OP4 (qhh.ft94) in the zipped file.

**Comment by SteveDoyle2** [comment]
Thanks.

It's supported now in the master/trunk.  It's Python 3 only now there as the 1.2 release was yesterday (I still haven't gotten around to announcing it).

**Comment by SteveDoyle2** [comment]
Also, I get that the QHH is a very specific table, but because the OP4 doesn't have explicit readers for the different matrices, they're not stacked together.  Also, it's not a guarantee that the matrix is actually square and not sparse, so rather than guessing I'll leave it up to the user.
You now get a list of forms and a list of matrices as the value for QHH.  Depending on the shape that you want, you may want to do an hstack, vstack or dstack.

**Comment by SteveDoyle2** [comment]
Note that if you only have 1 matrix, the format is the same as it was before.

**Comment by a-deblois** [comment]
Hello,

thanks for implementing your solution promptly. I am also interested in that feature. The problem is that our environment is under Anaconda5.1 (python 2.7.14). Our IT infrastructure is pretty rigid over here (!). 

Do I understand that python 2.7 is no longer supported as of pyNastran 1.2?

**Comment by SteveDoyle2** [comment]
Yes.  It's Python 3.6+ only now outside of a few bug fixes.

You can make virtual environments with anaconda with different versions of
python.  Just do this..
https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

Also, I strongly suggest encouraging you to bug your IT about upgrading.
Python 2.7 is end of life at the end of the year and will stop receiving
security updates from the PSF.  Matplotlib, ipython, and Jupyter. have all
dropped support completely.  Numpy and scipy are only doing bug fixes and
are done completely at the end of the year.

**Comment by a-deblois** [comment]
Hi again,

I was able to make a python 3.7 environment with our python2.7 (after multiple steps of permissions, missing packages, etc.!!). 

I successfully installed pyNastran1.2 from the 1.2 branch. However, it reproduces the same as 1.1. I assume that when you meant the Master branch, you referred to the 1.3. 

I am now in the process of installing the Master branch (1.3), and I get the following, despite my python 3.7 environment (emulated). Am I missing something?

$ python setup_no_gui.py install
fatal: Not a git repository (or any of the parent directories): .git
Upgrade your Python to 3.6+; version=(2.7.14)
(py3) 

Thanks for your help,
Antoine

**Comment by SteveDoyle2** [comment]
It sounds like you have another python on your path.  I'd make a simple
script like:

import sys
mport numpy
print(sys.version)
print(numpy.__path__)

and see what it tells you.  The first part will tell you what your python
is and the second where it is.

**Comment by a-deblois** [comment]
Appologies for my last email, there was indeed a permission issue (yet another) that prevented using python 3.7 .

I'm glad to say that pyNastran1.3 from the Master branch produces the expected results of QHH in a list.
thanks again,
Regards
