### ISSUE TITLE
bdf mirror with CAERO1

### ISSUE THREAD

**Issue by a-deblois** [SteveDoyle2/pyNastran#564]
Hi,
I seems that the bdf mirror ignores the coordinate frame (CP) defined on the CAERO1. The code should consider this coordinate system when computing the mirrored X1 and X4 of the CAERO1 card.
FYI, the code is fine to mirror the grids that have different CP, so you could recycle the same code for the X1 and X4.

To reproduce the error, simply put a CP on the CAERO1,
Thank you very much,
Antoine

**Comment by SteveDoyle2** [comment]
It's definitely not considered in the math and is documented as a limitation.

Is that really what should be done for the Cp though?  I've only ever used it as a sideslip coordinate system.  So for example, mirroring a rectangular wing that has sideslip on the coordinate system does should not exactly mirror the CAERO1 panels, but instead perform an ansymmetric mirroring.

**Comment by SteveDoyle2** [comment]
Uhhh...nevermind.  That's on the AERO/AEROS card.

Cp is easy.

**Comment by SteveDoyle2** [comment]
It should be working now.  I just needed to grab the right points.

**Comment by a-deblois** [comment]
Wonderful, it works fine now.
I have to say I am impressed with your efficiency!
Antoine

**Comment by SteveDoyle2** [comment]
Good stuff!  Keep finding errors in the aero stuff!  That's a lot of what I use.

It handles AESURF, AELIST, and mirroring of the coords used on the AESURF now as well.  The z-axis gets flipped (so it's an antisymmetric mirror), but the whole point of the y-axis of the coordinate system to set the hinge angle, so it's a bit of a cheat that should work well.
