### ISSUE TITLE
Problem with import results

### ISSUE THREAD

**Issue by Stefano2209** [SteveDoyle2/pyNastran#566]
Dear PyNastran users

I'm an user of Femap, NX Nastran and Autodesk Nastran (previously NEi Nastran) and I would like to try the software, but I have some problem with results loading.
I don't have problem with mesh loading but the software crash when I try to import .op2 results.

There's a particular option that I need to request in Autodesk Nastran or Femap software? where I'm wrong?
I attach a simple model: mesh file (lifting.nas) has been created with femap, while op2 file has been realized with autodesk nastran 2018.
[test.zip](https://github.com/SteveDoyle2/pyNastran/files/3537524/test.zip)

Thanks in advance

Best regards
Stefano

**Comment by SteveDoyle2** [comment]
That's an odd bug.  The date stamp was written in a slightly different format.  It should work now.

**Comment by Stefano2209** [comment]
I uninstall pynastran and re-install the updated version With "pip install pynastran" with anaconda console, but I have the same problem...

**Comment by Stefano2209** [comment]
I also try to open your op2 model in autodesk folder, but the result is the same.

**Comment by SteveDoyle2** [comment]
Using pip install will not give you the updated version, only the latest release version from 3 months ago.  You can clone the project using git or download the zip file.  The install procedure in the documentation talks about how to do that.
