### ISSUE TITLE
Example of how to access CQUAD4 shell forces?

### ISSUE THREAD

**Issue by trelau** [SteveDoyle2/pyNastran#568]
Any good example of how to access CQUAD4 element forces for a given element ID? I'm using op2.cquad4_force but it's not clear where to go from there. I have just a simple linear static analysis result.

**Comment by SteveDoyle2** [comment]
There is no examples of that.  The documentation goes through OP2 examples.  In particular, take a look at the CQUAD4 stress.  It’s very similar and if you understand that, you’ll understand all the OP2 objects.  That said, if you don’t know numpy, it’s going to be difficult.

If you run test_op2 on the output file, you’ll see all the data in the OP2 along with the data structure of each object.  You’re after the cquad4_force result.

Accessing a single element output is very inefficient, so it’s generally preferred to take advantage of numpy’s searchsorted method.

Steve
