### ISSUE TITLE
CQUAD4 stress in freq response

### ISSUE THREAD

**Issue by m-griebel** [SteveDoyle2/pyNastran#570]
I cloned the master branch and installed using setup_no_gui.py

The oes.py in the master branch appears to have a catch for mag/phase in freq response but the oes.py file that is created during setup (that lives in my anaconda site-packages) is not the same. Maybe this oes.py isn't part of the current release or maybe I've made a user error?

I believe that's why I get a Runtime Error: --Table3Data-- when trying to import an op2 with stress on CQUAD4 elements. I ran sine vibe on the iSat model and couldn't import the op2.

**Comment by SteveDoyle2** [comment]
It sounds like you have an old install in your site-packages.  Just delete it and it'll probably work.  You might need to run setup.py again.

If you're installing from a release, `pip install pyNastran` is a better approach.  If you're planning on ever updating pyNastran from some working version in the master/trunk, then `python setup.py develop` is better.  Really, the only difference is `python setup.py install` (or `pip install ..` just copy the files to site-packages, whereas `develop` does not (and creates a link).

**Comment by m-griebel** [comment]
Thanks. I uninstalled and reinstalled using `develop`. Made it through OESVM1, now I'm getting a NotImplementedError: b'RDSPARSE' is not a supported PARAM. I think RDSPARSE is the default in NX. I can open a new issue if you want to close this one.

**Comment by m-griebel** [comment]
works if I just add b'RDSPARSE' to the STR_PARAMS_1 list

**Comment by SteveDoyle2** [comment]
Thanks.  I'll add that one.

There are way too many parameters and a whole bunch of secret ones.
