### ISSUE TITLE
OP2 object has no attribute modal contribution

### ISSUE THREAD

**Issue by m-griebel** [SteveDoyle2/pyNastran#571]
I was able to read the op2, but the stresses get placed in table type `modal_contribution.cquad4_stress[1]`. When I try to assign that to a variable, I get an `AttributeError: OP2 object has no attribute modal_contribution`. I've attached my dat file.

```>>> model = read_op2(op2_filename)
>>> print(model.get_op2_stats(short=True)
    GridPointWeight: ref_point=0 mass=1e+06; [reference_point, M0, S, mass, cg, IS, IQ, Q]
    EQEXIN(nid, ndof, doftype); nnodes=5384
    BGPDT(cd, xyz); nnodes=5384
    modal_contribution.cquad4_stress[1]
    PARAM[GRDPNT] = [0]
    PARAM[POST] = [-1]
    PARAM[RDSPARSE] = ['NO']
    eigenvalues['ISAT_SM_LAUNCH_4PT MODES TO 100 HZ']
    Matrix['BHH'];      shape=(545, 545); type=scipy.sparse.coo.coo_matrix;      dtype=float64;   desc=symmetric
    Matrix['KHH'];      shape=(545, 545); type=scipy.sparse.coo.coo_matrix;      dtype=complex128; desc=symmetric
>>>stress = model.modal_contribution.cquad4_stress[1]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'OP2' object has no attribute 'modal_contribution'
```
[iSat_launch_100Hz_SineSweep.zip](https://github.com/SteveDoyle2/pyNastran/files/3699990/iSat_launch_100Hz_SineSweep.zip)

**Comment by SteveDoyle2** [comment]
Oh...I need to fix that.

model.modal_contribution.cquad4_stress should be listed as:

model.op2_results.modal_contribution.cquad4_stress

I guess I might as well get your thoughts. I'd like to maintain backwards
compatibility, but there should also be one obvious way to do things. The
OP2 class is a mess because of all the methods. Putting all the results
(e.g., things like self.eigenvectors) into op2_results would help
consistency, but would break backwards compatibility. As it is right now,
only special results are stuck in op2_results.

**Comment by m-griebel** [comment]
Backwards compatibility meaning if someone runs an old script with new pyNastran? I don't think you should keep yourself tied to old coding just to maintain backwards compatibility. Speed/consistency/clarity should definitely outweigh backwards compatibility in my mind. I had a lot of scripts start falling apart with projects dropping Python 2 support; the user just needs to know what to fix.

You could try to put in catches to redirect users to the way you'd like them to access things as you change it. So if someone put model.cquad4_stress but you're storing everything in model.op2_results.cquad4_stress now you just redirect it to the right place and issue a warning. I guess that means you carry around some compatibility methods, but then all the meat of your data will live in one place.

I think putting all results inside one location is definitely a good idea. Abaqus Python is like that: 
```
import odbAccess
session.odbs[name].steps[name].frames[i].fieldOutputs[name]
```

**Comment by SteveDoyle2** [comment]
fixed documentation of `test_op2`
