### ISSUE TITLE
read_op2 speed

### ISSUE THREAD

**Issue by m-griebel** [SteveDoyle2/pyNastran#572]
I've written a short script to read CQUAD4 stresses from a sine vibration run (SOL SEMFREQ). I started with the iSat model since it's provided as an example. I've requested quite a bit of frequency data, but not unreasonable (my output is ~1000 frequencies and ~7700 elements).

It's taking about 2 min to read the op2, which doesn't seem wild to me, but is longer than I expected based on other comments. The op2 is only 263MB. I'm just using read_op2(op2_filename, debug=False).

Any ideas? I can post to the user discussion if you think that's more appropriate.

**Comment by SteveDoyle2** [comment]
That data object is not vectorized, so it's slow.  If you turn debug on,
you'll see lots of messages about that.  The OESVM1 support is still new.

Vectorization helps large data blocks the most.  7000 elements will have a
much smaller data block vs a data block with 100,000 nodal displacements,
so it's less efficient.  The high number of frequencies also means that you
have to reread the table #3 many times to get the data (vs. say a single
frequency step).

**Comment by m-griebel** [comment]
Fair enough. I figured it was a newer feature. Definitely helpful. I see you're already grabbing von mises stress (it's labeled maxshr, but I assume that's just a copy/paste), any plan to write that to the OP2 in the future instead of just directional stresses?

**Comment by SteveDoyle2** [comment]
oohh...

It looks like I missed the von Mises part of OESVM1.  The first part of the NX complex table (OESVM1) is the same as MSC's table, so the first 3 terms are correct (oxx, oyy, txy), but the von Mises was dropped.

**Comment by m-griebel** [comment]
I thought about just adding it, but I'm not familiar enough with the implications yet.

**Comment by SteveDoyle2** [comment]
Still slow (and probably missed some strain tables), but at least von Mises stress exists now.

**Comment by m-griebel** [comment]
Sweet, thanks! I'll check it out.
