### ISSUE TITLE
How to write STEP(or)IGES(0r).Part from Surf(or)Mesh (or) STL ?

### ISSUE THREAD

**Issue by selvakarna** [SteveDoyle2/pyNastran#574]
How to write STEP(or)IGES(0r).Part from Surf(or)Mesh (or) STL ?

**Comment by SteveDoyle2** [comment]
I’m not really clear on the question.  There is no CAD support in pyNastran (so STEP and IGES).  

There is STL support, which is just a bag of triangles.  There is an STL class that has a write_stl method.  If you place the data right, you can write an STL.  However, it’s a very simple format, so I’m not sure if that buys you much.

The data still needs a source.

**Comment by selvakarna** [comment]
Okay,, thanks for spend your time... @SteveDoyle2
