### ISSUE TITLE
read_op2 avoiding crash

### ISSUE THREAD

**Issue by alby3z** [SteveDoyle2/pyNastran#577]
I am struggling to get `read_op2 `not crashing. Is there a way to tell pyNastran "just read this xyz table"?

I see that there is a private method `read_tables `in the `op2 `class, I would need something like that. The method `set_additional_result_tables_to_read` is not the right one for that scope.

**Comment by SteveDoyle2** [comment]
No.  You can tell it to read specific results, but you can't tell it to just read the OUGV1 table.  The OP2 is not consistent enough to read an OUGV1, GEOM1 and an IBULK with the same function.

The approach I taken is to just make the reader work.  If you have an example that doesn't work, I can take a look.

**Comment by alby3z** [comment]
It is always tricky to get something representative that I can share.

Running the command: `op2.read_op2(filename)`
I got an error related to `NotImplementedError: Invalid Table = b'MPOUT'`

> Traceback (most recent call last):
> 
>   File "<ipython-input-120-0dff3442d7ad>", line 1, in <module>
>     runfile('C:/Users/10758/Desktop/untitled1.py', wdir='C:/Users/10758/Desktop')
> 
>   File "C:\Users\10758\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\10758\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/10758/Desktop/untitled1.py", line 30, in <module>
>     op2.read_op2(filename,skip_undefined_matrices = False)
> 
>   File "C:\Users\10758\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.7.egg\pyNastran\op2\op2.py", line 597, in read_op2
>     load_as_h5=load_as_h5, mode=mode)
> 
>   File "C:\Users\10758\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.7.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1385, in read_op2
>     table_names = self._read_tables(table_name)
> 
>   File "C:\Users\10758\AppData\Local\Continuum\anaconda3\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.7.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1574, in _read_tables
>     raise NotImplementedError(msg)
> 
> NotImplementedError: Invalid Table = b'MPOUT'
> 
> If you have matrices that you want to read, see:
>   model.set_additional_matrices_to_read(matrices)  matrices = {
>       b'BHH' : True,
>       b'KHH' : False,
>   }  # you want to read some matrices, but not others
>   matrices = [b'BHH', b'KHH']  # assumes True
> 
> If you the table is a geom/result table, see:
>   model.set_additional_result_tables_to_read(methods_dict)
>   methods_dict = {
>       b'OUGV1' : [method3, method4],
>       b'GEOM4SX' : [method3, method4],
>       b'OES1X1' : False,
>   }
> 
> If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
>   methods_dict = {
>       b'OUGV1' : [method],
>   }
>   model.set_additional_generalized_tables_to_read(methods_dict)

I got the same message when I run `test_op2`.

I don't know if this may help.

**Comment by SteveDoyle2** [comment]
So based on the DMAP guide, MPOUT is some kind of Monitor Point table.  It should be pretty easy to just SPC a node in 123456 and start deleting large areas of your model and making sure the model still works and the op2 still fails.  Once you're down to a few elements, just change the properties to steel or something.  I'm sure you can send that.

Beyond that, you can remove them.

**Comment by alby3z** [comment]
I will see what I can do to get a representative model.

The point is that I am doing this analysis to recover the internal loads, so I cannot get rid of them ...

**Comment by SteveDoyle2** [comment]
closing due to innactivity
