### ISSUE TITLE
Reading sol 106 op2 error

### ISSUE THREAD

**Issue by wolof2008** [SteveDoyle2/pyNastran#579]
When I use read_op2 command to read a sol106 op2 file, it returns an error " 1 ndim Categorical are not supported at this time", it seems something wrong when building the dataframe. 
sol101 op2 file is OK.

**Comment by SteveDoyle2** [comment]
I'd need to see an example to see what's wrong.  I need more to go on than that.

Also, which version of python, pandas and pyNastran are you using?

**Comment by wolof2008** [comment]
I used python3.7, pandas 0.24.2 and pyNastran 1.2.1, the op2 and nastran file is attached.

[test.zip](https://github.com/SteveDoyle2/pyNastran/files/3783019/test.zip)

**Comment by SteveDoyle2** [comment]
That is strange.  There's is some issue with pandas that doesn't seem correct, but it's probably a pyNastran issue :)

https://github.com/pandas-dev/pandas/issues/29297

**Comment by SteveDoyle2** [comment]
So, it looks like this issue started with numpy >= 1.13, but I don't know why.  Regardless, Python 3.7 doesn't support numpy 1.12 (nor does pyNastran), so that doesn't really matter.

I rewrote the routine to work with modern numpy.  You'll need to get the trunk/master/github version.
