### ISSUE TITLE
del cards from a bdf file to replace

### ISSUE THREAD

**Issue by MarulandaAL** [SteveDoyle2/pyNastran#580]
Hello,
I need to do to a simple action but a dnot kno how.
I read a bdf file, i modified a long list of element-cards and put them in another bdf.
How can i replace the original cards in "model" with all the cards in "model_new_cards" (thay have the same id obvusly). 
Thanks a lot.

model = BDF()
model.read_bdf(bdf_filename)

model_new_cards = BDF()
model_new_cards.add_...

**Comment by SteveDoyle2** [comment]
Please post in the mailing list.  The issue tracker is for bugs and new features.

**Comment by MarulandaAL** [comment]
Sorry, but where is the mailing list?
Thanks.
