### ISSUE TITLE
Trouble reading op2 data

### ISSUE THREAD

**Issue by derrickearly** [SteveDoyle2/pyNastran#581]
Tried to run the following:

from pyNastran.op2.op2 import read_op2
op2_filename = 'goesr-fdlc-DMIG-sol-103_10.op2'
model=read_op2(op2_filename, build_dataframe=True, debug=False)

It throws this error:

  File "C:\Users\daearly\AppData\Local\Continuum\anaconda3\lib\site-packages\pyNastran\op2\result_objects\table_object.py", line 346, in build_dataframe
    major_axis=node_gridtype, minor_axis=headers).to_frame()  # to_xarray()

TypeError: Panel() takes no arguments

I have attached a copy of the op2 file.

[goesr-fdlc-DMIG-sol-103_10.zip](https://github.com/SteveDoyle2/pyNastran/files/3940424/goesr-fdlc-DMIG-sol-103_10.zip)

**Comment by SteveDoyle2** [comment]
You didn't mention your version, but it's working fine for me.

**Comment by derrickearly** [comment]
I'm running python..

import sys
print(sys.version)
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

I think that I'm running pyNastran version 1.2.1.  Here is a copy of the RECORD file.

[RECORD - Copy.txt](https://github.com/SteveDoyle2/pyNastran/files/3941267/RECORD.-.Copy.txt)

**Comment by SteveDoyle2** [comment]
Pandas broke backwards compatibility in v0.25, so if you use an older version than that (or update to the master version), it'll work.

**Comment by derrickearly** [comment]
Looks like pandas 24.2 did the trick!  Thank you.
