### ISSUE TITLE
get_ABD_matrices returns wrong results

### ISSUE THREAD

**Issue by wolof2008** [SteveDoyle2/pyNastran#584]
Hi,
When I tried to calculate the ABD matrice by "ABD = model.properties[1601].get_ABD_matrices()", it returns:
![ABD](https://user-images.githubusercontent.com/35770782/71576633-3373bd80-2b2c-11ea-830d-f7c247d40fdf.PNG)

The A and D matrix are not correct by comparing them with Altair Hypermesh output:
![ABD2](https://user-images.githubusercontent.com/35770782/71576314-30c49880-2b2b-11ea-89a7-6a5f8d248f30.PNG)

At first I thought it might due to the "SYM" symbol, after I rewrote  bdf without using "SYM", the A matrix became correct but the D matrix was still wrong.
My bdf is attached.
[pcomp_test.zip](https://github.com/SteveDoyle2/pyNastran/files/4009437/pcomp_test.zip)

**Comment by SteveDoyle2** [comment]
Thanks.  It's fixed now.  I only needed A before to make EI plots :)

There was an issue with the mids not handling symmetry correctly (so only the bottom half plies were calculated when symmetric).  I was also trying to be fancy with the D formula, which was just wrong.
