### ISSUE TITLE
PBEAM: Defaults for N2(A) and N2(B)

### ISSUE THREAD

**Issue by RafFloSan** [SteveDoyle2/pyNastran#585]
Hi Steve and Contributors!

First of all, I’d like to express my appreciation for your work!! This project is really great!

After using the bdf module occasionally, I came across an issue regarding the implementation of some defaults for the PBEAM card, which I wanted to let you know. The neutral axis offsets N1(A), N2(A), N1(B), N2(B) are specified on the last continuation. According to the QRG and the general use, the defaults for Ni(B) (end B) are the values for end A Ni(A).

![image](https://user-images.githubusercontent.com/59376666/71605136-0bee1680-2b67-11ea-9943-6e9f63bb0c53.png)

However, the defaults are currently implemented as follows:

N1a = 0.
N1b = 0.

AND
        if n2a is None:
            n2a = n1a
        if n2b is None:
            n2b = n1b  

Meaning, if no z-component is specified, the y-component is used (on both ends A and B).
This is somewhat significant, since it changes the inertias significantly.
The same issue seems to be applicable for CoG of NSM M2(A) and M2(B).

Would be great, if you could have a look into this.

Many thanks and best regards,
Rafael

**Comment by SteveDoyle2** [comment]
That was easy.  The naming scheme for those variables is so weird.  I get mixed up on node A/B and directions 1/2.  It should be fixed now.

**Comment by RafFloSan** [comment]
Wow, that was quick! I agree, the naming of these variables could be better and is easy to mix up. Anyway, looks good now. Thanks!
