### ISSUE TITLE
How to skip a unsupported table such as GEOMU in OP2 with read_op2? 

### ISSUE THREAD

**Issue by EmanueleCannizzaro** [SteveDoyle2/pyNastran#589]

**Comment by SteveDoyle2** [comment]
You can't.  It has to be added to the list of tables.  Tables are different enough that there isn't a common way to skip all of them.

**Comment by EmanueleCannizzaro** [comment]
Steve,

Thank you.

How do I add or remove GEOMU to the table list?

Emanuele

**Comment by SteveDoyle2** [comment]
Go to the pyNastran/op2/op2_interface and nx_tables or msc_tables.py and add GEOMU to one of the lists.  It’s a game of a whack-a-mole if you don’t know what’s in the table, but probably where the GEOM1 is.

**Comment by SteveDoyle2** [comment]
If none of those works, it needs a custom reader.
