### ISSUE TITLE
Skipped matrix in OP2 read 

### ISSUE THREAD

**Issue by lucasberso** [SteveDoyle2/pyNastran#592]
Hello Steve, 

I am trying to read an optimization output from MSC Nastran but at the time of reading the OP2 file the DSCMCOL table is skipped. According to the f06 the table has been generated, and for the DSCM2 matrix there has been no problem and I can find it inside the generated OP2 object under the matrixes attribute. 

Thank you so much!

Edit 1: I found a previous similar issue which is also related to the DSCMCOL output, however I could not figure out how to include it through the set_generalized_tables_to_read function. Nonetheless, I have attached the BDF, f06 and OP2 files in case it could be of any help. 

[goland_final_test.zip](https://github.com/SteveDoyle2/pyNastran/files/4250055/goland_final_test.zip)

[https://groups.google.com/forum/#!searchin/pynastran-discuss/op2$20table|sort:date/pynastran-discuss/vNYX70fGXe0/37tB_KKSBwAJ](url)

**Comment by SteveDoyle2** [comment]
The DSCMCOL is very poorly supported at this point.  You can skip it and that's about it.

I'm not entirely sure what's going on in your example, but it looks like my MSC DMAP guide is pretty outdated.  What I'm seeing is:

    seid=0 (weight)
    mode_num=1 subcase=1 seid=0 (normal modes)
    grid=1 comp=0 subcase=1 freq=1.3563156426940112e-19 ply=538976288 seid=0 (frequency response displacement)
    id=1 ???=0 subcase=1 freq=1.3563156426940112e-19 ply=538976288 seid=0 (???)

where the ??? is some undocumented response type (maybe it's stress?).  You also don't have any PCOMPs, so I have no idea what a ply id of 538976288 means.  

MSC also removed their documentation a few years ago.  Could you send me the latest QRG and DMAP guides?

Maybe also the bigger question is what should the output look like?  As far as I can tell, it's just a bunch of flags that you need to cross-reference, so maybe a dictionary of dictionaries?

**Comment by lucasberso** [comment]
Thank you for the quick response Steve. 

In the proposed example I was performing a modal analysis taking as objective function the weight and just one response, which would be the eigenvalue for the first mode. In that way, I get a sensitivity matrix with four columns. The first one for the weight response, and the remaining three for the eigenvalue, GMASS and GSTIFF (these last two I don't know why Nastran writes them in the OP2, nonetheless they are linked to the FREQ card that I used for computing the eigenvalue sensitivity). 

That's why I imagine that the data stored in the DSCMCOL should look like a dictionary of dictionaries, as you have said, that for each response (column in the sensitivity matrix) stores in some way the response type, subcase, component, etc. At the end I guess that it should mimic the lables that appear in the f06 when you print the sensitivity matrix. 

Regarding your code fragment, how did you get that output? It seems that it is properly identifying the weight and frequency responses but I have no clue what it could be the undocumented response. 

If you don't mind, it could be interesting to analyze how the output looks for the same example but with a static analysis and with a stress constraint in two elements. So I attach you that little example and all the DMAP and QRG documentation that you asked for. 

[STRESS_goland_final_test.zip](https://github.com/SteveDoyle2/pyNastran/files/4253982/STRESS_goland_final_test.zip)

[https://we.tl/t-sNo44tY0HA ](url)

**Comment by lucasberso** [comment]
I also found digging in the documentation that in the OP2Reader class it seems to be some kind of code to read the DSCMCOL table. However, in my Python editor this class looks completely different. 

[https://pynastran-git.readthedocs.io/en/latest/_modules/pyNastran/op2/op2_interface/op2_reader.html](url)

**Comment by SteveDoyle2** [comment]
Are you using 1.2 or are you using the master?  The docs you referenced are
for the master/latest.  1.2 was released ~May (so before the post that you
mentioned).  I'm not particularly prompt at doing releases.

DSCMCOL reading is significantly better than it was 2 days ago, so give it
a shot.  You can even dump a partial f06 with it now.

**Comment by lucasberso** [comment]
Hello Steve, I was using version 1.2 and now that I have updated it works perfectly. You can consider the issue solved. 

Thank you so much!

**Comment by SteveDoyle2** [comment]
Sounds good to me, but it will definitely crash on new results :)
