### ISSUE TITLE
The Panel class is removed from pandas.

### ISSUE THREAD

**Issue by Juanlvelar** [SteveDoyle2/pyNastran#594]
Hello,

I am trying to read some op2s, select subcases and combine loads with pandas, but the first problem I found is I cannot load the op2.

This is my code to read the database:

import os
import pandas as pd
pd.set_option('precision', 3)

import pyNastran
from pyNastran.op2.op2 import read_op2

op2_filename =  "THML_027_X02.op2"
model = read_op2(op2_filename, build_dataframe=True, debug=True, skip_undefined_matrices=True,encoding=None)

And this is the error message:

C:\ProgramData\Anaconda3\lib\site-packages\pyNastran\op2\tables\oes_stressStrain\real\oes_rods.py:95: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  self.data_frame = pd.Panel(self.data, major_axis=self.element, minor_axis=headers).to_frame()
ERROR:   op2.py:760                     type=RealRodStressArray nelements=8884
  eType
  data: [1, nelements, 4] where 4=[axial, SMa, torsion, SMt]
  element.shape = (8884,)
  data.shape = (1, 8884, 4)
  element type: CROD
  sort1
  lsdvmns = [20010]

ERROR:   op2.py:761                   build_dataframe is broken for RealRodStressArray

any solution?

thanks

**Comment by SteveDoyle2** [comment]
Pandas removed the Panel class in 0.25.  If you use an older version (~0.20-0.24), it'll work with pyNastran 1.2.

Alternatively, use the latest pyNastran in github that's available for checkout and download.  I promise it's better :)
