### ISSUE TITLE
read_op2: NotImplementedError: b'XXXXXXXX20182   1   \x00\x00\x00\x00        '

### ISSUE THREAD

**Issue by Lgcsimoes** [SteveDoyle2/pyNastran#596]
Hello!

I am trying to open an op2 file generated by MSC Nastran V2018.2, however I get an error when running the git cloned pyNastran version:

`>>> model = OP2()
>>> model.read_op2(op2_filename)
DEBUG:   op2.py:527                   combine=True
DEBUG:   op2.py:528                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1531           op2_filename = 'plate.op2'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lcsimoes\anaconda3\envs\pyNastran\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.8.egg\pyNastran\op2\op2.py", line 538, in read_op2
    table_names = OP2_Scalar.read_op2(self, op2_filename=op2_filename,
  File "C:\Users\lcsimoes\anaconda3\envs\pyNastran\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.8.egg\pyNastran\op2\op2_interface\op2_scalar.py", line 1549, in read_op2
    self.op2_reader.read_nastran_version(mode)
  File "C:\Users\lcsimoes\anaconda3\envs\pyNastran\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.8.egg\pyNastran\op2\op2_interface\op2_reader.py", line 225, in read_nastran_version
    mode = _parse_nastran_version(
  File "C:\Users\lcsimoes\anaconda3\envs\pyNastran\lib\site-packages\pynastran-1.3.0+dev.no.checksum.error-py3.8.egg\pyNastran\op2\op2_interface\op2_reader.py", line 5542, in _parse_nastran_version
    raise NotImplementedError(data)
NotImplementedError: b'XXXXXXXX20182   1   \x00\x00\x00\x00        '`

Am I doing anything wrong, or is this version not supported yet?

Thank you!

**Comment by SteveDoyle2** [comment]
Not sure.  Do you have an example?

**Comment by Lgcsimoes** [comment]
Sure, here goes a zipped op2 file.
Thanks!
[plate.zip](https://github.com/SteveDoyle2/pyNastran/files/4345621/plate.zip)

**Comment by SteveDoyle2** [comment]
That issue at least is fixed.  If you're just using results, it'll work.
The OP2 geometry reading is bugged though.  It looks like MSC changed the OP2 format for CQUAD4.  Could you attach the associated BDF as well as the QRG.pdf and DMAP.pdf guides?  MSC doesn't put them online anymore.

**Comment by SteveDoyle2** [comment]
There is no data because you're still on the array sizing step and it
crashed.  The data is saved during read_mode=2.

DEBUG: op2.py:528 -------- reading op2 with read_mode=1 (array sizing)
--------

>  Unfortunately I think I cannot share this OP2 with you.

Could you try running one of the frequency examples in the pyNastran/model
directory (e.g., pyNastran/model/elements/freq_elements.bdf)?  You might
need to modify it a bit to make the OUG1F table.

**Comment by Lgcsimoes** [comment]
Here are the QRG.pdf and DMAP.pdf guides.

Thanks, I will work on a model that output the OUG1F table and send to you soon..
[qrg.zip](https://github.com/SteveDoyle2/pyNastran/files/4374674/qrg.zip)

[dmap.zip](https://github.com/SteveDoyle2/pyNastran/files/4374664/dmap.zip)

**Comment by SteveDoyle2** [comment]
I added at least skipping support for the OUG1F table.  I think what's going on is that the OUG1 table has the static results while the OUG1F table has the frequency results.  

It's probably not very useful to not get the OUG1F data, but I need an example for that.

**Comment by Lgcsimoes** [comment]
Sorry taking too long, you can finally find an example OP2 and BDF for the Nastran run with the OUG1F table. Thank you for your support!
[acoust2_op2.zip](https://github.com/SteveDoyle2/pyNastran/files/4408847/acoust2_op2.zip)
[acoust2_bdf.zip](https://github.com/SteveDoyle2/pyNastran/files/4408850/acoust2_bdf.zip)

**Comment by SteveDoyle2** [comment]
No worries.  You gave me the new dmap guide :)

I think we're all not as super on the ball right now.  Looks like it works though!

![image](https://user-images.githubusercontent.com/1059417/78086195-0ffe2000-7372-11ea-9da4-a71c9e3f110d.png)

**Comment by SteveDoyle2** [comment]
looks like it's done; closing

**Comment by Lgcsimoes** [comment]
That's great, thank you!
