### ISSUE TITLE
SET2 Card Support

### ISSUE THREAD

**Issue by zuckberj** [SteveDoyle2/pyNastran#597]
Hey, I couln't find the SET2 class.
Is there any support to this card, or planned support?
If not, I could work on this!

Thanks in advance.

SET2 Definition on NX10:

_Grid Point List_

Defines a list of structural grid points in terms of aerodynamic macro elements.

FORMAT: SET2 SID MACRO SP1 SP2 CH1 CH2 ZMAX ZMIN

**Comment by SteveDoyle2** [comment]
No, there is no support for it.  I've never seen a model with it and try to only add cards that I have models for.

I'd love the help.  Cards are actually pretty easy to add, so it shouldn't take too long.  The cross-referencing stuff is really important as well.  Make sure to add some tests!

**Comment by zuckberj** [comment]
#600 linking to the PR

**Comment by SteveDoyle2** [comment]
merged; closing
