### ISSUE TITLE
Copy Paste Mistake

### ISSUE THREAD

**Issue by JensNeumannZAL** [SteveDoyle2/pyNastran#599]
In this file https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/converters/nastran/gui/nastran_io.py in line 228, there is a mistake that makes the code crash when it is run: `self.nastran_tools_menu.setVisiblnastran_tools_menue(False)`

The method is obviously meant to be `setVisible(False)`, but the `nastran_tools_menu` got in between.

**Comment by SteveDoyle2** [comment]
Thanks!  That was easy!
