### ISSUE TITLE
FUNDING.yml broken

### ISSUE THREAD

**Issue by timhoffm** [SteveDoyle2/pyNastran#601]
![image](https://user-images.githubusercontent.com/2836374/79309491-ae55be00-7efa-11ea-87bd-926994e67a96.png)

**Comment by SteveDoyle2** [comment]
Oh...I should fix that.

I thought I was done.  Looks like there are a few steps that I missed.  Thanks!

**Comment by SteveDoyle2** [comment]
Halfway done.  Looks like the ball is in Github's court now.  I think they to approve it again.  It says it should be done within 2 weeks, but hopefully it's sooner.

**Comment by SteveDoyle2** [comment]
I just got an approval email, so I think it's all live it.

Could you take a look at the page see what you think?

**Comment by timhoffm** [comment]
Looks good!
