### ISSUE TITLE
SEBULK validation issue

### ISSUE THREAD

**Issue by AlejandroStewart** [SteveDoyle2/pyNastran#608]
Hello,
When reading the geometry from an op2 that contains external superelements, I have the following problem with SEBULK cards: (trimmed error output)
![image](https://user-images.githubusercontent.com/14002967/84714687-b79cee80-af6e-11ea-8e6f-c814ee3a7e56.png)

 ```
 File "C:\ProgramData\Anaconda3\lib\site-packages\pyNastran\bdf\cards\superelements.py", line 1012, in validate
    assert self.superelement_type in ['PRIMARY', 'REPEAT', 'MIRROR', 'COLLCTR', 'EXTERNAL', 'EXTOP2'], self.superelement_type
AssertionError: 5
```
I have digged and apparently you define the field type with a string, but when the op2 returns the card it does so with an integer.

The funniest part is that it seems to be completly ok according to QRG and DMAP guide.

I wonder why they kept the method field as a string and not type...

![image](https://user-images.githubusercontent.com/14002967/84714669-a7850f00-af6e-11ea-8481-0477ee1f2a71.png)

![image](https://user-images.githubusercontent.com/14002967/84714752-dbf8cb00-af6e-11ea-9927-b35d1bb25b02.png)

**Comment by SteveDoyle2** [comment]
It's not a string internally, but rather an integer (see the DMAP guide).  The QRG defines it as a string and does not support integers, so it needs to be mapped.  They don't define what that mapping is, so a crash happens when the card is created incorrectly.

Given the following code, I'm not sure what's going.  You should have hit the NotImplementedError.

            (seid, superelement_type, rseid, method, tol, loc, media, unit) = out
            if superelement_type == 1:
                superelement_type = 'PRIMARY'
            elif superelement_type == 5:
                superelement_type = 'EXTOP2'
            elif superelement_type == 6:
                superelement_type = 'MIRROR'
            elif superelement_type == 7:
                superelement_type = 'FRFOP2'
            else:  # pragma: no cover
                raise NotImplementedError(f'superelement_type={superelement_type} not in [PRIMARY, EXTOP2, MIRROR, FRFOP2]')

            # other stuff
            sebulk = self.add_sebulk(seid, superelement_type, rseid,
                                     method=method, tol=tol, loc=loc, unitno=unit)
            sebulk.validate()

I think I need to an example.

**Comment by AlejandroStewart** [comment]
I just realized that the python environment was not using the latest  pynastran version and those lines don´t even exist. my bad, sorry
