### ISSUE TITLE
implement better method for tracking revision number

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#61]
```
when developing it is impractical to update the revision every time i want to 
commit.  additionally, any users that submit bug reports need to be correct in 
their version number.  pySVN seems to return inaccurate revision numbers...
```

Original issue reported on code.google.com by `mesheb82` on 24 Jan 2012 at 7:15

**Comment by SteveDoyle2** [comment]
The scipy message Nils' had was actually the chosen approach (it only took 3 years).  Scipy is using git to create version numbers, so now that pyNastran uses git, it can too.
