### ISSUE TITLE
Failed to read PSD results

### ISSUE THREAD

**Issue by qlshzjw** [SteveDoyle2/pyNastran#610]
Hello all，
The lastest version supports the PSD results. I tried to read but failed. Can someone show a short sample to read the psd stress?

**Comment by SteveDoyle2** [comment]
There are multiple ways to store PSD results (e.g., PSDF, OUGPSD2 tables) and I'm far from an expert on how to do it, especially given that there is MSC/NX/Autodesk Nastran.

I suggest reading through the documentation on how test_op2 works and how to interpret it's printouts.  Then look at some of the random examples.

**Comment by qlshzjw** [comment]
Thank you for your suggestion. I think the problem is that my processing software is OPTISTRUCT. After trying test_op2, it appears that the shape of element_node array can not meet the shape of the result arrays.

**Comment by SteveDoyle2** [comment]
I'd have to see an example.  Optistruct is supported, but I haven't seen a random example of theirs.

**Comment by qlshzjw** [comment]
I've send you an email containing the op2 result and also the fe-model.

**Comment by SteveDoyle2** [comment]
So I definitely get the same error as you do in 1.3.3.  

However, I did a lot of work on improving random support (that's not included in that version) and if you're running the main branch, it seems to work fine.  If you run:

    test_op2 -f model_sort1.op2

You'll get an partial f06, but it's got quite a bit.  There's an issue with the RMS writing.
