### ISSUE TITLE
nptyping version requirement

### ISSUE THREAD

**Issue by marcodlk** [SteveDoyle2/pyNastran#611]
I was unable to do `from pyNastran.bdf.bdf import BDF` due to error in the statement `NDArrayNbool = NDArray[(Any, ), bool]` in the `pyNastran.typing` module. At the time, I had `nptyping` version 1.1.0 installed. Upgrading to `nptyping` version 1.2.0 resolved the issue.

**Comment by SteveDoyle2** [comment]
It wasn't an error when it was created for 1.0.1.  The format requirements
changed.  The package isn't required.  I'm glad 1.2 fixes it...

**Comment by SteveDoyle2** [comment]
To be clear, a 1D numpy array has a shape of (N, ), not N.  So, the right way should be NDArrayNbool = NDArray[(Any, ), bool]

**Comment by marcodlk** [comment]
Makes sense that the package is not required. However, `pip install pyNastran` did install the nptyping package and at version 1.1.0.

**Comment by SteveDoyle2** [comment]
It's a useful feature and a lightweight package, so yeah it was included.

**Comment by SteveDoyle2** [comment]
There's a new version of pyNastran (1.3.3) that explicitly bans nptyping=1.1.0, so:

    nptyping >= 1.0.1, !=1.1.0
