### ISSUE TITLE
cannot determine endian of op2

### ISSUE THREAD

**Issue by mzme** [SteveDoyle2/pyNastran#613]
Hello,
first of all thanks for this great package.

I`m trying to read in an OP2 file and the read_op2 function throws the error: "FatalError: cannot determine endian", for detailed error see [error_message.txt](https://github.com/SteveDoyle2/pyNastran/files/4836977/error_message.txt)
.
The Program for generating the op2-files ist  "Simcenter Nastran 2019.1" with "NX Simcenter 1867".

Until now I always was able to read the OP2 files, so I did a row of tests, containing:

- size of the model (--> size of op2)
- name of models and solutions
- loads and boundary conditions
- element-types
- BULK-Data PARAM CARDS

All op2 files could be read, except for the latest model.
The only difference i could find is a "routine" writing op2 in the F06-Output:

- USER INFORMATION MESSAGE 4109 (OUTPBN2)  -> this op2 can be read
- USER INFORMATION MESSAGE 4109 (OUTPX2)   -> this op2 can NOT be read

I have opened a ticket at Siemens PLM why a different "routine" is used.

May the reason for the error can be determined with the attached [op2_files.zip](https://github.com/SteveDoyle2/pyNastran/files/4840546/op2_files.zip).

**Comment by SteveDoyle2** [comment]
Which version are you using?  I'd guess it's less than 1.3.2 given that error.  Your issue is that you're writing a 64-bit op2.  That's probably happening because you have large node and element ids.

I pushed a small bug fix so you can read 2019.1, but you'll need to pull from the trunk.
