### ISSUE TITLE
load op2 file - ValueError

### ISSUE THREAD

**Issue by mzme** [SteveDoyle2/pyNastran#614]
Hallo,

thanks for the fast fix of the 64-Bit issue with NX Nastran 2019.1.

Now I have version 1.3.3 installed (the version you published on PyPI).
Small 64-Bit op2-files can be read in now.
But i get an ValueError for lager files [see](https://github.com/SteveDoyle2/pyNastran/files/4845227/Error_Message.txt)

I`m not sure if the filesize is the reason for the error.

An Example op2-files raising an error can be downloaded from [GoogleDrive](https://drive.google.com/file/d/1dZLStX4aVItbwgk8mzq_nCdaOO2rMvjp/view?usp=sharing) since it was too large for GitHub.

**Comment by SteveDoyle2** [comment]
It looks like you have a few elements that don't support in 64 bit (e.g., CBEAM, CBUSH) yet.

It'll take me some time to fix.  I will also probably not be including new 64-bit results support (geometry was included) it in the next release.  It's quite a bit messier.  I think I did for a few easy ones, but it depends.

**Comment by mzme** [comment]
Thanks again. 
If I can provide support, for example with specific op2 files, please let me know.

**Comment by SteveDoyle2** [comment]
Thanks, but I’m good.  I found a way to make supporting 64-bit way easier,
but it means I need to undo some of the things from before, so it’s not
quite done yet.

If was possible to get node/element ids of 0 and I think that’ll just go
away.

**Comment by SteveDoyle2** [comment]
This is definitely more work than I thought it would be, but I'm making (slow) progress.

**Comment by SteveDoyle2** [comment]
yeah...that was work...

Stress/strain should all work fine now.  I'm somewhat crossing my fingers on forces, but I'm calling it done for now.

It's definitely going into 1.4.  It's too much of a change to backport that.
