### ISSUE TITLE
Read Issues with Strain Tables in OP2 Files

### ISSUE THREAD

**Issue by mcmullen-ms** [SteveDoyle2/pyNastran#615]
I'm using the following code snippet to read in an OP2 file that was generated using NX Nastran....

from pyNastran.op2.op2 import OP2
model = OP2()
model.set_as_nx()
model.read_op2('nastran_updated.op2')

This code when run against pyNastran-1.3.3 generates the following errors...

DEBUG:   op2.py:542                   combine=True
DEBUG:   op2.py:543                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1556           op2_filename = 'nastran_updated.op2'
WARNING: op2_reader.py:5754           nx version='2020.1' is not supported
DEBUG:   op2_reader.py:270            mode = 'nx'
DEBUG:   op2_scalar.py:1735             table_name=b'PVT0'
DEBUG:   op2_scalar.py:1735             table_name=b'GPL'
DEBUG:   op2_scalar.py:1735             table_name=b'CSTM'
DEBUG:   op2_scalar.py:1735             table_name=b'GPDT'
DEBUG:   op2_scalar.py:1735             table_name=b'EPT'
DEBUG:   op2_scalar.py:1735             table_name=b'MPT'
DEBUG:   op2_scalar.py:1735             table_name=b'GEOM2'
DEBUG:   op2_scalar.py:1735             table_name=b'GEOM3'
DEBUG:   op2_scalar.py:1735             table_name=b'GEOM4'
DEBUG:   op2_scalar.py:1735             table_name=b'GEOM1'
DEBUG:   op2_scalar.py:1735             table_name=b'BGPDT'
DEBUG:   op2_reader.py:1846           table_name = b'BGPDT'
DEBUG:   op2_scalar.py:1735             table_name=b'CASECC'
DEBUG:   op2_scalar.py:1735             table_name=b'EQEXIN'
DEBUG:   op2_scalar.py:1735             table_name=b'OGPWG'
DEBUG:   op2_scalar.py:1735             table_name=b'OQG1'
DEBUG:   op2_scalar.py:1735             table_name=b'BOUGV1'
DEBUG:   op2_scalar.py:1735             table_name=b'OES1'
DEBUG:   op2_scalar.py:1735             table_name=b'OEF1'
DEBUG:   op2_scalar.py:1735             table_name=b'OSTR1X'
DEBUG:   op2_scalar.py:1735             table_name=b'OES1C'
DEBUG:   op2_scalar.py:1735             table_name=b'OEFIT'
DEBUG:   op2_scalar.py:1735             table_name=b'OSTR1C'
failed reading b'OSTR1C' isubtable=-4
Traceback (most recent call last):
  File "tmp.py", line 5, in <module>
    model.read_op2('nastran_updated.op2')
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2.py", line 554, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_scalar.py", line 1588, in read_op2
    table_names = self._read_tables(table_name)
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_scalar.py", line 1755, in _read_tables
    op2_reader.read_results_table()
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 4663, in read_results_table
    self.read_results_table4()
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 4686, in read_results_table4
    self._read_subtables()
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 4885, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 5010, in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/fortran_format.py", line 97, in _read_subtable_results
    data, ndata = op2_reader._skip_record_ndata()
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 4491, in _skip_record_ndata
    return self._skip_record_ndata4(debug=debug, macro_rewind=macro_rewind)
  File "/Users/mcmu/pyNastran-1.3.3/pyNastran/op2/op2_interface/op2_reader.py", line 4509, in _skip_record_ndata4
    raise FortranMarkerError(msg)
pyNastran.op2.errors.FortranMarkerError: marker0=-20*4 len(record)=4; table_name=b'OSTR1C'

Similar error messages are generated when I use older (1.2.1) versions of pyNastran. However, OP2 files that contain only stress tables are read in successfully. 

Are there additional flags that need to be set to properly read in an NX OP2 file that contains the strain tables?

Regards,
Matt

**Comment by SteveDoyle2** [comment]
I'll have to take a look.  Do you have a small example?

I'm out of town until next week, so no rush.

**Comment by mcmullen-ms** [comment]
[beam.op2.gz](https://github.com/SteveDoyle2/pyNastran/files/4893731/beam.op2.gz)

The above file is a simple composite beam. It generates the error messages shown below. FYI, when I use MAT1 cards on the beam flanges - the OP2 strain table import successfully works in PyNastran. This suggests an issue in the support of multi-layered composite materials.

Thanks for the help,
Matt


DEBUG:   op2.py:620                   combine=True
DEBUG:   op2.py:621                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1469           op2_filename = 'beam.op2'
DEBUG:   op2_reader.py:255            mode = u'nx'
DEBUG:   op2_scalar.py:1620             table_name='PVT0'
DEBUG:   op2_scalar.py:1620             table_name='GPL'
DEBUG:   op2_reader.py:1034           table_name = 'GPL'
DEBUG:   op2_scalar.py:1620             table_name='CSTM'
DEBUG:   op2_scalar.py:1620             table_name='GPDT'
DEBUG:   op2_reader.py:1104           table_name = 'GPDT'
DEBUG:   op2_scalar.py:1620             table_name='EPT'
DEBUG:   op2_scalar.py:1620             table_name='MPT'
DEBUG:   op2_scalar.py:1620             table_name='GEOM2'
DEBUG:   op2_scalar.py:1620             table_name='GEOM3'
DEBUG:   op2_scalar.py:1620             table_name='GEOM4'
DEBUG:   op2_scalar.py:1620             table_name='GEOM1'
DEBUG:   op2_scalar.py:1620             table_name='BGPDT'
DEBUG:   op2_reader.py:1221           table_name = 'BGPDT'
DEBUG:   op2_scalar.py:1620             table_name='CASECC'
DEBUG:   op2_scalar.py:1620             table_name='EQEXIN'
DEBUG:   op2_scalar.py:1620             table_name='OQG1'
DEBUG:   op2_scalar.py:1620             table_name='BOUGV1'
DEBUG:   op2_scalar.py:1620             table_name='OES1'
DEBUG:   op2_scalar.py:1620             table_name='OEF1'
DEBUG:   op2_scalar.py:1620             table_name='OSTR1X'
DEBUG:   op2_scalar.py:1620             table_name='OES1C'
DEBUG:   op2_scalar.py:1620             table_name='OEFIT'
DEBUG:   op2_scalar.py:1620             table_name='OSTR1C'
failed reading OSTR1C isubtable=-4
Traceback (most recent call last):
  File "/share_home/xxxx/nx_nastran_test/fine_simple_beam/nastran_outputs.py", line 6, in <module>
    model.read_op2(filename)
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2.py", line 632, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1485, in read_op2
    table_names = self._read_tables(table_name)
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_scalar.py", line 1639, in _read_tables
    op2_reader.read_results_table()
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3305, in read_results_table
    self._read_subtables()
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3400, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3505, in _read_subtable_3_4
    unused_n = op2._read_subtable_results(table4_parser, record_len)
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/fortran_format.py", line 103, in _read_subtable_results
    data, ndata = op2_reader._skip_record_ndata()
  File "/share_home/xxxx/.local/lib/python2.7/site-packages/pyNastran/op2/op2_interface/op2_reader.py", line 3134, in _skip_record_ndata
    raise FortranMarkerError(msg)
pyNastran.op2.errors.FortranMarkerError: marker0=-20*4 len(record)=4; table_name='OSTR1C'

**Comment by SteveDoyle2** [comment]
Thanks for that.  

FYI, I'm busy fixing anther bug, so I haven't been able to get to this yet.

**Comment by mcmullen-ms** [comment]
Sorry to bother you, but I'm working on a deadline and it would be great to understand when this issue will be addressed. Could you give me a rough estimate (plus or minus a week) as to when this issue might be fixed?

Thanks,
Matt

**Comment by SteveDoyle2** [comment]
Matt,

No worries.  I was 3rd on my list when you reported it, but it's the
current bug I'm trying to fix.  It seems to be a way to short-circuit
the finishing of a table.

It's easy enough to make that example work because that one occurs at the
end of the file, but it breaks other tests.  It also doesn't work for
the other examples of that bug.  I'm hoping for it to be fixed within
another week.  It's hard to make much progress during the work week since
it's unpaid.

That said, if that's an issue, there are more direct routes that would let
me work on company time.  That involves a contract though.

**Comment by SteveDoyle2** [comment]
Give it a shot.  I assume you have a harder problem, so we'll see.  I definitely don't understand quite why it happens.

**Comment by mcmullen-ms** [comment]
Thanks for the help – will test it later today.

Regards,
Matt
