### ISSUE TITLE
Element IDs set to zero in OP2 grid point forces table

### ISSUE THREAD

**Issue by mcmullen-ms** [SteveDoyle2/pyNastran#619]
I'm using the following code snippet to read in an OP2 file and access the grid point force information...

import numpy
from pyNastran.op2.op2 import OP2
model=OP2()
model.set_as_nx()
model.read_op2('nastran.op2')

data=model.grid_point_forces[1]
eid=data.node_element[0,:,:]
forces=data.data[0,:,:]

total=numpy.zeros((6),dtype=numpy.float64)
for i in range(14):
    total+=forces[i,:]
    print i,eid[i,:],forces[i,:]
    
print total

I'm just looping over the first 14 entries in the table, and I get the following output....

DEBUG:   op2.py:620                   combine=True
DEBUG:   op2.py:621                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1469           op2_filename = 'nastran.op2'
DEBUG:   op2_reader.py:255            mode = u'nx'
DEBUG:   op2_scalar.py:1620             table_name='PVT0'
DEBUG:   op2_scalar.py:1620             table_name='GPL'
DEBUG:   op2_reader.py:1034           table_name = 'GPL'
DEBUG:   op2_scalar.py:1620             table_name='CSTM'
DEBUG:   op2_scalar.py:1620             table_name='GPDT'
DEBUG:   op2_reader.py:1104           table_name = 'GPDT'
DEBUG:   op2_scalar.py:1620             table_name='EPT'
DEBUG:   op2_scalar.py:1620             table_name='MPT'
DEBUG:   op2_scalar.py:1620             table_name='GEOM2'
DEBUG:   op2_scalar.py:1620             table_name='GEOM3'
DEBUG:   op2_scalar.py:1620             table_name='GEOM4'
DEBUG:   op2_scalar.py:1620             table_name='GEOM1'
DEBUG:   op2_scalar.py:1620             table_name='BGPDT'
DEBUG:   op2_reader.py:1221           table_name = 'BGPDT'
DEBUG:   op2_scalar.py:1620             table_name='CASECC'
DEBUG:   op2_scalar.py:1620             table_name='EQEXIN'
DEBUG:   op2_scalar.py:1620             table_name='OQG1'
DEBUG:   op2_scalar.py:1620             table_name='BOUGV1'
DEBUG:   op2_scalar.py:1620             table_name='OES1'
DEBUG:   op2_scalar.py:1620             table_name='OEF1'
DEBUG:   op2_scalar.py:1620             table_name='OES1C'
DEBUG:   op2_scalar.py:1620             table_name='OEFIT'
DEBUG:   op2_scalar.py:1620             table_name='OGPFB1'
DEBUG:   op2.py:640                   -------- reading op2 with read_mode=2 (array filling) --------
DEBUG:   op2_reader.py:255            mode = u'nx'
DEBUG:   op2_scalar.py:1620             table_name='PVT0'
DEBUG:   op2_scalar.py:1620             table_name='GPL'
DEBUG:   op2_reader.py:1034           table_name = 'GPL'
DEBUG:   op2_scalar.py:1620             table_name='CSTM'
DEBUG:   op2_scalar.py:1620             table_name='GPDT'
DEBUG:   op2_reader.py:1104           table_name = 'GPDT'
DEBUG:   op2_scalar.py:1620             table_name='EPT'
DEBUG:   op2_scalar.py:1620             table_name='MPT'
DEBUG:   op2_scalar.py:1620             table_name='GEOM2'
DEBUG:   op2_scalar.py:1620             table_name='GEOM3'
DEBUG:   op2_scalar.py:1620             table_name='GEOM4'
DEBUG:   op2_scalar.py:1620             table_name='GEOM1'
DEBUG:   op2_scalar.py:1620             table_name='BGPDT'
DEBUG:   op2_reader.py:1221           table_name = 'BGPDT'
DEBUG:   op2_scalar.py:1620             table_name='CASECC'
DEBUG:   op2_scalar.py:1620             table_name='EQEXIN'
DEBUG:   op2_scalar.py:1620             table_name='OQG1'
DEBUG:   op2_scalar.py:1620             table_name='BOUGV1'
DEBUG:   op2_scalar.py:1620             table_name='OES1'
DEBUG:   op2_scalar.py:1620             table_name='OEF1'
DEBUG:   op2_scalar.py:1620             table_name='OES1C'
DEBUG:   op2_scalar.py:1620             table_name='OEFIT'
DEBUG:   op2_scalar.py:1620             table_name='OGPFB1'
DEBUG:   op2.py:922                   combine_results
DEBUG:   op2.py:653                   finished reading op2
0 [1 0] [  3.9650128 -10.82303   -80.693115  165.83487    76.67913    -5.3524613]
1 [   1 7662] [10083.021      144.7242    -138.67783    -26.243092  1484.2363
  -119.46086 ]
2 [   1 8436] [-973.12634    26.745134 1626.6244    -93.42488  5346.2764   -169.87047 ]
3 [   1 8481] [-10922.132   -11267.841    -1292.5624    -390.20456    379.71432
   -131.95142]
4 [   1 9083] [8190.231    8410.206    -101.760315  937.21405  -910.0623    109.9017  ]
5 [1 1] [-4253.7773  -3796.6062   4183.9214    394.5395    397.01895  1307.9253 ]
6 [   1 2157] [-2.5711255e+03  4.5182384e+01 -1.1853569e+03  1.0672484e+01
  2.1231370e+00 -3.7721924e+02]
7 [   1 2177] [ 846.8973  1182.1204  1456.9437   201.599    201.14546 -190.46382]
8 [   1 2205] [-536.74945    -81.10467   -121.96288     70.29457      3.5971055
 -470.53146  ]
9 [   1 3309] [ 2.6730568e+04  7.1562915e+03 -1.6444238e+02  6.8655652e+02
  5.5390049e+01  3.8673599e+00]
10 [   1 3480] [   652.3726 -14072.074   -2116.1934  -4409.0244   6728.026      81.7539]
11 [   1 3486] [-2.9531211e+04  5.6228301e+03 -2.4219626e+03  4.8537656e+02
 -1.6245478e+04 -2.9259840e+01]
12 [   1 3514] [2281.065     6640.349      356.12216   1966.8092    2481.333
   -9.3386965]
13 [1 0] [ 1.1646080e-09  3.7953214e-09  1.1741577e-08 -3.4106051e-12
  7.0576789e-10  2.2502888e-11]
[-7.46487407e-04 -1.02993031e-04 -1.75464333e-04 -2.03132633e-04
 -1.13486538e-04 -1.21593250e-05]

The first entry contains a list [nodal id,element id]=[1,0] (the force applied to this node is not inconsequential).  As there is no "0" element in my model, I'm uncertain what element this force is associated with. Do I need to use an additional mapping to dereference this "0" index to the original element id?

**Comment by SteveDoyle2** [comment]
I'd need to see an example, but it's possible that that's a NaN row.  If you have a transient/frequency/modal solution, elements that don't have load are removed.  Thus, you can have blank entries.  It's an integer table, so the concept of NaN doesn't exist.

**Comment by SteveDoyle2** [comment]
Closing due to inactiity.
