### ISSUE TITLE
grid point strain problem

### ISSUE THREAD

**Issue by xiaomaiAI** [SteveDoyle2/pyNastran#627]
Hi,
  Recently I tried to output grid point strain from `.op2` file, but it did not work, I checked the `.f06` file and found grid point strain results. Is there any way to output it? Thank you.

**Comment by SteveDoyle2** [comment]
Do you have an example?

**Comment by xiaomaiAI** [comment]
here is the `.bdf` file, Thanks.
[bdf.zip](https://github.com/SteveDoyle2/pyNastran/files/5478817/bdf.zip)

**Comment by SteveDoyle2** [comment]
I'm not sure exactly the specifics of the solver that you're using.  I
always stick PLOT on my requests to get op2 results.  Depending on the
vendor, version and solution, sometimes PLOT is the default.  Other times,
it's not.
GPSTRAIN(PLOT)=30
GPSTRESS(PLOT)=30

Do you see any log messages like:
INFO:    op2_reader.py:5516           skipping table_name = b'OGSTR1'

**Comment by xiaomaiAI** [comment]
Hi，
  There is no `INFO` like this, I found the GPSTRAIN result in `.f06` file, but when I print the `.op2` result in python, no such results were found, Is there any function familiar with `grid_point_surface_stresses`? Thank you.

**Comment by SteveDoyle2** [comment]
Did you update the following?  I added the grid_point_strain results in my
last commit.  They're stored in the OGSTR1 table, so if you don't get that
info message, you should have them or they're not in the OP2.

GPSTRAIN(PLOT)=30
GPSTRESS(PLOT)=30

What version of Nastran are you using?  I tested it in MSC 2020 and NX 2019
and it works for both.

**Comment by xiaomaiAI** [comment]
Hi,
  I tried to update the `.bdf` file, it did not work. pyNastran v1.3.2 is the lastest version? now I work on MSC 2018, I'll update it and test again, thank you.

**Comment by SteveDoyle2** [comment]
Yeah, you need to use the version on github, not an official release in order to access the new results.  Using 1.3.2, you should see the info message I mentioned before if you updated the BDF correctly.  

Alternatively, just run this.  It's almost the same thing as what you sent.
[nx_ogstr.txt](https://github.com/SteveDoyle2/pyNastran/files/5491444/nx_ogstr.txt)

**Comment by xiaomaiAI** [comment]
Thank you, I update the version from Github, then I print a `INFO`, and I recognized that I comment that codes before, but there is no gpstrain data in `.op2` file you sent to me, and I'll update my MSC version and test soon.
