### ISSUE TITLE
GUI control surface visualization

### ISSUE THREAD

**Issue by jpdeslich** [SteveDoyle2/pyNastran#631]
While debugging a model with the GUI, I noticed that the aerodynamic control surface panels are not being properly displayed.  The AESURF and AELIST entries that I used are:

`AELIST      2000    2009    2019    2029    2039    2049    2059    2069+0 `     
`+0          2079    2089    2099    2109    2119    2129    2139    2149`
`AESURF      2000    Elev    2000    2000 `

In this case, the aero panels should be along the trailing edge according to the Nastran convention, however this is not the case. Below shows all the control surface aero panels at the wingtip, but they should be between the dashed black lines.

![image](https://user-images.githubusercontent.com/50683883/103807698-d525c880-5024-11eb-817f-52e2359df6b4.png)

Is my convention wrong or is there an issue with how the GUI displays the control surface aero panels?

Thanks!

**Comment by SteveDoyle2** [comment]
Paneling is dependent on your CAERO card, so I can't tell from just that.
Assuming that's one CAERO1 card, paneling should have gaps based on the
following.  Your AELIST IDs aren't sequential and they don't have a
consistent gap, so I'm not sure.  It' might be a bug, but I can't tell
based on just that.

[image: image.png]

**Comment by SteveDoyle2** [comment]
Yeah, that's definitely not right.  I'll have to fix that.  I think I know
what this issue is, but I think I was trying to fix another bug.

It's going to take me a bit.  I need to push my other changes.

An example...
SOL 144
CEND
BEGIN BULK
CAERO1      1000       1               3       2                       1
              0.      0.      0.      1.      1.     15.      0.      1.
PAERO1         1
AESURF        10    FLAP       0      10
AELIST        10    1001    1003    1005
GRID,1
[image: image.png]
So elements = 1001, 1003, 1005 should have the panels applied on the
trailing edge and as you figured out, they don't.

[image: image.png]

Steve

**Comment by SteveDoyle2** [comment]
Well that was easier than I thought  The points were out of order.

**Comment by jpdeslich** [comment]
I checked out the fix and it looks like the number of chord wise and span wise panels are switched. For example, I have this as the CAERO1 entry:

`CAERO1      2000    2000       0      15      10                       1+0`     
`+0      7.314386      0.-0.182881.4638548.2227551.573341-0.182880.365963`

But the viewer shows this:

![image](https://user-images.githubusercontent.com/50683883/103892614-de14a980-50b9-11eb-8eec-b7ebbf29382e.png)

Which has 10 spanwise panels and 15 chord wise panels.  Obviously this affects the visualization of the control surface as well.

Thanks for all the help!
Josh

**Comment by SteveDoyle2** [comment]
oh that's annoying...I fixed one bug and made another a lot worse.  My xy plot from before was right, but the indicies were not, so it messed up the GUI.  It should at least be right for the CAERO1 now.  I still need to check the others.

Nobody uses CAERO3s right?  It's not clear to me exactly what the paneling looks like.

**Comment by jpdeslich** [comment]
Thanks for checking it out again!  I have never used/ heard of anyone use CAERO3's... I would think that for most work, CAERO1 is sufficient as it does both sub and supersonic.

**Comment by SteveDoyle2** [comment]
I added some more tests for other cards.  Closing again...
