### ISSUE TITLE
Method "update_card" malfunction for 'CTETRA' elements

### ISSUE THREAD

**Issue by MartinSiemann** [SteveDoyle2/pyNastran#633]
Using the method *update_card()* works well for 'GRID' objects but it does not work when applied to 'CTETRA' objects. I am not able to trace why this fails for 'CTETRA' objects.
What I observe is that the element data does not change when executing the *update_card()* method, i.e. the data remains unchanged.

Code snippet
```
model = BDF()
model.read_bdf(bdf_filename)

eID = 2
# update PID (field number 2) to value 5
model.update_card('CTETRA', eID, 2, 5)
```

**Comment by SteveDoyle2** [comment]
It looks like your model is cross-referenced, so it's pulling the property id from (probably) a PSOLID.

You can set `xref=False` in `BDF()` and call `model.cross_reference()` later (or just skip it entirely).  You can also call uncross_reference on the model/card and re-cross-reference it after.

**Comment by MartinSiemann** [comment]
Thanks, Steve. I called """xref=False""" in """read_bdf()""" and it worked. I need to get accomodated to the referencing between cards...
