### ISSUE TITLE
reproducibility issue

### ISSUE THREAD

**Issue by ggbioing** [SteveDoyle2/pyNastran#638]
https://github.com/SteveDoyle2/pyNastran/blob/70c078a1b0995d90d482a7a70286153812f97456/pyNastran/op2/op2.py#L539
The reproducibility of computational pipelines should not depend on the environment where the computation happens (in this case ipython).
I propose to set the argument build_dataframe either to a True or False default.

**Comment by SteveDoyle2** [comment]
That's a good point.  I was never the biggest fan of it anyways, even though I've started to like pandas.

The default is now False.  None still works.
