### ISSUE TITLE
Cannot extract NX contact separation from OP2 

### ISSUE THREAD

**Issue by Bravo-Kilo** [SteveDoyle2/pyNastran#639]
linear, static analysis
i can load the op2 with 

model = read_op2(file_name, build_dataframe=True, debug=False)

and access results like displacements with
displacements = model.displacements[1]
model = read_op2(file_nameS, build_dataframe=True, debug=False)

but i cannot get to the contact separation results.
I do not see contact or separation or OSPDS1 when i view the model object in Spyder's variable explorer.
(OSPDS1 is referenced in pyNastran.op2.op2_interface.op2_scalar as contact separation)

I've tried a few forms of 
read_op2(file_nameS, build_dataframe=True, debug=False, include_results = ['all_results'])
read_op2(file_nameS, build_dataframe=True, debug=False, include_results = [b'OSPDS1'])

I see in the code/docs that separation results are an 'NX_extra_table' and i don't know that they are actually loaded with the read_op2 method or how to load them.

I've tried using
model.set_additional_result_tables_to_read(methods_dict)
with methods_dict = OSPDS1 
which runs but doesn't seem to load the results.

**Comment by Bravo-Kilo** [comment]
Thank you for the fast response.
I've made a small model and attached it w/ the op2 file (had to add .txt to both inorder to upload them)


[op2_contact_model-003.op2.txt](https://github.com/SteveDoyle2/pyNastran/files/6133021/op2_contact_model-003.op2.txt)
[op2_contact_model-003.dat.txt](https://github.com/SteveDoyle2/pyNastran/files/6133022/op2_contact_model-003.dat.txt)

**Comment by SteveDoyle2** [comment]
The model now works.  I need to redo the object so it can print the f06, op2, and the stats.  It's implemented as a dictionary currently.  It's a bit weird in that it's not documented in the dmap guide, so there might be some issues.

Check out:

        model.separation_initial
        model.separation_final

**Comment by Bravo-Kilo** [comment]
Thank you.  I'm in the middle of somework and don't want to try and update
my pyNastran install but will do so soon.

**Comment by SteveDoyle2** [comment]
I've updated the code to store the objects in model.op2_results.separation_initial/final.  They now come with a write_f06/op2 method instead of just being dictionaries.

**Comment by Bravo-Kilo** [comment]
Thank you very much
I tried to work it this weekend but somehow broke my spyder when upgrading
to v 5. I'm a much better mech eng than coder.
You however, are awesome coder.
