### ISSUE TITLE
Extract ply stresses from solid elements, from OP2 file

### ISSUE THREAD

**Issue by benvb-97** [SteveDoyle2/pyNastran#640]
Hi,

(NX Nastran)
For a linear static analysis, I am able to read the op2 file using 

```
model = OP2()
model.read_op2(filename)
```
and access different stress results with
```
ctetra_stres = model.ctetra_stress[1]
chexa_stress = model.chexa_stress[1]
```
But there doesn't seem to exist a method yet to retrieve stress results from solid laminates (which I believe are referenced by OES1C). I already saw some similar issues listed for other unsupported results (e.g. issue #639), from which it seems that there is not really any way to access unsupported results.

I was wondering if it's possible to retrieve the data under OES1C using pyNastran, somehow?

Thank you for the great work on pyNastran.
Kind regards,

**Comment by SteveDoyle2** [comment]
Do you have an example?  I think that result is supported.

For reference since I didn't see it on the issue tracker, you can add results yourself.  You may have seen this error message in the code, which gives a decent explanation of how to do it.

```
Invalid Table = 'table_name'

If you have matrices that you want to read, see:
  model.set_additional_matrices_to_read(matrices)  matrices = {
      b'BHH' : True,
      b'KHH' : False,
  }  # you want to read some matrices, but not others
  matrices = [b'BHH', b'KHH']  # assumes True

If you the table is a geom/result table, see:
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OUGV1' : [method3, method4],
      b'GEOM4SX' : [method3, method4],
      b'OES1X1' : False,
  }

If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
  methods_dict = {
      b'OUGV1' : [method],
  }
  model.set_additional_generalized_tables_to_read(methods_dict)

```

You'd probably want to modify the second choice (set_additional_result_tables_to_read).

**Comment by benvb-97** [comment]
Thank you for the fast response, and my apologies, I forgot to attach the example file (it's a very simple model to get the hang of pyNastran):

[test.dat.txt](https://github.com/SteveDoyle2/pyNastran/files/6162049/test.dat.txt)
[test.op2.txt](https://github.com/SteveDoyle2/pyNastran/files/6162050/test.op2.txt)

I tried your suggestion of setting additional result tables, my code is shown below
```
from pyNastran.op2.op2_interface.op2_scalar import OP2_Scalar
model = OP2(mode='nx')
model.set_additional_result_tables_to_read({b'OES1C': [OP2_Scalar._read_oes1_3, OP2_Scalar._read_oes1_4]})
```
_read_oes1_3 & 4 are the two methods that seem to be used for OES1C when I look at the OP2_scalar file at line 852:
`            b'OES1C'  : [self._read_oes1_3, self._read_oes1_4], # stress - composite
`
When I try to read the results this time using model.read_op2(filename), I get a TypeError:

```
failed reading b'OES1C' isubtable=-3
Traceback (most recent call last):
  File "...\venv\lib\site-packages\pyNastran\op2\op2.py", line 554, in read_op2
    load_as_h5=load_as_h5, mode=mode)
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1588, in read_op2
    table_names = self._read_tables(table_name)
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1756, in _read_tables
    op2_reader.read_results_table()
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py", line 4663, in read_results_table
    self.read_results_table4()
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py", line 4686, in read_results_table4
    self._read_subtables()
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py", line 4885, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "...\venv\lib\site-packages\pyNastran\op2\op2_interface\op2_reader.py", line 4972, in _read_subtable_3_4
    table3_parser(data, ndata)
TypeError: _read_oes1_3() missing 1 required positional argument: 'unused_ndata'
```
For your interest, I noticed that when I only run model.read_op2(filename), without setting additional tables to read, the OES1C table is shown in model.table_names:

`[b'IBULK', b'ICASE', b'CASECC', b'PVT0', b'GPL', b'GPDT', b'EPT', b'MPT', b'GEOM2', b'GEOM3', b'GEOM4', b'GEOM1', b'BGPDT', b'DIT', b'EQEXIN', b'BOUGV1', b'OES1C']`

I'm not sure how to check if there is any data related to that table_name as well. There are methods like 'model.cquad4_composite_stress' to read composite stresses for CQUAD4,8 , ... and other shell elements, but not for solid elements like CHEXA8.

**Comment by SteveDoyle2** [comment]
Ahhh...the nonlinear composite solids were added.  I gotta see if I can make a common class, but it doesn't look too bad.  It'll probably take me some time though.  I got too many things to do lately.

**Comment by SteveDoyle2** [comment]
OES1C is definitely what you want.  The other tables are geometry outside of the BOUGV1, which is the displacements in coordinate system 0 (the basic frame).

To be clear on the functions, they take self, data and ndata.  

The table 3 function reads the header of which the default is probably fine (the header defines the subcase info and element type) and is 528 bytes for single precision.  

The table 4 header has a first pass (read_mode=1) that sets data to None, but ndata (the length of data) is set right.  You need to return ndata and setup the object by combining the sort_code, format_code, numwide, element_type, and element_name.  On the second pass (read_mode=2), data is set and you can fill the object.

If you want, can just add the single element type (269) and call the standard function for other cases.

**Comment by benvb-97** [comment]
Thank you for the suggestions! I'll try to dive into the code a bit and make it work, the way you proposed, in the meantime.

**Comment by SteveDoyle2** [comment]
I've updated the code to support model.chexa_composite_stress/strain.  There is f06 support, but currently no op2 support.

**Comment by SteveDoyle2** [comment]
It turns out there are no examples in the TPL directory, so kinda hard to test things that don't exist.  CPENTAs are also not supported.
