### ISSUE TITLE
OP2 reader fails when model features glue contact and OP2 file contains table 'OFCON3D0'

### ISSUE THREAD

**Issue by MartinSiemann** [SteveDoyle2/pyNastran#642]
I have been using pyNastran to read OP2 results (mainly displacement and ctetra_stress). When attempting to read an OP2 file of a model that contains glued contacts, there seems to be a table that causes the reader to fail as it seems to be not implemented. I do not need the data of this table so it could simply be bypassed; however, I did not succeed doing this.

I have tried in file _'..\pyNastran\op2\op2_interface\op2_scalar.py'_ with something like `elif table_name in [b'OFCON3D0']: pass` but without success.

Could you please let me know how I can overcome this issue?

### Output with error

Traceback (most recent call last):

  File "C:\Users\username\Desktop\py_tools\main.py", line 66, in <module>
    model.read_op2(op2_filename = op2_filename)

  File "C:\Users\username\anaconda3\lib\site-packages\pyNastran\op2\op2.py", line 554, in read_op2
    load_as_h5=load_as_h5, mode=mode)

  File "C:\Users\username\anaconda3\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1588, in read_op2
    table_names = self._read_tables(table_name)

  File "C:\Users\username\anaconda3\lib\site-packages\pyNastran\op2\op2_interface\op2_scalar.py", line 1790, in _read_tables
    raise NotImplementedError(msg)

NotImplementedError: Invalid Table = b'OFCON3D0'

If you have matrices that you want to read, see:
  model.set_additional_matrices_to_read(matrices)  matrices = {
      b'BHH' : True,
      b'KHH' : False,
  }  # you want to read some matrices, but not others
  matrices = [b'BHH', b'KHH']  # assumes True

If you the table is a geom/result table, see:
  model.set_additional_result_tables_to_read(methods_dict)
  methods_dict = {
      b'OUGV1' : [method3, method4],
      b'GEOM4SX' : [method3, method4],
      b'OES1X1' : False,
  }

If you want to take control of the OP2 reader (mainly useful for obscure tables), see:
  methods_dict = {
      b'OUGV1' : [method],
  }
  model.set_additional_generalized_tables_to_read(methods_dict)

**Comment by SteveDoyle2** [comment]
I'm surprised that you're getting that error.  Are you using the latest dev version?

If you're not, that makes a lot more sense :)

Also, do you have a small example?

**Comment by MartinSiemann** [comment]
Hi Steven,

Thanks for your quick reply. I am using PyNastran version 1.3.3 and afaik this is the latest available. Although the website states v1.4 I cannot install this version using “pip install pyNastran==1.4”. So any other idea on your side?

 

I cannot provide any example due to high work load these days, unfortunately.

 

Best regards,

Martin

 

Von: Steven Doyle ***@***.***> 
Gesendet: Mittwoch, 14. April 2021 17:00
An: SteveDoyle2/pyNastran ***@***.***>
Cc: MartinSiemann ***@***.***>; Author ***@***.***>
Betreff: Re: [SteveDoyle2/pyNastran] OP2 reader fails when model features glue contact and OP2 file contains table 'OFCON3D0' (#642)

 

I'm surprised that you're getting that error. Are you using the latest dev version?

If you're not, that makes a lot more sense :)

Also, do you have a small example?

**Comment by SteveDoyle2** [comment]
You're probably looking at readthedocs, which the latest is the dev
version.  It should be 1.4-dev.

Anyways, 1.4 should be out in the next few days, but at the moment, the dev
version is 1.4.
