### ISSUE TITLE
gpdt.xyz incorrect

### ISSUE THREAD

**Issue by JelleBosmans** [SteveDoyle2/pyNastran#644]
Hello Steve,

I have been using pyNastran and would like to thank you for your great work.

Now I seem to encounter an error when reading the gpdt from an op2 file. In short, I've found the data in model_op2.gpdt.xyz to be incorrect for my model. The entries in the table appear to be more or less random, or at least I cannot see a pattern or establish a link to what the node xyz should be based on the bdf. 

My model is relatively large (1.4m nodes). My preprocessor is Siemens NX, the model is solved with NX Nastran. I can share the bdf and op2 file if required. However, they are too large to add as attachment here so I will have to use another file sharing solution.

Version:
```
pyNastran 1.3.3 
python 3.8.5
```

This is the code I'm using to read in the models and compare to the bdf nodes:

```
#%% Read bdf 
model_op2 = OP2()
model_op2.read_op2(op2_filepath)

#%% gpdt
gpdt = model_op2.op2_results.gpdt
gpdt_xyz = gpdt.xyz # xyz coordinates 

#%% Read bdf 
model_bdf = BDF()
model_bdf.read_bdf(bdf_filepath, xref=True)

#%% bdf_nodes
bdf_nodes = model_bdf.nodes
bdf_gpdt_nodemap = model_bdf.nid_map 

#%% Comparison
bdf_nid_test = 9805 # Test node hard-coded, this is actually the node with the lowest node number in the model
error = bdf_nodes[bdf_nid_test].xyz - gpdt_xyz[bdf_gpdt_nodemap[bdf_nid_test]]
print(error)
```

Result: 
```
bdf_xyz_test: 
[423.67443848 189.31692505  40.        ]
gpdt_xyz_test: 
[-8.4740722e-41  3.9137444e+00  2.0098305e+00]
error: 
[423.67443848 185.4031806   37.99016953]
```

Thanks in advance for taking a look at this issue and don't hesitate to let me know if you need more information!

Best regards,
Jelle Bosmans

**Comment by SteveDoyle2** [comment]
Thank for your kind words!

I'm very surprised the xyz locations are off.  I'll have to take a look.
That's very much a non-standard way to read the grid points.

If you have Dropbox, you can send it that way.  Alternatively, throw away
90% of the model.  I have  NX Nastran, so I can run the model as long as
the error shows up in the op2.

**Comment by JelleBosmans** [comment]
Thanks for the quick reply! 

I'm quite new to using PyNastran and to using Python in general - so that's probably why my implementation is non-standard. If there is a better way, I'd be very happy to hear your suggestions. 

In the past I experimented with a smaller sub-mesh of this model and I didn't encounter the issue, so I don't think the issue will be reproducible if I send you a small part of the model. I think the issue might be related to the size of the model. I will try to send you the file through dropbox or a similar service. Can I use the email address mentioned on your github profile? I do not wish to post the download link on this public page. 

FYI: By reading the bdf as in the code snippet above, I do get the correct grid points. So with this workaround I can continue my work. Hence, I'd say this is now a low-priority issue :-)

**Comment by SteveDoyle2** [comment]
That's interesting.  I wonder if the buffer is off.     I'm more curious as
to how you're getting the GPDT table :)

Yeah, you can send the link to my email.

The read_bdf method will always be the best in terms of robustness, but the
read_op2_geom method is a lot faster.  I'm not convinced it always gets
the orientation vectors on CBARs/CBEAMs correct (Nastran writes them in a
very old and undocumented format), but GRID points will be fine.

**Comment by JelleBosmans** [comment]
I will send you the download link soon. 

I just tried reading the GRID cards with  `model = read_op2_geom(op2_filepath, xref = False, debug=False)`, but that gave an error during the validation of the read model: 
```
  File "...\Anaconda3\envs\PyNastEnv\lib\site-packages\pyNastran\bdf\cards\nodes.py", line 1206, in validate
    assert self.cd >= -1, 'cd=%s' % (self.cd)

AssertionError: cd=-2147423175
```
When I skip the validation, the coordinates returned by calling `model.nodes[bdf_nid_test].xyz` are the same erroneous values as present in the gpdt table mentioned above.

**Comment by SteveDoyle2** [comment]
this is fixed now
