### ISSUE TITLE
HTML Installation Header Issues

### ISSUE THREAD

**Issue by josiahlund** [SteveDoyle2/pyNastran#646]
The installation.rst file appears to have heading definitions that are not being properly processed when converted to HTML.

Sample of documentation from .rst file:

<img src="https://user-images.githubusercontent.com/24754210/118088477-ffddb000-b37b-11eb-928b-fa6ce7ac8e5e.png" alt=".rst" width="600"/>

Sample of documentation from HTML:

<img src="https://user-images.githubusercontent.com/24754210/118088557-171c9d80-b37c-11eb-9957-d721725a2ca6.png" alt=".html" width="600"/>

Note that the HTML is missing the "Overview" heading altogether.

Recommend editing the .rst to follow the heading level example given in the sphinx documentation [here](https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings)

**Comment by josiahlund** [comment]
This issue seems pretty straight forward and I'd be happy to have it's fix be my first merge request with this project. The rst format looks easy enough to use, but I'm curious: Is there a reason rst being used over something like markdown here?

**Comment by SteveDoyle2** [comment]
I prefer markdown too, but as far as I know, markdown isn't supported by sphinx.  

When I"m testing by hand, I run: 

    sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html > rtd.out 2>&1

The output gets automatically run by readthedocs during the auto-testing process.

**Comment by josiahlund** [comment]
I'm ending up having more trouble than this than I expected. It looks like the web documentation on readthedocs.io is still for release 1.3 (https://pynastran-git.readthedocs.io/en/1.3/installation/installation.html). I tried editing the URL to point to 1.4 but that ended in a page not found error. I believe I have a properly formatted version of the .rst from the current master branch but haven't yet figured out how to use Sphinx even with the line of code posted above. My question now is: Is there more work needed to the documentation than just formatting? Should I submit a pull request for the revisions I have made so far even though I haven't been able to verify on my own that they will work?

Let me know

**Comment by SteveDoyle2** [comment]
Oops...looks like I never turned on the 1.4 page.  That's fixed now.

I don't think you can build anything on read the docs without tying it to
your account.  You can build it on your computer though, which is probably
the easiest way.  You just have to run:
    >>> pip install sphinx

I wouldn't worry about it though.  I'd say make a pull request and
hopefully it's fixed.

**Comment by josiahlund** [comment]
It looks like this specific issue is resolved with the new documentation. I still didn't find the documentation extremely easy to follow and the link to the documentation in the README needs to be updated but that doesn't fit the scope of this issue. I'm going to go ahead and close this issue as resolved by the publishing of the v1.4 documentation.

**Comment by josiahlund** [comment]
> I prefer markdown too, but as far as I know, markdown isn't supported by sphinx.
> 
> When I"m testing by hand, I run:
> 
> ```
> sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html > rtd.out 2>&1
> ```
> 
> The output gets automatically run by readthedocs during the auto-testing process.

How attached to Sphinx are you? I was doing some research and found something called [MkDocs](https://mkdocs.readthedocs.io/en/0.15.3/) which uses markdown to generate documentation. I'm playing around with it now and it seems very user friendly.

**Comment by SteveDoyle2** [comment]
I kinda hate sphinx :)  It's obtuse and requires me to constantly add blank
lines for bulleted lists.  The bulleted lists also look bad.

I guess the biggest things I'm attached to is numpydoc, which supports a
docstring format that I think is readable.  At least at a cursory level,
mkdocs looks like it supports numpydoc.
https://github.com/greenape/mktheapidocs

The other thing is the jupyter notebooks, which are exported to sphinx
using nbconvert.  That one looks like it's handled by mkdocs-juypter.
https://github.com/danielfrg/mkdocs-jupyter

**Comment by josiahlund** [comment]
> It's obtuse and requires me to constantly add blank lines for bulleted lists. The bulleted lists also look bad.

AMEN. After two days of playing with it, I'm starting to feel like I understand at a surface level how to use it. I really dislike reST. I've seen mentions that Sphinx is capable of using markdown, but from what I've found, that requires additional bolt-on libraries. I'll keep poking around and report back when I have something I feel is actionable.
