### ISSUE TITLE
export OP2 to vtk

### ISSUE THREAD

**Issue by berndhahnebach** [SteveDoyle2/pyNastran#651]
Hi there,

I found this in version 1.4 https://github.com/SteveDoyle2/pyNastran/blob/1.4/pyNastran/op2/export_to_vtk.py  this dates back over a year ago. Will this go into master? Is it possible to somehow back port to the current stable? I would do it myself it the export module would work on 1.3.3 version of pyNastran.

Or are there any other possibilities to convert a OP2 to vtk format?

VTK is very very easy to import into FreeCAD. That is why I am asking.

cheers bernd

**Comment by SteveDoyle2** [comment]
I'd really like to keep that file dead.  It was never more than a prototype.

I just created a new example that uses a much better vtk translator.      https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/converters/nastran/nastran_to_vtk.py

It's still preliminary (doesn't support transient/modes or complex results), but it's based on the GUI, so I know results creation and model support is solid.  I've attached a sample vtu file.

Do you know if the VTK xml file supports:
 - complex results natively
 - a difference in the title and the label in the scalar bar that can go in the vtk xml file (*.vtu)
 - flagging an integer vtk array with a mask id (e.g., display all values of -1 as nan to represent invalid data)
[static_elements.vtu.txt](https://github.com/SteveDoyle2/pyNastran/files/6880813/static_elements.vtu.txt)

**Comment by berndhahnebach** [comment]
Wow, great to see this new translator example. I will give it a try. 



> Do you know if the VTK xml file supports:
> 
>     * complex results natively
> 
>     * a difference in the title and the label in the scalar bar that can go in the vtk xml file (*.vtu)
> 
>     * flagging an integer vtk array with a mask id (e.g., display all values of -1 as nan to represent invalid data)


The VTK integration in FreeCAD was done by someone else. Means I do not much know about the file format in detail. Thus I do not know anything about your questions. 

cheers bernd

**Comment by berndhahnebach** [comment]
I have not yet used the pyNastran Gui. does it mean I need to run this module from inside this Gui?

**Comment by SteveDoyle2** [comment]
The GUI does not need to be opened.  I just hooked in through the testing
path.  After loading, I added the arrays to the unstructured grid and wrote
them using the vtkXMLUnstructuredGridWriter class.

It requires vtk, numpy, and scipy.  PyQt5/PySide2/m Is also required, but I
can remove it if that’s an issue.

Regarding those issues I mentioned, they’re not pressing, but we could just
flag them in the array name.

**Comment by berndhahnebach** [comment]
no the imports are not the problems at all. I can install the needed packages on debian or with pip. I am missing the big picture like I did when I started with pyNastran and bdf.

Assumed I have pyNastran the module above and a OP2 file. How would I convert this OP2 to vtk. I am missing something what is for you guys very obviously.

cheers bernd

**Comment by SteveDoyle2** [comment]
You execute the nastran_to_vtk function

The main example is:
```
def main() -> None:
    PKG_PATH = pyNastran.__path__[0]
    MODEL_PATH = os.path.join(PKG_PATH, '..', 'models')

    op2_filename = os.path.join(MODEL_PATH, 'elements', 'static_elements.op2')
    vtk_filename = os.path.join(MODEL_PATH, 'elements', 'static_elements.vtu')
    nastran_to_vtk(op2_filename, vtk_filename)

    op2_filename = os.path.join(MODEL_PATH, 'elements', 'modes_elements.op2')
    vtk_filename = os.path.join(MODEL_PATH, 'elements', 'modes_elements.vtu')
    nastran_to_vtk(op2_filename, vtk_filename)

```

So simply:

```
from pyNastran.converters.nastran.nastran_to_vtk import nastran_to_vtk
nastran_to_vtk(op2_filename, vtk_filename)
```
That's assuming the geometry is stored in the op2.  If you look at the code, you'll see:
```
    test.load_nastran_geometry(op2_filename)
    test.load_nastran_results(op2_filename)
```
It can be streamlined, but for the moment that's what's done.

**Comment by SteveDoyle2** [comment]
I'm calling this closed.  The functionality is there and supports all(???) static/modal/transient results (so not frequency domain results).  I'm sure it could be cleaner, but that's for another issue.

Since it's not quite finalized, I'm going to hold off putting it in the new version until the API is a bit more settled.
