### ISSUE TITLE
Unable to install latest version on linux

### ISSUE THREAD

**Issue by Gypaets** [SteveDoyle2/pyNastran#654]
I'm trying to use the latest version of pyNastran.  I've cloned the repository, installed all the packages listed in the [documentation](https://pynastran-git.readthedocs.io/en/1.3/installation/installation.html#installation) and ran `python setup.py install --user`.

When I try to import `pyNastran`, I get the following error:

```
>>> import pyNastran
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
>>> 
```
I've run this from a Debian computer with python 3.9, and another computer with CentOS 8 and python 3.8. In both cases, I get the same error.

What could be the reason, and how can I fix it?

**Comment by SteveDoyle2** [comment]
I don't think I've tested that method in quite a while.  I think I never expected someone to use "setup.py install" if it's not a release version.  I was expecting "setup.py develop".  Not sure why the weird git message happened, but I think it's fixed.

I broke the build adding a test for that.  I'm not sure how I can run the tests if it's installed like that (e.g., the test files don't get sent to the install folder).  Thoughts?

**Comment by Gypaets** [comment]
Thanks, with the `develop` option it works. I've just recently started working with custom python modules and didn't knew the install option `python setup.py develop`. Perhaps if you add it to the section _Installation from source_ the installation will be easier for newbies. I've just created a pull request with it, feel free to accept it.

**Comment by SteveDoyle2** [comment]
There is an installation from source section though it says to use install
:)

https://pynastran-git.readthedocs.io/en/1.3/installation/installation.html#installation-from-source

Honestly, if anything, the installation section is too long and
complicated.  I probably should get rid of that section.
