### ISSUE TITLE
v1.4.0 module pyNastran.op2.op2 not found

### ISSUE THREAD

**Issue by chrissorin** [SteveDoyle2/pyNastran#665]
After installing the v1.4.0 using git clone and "python setup_no_gui.py install", the modules structure seems to be different from v1.3.3
How do we read op2 files since the module pyNastran.op2.op2 doesn't seem to be part of the v1.4.4 install.
Thank you.
![module_issue](https://user-images.githubusercontent.com/91917975/136585058-3d0234b2-b200-43e0-acb8-3ac75ea9d6cc.png)

**Comment by chrissorin** [comment]
All good now.

**Comment by SteveDoyle2** [comment]
What was the issue?

**Comment by chrissorin** [comment]
There was something wrong with the site-packages install. Just cleaned it up and re-installed by downloading the v1.4 zip.
