### ISSUE TITLE
pyNastran.__path__[0] returns different values with PyCharm and Jupyter

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#670]
# Summary
I was trying to run the [BDF Introduction Jupyter notebook](https://pynastran-git.readthedocs.io/en/latest/quick_start/bdf_demo.html) and I noticed that when I run it with PyCharm `pyNastran.__path__[0]` returns `C:\Users\qa21944\git\pynastran\pyNastran`, that is to say the location where I cloned pyNastran from github, while when I run it with Jupyter the same call returns `C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\pynastran-1.4.0+dev.90f957887-py3.8.egg\pyNastran`, that is to say the location of the package within the anaconda environment. In Jupyter this causes an error because the `models` folder is not present at the package location.

# Bug reproduction
Open the .ipynb file with PyCharm and follow the indication to set the environment used to run pyNastran as kernel of the notebook. Execute the first code block of the notebook. Start Jupyter (I use chrome as browser) and open the .ipynb file. Select the kernel set up by PyCharm and execute the first code block again.

# Versions
pyNastran.__version__ --> '1.4.0+dev.90f957887'
platform.python_version() --> '3.8.12'

**Comment by fmamitrotta** [comment]
I installed pyNastran from source, cloning the repository from the main branch and running `python setup.py install`.

As a consequence, I have the `models` directory in `C:\Users\qa21944\git\pynastran`, while I do not have it in `C:\Users\qa21944\Anaconda3\envs\pynastran\lib\site-packages\pynastran-1.4.0+dev.90f957887-py3.8.egg`. For this reason, I do not get the error running the Jupyter notebook both with PyCharm and with Jupyter, I only get it with Jupyter.

Of course I can update the path to the example (or copy the `models` folder to the location of the package in the anaconda environment), but I wanted to understand whether it is normal to get two different outputs from `pyNatran.__path[0]__` depending on the used software (PyCharm and Jupyter). May this behavior be caused by the fact that I used `python setup.py install` instead of `python setup.py develop`? Or is the reason related to something else?

**Comment by SteveDoyle2** [comment]
Maybe I missed it, but where does it say   python setup.py install?  It
shouldn't.

It works, but you don't get the models.  So many people do it though.  The
reason I discourage it is when people pull the latest version, they don't
get the updates.  It's also slightly different than the whl format, which
is annoying.  Really, setup.py needs to go (it's deprecated), but I'm not
sure how to do dynamic versions of packages without it.

**Comment by fmamitrotta** [comment]
Sorry, nothing wrong with the installation instructions, I forgot to add that I ran `python setup.py install` and I realized only later that the indicated command was with `develop`. Since it worked anyway, as you said, I did not give much attention to it. I will reinstall everything using `python setup.py develop`.

By the way, I was reading here about the difference between `python setup.py install` and `develop`. `pip install -e` is recommended for developer install, maybe coud be of help? Sorry, I am not an expert (as you can judge), and maybe you have already taken into consideration this. Also what do you mean by dynamic versions of packages? Do you refer to pyNastran or to the required packages?

**Comment by fmamitrotta** [comment]
I have built from scratch pynastran (in develop mode) and the docs today and everything seems to work
