### ISSUE TITLE
Load bdf file with bulk data only

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#671]
# Summary
I would like to load a bdf file that has only the bulk data section. The file may start with `BEGIN BULK` and end with `ENDDATA`. I tried to run `read_bdf` with `punch=True` on the file attached, but I get an error.

# Issue reproduction
This is my code:
```
import os
from pyNastran.bdf.bdf import BDF

# Define location of bdf file
bdf_filename = os.path.join('C:\\Users\\qa21944\\git\\tacs-2.0.0\\examples\\crm', 'uCRM-9_wingbox_coarse.bdf')
# Instantiate the model
model = BDF()
# Read bdf file with punch=True to avoid error caused by missing Executive and Case Control Deck
model.read_bdf(bdf_filename, punch=True)
```

And this is the error I get:
```
pyNastran.bdf.errors.SuperelementFlagError: Is there a second BEGIN BULK in your deck?
Another possibility is that punch=True and there is a BEGIN BULK in your deck.
['BEGIN BULK\n']
```

The file `uCRM-9_wingbox_coarse.bdf` is in the .zip folder attached below.
[uCRM-9_wingbox_coarse.zip](https://github.com/SteveDoyle2/pyNastran/files/7379589/uCRM-9_wingbox_coarse.zip)
As I mentioned it starts with `BEGIN BULK` and ends with `ENDDATA`. Apparently the `read_bdf` method does not accept `BEGIN BULK` in the deck when `punch=True`. Why is that the case? I would be more than happy to contribute to the code and implement a way to handle this kind of files, but I need to understand the rationale behind the checks first.

# Versions
`pyNastran.version` --> `1.4.0+dev.90f957887`
`platform.python_version()` --> `3.8.12`

**Comment by SteveDoyle2** [comment]
The punch argument name comes from the *.pch file, which looks like a typical bdf, but it only contains BULK data cards (e.g., no header).  It's format is specified by the SOL 200 output and includes things like design variables, materials and properties.  It can also be used for superelements and you'll end up with DMIG cards.  To be clear, this is different than the *.pch result file that can store things like displacement and stress.

The BEGIN BULK line is part of the case control deck.  Thus, you definitely should not be using punch=True.

![image](https://user-images.githubusercontent.com/1059417/138135014-d9408653-65c9-421d-aada-ed1b142e62ca.png)

I'm not sure what the right way would be to support this or if it even should be.  Why do you have an extra line at the top?

**Comment by stephinity** [comment]
In case it is helpful for others:

I've also faced this issue, and as a work around I just create a "dummy" Nastran deck  (attached) with the minimum necessary Executive and Case Control Cards.
This does not directly solve @fmamitrotta's problem, as calling `bdf.write_bdf()` will write out the dummy Executive & Case Control cards, however as those are only a few (same) lines they can be removed with only a little extra code.

[DUMMY.zip](https://github.com/SteveDoyle2/pyNastran/files/7390385/DUMMY.zip)
