### ISSUE TITLE
read_op2 error in reading op2 created by comlab

### ISSUE THREAD

**Issue by mizushimayasunori** [SteveDoyle2/pyNastran#673]
I'm trying reading op2 output created by Comlab
(https://www.mystran.com/forums/forumdisplay.php?fid=11)
I attached reading python scripts and OP2 files.
[nasa95op2.zip](https://github.com/SteveDoyle2/pyNastran/files/7439737/nasa95op2.zip)
 But I encountered error when reading.
I tried two types of op2 files.
One is msc formatted data, the other is nasa95 formatted data.
Comlab supports only msc format by default, but Dr. Harry Shaeffer, who is a developer of Comlab, added ability to read nasa95 format for me.

But both types cannot be read with pyNastran due to different errors, respectively.

Is there any way to solve this problem?

**Comment by SteveDoyle2** [comment]
Your example doesn't run.  I'm getting an encoding error.

**Comment by SteveDoyle2** [comment]
Looking at the examples directly, Nastran 95 doesn't support 64-bit,  The GPL and EQEXIN tables are also malformed.

Either I need a better definition of the GPL and EQEXIN tables or I need an MSC/NX example.  I can't rely on Comlab's MSC format as an valid file format for MSC.
