### ISSUE TITLE
Wrong equality check of output length in gui_io

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#676]
# Summary
The `load_file_dialog` function of the `gui_io.py` module checks the length of the variable `output` when `_gui_mode` is either `pyqt` or `pyside`:
```
output = QFileDialog.getOpenFileName(form, title,
            dirname, qt_wildcard)
        if len(output) == 1:
            fname, wildcard_level = output
        else:
            fname = output
```

However, if I understand correclty the objective of this `if` `else` statement, when the length of `output` is 2 we should have `fname, wildcard_level = output`, otherwise the `output` is just the string containing the path to the file.

# Issue reproduction
For example, try the following (of course you need the gui to work either with `pyqt` or `pyside`):
```
from pyNastran.op4.op4 import read_op4

matrices = read_op4()
```

After selecting a file, this is the error you should get:
```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not tuple
python-BaseException
```
caused by line 19 of `genericpath.py` because `path` is a tuple and not a string.

# Versions
`pyNastran.version` --> `1.4.0+dev.eda651ac2`
`platform.python_version()` --> `3.10.0`

# Proposed solution
If I am correct, the solution should just be to substitute `if len(output) == 1` with `if len(output) == 2`. Can I do it with a pull request, just for me to exercise with the process?

**Comment by SteveDoyle2** [comment]
Yeah that's definitely wrong.

Go ahead and make the pull request.

**Comment by fmamitrotta** [comment]
Done! Did I execute the procedure correctly?
