### ISSUE TITLE
Cannot find OLOAD resultant data in OP2 object

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#678]
# Summary
I read a op2 file with `read_op2` and I cannot find the OLOAD resultant data anywhere in the `OP2` object. The `oload_resultant` property appears to be `None`. The `applied_loads` property appears to be an empty dictionary. I looked for OLOAD in the docs and I found something in `pyNastran.op2.tables.opg_appliedLoads.opg` but this does not correspond to anything usable in the `OP2` object.

# Bug reproduction
Below you can find a sample bdf file and a sample python script.

```
SOL 106
CEND
$
TITLE=TRACE LARGE DEFLECTION OF A CANTILEVERED BEAM
SPC=1
OLOAD = ALL
DISP=ALL
SPCF=ALL
NLPARM=10
$
SUBCASE 10
LOAD=200
$
BEGIN BULK
GRID,1,,0.,0.,0.
GRID,2,,10.,0.,0.
CBEAM,101,1,1,2,0.,0.,1.
PBEAM,1,1,1.,1.-2,1.-2,,2.-2
MAT1,1,10.E6,,.0
$
SPC,1,1,123456
$
FORCE   11      2               1.      -1.e4
LOAD    200     .2      1.      11
$
NLPARM  10                                                      YES
NLPCI   10      RIKS
$
PARAM,LGDISP,1
PARAM,POST,1
$
ENDDATA

```

```
# Import packages
import os
import numpy as np
from pyNastran.op2.op2 import read_op2
import pandas as pd

# Set default precision of real numbers for pandas output
pd.set_option('display.precision', 3)
np.set_printoptions(precision=3, threshold=20, suppress=True)

# Read op2 file
op2_filename = os.path.join(os.getcwd(), 'lgdisp1_arclength.op2')
op2 = read_op2(op2_filename, build_dataframe=True, debug=False)
print(op2.oload_resultant)
print(op2.applied_loads)

```

# Versions
`pyNastran.__version__` --> 1.4.0+dev.c560bf822
`platform.python_version()` --> 3.10.0

**Comment by SteveDoyle2** [comment]
The oload_resultant is a holdover from the f06 parser.  Nastran doesn't
write it to the op2.  For most models (e.g., without SPOINTs), you can just
calculate it from the sum of the applied load.

Regarding the applied load, you need OLOAD(PLOT) = ALL.  PLOT means put the
data into the op2.  You're putting all the data into the f06.

**Comment by fmamitrotta** [comment]
Thanks for the answer. All clear for the `oload_resultant` property. Regarding the `applied_loads` property, I've tried to run Nastran with `OLOAD(PLOT) = ALL` and to load the op2 file but I still see an empty dictionary. Do you have any other idea why that can happen?

**Comment by SteveDoyle2** [comment]
Checking your deck again...you're using PARAM,POST,1, not -1 or -2.  I
don't know what values > 0 mean.  I'm surprised it didn't crash.

**Comment by fmamitrotta** [comment]
I have tried both -1 and -2 for `PARAM,POST`, also adding `PARAM,POSTEXT,YES` as I found in one example in the docs, but I still see `applied_loads` as an empty dictionary unfortunately.

By the way, according to the Quick Reference Guide of MSC Nastran v2018, "_`PARAM,POST,1` outputs the appropriate files for the SimXpert and Patran programs and should be used to obtain results from the latest result data blocks from SOL 400 and other recent MSC Nastran developments such as NEF_". In the guide it is also mentioned that `PARAM,POST,1` should
be used in place of `PARAM,POST,-1` for more recent versions than v2012.

**Comment by SteveDoyle2** [comment]
I'd have to see an op2.   I'd also start with a SOL 101 example. The SOL
400 part is also super important.

Regarding the QRG note, that's not pyNastran.  As far as I know, the op2
will be "ascii" if you have post > 0.  That's not supported.  I don't know
if/how that was changed for SOL 400, but it's possible they don't put it in
the standard table, which is why it's not loaded.

**Comment by fmamitrotta** [comment]
I have modified the bdf file to have a SOL 101 example. Please see the bdf file below and the attached op2 file.

I checked the op2 file that I obtained with `PARAM,POST,1` and it is not ASCII, in fact I cannot read it with Notepad++. `read_op2` seems to work well, except for the `applied_loads` property.

```
SOL 101
CEND
$
SPC=1
OLOAD(PLOT) = ALL
DISP=ALL
SPCF=ALL
$
SUBCASE 10
LOAD=200
$
BEGIN BULK
GRID,1,,0.,0.,0.
GRID,2,,10.,0.,0.
CBEAM,101,1,1,2,0.,0.,1.
PBEAM,1,1,1.,1.-2,1.-2,,2.-2
MAT1,1,10.E6,,.0
$
SPC,1,1,123456
$
FORCE   11      2               1.      1.e4    1.e3
LOAD    200     .2      1.      11
$
PARAM,POST,-2
PARAM,POSTEXT,YES
$
ENDDATA

```
[sol101.zip](https://github.com/SteveDoyle2/pyNastran/files/7977680/sol101.zip)

**Comment by SteveDoyle2** [comment]
The result is on model.load_vectors

**Comment by fmamitrotta** [comment]
Ok I understand. I indeed had a look at the `load_vectors` property and I saw it contains the load vector applied at every node. So should I assume that the `applied_loads` property is another holdover and that the only way to obtain the overall applied loads is to sum up the vectors in the `load_vectors` property?

No, I haven't tried `test_op2`, I will have a look at it, thanks for pointing that out!

**Comment by SteveDoyle2** [comment]
applied_loads is just a dead name for the same variable.  At some point,
they were merged.  Basically, you used to get get the same basic result
going to different places based on solution because it was coming from a
different OP2 result table.

**Comment by fmamitrotta** [comment]
Understood, thanks for the explanation!
