### ISSUE TITLE
PBEAML error: at least 1 station must be defined

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#680]
# Summary
If I use the `add_pbeaml` method with input `xxb=''` to add a `PBEAML` card to my model I get the following error:
```
IndexError: pid={pid:d}; len(xxb)=0; at least 1 station must be defined
```
However the following input is considered valid in a bdf file:
```
$-------PID-----MID-----GROUP---TYPE----6-------7-------8-------9-------10------
$-------DIM1(A)-
PBEAML  1       1               ROD
        10.
```
This means that if I want to specify constant cross-sectional properties, I only need to specify the dimensions at the first point of the element (point A), and the field `X(j)/XB` can be left blank.

Is there a reason why the `add_pbeaml` method does not consider this possibility?

# Reproduction
bdf file:
```
SOL 101
CEND
$
SPC=1
OLOAD(PLOT) = ALL
DISP=ALL
SPCF=ALL
$
SUBCASE 10
LOAD=200
$
BEGIN BULK
GRID,1,,0.,0.,0.
GRID,2,,10.,0.,0.
CBEAM,101,1,1,2,0.,0.,1.
$
PBEAML  1       1               ROD
        10.
$
MAT1,1,10.E6,,.0
$
SPC,1,1,123456
$
FORCE   11      2               1.      1.e4    1.e3
LOAD    200     .2      1.      11
$
PARAM,POST,-2
PARAM,POSTEXT,YES
$
ENDDATA
```
Python file:
```
from pyNastran.bdf.bdf import BDF
model = BDF()
pid = 1
mid = 1
beam_type = 'ROD'
d = 20  # [mm]
dimensions = [d/2]
model.add_pbeaml(pid, mid, beam_type, xxb='', dims=dimensions)
```

# Versions
`pyNastran.__version__` --> 1.4.0+dev.9328dc94b
`platform.python_version()` --> 3.9.7

**Comment by SteveDoyle2** [comment]
It does support single section.

Your xxb value is a string and it's supposed to be a list of floats (see the docstring for add_pbeaml).  There's an implicit 0.0 in the file that's not implicit in the method.  If that wasn't the case, dimensions and xxb would have different lengths (more confusing for multi-sections).

Additionally, dimensions should be 2D.  The corrected call is:

`model.add_pbeaml(pid, mid, beam_type, xxb=[0.], dims=[dimensions])`
