### ISSUE TITLE
Why does BDF class initialize case_control_deck property as None?

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#681]
I am creating a bdf file from scratch using the `BDF` class. I start with these lines:
```
from pyNastran.bdf.bdf import BDF
model = BDF()
```
and I can observe that the `case_control_deck` property is initialized with `None` value. Since I want to define the defaults for all subcases, I tried the following:
```
model.create_subcases(0)
```
and I got the following message: `subcase=0 already exists...skipping`. It looked weird, because `case_control_deck` was supposed to be `None`, but then I discovered that the `create_subcase` method creates an empty `CaseControlDeck` object if `case_control_deck` is `None`.

My question is: why does the `BDF` class initialize the `case_control_deck` property as `None` instead of an empty `CaseControlDeck` object? And if this behavior was designed intentionally, what is the most correct way to initialize an empty `CaseControlDeck` object for the `case_control_deck` property?

**Comment by SteveDoyle2** [comment]
Please ask questions in the discussion forum.  The project looks dead otherwise.
