### ISSUE TITLE
CAN'T RUN PYNASTRAN GUI! [EASY]

### ISSUE THREAD

**Issue by mia0120** [SteveDoyle2/pyNastran#690]
Hello all and dear Steve Doyle,

I can't run pynastran gui with geometry and result files. I am doing in the way that it gives in website [Pynastran](https://pynastran-git.readthedocs.io/en/1.3/quick_start/gui.html). I am trying to run from the command prompt. The code that I use is `pyNastranGUI -f nastran -i model.bdf -o model1.op2 -o model2.op2`. However it gives an error like 
![image](https://user-images.githubusercontent.com/98092736/160799516-517191d7-63f0-4205-b44c-b4e04509bff3.png)

Thanks in advance.

**Comment by SteveDoyle2** [comment]
That's odd.  I don't get that error.  I suspect you're on an older version.

You can also just call:
 >>> pynastrangui -f nastran quasi-static.bdf quasi-static.op2

or because you have a .bdf file (dat is ambiguous):
 >>> pynastrangui quasi-static.bdf quasi-static.op2

If you have multiple op2s, you can do:
 >>> pynastrangui quasi-static.bdf quasi-static.op2 -o other1.op2 -o
other2.op2

**Comment by mia0120** [comment]
I am using 1.3.3. pyNastran and pyNastranGUI. I tried every combination but I still get error. 
![image](https://user-images.githubusercontent.com/98092736/161054173-c65ee5a7-dae3-4df4-b517-6a663449266e.png)

**Comment by SteveDoyle2** [comment]
I'd upgrade or just load the file from the gui.
