### ISSUE TITLE
How to Create rbe2 with equal distance in my BDF files

### ISSUE THREAD

**Issue by weiweiisok** [SteveDoyle2/pyNastran#694]
Hi, dear SteveDoyle, I have some problems with my BDF files，I want create rbe2 grid element to connect two nodes with equal distance or  turn two nodes (which are not in the same part, because I want connect each part of finite element model) into one node with equal distacne, and my finite element models are just all 2D quads. Is there any way to do it? I would be very grateful if you made any suggestions!

**Comment by SteveDoyle2** [comment]
Check out the BDF.add_rbe2(...) method.

**Comment by weiweiisok** [comment]
Hi SteveDoyle, thank you very much for replying to me. I have checked your suggestion which is very useful to me. And I am very new about pyNastran, so the last difficulty is how to find potential welding spots between two components to be connected at equal intervals.

**Comment by SteveDoyle2** [comment]
With no understanding of your geometry, the best way to do it would just be to have a periodic surface in which case, you pull all the nodes along a line and take every 3rd and connect them.  That or just pick them by hand.

There's 100 ways to do it, but that all depends on what you're really trying to do.
