### ISSUE TITLE
issue reading geometry from OP2

### ISSUE THREAD

**Issue by M4cDarvvin** [SteveDoyle2/pyNastran#702]
Hello everyone,

(And of course Thank you Dr Doyle for your work and this amazing library)

I'm currently working on getting the possibility to extract the geometry from the OP2 file using the read_op2_geom from the pyNastran.op2.op2_geom module, however it seems I have an issue related to geom3.

it seems some part of the file can be read, but I get then an assertion error related to geom3. I cannot understand yet if the problems related to my file as a non-Nastran user

############################################################################
DEBUG: op2_common.py:626 found keys=( 4401, 44, 26) name=GRAV - b'GEOM3'
DEBUG: op2_common.py:626 found keys=( 4551, 61, 84) name=LOAD - b'GEOM3'
DEBUG: op2_common.py:626 found keys=( 4801, 48, 19) name=MOMENT - b'GEOM3'
DEBUG: op2_common.py:626 found keys=( 7209, 72, 299) name=PLOAD4 - b'GEOM3'
**failed reading b'GEOM3' isubtable=-7**
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
#############################################################################

I can if necessary put the full error message.

**Comment by SteveDoyle2** [comment]
Dr?  Not quite.

Without a small example, I can't say much.  About the only thing I'd guess is you're using MSC 2021 or 2022.

Also, the read_op2_geom is quite clear that it's a harder problem than reading the BDF, so you can just get the geometry from there.  The geometry in particular is a moving target, moreso with MSC Nastran.  I don't have access to MSC Nastran anymore, so it make it harder.

**Comment by M4cDarvvin** [comment]
My mistake I thought the library was part of a PhD  :) always happy to generate laugh, 

anyway thanks for your answer I will go for the BDF.
