### ISSUE TITLE
add_modtrak method not linked with MODTRAK Class

### ISSUE THREAD

**Issue by jpdeslich** [SteveDoyle2/pyNastran#704]
The add_modtrak method exists as a bdf module method but does not appear to be linked up with the MODTRAK class. 

![image](https://user-images.githubusercontent.com/50683883/189732020-ab4e5863-2513-4395-b09f-7ab306ee12d1.png)

**Comment by SteveDoyle2** [comment]
I’m not sure if that means it’s not done or a mistake. I’ll take a look
when I’m back in town

**Comment by SteveDoyle2** [comment]
Sorry for the delay.  Been really busy.  MODTRAK is a new card in 1.4-dev.  You need to use the main to get MODTRAK.

**Comment by SteveDoyle2** [comment]
this was finished a while ago
