### ISSUE TITLE
Cross-reference errors 

### ISSUE THREAD

**Issue by neotake** [SteveDoyle2/pyNastran#706]
Loading this "official" example: http://www.mscsoftware.com/doc/nastran/mdug/input_files/ch001/ch01.bdf produces cross-reference errors:

KeyError: 'Invalid Hyperelastic Material ID:  mid=1\n, which is required by PLPLANE pid=1'
card=PLPLANE        1       1       0    GRID

KeyError: 'Invalid Hyperelastic Material ID:  mid=2\n, which is required by PLPLANE pid=2'
card=PLPLANE        2       2       0    GRID

More information about the example can be found here: https://help.hexagonmi.com/bundle/MSC_Nastran_2022.2_Demonstration_Problems_Manual-Implicit_Nonlinear/resource/MSC_Nastran_2022.2_Demonstration_Problems_Manual-Implicit_Nonlinear.pdf Chapter 1: 2-D Cylindrical Roller Contact

**Comment by SteveDoyle2** [comment]
PSHLN2 is not supported.

**Comment by SteveDoyle2** [comment]
Also, there is no valid material.  Per the QRG, a MATHE or MATHP is required.  MAT1 is incorrect according to the 2018.2 QRG.
