### ISSUE TITLE
Heavy Op2 file Issue

### ISSUE THREAD

**Issue by MarkSttc** [SteveDoyle2/pyNastran#709]
Hi guys, I'm currently working on op2 file which is around 4 GB. Hence, there is an allocation problem when using read_op2 method for the whole data. However, I just want to work with only few grid points (80 from >1e6 nodes). I'm doing modal analysis, thus I need to build DataFrame with the nodes corresponding eigenvectors

**Is it possible for me to specify the interested nodes when calling read_op2 method? or Are there any alter solutions to my issue?**

Btw, Kudos to the PyNastran team. You guys did an amazing job and please don't stop developing this amazing module :D.

Cheers,

**Comment by SteveDoyle2** [comment]
Thanks!  Just my little hobby project :)

What is the allocation error?  That seems like the easiest fix.  A 4 GB
file is small and sound be read in ~8 seconds.

 If you want fewer points in the table you can do:

SET 1=1,THRU,80, 100
DISP{PLOT)=1

**Comment by MarkSttc** [comment]
Thanks for the instant reply!. Please find the error message below

“MemoryError: Unable to allocate xx GiB for an array with shape (xxxxxxx , xx) and data type float32” 

I can mitigate this issues by moving my virtual memory to different drive just to expand my computing space but would be better if I know how to play around with the codes. 😆

SET 1=1,THRU,80, 100
DISP{PLOT)=1
So we specify this in op2 file or read_op2 method

**Comment by SteveDoyle2** [comment]
This wasn't added to the thread...

Are you on 32 but python?  It’s the default on [python.org](http://python.org/) for whatever reason, but yeah use 64-bit

If you just type python on the command line, it’ll tell you.

Also,

> SET 1=1,THRU,80, 100
DISP{PLOT)=1
So we specify this in op2 file or read_op2 method

neither.  The input file,

**Comment by MarkSttc** [comment]
> 
As you suggested, specify nodes in the input file really helped me solve the issue. Therefore, I don't have to filter them out from the DataFrame :D

However, Sometimes I want to randomly pull the nodes information out from Dataframe, then I still need to resolve the memory issue. I'm using currently Python 3.8.13 64-bit, so I don't think bits should be the main reason.

**Comment by SteveDoyle2** [comment]
You didn't give me much to go on regarding your memory issue.  I need an example to test much of anything and the op2 reader doesn't really waste much RAM.  You probably just need more RAM or to not use pandas.

**Comment by MarkSttc** [comment]
Seems like It's related to RAM and pandas, I might need to consider upgrading my laptop's RAM (8Gb). Ahahaha.

but Thanks again for helping me solving the issue.

**Comment by SteveDoyle2** [comment]
Are you on 32 but python?  It’s the default on python.org for whatever
reason, but yeah use 64-bit

If you just type python on the command line, it’ll tell you
