### ISSUE TITLE
add nonlinear stress support for CBEAMs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#71]
```
Hi,
I don't understand why pynastran returns a empty printResults() on an op2 
containing stresses (I have checked with Patran) from a sol129 (transient non 
linear)?

I gess it is because the type is non linear stresses... is it supported. How 
could I dodge the problem?

Thanks anyway for your package.

Alexandre

op2 attached
```

Original issue reported on code.google.com by `vallet...@gmail.com` on 23 Mar 2012 at 8:04

Attachments:
* [cbeam_stress_1.op2](https://storage.googleapis.com/google-code-attachments/pynastran/issue-71/comment-0/cbeam_stress_1.op2)

**Comment by SteveDoyle2** [comment]
a vectorized object has been created...still need to push changes
