### ISSUE TITLE
pyNastranGUI doesn't start with command line options.

### ISSUE THREAD

**Issue by kovalev-nnov** [SteveDoyle2/pyNastran#712]
Hello Steve. Could you please fix a problem of running pyNastranGUI from command line with any of option, for instance, -q.

1.3.4:
> pyNastranGUI.exe -q
> Traceback (most recent call last):
>   File "gui.py", line 9, in <module>
>   File "arg_handling.py", line 95, in get_inputs
>   File "arg_handling.py", line 327, in run_argparse
>   File "arg_handling.py", line 395, in _update_argparse_argdict
> KeyError: 'qt'
> [23112] Failed to execute script 'gui' due to unhandled exception!

1.3.3 & 1.3.2:
> pyNastranGUI.exe -q
> Traceback (most recent call last):
>   File "pyNastran\gui\gui.py", line 9, in <module>
>   File "pyNastran\gui\arg_handling.py", line 99, in get_inputs
>   File "pyNastran\gui\arg_handling.py", line 323, in run_argparse
>   File "pyNastran\gui\arg_handling.py", line 408, in _update_argparse_argdict
> UnboundLocalError: local variable 'input_formats' referenced before assignment
> [4444] Failed to execute script gui

TIA, Alex

**Comment by kovalev-nnov** [comment]
According to 'help' info, -q is an argument:
> pyNastranGUI.exe --help
> ...
> Info:
>   -q, --quiet    prints debug messages (default=True)
> ...

There is the same error for another arguments:
> pyNastranGUI.exe -f nastran -i Test_12x4.dat -o Test_12x4.OP2
> Traceback (most recent call last):
>   File "gui.py", line 9, in <module>
>   File "arg_handling.py", line 95, in get_inputs
>   File "arg_handling.py", line 327, in run_argparse
>   File "arg_handling.py", line 395, in _update_argparse_argdict
> KeyError: 'qt'
> [14824] Failed to execute script 'gui' due to unhandled exception!

I've **fixed** it in my local version (file "arg_handling.py", line 395):
**`    if argdict.get('qt') is not None:`**
instead of 
`    if argdict['qt'] is not None:`

The reason of the problem:
after app building I have 'is_pynastrangui_exe = True',
so the 'dev' is not filled here:
```
    if not pyNastran.is_pynastrangui_exe:
        #dev = ' [--noupdate] [--test] [--qt Qt] [--plugin]'
        dev_list = ['--noupdate', '--test', '--qt', '--plugin']
        dev = ''.join([' [%s]' % devi for devi in dev_list])
```
'dev' is empty and '--qt' argument is not added:
```
    if dev:
        parent_parser.add_argument('--qt', type=str, help='{pyqt5, pyside2} msg')
```
then attempt to get 'qt' key raised 'KeyError'
`    if argdict['qt'] is not None:`

With the fix I've mentioned it works as expected.

**Comment by SteveDoyle2** [comment]
Ahh that makes sense.  I was super confused by the error.  That idea with the exe mode crossed my mind, but nah that's fine.

The qt flag is for flipping backends in case you broke one by having 2 installed or just testing multiple backends.  It's not necessary for exe mode cause there is one mode.

I never use -q.  I probably added it to make less prints for testing.

It's fixed.
