### ISSUE TITLE
unknown version=b'OS2021.1'

### ISSUE THREAD

**Issue by tjc0726** [SteveDoyle2/pyNastran#713]
Hi，I would like to read op2 made by optistruct 2021 or 2022,similar issue to the following one：
https://github.com/SteveDoyle2/pyNastran/issues/541#issue-395965710
Is there any way to bypass this version check,thanks!

**Comment by SteveDoyle2** [comment]
I've added b'OS2021.1'.  If there are other ones, I need them explicitly.  I don't have Optistruct to test on and prefer not to guess.

**Comment by tjc0726** [comment]
THANKS!

**Comment by Csr-Mur** [comment]
Hi,
Can you please let me know how this issue was fixed? (unknown version=b'OS2021.1')
Thanks

**Comment by SteveDoyle2** [comment]
You need to use the dev version

**Comment by tjc0726** [comment]
> Hi, Can you please let me know how this issue was fixed? (unknown version=b'OS2021.1') This is what I have in op2_reader.py:
> 
> `elif version in OPTISTRUCT_VERSIONS:` ` # should this be called optistruct or radioss?` ` mode = 'optistruct'` `#elif data[:20] == b'XXXXXXXX20141 0 ':` ` #self.set_as_msc()` ` #self.set_table_type()` `else:` ` raise RuntimeError(f'unknown version={version!r}')` `return mode`
> 
> Thanks

If you're using 1.3.4,there's somewhere in op2_reader.py like 

```
OPTISTRUCT_VERSIONS = [
    b'OS11XXXX', b'OS12.210', b'OS14.210',
    b'OS2017.1', b'OS2017.2',
    b'OS2018.1',
]
```

just add your version

**Comment by Csr-Mur** [comment]
Thanks for your help. I think now it picking up the version.

I am new user of PyNastran. My code is still giving me errors, so I am now reviewing the documentation.
Regards
