### ISSUE TITLE
Read ODB2OP2 version with BGDPT table

### ISSUE THREAD

**Issue by Clemoreau** [SteveDoyle2/pyNastran#716]
Hello Steve, 

First of all thank you for your contribution, pyNastran is very usefull to me.

I'm currently trying to read an .op2 file that was generated by abaqus (hence the ODB2OP2 version since .odb is an abaqus format). So I was looking at what was missing to be able to read that file.

I've got a BGDPT table while it's arleady implemented for BGPDT. I was wondering what was the difference because I'm not finding any reference on internet.

Thank you !

Clément
@helene-t

**Comment by SteveDoyle2** [comment]
Clément,

There’s an Abaqus op2?  Really?  I wonder who they added it for.

No idea what tables are in their op2.  BGPDT is the grid points in cid=0,
so not a result.

I’d have to see a deck.  Im sure there are other oddities.

Steve

**Comment by Clemoreau** [comment]
Steve, 

Yes ! A colleague of mine exported some results from Abaqus under op2 format because I was not able to read .odb file. But obviously the data is not organized in the same way than Nastran/Optistruct. I was able to open it with Hyperview as a Nastran file though.

I guess that's a more efficient way to export results from abaqus than .txt files, and also .op2 is a well known format.

The file is quite heavy and there may be some confidentiality issue... I'll see if I find a way to share it whit you.

Thanks

Clément

**Comment by SteveDoyle2** [comment]
I’d much prefer a tiny model with lots of features over a big model.  It’s
easier to look at the data and I can make a good test with it

**Comment by Clemoreau** [comment]
Hello Steve, 

I managed to get a tiny model so that you can have a look at the data. Here is an .op2 file generated with abaqus.

[Job_modal_abaqus_odb_converted_to_op2.zip](https://github.com/SteveDoyle2/pyNastran/files/10697880/Job_modal_abaqus_odb_converted_to_op2.zip)

...

**Comment by Clemoreau** [comment]
...

And here is an op2 file of the same model but run with nastran so that it can be read with pynastran.
[Job_modal_converted_to_nastran.zip](https://github.com/SteveDoyle2/pyNastran/files/10697895/Job_modal_converted_to_nastran.zip)

I tried to have a look a the BGDPT table but I'm not sure to understand what it is. 

Thank you 


Clément

**Comment by helene-t** [comment]
Hello Steve,

I am a colleague of Clement's. Have you had the opportunity to have a look at the files?

Thank you,
Helene

**Comment by SteveDoyle2** [comment]
I think I fixed that a while ago.  I've been really busy and that's not
changing.  it seems to work in the latest version.

[image: image.png]

**Comment by helene-t** [comment]
Hello,

I have tried to open the file from the zip sent by Clement ([Job_modal_abaqus_odb_converted_to_op2.zip](https://github.com/SteveDoyle2/pyNastran/files/10697880/Job_modal_abaqus_odb_converted_to_op2.zip)) with the read_op2 command from the current version, and I still get an issue in op2_reader.read_table_name4

Should I be using another function to read the file?

**Comment by SteveDoyle2** [comment]
Did you pull Friday m GitHub or did you download the zip file?

The latest version is on GitHub.  You can’t run pip install to download it.

Steve

**Comment by helene-t** [comment]
I pulled from GitHub directly

**Comment by SteveDoyle2** [comment]
If you have the following file, then you have the latest.:
- pyNastran/op2/result_objects/qualinfo.py

Beyond that I need an error message.  it works for me
