### ISSUE TITLE
failed reading b'GEOM2' isubtable=-3 (CQUADR cards)

### ISSUE THREAD

**Issue by fmamitrotta** [SteveDoyle2/pyNastran#720]
# Summary
I am trying to read the attached op2 file using the function `read_op2` with `load_geometry=True`. I get the following final debug messages:

```
DEBUG:   op2_common.py:696              found keys=( 8009,  80, 367) name=CQUADR - b'GEOM2'
failed reading b'GEOM2' isubtable=-3
```

and the following error:

```
Traceback (most recent call last):
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 2174, in _read_dual_card_load
    n, elements = msc_read(data, n0)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 3179, in _run_cquad4_msc_60
    assert minus1 == -1, minus1
AssertionError: 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2.py", line 591, in read_op2
    OP2_Scalar.read_op2(self, op2_filename=self.op2_filename, mode=mode)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 1987, in read_op2
    self._read_tables(table_name, table_names)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_scalar.py", line 2179, in _read_tables
    op2_reader.read_geom_table()  # DIT (agard)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6498, in read_geom_table
    self._read_subtables()
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6567, in _read_subtables
    self._read_subtable_3_4(table3_parser, table4_parser, passer)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_reader.py", line 6729, in _read_subtable_3_4
    unused_n = table4_parser(data, ndata)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 181, in read_geom2_4
    return self.op2._read_geom_4(self.geom2_map, data, ndata)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\op2_interface\op2_common.py", line 699, in _read_geom_4
    n = func(data, n)  # gets all the grid/mat cards
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 3443, in _read_cquadr
    n = self._read_dual_card(
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 2154, in _read_dual_card
    n, elements = self._read_dual_card_load(
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 2177, in _read_dual_card_load
    n, elements = nx_read(data, n0)
  File "c:\users\qa21944\git\pynastran\pyNastran\op2\tables\geom\geom2.py", line 3209, in _run_cquad4_nx_56
    assert leftover == 0, leftover
AssertionError: 36
python-BaseException
```

My understanding is that `geom2.py` is trying to read the NX version of the CQUADR cards, while I'm using MSC Nastran. Is this correct? And why does this happen?

# Reproduction
Read the attached op2 file using:
```
read_op2(op2_filename='ucrm9_linear_buckling.op2', load_geometry=True, debug=True)
```
[ucrm9_linear_buckling.zip](https://github.com/SteveDoyle2/pyNastran/files/10832120/ucrm9_linear_buckling.zip)

# Versions
`platform.python_version()` --> 3.9.13
`pyNastran.__version__` --> 1.4.0+dev.no.checksum.error ([this commit](https://github.com/SteveDoyle2/pyNastran/commit/c8315d3ffe1b219bd918e090ac79c4f1e1e65b21))

**Comment by SteveDoyle2** [comment]
![image](https://user-images.githubusercontent.com/1059417/221454147-d5b3e351-07e2-45f0-9686-00f3b643d417.png)

It looks about right for the CRM.  MSC didn't document their new CQUADR format, so I had to reverse engineer it (and didn't get it right).  I suspect the material theta/mcid is wrong as the -1 flag is not -1.  I'd need the BDF to check.

**Comment by SteveDoyle2** [comment]
Some models comments:
 - Your SPCs look like they're causing 0 deflection/stress in the root region.  You can probably delete those elements and run a bit faster
 - You probably need a spar or 2
 - You load distribution doesn't look elliptical

**Comment by fmamitrotta** [comment]
Thanks for your help and for your comments Steve. Please find the zip folder attached with the bdf files (uCRM9_linear_buckling.bdf is the main file, uCRM-9_wingbox_coarse.bdf contains the structural model and uCRM-9_aero_forces_1.0g_coarse.bdf the applied load).

[uCRM9_linear_buckling.zip](https://github.com/SteveDoyle2/pyNastran/files/10837587/uCRM9_linear_buckling.zip)

Please also see the below snippet about the CQUADR card from the MSC Nastran Quick Reference Guide if it can be of help (but I guess you were referring to the format in the op2 file, so probably the snippet is not useful).

![image](https://user-images.githubusercontent.com/20526753/221517504-9a8ebb15-b20b-4a95-abcc-c2d370702ba1.png)

About your comments:

- the uCRM wingbox has clamped boundary conditions at the symmetry plane and semi-flexible boundary conditions at the wing-fuselage junction (zero displacements u and w), as described in the paper below (see figure 3). I'm not 100% familiar with the model, but the root region where you see 0 deflections/stress is supposed to be the carry-through portion of the wingbox.
  [Brooks2018_Benchmark_Aerostructural_Models_for_the_Study_of_Transonic_Aircraft_Wings.pdf](https://github.com/SteveDoyle2/pyNastran/files/10837618/Brooks2018_Benchmark_Aerostructural_Models_for_the_Study_of_Transonic_Aircraft_Wings.pdf)
- The uCRM wingbox model was developed with no internal spar and smearing the effect of the stiffners into the thickness of the wingbox panels, as described in the paper mentioned above. The bdf files I'm using for the structural model and the applied loads are taken from [this](https://data.mendeley.com/datasets/gpk4zn73xn/1) Mendeley data page.
-  The original uCRM model includes leading and trailing edge masses and engine mass, with gravity loads applied to the structure. To simplify my tests I've removed the masses and the gravity loads, applying only the 1g aero forces. It is possible that this is not a good idea, but I just wanted to reduce the size of the model for the moment.

By the way, how did you obtain the picture in your first reply? Did you use the pyNastran GUI?

**Comment by SteveDoyle2** [comment]
The change they did is not in the op2 format.    I think they may have
actually fixed it vs just making it different (I.e., to artificially make
it harder to use older post-processors).

The way they stored theta vs mcid on the quad/tris means that to recover
it, you check if it’s greater than 511.  If it is, you divide by 512 and
subtract 1.  If that’s an integer, then you have an mcid.  Otherwise,
that’s the angle.  It’s weird to put it mildly.  I’m hoping they fixed it,
but it takes time to decipher it considering they didn’t document it in the
DMAP guide.

To get the bdf, I ran “test_op2 -gnc filename”. I had to modify
_run_cquad4_msc_60 in pynastran/op2/tables/geom to remove the “assert
minus1 == -1, minus1” line.  You’re hitting that before try-excepting into
the other function.

**Comment by fmamitrotta** [comment]
I understand. Yes, the old way of storing theta vs mcid is definitely weird. Also because to discern between the two it would be sufficient to ask the user to input an integer for mcid and a floating point for theta, wouldn't it?

Anyway, deleting that line now I'm able to read the geometry, thanks!

Should I close this issue or do you want to keep it open until you decipher how they changed the way they store theta vs mcid?

**Comment by SteveDoyle2** [comment]
> Also because to discern between the two it would be sufficient to ask the user to input an integer for mcid and a floating point for theta, wouldn't it?

The user enters that in the BDF, so but this is in the op2.  They made the decision to put a float and int in 4 btyes, but they made a bad decision.  It especially falls apart when you're doing optimization you set an angle > 360 to avoid making a negative angle (you can use a better optimization method because you avoid 0.0).

I'll close it.  I need to fix the bug.

**Comment by fmamitrotta** [comment]
I see your point.

May I just ask you how you obtained the picture in your first reply? Did you use the pyNastran GUI?

**Comment by SteveDoyle2** [comment]
should be fixed now.

**Comment by SteveDoyle2** [comment]
Error is a bit strong of a word.  The parser is wrapped in a try except and
can’t fail.  In need to clean it up, but I need to find all the arguments,
so with that I’m closer!

In general though, it should be quieter than the previous approach.  It
just takes a bit to get there

**Comment by fmamitrotta** [comment]
Sorry, bad wording, I meant warning and error messages :-)

I've tried to understand the logic behind the messages looking at op2_reader.py. I think what happens is that you try to instantiate an instance of `QualInfo` class but this fails becasue there are unexpected keyword arguments (namely PRELOAD and MPC) and the error is caught in by the try except that calls `_parse` with `debug=True`, which in turn prints all the warning and error messages.

Am I correct? If this is the case the solution should be to include PRELOAD and MPC in the input arguments of `QualInfo` constructor method. If you want I can do it!

Just one more question, for my understanding: what is actually happening here? What part of the op2 file is the code reading and what does `QualInfo` represent?

**Comment by SteveDoyle2** [comment]
Yeah if you want to do a pull request, that’d an easy one.

As to what it means, it’s looks like a bunch more f case control flag
info.  No idea why there are multiple lines and a bunch of 0s.  Nastran FTW!

**Comment by fmamitrotta** [comment]
Hi Steve, I've seen that the additional warnings have been eliminated with [this commit](https://github.com/SteveDoyle2/pyNastran/commit/dc06aa01c0cddc125c6e3b582445825fcf75eeb3), thanks for that! I was about to start working on it when I saw your commit. I've seen you have reorganized quite a bit, for sure it's better for the code with respect to what I would have done :-)

**Comment by SteveDoyle2** [comment]
preload and a few others should work now.  Either way it won't crash.  I'd bet I don't have everything.

I code by throwing stuff at the wall.  If you look closely ;)
