### ISSUE TITLE
Get transformation matrix between 2 Coordinate Sys?

### ISSUE THREAD

**Issue by Su-yes** [SteveDoyle2/pyNastran#721]
Hi, Steve! Thanks for all that you do in regard to pyNastran! I appreciate its existence more and more every time I use it. I am not sure if this is the right place to ask this; I'm not very familiar with GitHub's UI. I am looking at the `coordinate_systems` module. Is there a way or an existing method I can call to get a transformation matrix given 2 CSs? I am not looking to transform a CS. I believe, `transform_coords_vectorized()` does that. I just want to back out a transformation matrix between 2 CS. If not, that's okay! It shouldn't be too difficult to calculate.  Thank you!

**Comment by SteveDoyle2** [comment]
I'm not sure what your goal is, so It's hard to give you what you want.  What are you trying to transform?

Assuming they're both rectangular, you can just call the 3x3 x 3x3 dot product of `coord1.beta() @ coord2.beta().T`.  If there's a cylindrical/spherical coordinate system, it gets harder.

There's also a 4x4 transform, which can shift, scale, and rotate.

**Comment by Su-yes** [comment]
Hi, Steve. Thanks for the response!
 
I have results (in excel) that needs some post-processing. Right now, I read in the bdf to get ele/node location to process the data. But, turns out some responses are in different CSs. I am looking to transform the data from $CS_A$ to $CS_B$. I am looking for $T$ such that $CS_B = T\cdot CS_A$

I checked out the `.beta()` method. Looks like it returns the $T$ with respect to its definition system. What you suggested works for when CS_A and B both share same parent CS. 

If A and B do not have the same parent CS.  It appears to me that I would have to go down the chain for each CS (calling `beta()` at each step), until there is a common parent CS (Say, $CS_P$). Then, I would do $T_{AB}=CS_{A-P}  \cdot  (CS_{B-P})'$.  Where, subscript $(X-P)$ refers to the transformation matrix w.r.t $P$ and is the product of all $T$ matrices in the respective chain. Now, $CS_B = T_{AB}\cdot CS_A$.

For now, I can work the `.beta()`. Thank you for pointing that out to me!

**Comment by Su-yes** [comment]
I've been perusing the documentation. Actually, for the case where $CS_A$ and $CS_B$ don't share the same parent, I could just do $T_{AB} =$ `CS_B.global_to_local @ CS CS_A.global_to_local.T` or $T_{AB} =$ `CS_B.global_to_local @ CS CS_A.local_to_global`.

**Comment by Su-yes** [comment]
Gotcha. Thanks! 

Also, I was using the `beta_n()` method and noticed that it's not including the 3rd row and col of the 3x3 T matrix. 
![image](https://user-images.githubusercontent.com/95985254/223410247-70086716-a523-4ea7-ac1d-39b16fee315c.png)

Looking the source code I see that you're only grabbing the first 2 rows and cols. The `3+2` on the left and 2 in the slicing index `0:2` is not inclusive. 
![image](https://user-images.githubusercontent.com/95985254/223410684-8268c015-a68a-46df-963b-d163d1a5db29.png)
Is this intentional? 

In my case, I made a simple change: `t[i*3:i*3+3, i*3:i*3+3] = matrix[0:3, 0:3]`. It now gives me what I am looking for.  
![image](https://user-images.githubusercontent.com/95985254/223412600-4d6c0482-956a-4453-8051-11ac13690a72.png)

**Comment by SteveDoyle2** [comment]
Yeah, that's an error.

It should be:
            t[i*3:i*3+3, i*3:i*3+3] = matrix

I'll  be pushing that shortly.
