### ISSUE TITLE
Nonlinear Solid Data Header Names

### ISSUE THREAD

**Issue by mason-hickman** [SteveDoyle2/pyNastran#733]
Equivalent stress is incorrectly named as effective plastic strain in the data headers for nonlinear solid elements, as shown below.  The effective plastic strain header is duplicated.  Noticed the issue for CHEXA and CTETRA elements. Have not checked others.

The code:
`results = OP2()

results.read_op2(file)

headers = results.nonlinear_chexa_stress_strain[case_id].get_headers()`

Produces the following: 
 data: [ntimes, ntotal, 15] where 15=[oxx, oyy, ozz, txy, tyz, txz, eff_plastic_strain, eff_plastic_strain, eff_creep_strain, exx, eyy, ezz, exy, eyz, exz]

**Comment by SteveDoyle2** [comment]
Ooops!  I never replied.

Do you have an example?  I suspect you're using a newer version than what the code was designed for and MSC/Siemens updated the format.

**Comment by SteveDoyle2** [comment]
closed due to innactivity
