### ISSUE TITLE
Reading a table of USET table format

### ISSUE THREAD

**Issue by ryakoub** [SteveDoyle2/pyNastran#734]
Hello,

I have an OP2 file that has a table named USET and it is of USET table format, DOF id and DOF set membership.  The OP2 reader is not recognizing it since the name is not standard.  How to tell the OP2 module that this table is of USET format?

**Comment by SteveDoyle2** [comment]
I don’t use USET.  I thought it supported it, but I’d need to see an
example

**Comment by SteveDoyle2** [comment]
closing due to innactivity
