### ISSUE TITLE
export_to_vtk

### ISSUE THREAD

**Issue by shengqingke** [SteveDoyle2/pyNastran#735]
Hello,
      I am using export_to_vtk.py, could you add the mode judgment to the instantiation of BDF in the function export_to_vtk_filename?For example, for optistruct files, you should pass parameter mode="optistruct", otherwise the subsequent map_version function is meaningless. And that default mode value is  "msc", and subsequent code will be failed.

**Comment by SteveDoyle2** [comment]
That function has been removed in favor of
pyNastran/converters/nastran/nastran_to_vtk

It takes in an op2 with geometry.  The op2 is expected to have a version
listed in the binary, which I would assume unless you're throwing special
flags (e.g., PARAM,POST,-2 in MSC/NX), it does.

**Comment by shengqingke** [comment]
thanks for your reply, i will try this function.



---- Replied Message ----
| From | Steven ***@***.***> |
| Date | 06/19/2023 23:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [SteveDoyle2/pyNastran] export_to_vtk (Issue #735) |

That function has been removed in favor of
pyNastran/converters/nastran/nastran_to_vtk

It takes in an op2 with geometry. The op2 is expected to have a version
listed in the binary, which I would assume unless you're throwing special
flags (e.g., PARAM,POST,-2 in MSC/NX), it does.
