### ISSUE TITLE
Cannot Read .op2 file SOL 108

### ISSUE THREAD

**Issue by Benid22** [SteveDoyle2/pyNastran#736]
I just got an op2 file generated by Simcenter ver2020.2 containing FRF data. 
Using the following code snippet fails to read the file, throwing an exception: "AssertionError: word=b'FRFGEN'". 
I wonder if the issue is related to the NX Nastran version ([supported until NX 2019.1](https://github.com/SteveDoyle2/pyNastran/blob/1.3/releaseNotes.md)), or something else.

```
from pyNastran.op2.op2 import OP2
op2 = OP2()
op2.read_op2(op2File)
```

### OP2 file generation info:
•	Software
PrePost : Simcenter3D ver2020.2
Solver : Simcenter Nastran ver2020.2
•	Output setting
Physical quantity : Acceleration, Displacement
export files : op2
•	Solver setting
SOL : 108
Subcases : each connection DoFs (= 6 node * 3 directions)

### LOG
```
PS C:\DEV\ReadOp2>  & 'C:\Users\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users \.vscode\extensions\ms-python.python-2023.10.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '57732' '--' 'C:\DEV\read_op2.py' 
DEBUG:   op2.py:542                   combine=True
DEBUG:   op2.py:543                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1672           op2_filename = 'C:/DEV/Datasets/op2/sol108_frf.op2'
DEBUG:   op2_reader.py:231            date = (6, 2, 23)
DEBUG:   op2_reader.py:302            mode = 'nx'
DEBUG:   op2_scalar.py:1850             table_name=b'IBULK'
DEBUG:   op2_scalar.py:1850             table_name=b'ICASE'
DEBUG:   op2_scalar.py:1850             table_name=b'CASECC'
DEBUG:   op2_scalar.py:1850             table_name=b'PVT0'  
failed reading b'PVT0' isubtable=-3

```
### ISSUE – EXCEPTION:
```
Exception has occurred: AssertionError
word=b'FRFGEN'
  File "C:\DEV\read_op2.py", line 20, in <module>
    op2.read_op2(op2File)
AssertionError: word=b'FRFGEN'

```

**Comment by SteveDoyle2** [comment]
Try giving the version on github a try.  It's quite a bit newer.  Beyond that, I'd need to see an example.  I'm surprised the error message is that bad.

**Comment by SteveDoyle2** [comment]
The latest is 1.4-dev.  You’ll have to install from source.  You can either
use git to download it or download a zip file of the source. Then run
“python setup.py develop” in the root folder.

**Comment by SteveDoyle2** [comment]
closing due to innactivity
