### ISSUE TITLE
How to make a mode shape screenshot automatically?

### ISSUE THREAD

**Issue by Jongkyukim123** [SteveDoyle2/pyNastran#738]
I would like to make a picture files including modes shape with eigenvalues, using pynastran and op2 file(solved by MSC nastran SOL103) without bdf.
I struggled to get the result.
Extracted node position, element data, eigenvector, etc.
And imported and used vtk.
But it is very difficult to me that all extracted datas translate to vtk type data.
I need your help.
And if you need detail code, I.will re-upload.
Thank you

**Comment by SteveDoyle2** [comment]
Have you tried the gui?  Select your mode shape, open up the legend menu,
find your displacement scale factor, and open up the animation menu from
there.

Beyond that, you could also try Paraview

**Comment by Jongkyukim123** [comment]
Thank you for your rapid reply~
I already have tried use pynastrangui. It give me proper result.
But I want make a picture file automattically with one click, using only OP2 file.

So, I made a plan to make a code using pyNastran below.
1st : extract node position.
2nd : extract element imformation.
3rd : extract eigenvector and make a new position.
4th : generate vtk data
5th : visualize by vtk

But I think you already have a these proccess. So If you have any good ideas for making these processes, please share them.

**Comment by SteveDoyle2** [comment]
There’s an example of using the gui to take a screenshot and close the gui
with one command line call.

If you want to do it a different way, I don’t really have a good suggestion.

**Comment by Jongkyukim123** [comment]
Then could you share the example?

**Comment by SteveDoyle2** [comment]
Checkout the end of the gui overview.  It’s under command line scripting

**Comment by Jongkyukim123** [comment]
Where can I find gui overview?
Because this is my first time for using github, So I'm not used to this system.

**Comment by SteveDoyle2** [comment]
https://pynastran-git.readthedocs.io/en/1.3/quick_start/index.html#gui

**Comment by Jongkyukim123** [comment]
Thank you~!!
