### ISSUE TITLE
Reading multiple include files skips files

### ISSUE THREAD

**Issue by jacoues** [SteveDoyle2/pyNastran#739]
Hi there,
I was experimenting with multiple include files and found that read_bdf with save_file_structure=True was skipping some of the include files listed in the "master" file when they were listed in this format:
```
BEGIN BULK
$Includes
INCLUDE 'include1.dat'
INCLUDE 'include2.dat'
INCLUDE 'include3.dat'
INCLUDE 'include4.dat'
INCLUDE 'include5.dat'
$ Direct Text Input for Bulk Data
```
but not in this format:
```
BEGIN BULK
$Includes
INCLUDE 'include1.dat'
$
INCLUDE 'include2.dat'
$
INCLUDE 'include3.dat'
$
INCLUDE 'include4.dat'
$
INCLUDE 'include5.dat'
$ Direct Text Input for Bulk Data
```
It's a minor inconvenience, but is that intentional? Additionally, do you have good examples of workflows using many include files? Thank you

**Comment by SteveDoyle2** [comment]
No.  It doesn’t really seem to be a feature that people use, so I think
this is the first time anyone has had an issue.  There is a test for it
though.

Is all you did add a $ on the previous line?  That doesn’t seem related to
the file structure write?  Am I missing something?

**Comment by SteveDoyle2** [comment]
Can you send me a small example of that with the script?  I’ve never run
into that.

**Comment by jacoues** [comment]
sure! To replicate, the bdf (debugtemplate.bdf) should read:
"$EXECUTIVE CONTROL DECK
SOL 100
CEND
$CASE CONTROL DECK
BEGIN BULK
$Includes
INCLUDE 'include1.dat'
INCLUDE 'include2.dat'
INCLUDE 'include3.dat'
INCLUDE 'include4.dat'
INCLUDE 'include5.dat'
ENDDATA
"
My script contains:
"
from pyNastran.bdf.bdf import BDF

model = BDF()
model.read_bdf('debugtemplate.bdf',save_file_structure=True,read_includes=False)

print(model.include_filenames)
"
You should see only 1 3 and 5 llisted. To make the error go away, add the $ signs in between each include line.

**Comment by SteveDoyle2** [comment]
Should be fixed!  I apparently never use read_includes=False, so there needs to be an i-=1 to reprocess the removed include line (includes are pulled out and handled separately).

Also, it's weird to use save_file_structure=True and read_includes=False.  There's no need to use save_file_structure unless you're writing to multiple files.

**Comment by jacoues** [comment]
Great! I was setting read_includes=False because I haven't populated the
include files yet, but I will be doing that.
On a different note, it's been a bit tricky managing the include files. I
might take some time to update the documentation and you can tell me if I
understood correctly how this works.

**Comment by bealonso2** [comment]
Hey @SteveDoyle2 are you open to accepting a PR that expands `save_file_structure` to work with include paths not relative to the main directory?

Take the following folder structure for example:
main_dir/
| main_rundeck.bdf
| --- Include/
       | some_assembly.bdf
       | part1.bdf
       | part2.bdf

Where `main_rundeck` has a line `Include 'Include/some_assembly.bdf'` (which works fine). But `some_assembly` has a line `Include 'part1.bdf'` and pynastran can't find this include because it starts the search from `main_dir`.

I'm happy to work this.

**Comment by SteveDoyle2** [comment]
Yup!  Pull requests are good, but especially for this, a small test example is good.  It's frustrating for everyone when things accidently break.
