### ISSUE TITLE
OP2 problem loading eigenvalues, all values are 0

### ISSUE THREAD

**Issue by Hiram018** [SteveDoyle2/pyNastran#744]
Hello I have a problem with a component in a s103 modal analysis, this is a super element, I created both reductions and modal analysis deck, but when I want to open my op2 file in Hypermesh is not loading because all eigenvalues are 0, I used DISPLACEMENT=ALL to see it in the .f06 file, if someone could give me a feed back I will be very happy

**Comment by SteveDoyle2** [comment]
I’d ask Altair.  They have a forum that seems responsive.

If that was in MSC or NX/Simcenter, you wouldn’t get an op2.  Since you
have one, I’m not sure what’s wrong.

**Comment by Hiram018** [comment]
Thank you so much, I will go there.
Yes I have an op2 file but I am expecting to see the values in my f06 file (but open it in hyperview with op2)
