### ISSUE TITLE
Error in reading vibroacoustics simulation OP2 file

### ISSUE THREAD

**Issue by Pranav4495** [SteveDoyle2/pyNastran#745]
Hi,

I have been trying to read an op2 file for my vibroacoustics simulation, but it seems that pyNastran is having trouble reading a table. I am using the latest 1.3.4 version, which I installed with pip. Previously, I was using the 1.4-dev version, where I modified the op2.py file to ignore this error, but the same process is not working for the new version. I have attached the error along with my op2 file for your reference. Any help would be appreciated.

Thanks,

[vbaop2_test.zip](https://github.com/SteveDoyle2/pyNastran/files/12622281/vbaop2_test.zip)

<img width="658" alt="vba_read_error" src="https://github.com/SteveDoyle2/pyNastran/assets/70219987/50758a91-300d-45f0-9738-0ce71ee5bde1">

**Comment by SteveDoyle2** [comment]
Can you attach a small model?  This has 36,000 elements and I'm looking for something with 5 elements max.  It's too big for a test.

I also need the associated BDF since acoustics isn't well supported.

**Comment by SteveDoyle2** [comment]
Regarding why your code doesn't work, I'm not sure.  1.4 had a rewrite of how params are read from the op2, so there might be some subtle differences.

**Comment by Pranav4495** [comment]
I was able to create a simple example with 4 structural elements but could not reduce the number of fluid elements to less than 66 due to requirements on the AML surface. I have attached the model here. 

[test_vba.zip](https://github.com/SteveDoyle2/pyNastran/files/12677117/test_vba.zip)

**Comment by SteveDoyle2** [comment]
fixed a while ago.  I finally added a test.

Doing so makes it so ACMODL reads in and writes out CTYPE properly.  That fixes a bug there.
