### ISSUE TITLE
Cannot read 'BOPHIG' card

### ISSUE THREAD

**Issue by MarkSttc** [SteveDoyle2/pyNastran#748]
Hi Steve, 

Thanks again for keep updating PyNastran, ensuring the compatibility with newer Nastran version. However, I've tried reading my *op2 file with read_op2  but it failed for some reasons. After performing the test, it seems to relate with BOPHIG card.  Please find the attached image below.

My goal is to extract eigenvectors/eigenvalues out for my application. Therefore, if possible, could you please tell me how to skip this card if it is not important with modal analysis results?  

Thank you so much for your help!!

![image](https://github.com/SteveDoyle2/pyNastran/assets/91675595/5f48819e-89cb-4867-beed-7a5c4ebe0e1d)

**Comment by MarkSttc** [comment]
Also, this model can be visualised in post-processing tool such as Hyperview and the other models seems to work fine with PyNastran.

**Comment by SteveDoyle2** [comment]
Mark,

The BOPHIG table is the eigenvectors, so skipping it won’t work.  It looks
like you probably are running 1.3.4, so trying out 1.4-dev might work.
Other than that, I’d need to see a small example that has that problem.

**Comment by MarkSttc** [comment]
Hi Steve, 

I'm currently using 1.4dev version, which was directly downloaded from source. Unfortunately, I cannot provide you with a small sample as it is proprietary to the company. However, I'm happy to do all the checks required to identify the source of errors.

**Comment by SteveDoyle2** [comment]
There's not really anything I can do if I don't have an example.

Why is a small example proprietary?  By being a small example, it makes it
not proprietary.  If you can boil it down to 1 quad tlate that's 10 mm
thick and uses steel, that's totally fine.  Feel free to fake numbers all
over.

**Comment by SteveDoyle2** [comment]
Reopen if there's an example.
