### ISSUE TITLE
PBEAM - N2(B) always omitted in output

### ISSUE THREAD

**Issue by RafFloSan** [SteveDoyle2/pyNastran#756]
Hi Steve,
There's a little typo in the repr_fields() method of the PBEAM class:
/pyNastran/bdf/cards/properties/beam.py
The offset at grid B in element z direction - N2(B) - is always omitted in the output, regardless of the value, because of a little typo in the method, line 1006;
As is:
n2b = set_blank_if_default(self.n2b, self.n2b)
To be (like for n1b, one line above):
n2b = set_blank_if_default(self.n2b, self.n2a)

I've been overwriting this in my version, but it would be a quick fix in the main branch, I guess.

Many thanks and best regards,
Rafael

**Comment by SteveDoyle2** [comment]
thanks, just fixed

**Comment by RafFloSan** [comment]
Thanks!
