### ISSUE TITLE
PBEAM illegal data due to missing last empty line

### ISSUE THREAD

**Issue by ChristopheBozec** [SteveDoyle2/pyNastran#757]
Hello all,

When exporting PBEAM properties, the last line containing Ci, Di, Ei, Fi should be written even if empty, as it is causing illegal data error in Nastran (2013.1.0)

```
from pyNastran.bdf.bdf import BDF
nastran_model = BDF()
nastran_model.add_pbeam(1001, 1, [0., 1.], ['YES', 'YES'], [10., 10.], [50., 50.], [55., 55.], [0., 0.], [30., 30.])
nastran_model.add_pbeam(1002, 1, [0., 1.], ['YES', 'YES'], [10., 10.], [50., 50.], [55., 55.], [0., 0.], [30., 30.])
nastran_model.write_bdf('output_test_pbeam.bdf', size=8)
```

The exported file contains:

```
$pyNastran: version=msc
$pyNastran: punch=True
$pyNastran: encoding=utf-8
$pyNastran: nnodes=0
$pyNastran: nelements=0
$PROPERTIES
PBEAM       1001       1     10.     50.     55.             30.
+
             YES      1.     10.     50.     55.             30.
PBEAM       1002       1     10.     50.     55.             30.
+
             YES      1.     10.     50.     55.             30.

```

By correcting it by hand to:
```
PBEAM       1001       1     10.     50.     55.             30.
+
             YES      1.     10.     50.     55.             30.
+
PBEAM       1002       1     10.     50.     55.             30.
+
             YES      1.     10.     50.     55.             30.
+
```
It then runs correctly.

**Comment by SteveDoyle2** [comment]
Why not just use a single line?

**Comment by ChristopheBozec** [comment]
I am guessing you mean this ?
```
PBEAM       1002       1     10.     50.     55.             30.
             YES      1.     10.     50.     55.             30.
```
I didn't try, this should work as well. However, I am wondering why the continuation is written by default for the first empty line and not the second ? Since I defined no data for either.

**Comment by SteveDoyle2** [comment]
Oh…I didn’t catch that.  That definitely doesn’t make sense.  I’ll take a
look.

**Comment by SteveDoyle2** [comment]
The continuation line is required because that line defines C1(A)-F2(A).

[image: image.png]
Why are you adding a continuation line at the end and why 1 and not 2?  All
of those values on the last 2 lines have defaults.

**Comment by SteveDoyle2** [comment]
Weird...seems like they just have a bad parser.  Anyways, it should be fixed now, which you can get if you update.  You can also just set C1(B) to be 1e-16 or whatever.
