### ISSUE TITLE
CBEAM orientation vector not exported

### ISSUE THREAD

**Issue by ChristopheBozec** [SteveDoyle2/pyNastran#758]
When writing the card for a CBEAM, the orientation vector is not exported:

```
from pyNastran.bdf.bdf import BDF
nastran_model = BDF()
nastran_model.add_cbeam(1001, 1001, [1, 2], [0., 1., 0.], '')
nastran_model.write_bdf('output_test_cbeam.bdf', size=8)
```

The exported file looks like:
```
$pyNastran: version=msc
$pyNastran: punch=True
$pyNastran: encoding=utf-8
$pyNastran: nnodes=0
$pyNastran: nelements=1
$ELEMENTS
CBEAM       1001    1001       1       2
```

I would have expected to get:
`CBEAM       1001    1001       1       2      0.      1.      0.`

Am I doing something wrong ?

**Comment by SteveDoyle2** [comment]
Try specifying x and g0 explicitly.  There are other parameters that those
terms than you might br setting.  Options also get moved around, so it’s
good practice regardless.

It also looks like you’re specifically offt as ‘’, which is not a valid
option.  ‘GGG’ is the default.

**Comment by SteveDoyle2** [comment]
Actually, most likely your offt blank option is actually g0 and that is
taking priority over x.

**Comment by ChristopheBozec** [comment]
I tried with `nastran_model.add_cbeam(1001, 1001, [1, 2], [0., 1., 0.])` first but I was getting an error because g0 was not defined as it is not optional, so I tried blanking it with '' but that might be overriding the vector, indeed. How am I supposed to write it in order to specify only the vector ?

**Comment by SteveDoyle2** [comment]
One of them is required, not both.  In your case, g0 should be None.

These are all fine.

nastran_model.add_cbeam(1001, 1001, [1, 2], [0., 1., 0.])

nastran_model.add_cbeam(1001, 1001, [1, 2], x=[0., 1., 0.])

nastran_model.add_cbeam(1001, 1001, [1, 2], x=[0., 1., 0.], g0=None)

nastran_model.add_cbeam(1001, 1001, [1, 2], x=[0., 1., 0.], g0=None, offt='GGG')

**Comment by ChristopheBozec** [comment]
Your first two lines return the same error I was getting :
TypeError: AddCards.add_cbeam() missing 1 required positional argument: 'g0'

The third one works, I will go with that. Thanks a lot !

**Comment by SteveDoyle2** [comment]
Oh...gotcha...those first two are no good.  They would work if it was a
CBAR.  They should be optional.  I'll update that.

These are fine though.

nastran_model.add_cbeam(1001, 1001, [1, 2], [0., 1., 0.], None)

nastran_model.add_cbeam(1001, 1001, [1, 2], x=[0., 1., 0.], g0=None)

**Comment by SteveDoyle2** [comment]
I updated the CBEAM to have similar defaults as the CBAR on the add_card method.
