### ISSUE TITLE
Is it convenient to share the XDB file format document?    Thanks!!!!!!!!!

### ISSUE THREAD

**Issue by YuDe95** [SteveDoyle2/pyNastran#767]

**Comment by SteveDoyle2** [comment]
I don’t have it. I was reverse engineering it.

**Comment by YuDe95** [comment]
I know an open-source project is used to read XDB files, is it helpful for writing XDB formats?
website  ：https://ferespost.eu/

**Comment by SteveDoyle2** [comment]
I've seen the project.  Adding XDB support isn't a priority.  If someone
wants to do it, that's fine, but I don't see any advantages over OP2.  It's
just a bit different, but very similar.

Why do you have an interest in it?

**Comment by YuDe95** [comment]
I want to do some work of read/write result data to an xdb file? According to your description, op2 has the same ability as xdb

**Comment by SteveDoyle2** [comment]
XDB is not supported, so yeah OP2 would be the way to go.

Just as an FYI, XDB is no longer supported by MSC Nastran, while OP2 is.  Don't know about Siemens, but it's a good enough reason for me to never add it.
