### ISSUE TITLE
Read info in F06 excluded in OP2

### ISSUE THREAD

**Issue by JacobWennersten** [SteveDoyle2/pyNastran#774]
Hello. In the F06 file there are two sections called "Element internal forces and moments" and "Summation of element oriented forces on adjacent elements". I have been trying to read these results with PyNastran through OP2 file but without success. I have also found threads from years ago where people had the same problem, where they said that it didn't exist in the OP2 file. Does anyone has some more information on this?

I have to read the F06 file somehow to extract this information. As I understand it, one can not read the F06 with the current version of PyNastran, but I have found some information that you could read it in earlier version. I tried with v0.7.2 but without success.

If non of these ways work, how can I proceed to extract this information?

**Comment by SteveDoyle2** [comment]
https://github.com/SteveDoyle2/pyNastran/issues/349

Per MSC's param listing
![image](https://github.com/SteveDoyle2/pyNastran/assets/1059417/a509320b-d8f0-45ec-8f29-e38f9edc2761)

Per the NX GPFORCE Case Control listing:
![image](https://github.com/SteveDoyle2/pyNastran/assets/1059417/fa6c3d78-abe3-4000-a436-45988f2e0e31)

How is that different than just using the element forces for bars?

**Comment by SteveDoyle2** [comment]
closing due to innactivity
