### ISSUE TITLE
nastran_to_vtk

### ISSUE THREAD

**Issue by karma0704** [SteveDoyle2/pyNastran#775]
When I used the nastran_2_vtk() method to export files, I found that the LOAD data in the BDF model file was not included in the vtk_ugrid object. The finally exported vtk_ugrid object did not contain load data. In addition, how do I need to follow the instructions for the data in the Load Set? How to calculate a specific formula and how it should be expanded

**Comment by SteveDoyle2** [comment]
The converter uses the reader for the GUI to convert it.  It's not a
complete thing, but it does do most static loads that are referenced in the
case control deck.  I'd need to see an example if something isn't working.

**Comment by karma0704** [comment]
Hi, it’s like this. I hope that after exporting some original data in the BDF model to a VTK file, I can still retrieve these data, and at the same time retrieve the corresponding data calculated based on these original data, but now I can't distinguish from the result data, the original data and the result data calculated from the data, such as LOAD. I hope that the exported VTK original data contains the original data of Force, and also contains the result data obtained after my calculation. , if it is a Moment type, the same is true. The original data can be queried, and the calculation result data can also be queried.Maybe you provided the function, but I couldn't find it and don't know how to use it

**Comment by SteveDoyle2** [comment]
> I hope that after exporting some original data in the BDF model to a VTK file, I can still retrieve these data

What data are you trying to retrieve?

> but now I can't distinguish from the result data, the original data and the result data calculated from the data, such as LOAD

I'm confused by that.  Please provide an example.

> I hope that the exported VTK original data contains the original data of Force, and also contains the result data obtained after my calculation.

Again, it's exports as a load case.  Have you tried splitting up the load cases?

> The original data can be queried, and the calculation result data can also be queried.  Maybe you provided the function, but I couldn't find it and don't know how to use it

Once you exported it, you've lost the connection to the BDF/OP2.  That's the point of exporting it.  That lets you load it into Paraview.  If you the connection to the model, query the bdf/op2 objects.

**Comment by karma0704** [comment]
> > I hope that after exporting some original data in the BDF model to a VTK file, I can still retrieve these data
> 
> What data are you trying to retrieve?
> 
> > but now I can't distinguish from the result data, the original data and the result data calculated from the data, such as LOAD
> 
> I'm confused by that. Please provide an example.
> 
> > I hope that the exported VTK original data contains the original data of Force, and also contains the result data obtained after my calculation.
> 
> Again, it's exports as a load case. Have you tried splitting up the load cases?
> 
> > The original data can be queried, and the calculation result data can also be queried.  Maybe you provided the function, but I couldn't find it and don't know how to use it
> 
> Once you exported it, you've lost the connection to the BDF/OP2. That's the point of exporting it. That lets you load it into Paraview. If you want the connection to the model, query the bdf/op2 objects.

Oh My God! I'm sorry that I can't describe my problem correctly. I don't know much about how the data in the BDF model corresponds to the data in the VTK file. I feel that some CARDs in the BDF model don't know where they are in the VTK file after conversion. Is part of it corresponding to this CARD?
In addition, gentlemen, can you consider the compatibility of python3.7.X version on win7 system? If it's compatible, that would be great!

**Comment by SteveDoyle2** [comment]
The data in the Vtk file is the same data that shows up in the gui.  Total
element thickness isn’t needed for a PSHELL, but is for a PCOMP.  It’s not
a 1:1 mapping of everything and you can’t go from that data back to a
similar BDF.  Oh some things you can probably get close, but that is not a
goal.

I still don’t understand what you’re really trying to do.  You can
definitely add whatever you want to the object.

Regarding the version, 3.7 is too old. An installer was last created for
3.7.9, which was released in August 2020.  It’s not just python, but all
the changes to numpy/vtk.  3.11/3.12 are so much faster that you really
should be upgrading.  I had originally dropped 3.9, but put it back in, so
that’s very old too.
