### ISSUE TITLE
PARAM POST 1 (XDB), 0, -5,-6 support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveDoyle2/pyNastran#78]
```
result files aren't always in PARAM,POST,-1

support others at some point
```

Original issue reported on code.google.com by `mesheb82` on 25 Apr 2012 at 11:41

**Comment by SteveDoyle2** [comment]
-3 is now supported

**Comment by SteveDoyle2** [comment]
-4 is supported with a test problem.  You need to throw the op2.post = -4 flag.

**Comment by SteveDoyle2** [comment]
Per MSC, XDB is deprecated
