### ISSUE TITLE
op2 reader fails when reading version/mode from custom OUTPUT2 files

### ISSUE THREAD

**Issue by M4Nascenzi** [SteveDoyle2/pyNastran#782]
I am trying to read a DSCMCOL table written to an op2 file. When it tries to read the op2, the code fails to read the version/mode. I tried setting the mode when initializing the op2 python object, but that did not help. 

Maybe I'm missing something, but I imagine pyNastran should just not attempt to read the mode/version if the user manually sets it. Let me know if you need an example op2 and I will email one to you.

Nastran file:
ASSIGN OUTPUT2 = 'dscmcol.op2', UNIT = 95, UNFORMATTED
...ALTER...
OUTPUT2 DSCMCOL,,,,//-1/95/'DSCMCOL'
OUTPUT2 ,,,,//-9/95
...
Python script:
op2=OP2(mode='nx')
op2.read_op2('dscmcol.op2')

**Comment by SteveDoyle2** [comment]
Looks like you're going into the title block (the first block).  It's expecting a [4, 2, 4], [4, 4, 4] at the top, which you can make by writing a 2 and -4 in separate write commands.  Not really sure how to do that though.  ATA uses the forum, so it's worth asking there.

Alternatively, you could ditch the OUTPUT2 alter and try:

    DSAPRT(NOPRINT,EXPORT,END=SENS)

Looks like the param,iunit,95 is also useful 
![image](https://github.com/SteveDoyle2/pyNastran/assets/1059417/f3ca2abe-01b7-4970-8854-2cbe89f4152c)

**Comment by SteveDoyle2** [comment]
Oh, nevermind.  You do have the title/nastran fort tape code, but you don't list a nastran version.  Are you on a new version of Nastran?

**Comment by SteveDoyle2** [comment]
That’s the pynastran op2 writer, so it’s not using that code to read it.
Mode doesn’t affect the header, so there is an issue with the way the file
was written.

Maybe is misunderstood your file units.  Set the iunit to the file you want
the result to go to.  I don’t have access to Nastran, so I can’t debug your
DMAP call. You’ll probably get an answer in the forum if you provide enough
info.

**Comment by SteveDoyle2** [comment]
This code cause github is bad with 2 pics:

![image](https://github.com/SteveDoyle2/pyNastran/assets/1059417/d11ba053-9aeb-453d-ab8b-26b8c60af2c0)

The provided op2 has been flagged with the post=-1 option and is nearly complete.  It's missing a version, which is throwing things off.  The file was probably created wrong in some way, but you should be able to use DSAPRT to get what you want (and have it go to an independent file).

**Comment by M4Nascenzi** [comment]
Alright, I did some tests. I tried parsing the DSAPRT version of the file and the OUTPUT2 version of the file. I did it with MSC NASTRAN 2021.3, Simcenter Nastran 2312, and Simcenter Nastran 2020.1. Both versions of Simcenter Nastran behaved the same. I also tried it with a range of ITAPE and POST parameters (just in case). I also tried it with modified version of pynastran that ignores version reading if the mode is specified. With an unmodified pyNastran, it can only parse the OUTPUT2 version from MSC nastran.

Here are the results:

with dsaprt:
	msc: bad closer
_ERROR:   op2_reader.py:2986           finished table_name = b'DSCMCOL'
ERROR:   op2_reader.py:2991           There was a Nastran FATAL Error.  Check the F06.
last table=b'DSCMCOL'; post=-2 version='msc'_
	simcenter: bad header
_RuntimeError: unknown version=b'DSCMCOL'_
	simcenter and force mode to 'nx': bad closer
_ERROR:   op2_reader.py:2986           finished table_name = b'DSCMCOL'
ERROR:   op2_reader.py:2991           There was a Nastran FATAL Error.  Check the F06.
last table=b'DSCMCOL'; post=-1 version='nx'_


with DSCMCOL and file closer OUTPUT2 commands
	msc: works
	simcenter: bad header
_RuntimeError: unknown version=b'DSCMCOL'_
	simcenter and force mode to 'nx': works

**Comment by SteveDoyle2** [comment]
You should try writing the version yourself.  You're missing a version string and maybe a 0 to close the table (which will write 4,0,4).

This is interesting.  Label=XXXXXXXX is the flag for MSC Nastran, so presumably you can change that to '2312    ' (8 characters) and it'll work.  The version doesn't matter all that much though.

![image](https://github.com/SteveDoyle2/pyNastran/assets/1059417/d5828046-d76e-4c88-889e-0baa4c3b3a5d)


I'd start with this

    OUTPUT2 ,,,,, //-9/12/ $

The more direct you can write the file, the easier it will be to fix it.

**Comment by M4Nascenzi** [comment]
Ok, I think I figured out what is going on. I believe what you are reading as the version is actually the file label (LABL). I was labeling the output as DSCMCOL, so it read the version as DSCMCOL. This also appears to be something that you've somewhat accounted for in the code. In _parse_nastran_version_8 you have MSC_VERSIONS which includes 'XXXXXXXX'. This is just the default LABL that gets printed. So, if I don't specify a label, pyNastran reads 'XXXXXXXX' and assumes it is MSC. I could also label it 'nx', and pyNastran would assume it is NX.

**Comment by SteveDoyle2** [comment]
Oh ok.  Yeah that’s where MSC and NX put the version.  It was XXXXXXXX for
MSC for like 10 years before they switched in ~2014.  NX has been writing
it that way since at least NX8.5.  IMAT and Optistruct do the same thing.

**Comment by SteveDoyle2** [comment]
I think this is done.  Pretty sure it just means that  you just do this.

```
ASSIGN OUTPUT2 = 'dscmcol.op2', UNIT = 95, UNFORMATTED
...ALTER...
OUTPUT2 DSCMCOL,,,,//-1/95/
OUTPUT2 ,,,,//-9/95
```
and not
```
ASSIGN OUTPUT2 = 'dscmcol.op2', UNIT = 95, UNFORMATTED
...ALTER...
OUTPUT2 DSCMCOL,,,,//-1/95/'DSCMCOL'
OUTPUT2 ,,,,//-9/95
```

reopen if not done
