### ISSUE TITLE
DESVAR card label length restriction

### ISSUE THREAD

**Issue by dsandler133** [SteveDoyle2/pyNastran#784]
I've recently run into an issue reading in a BDF after upgrading pyNastran. There is an assertion during the initialization of a DESVAR card requiring the length of the design variable label to be 8 characters or less:

assert len(label) <= 8, f'desvar_id={desvar_id} label={label!r} must be less than 8 characters; length={len(label):d}'

This assert statement was added some time after version 1.3.4, which is what I upgraded from. Is there a reason for this restriction? As far as I can tell, I should be able to use up to 16 characters in long field format. I am using pyNastran to read a BDF for a different FEA software that supports the format however, so I might not be aware of a limitation by Nastran. 

Thank you!

**Comment by SteveDoyle2** [comment]
Yes. I ran into an issue with it. If you have a deck & the op2 result (without PARAM,OGEOM,NO) that is ok with it, I'll change it and make that case work too.

**Comment by dsandler133** [comment]
The program we're using writes its output in a different format, so we're only using pyNastran on the input side.  So there's no issue with longer labels for us, but it's also not a big deal to keep them shorter. While there's an outstanding issue, you don't need to make changes on my behalf. I appreciate the response though!
