### ISSUE TITLE
Feature Request: Track Include Source for each Card

### ISSUE THREAD

**Issue by dmarc3** [SteveDoyle2/pyNastran#789]
Hi there! First off, thanks for the great work here! `pyNastran` is very useful.

I have a use case where it would be helpful to be able to determine the name of the file in which the `card` has come from. i.e. something like this:

```python
from pyNastran.bdf.bdf import BDF

model = BDF()
model.read_bdf('PATH_TO_MODEL')

for nid, node in sorted(model.nodes.items()):
    print(node.source) # source = run deck name or include file path in which this GRID card is found in
```

I'd mainly like to be able to determine the source for elements in my use case but I think it probably makes sense to include this as an attribute on all cards. Thoughts?

**Comment by SteveDoyle2** [comment]
When calling read_bdf there’s a save_file_structure=False flag. Set that to
True and there is an integer ifile flag on every card.

You can then use the model.write_bdfs(…) method and write out all/a subset
of files you’ve changed. The out_filenames/renamed to include_file_map in
the latest (I think) is a dictionary of old_name to new_name that uses the
ifile and model.include_files (maybe filenames) to map the includes.

The docs are quite a bit better in the latest dev version.
