### ISSUE TITLE
BDF.get_cards_by_card_types method does not return for MOMENTs

### ISSUE THREAD

**Issue by mhudayi** [SteveDoyle2/pyNastran#795]
For a model imported as punch file, when i try to get MOMENT cards with get_cards_by_card_types() method, list is empty. I am not sure which cards also not listed properly.

Here is an example of punch to be read:
```
FORCE   1001    47              1.0     444.    555.    666.
MOMENT  1001    47              1.0     777.    888.    999.
```

Sample script:
```
from pyNastran.bdf.bdf import BDF 
model = BDF(debug=False)
model.read_bdf("loads.bdf", punch=True, xref=False)
print(model.card_count)
print("FORCES:", model.get_cards_by_card_types(["FORCE"])["FORCE"])
print("MOMENTS:", model.get_cards_by_card_types(["MOMENT"])["MOMENT"])
```

Output:
```
{'FORCE': 1, 'MOMENT': 1}
FORCES: [FORCE       1001      47              1.    444.    555.    666.]
MOMENTS: []
```

platform.python_version() : '3.11.5'
pyNastran.__version__ : '1.4.1'

**Comment by davidrivas12** [comment]
That might be caused by a formatting error in the BDF. 

Reference the Nastran Quick Reference Guide Chapter 9 "Bulk Entries" 
![image](https://github.com/user-attachments/assets/9651f898-72c2-42c5-8992-0d45a01eafce)

**Comment by mhudayi** [comment]
There is no format error. Actually i figured out the solution. When type_to_id_map is resetted manually, it runs properly;

```
model._reset_type_to_id_map()
print("FORCES:", model.get_cards_by_card_types(["FORCE"])["FORCE"])
print("MOMENTS:", model.get_cards_by_card_types(["MOMENT"])["MOMENT"])
```

The bug arises when there are forces and moments with same sid exist. That is actually very common usage for nastran.

**Comment by SteveDoyle2** [comment]
Yeah the OG should still work

**Comment by SteveDoyle2** [comment]
It's been fixed.
