### ISSUE TITLE
failed reading Optistruct model with b'OSTR1C in pyNastran 1.4 (composite strain cquad4)

### ISSUE THREAD

**Issue by noferusername** [SteveDoyle2/pyNastran#797]
Hello,

This issue matches the exact description in this closed issue below:
https://github.com/SteveDoyle2/pyNastran/issues/615

I can reproduce it on a simple plate bending model with CQUAD4 and PCOMP card
Running Python 3.9.7 with pyNastran-1.4.1-py3 with optistruct 2023

===========
DEBUG:   op2.py:589                   combine=True
DEBUG:   op2.py:590                   -------- reading op2 with read_mode=1 (array sizing) --------
INFO:    op2_scalar.py:1963           op2_filename = 'C:\\TEMP\\Composite_Plate_Outputs_OP2-mode.op2'
DEBUG:   op2_reader.py:299            date = (8, 22, 24)
DEBUG:   op2_reader.py:382            mode='optistruct' version='OS2023'
DEBUG:   op2_scalar.py:2172             table_name=b'CASECC'   (case control)
DEBUG:   op2_scalar.py:2172             table_name=b'GEOM1S'   (grid/coord cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'GEOM2S'   (element cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'GEOM3S'   (constraint cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'GEOM4S'   (load cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'EPTS'     (property cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'MPTS'     (material cards (superelement))
DEBUG:   op2_scalar.py:2172             table_name=b'OES1C'    (composite stress)
DEBUG:   op2_scalar.py:2172             table_name=b'OSTR1C'   (composite strain)
failed reading b'OSTR1C' isubtable=-4
Traceback (most recent call last):
...
...
...
 assert op2.is_strain is True, op2.code_information()
AssertionError: --Table3Data--
  device_code   = 1   Print
  analysis_code = 1   Statics
  table_code    = 5   OSTR1C-OES - Element Stress
  format_code   = 1   Real
  result_type   = 0   Real
  sort_method   = 1
  sort_code     = 0
    sort_bits   = (0, 0, 0)
    data_format = 0   Real
    sort_type   = 0   Sort1
    is_random   = 0   Sorted Responses
  random_code   = 0  
  element_type  = 95  QUAD4-nonlinear
  s_code        = 0   Coordinate Element - Stress Max Shear (Octahedral)
  thermal       = 0   isHeatTransfer = False
  thermal_bits  = [0, 0, 0, 0, 0]
  num_wide      = 11 
  isubcase      = 1  
  lsdvmn        = 1
  NX Nastran

Thanks!

**Comment by SteveDoyle2** [comment]
Can you attach a small example? Also, 3.10 is the minimum supported version
these days.

**Comment by noferusername** [comment]
Hi Steve, 

Thanks for taking a look!

* Just tried with Python 3.11. No luck.
* Yesterday tried the Python 3.9 with older pyNastran, but no luck either (cannot go backwards that much because I hit a compatibility limitation between Optistruct and pyNastran. Oldest Optistruct I have handy is 2022)

Attaching .fem, op2 
Fernando

[files.zip](https://github.com/user-attachments/files/16730174/files.zip)

**Comment by SteveDoyle2** [comment]
Can you also attach the f06?  OSTR1C is a strain table and you have it flagged with stress. I need to make sure it's actually stress/strain.

**Comment by noferusername** [comment]
Hi Steve, so far I've been unable to get the f06 file from optistruct. I'll keep digging. 
Fernando

**Comment by SteveDoyle2** [comment]
What is the output file that gets really big when you do
STRESS(PLOT,PRINT)=ALL and STRAIN(PLOT,PRINT)=ALL. Sometimes it’s called
.out in regular Nastran, but same thing

**Comment by noferusername** [comment]
Nothing extra that resembles table output seems to gets created when I use the PLOT option. Not at least in ascii format. Attaching the zip with all the files.  I just contacted the vendor regarding the F06 file. I'll let you know.

[composite_plate_F06_PLOT.zip](https://github.com/user-attachments/files/16800634/composite_plate_F06_PLOT.zip)

**Comment by SteveDoyle2** [comment]
Yeah, that doesn't have your output in ASCII format. Optistruct isn't quite
Nastran, so I'm not sure what differences there are.

Your vendor would be your best bet.

**Comment by AlejandroStewart** [comment]
in Optistruct you use OPTI instead of PRINT to get the ascii output

**Comment by noferusername** [comment]
Thanks Alejandro! Way more helpful than what I got from the vendor...
 
When I get the ascii output, pynastran works -without- issues. 
So I guess the data is read from both op2 and the fd06 equivalent table, right?

[Composite_Plate_F06_PLOT_OPTI.zip](https://github.com/user-attachments/files/16854943/Composite_Plate_F06_PLOT_OPTI.zip)

**Comment by SteveDoyle2** [comment]
My guess is you didn’t keep the op2 request. I’d check if the file size is
the same.

**Comment by noferusername** [comment]
That's correct. My bad. It was working because me OP2 file did not have strains. They only were in the the Ascii table. I just checked it from pyNastran and the strain dataset is empty.

When I request the full output set below, I go back to the same error "failed reading b'OSTR1C' isubtable=-4"
CSTRAIN(PLOT,OPTI) = ALL
CSTRAIN(OUTPUT2,NDIV=1) = ALL
CSTRESS(OUTPUT2,NDIV=1) = ALL
CSTRESS(PLOT,OPTI) = ALL

**Comment by SteveDoyle2** [comment]
It sounds like it is strain that it was failing on then. I thought strain
was in that output (definitely stress). The stress table looks different,
so that probably explains why the results looked weird. I couldn’t find the
pattern, but should be able to now

**Comment by lucagrizzo** [comment]
Hi Steve

I hope I'm posting in the right thread, I'm also having problems reading cquad4 composite strains, in particular when I try to read them pynastran alwaysreads ctria_strain, whereas everything works with stresses

![cquad_strain](https://github.com/user-attachments/assets/83eeffeb-2341-494f-8b28-4a2687b8d057)

**Comment by SteveDoyle2** [comment]
@lucagrizzo are you using optistruct?

**Comment by SteveDoyle2** [comment]
@noferusername 
![image](https://github.com/user-attachments/assets/204e7529-8d66-4bf6-b6d3-a9f6ac0a6f4a)

Looks like the format for stress/strain isn't as bad as I thought. The data matches, except for max shear? It's not calculated, so I don't get it.

Strain also matches other than the max shear.
![image](https://github.com/user-attachments/assets/f214deb1-a022-40c8-828e-a24fd2b69706)

Here's the new check 
![image](https://github.com/user-attachments/assets/4de878b6-d549-4adf-b2aa-5ee4a223a8c4)
