### ISSUE TITLE
Unable to write dataframe from op2 file with multiple frequency steps

### ISSUE THREAD

**Issue by rackdisciprine** [SteveDoyle2/pyNastran#799]
I had a NX nastran model (SEDFREQ) that has multiple frequencies, and was unable to create dataframe of all frequencies. Debugged and found that ComplexGridPointForcesArray is missing code to create dataframe that includes all frequencies. Copied code from ReadGridPointForcesArray and dataframe was created without issues.

I submitted a push (?), still new to GitHub. Apologies in advance if I did something wrong with the push/pull request.

**Comment by SteveDoyle2** [comment]
I didn't get a pull request, but I made #800, so it's in there now. Thanks!
