### ISSUE TITLE
Read mass (.k.op2) and stiffness (.m.op2) matrix (PARAM,POST,-5)

### ISSUE THREAD

**Issue by PedroMOMillan** [SteveDoyle2/pyNastran#803]
Hello Steve, 

I am using "PARAM,POST,-5" to output the mass and stiffness matrices (saved as ().m.op2 and ().k.op2) of an OptiStruct model.

However, when I try to read the ().m.op2 and ().k.op2 , by calling pyNastran from Matlab, I get the error below.

I suspect that this is a limitation of the code, that cannot read the mass and stiffness matrices as ().k.op2 and ().m.op2 files. Am I correct? If so, do you know some way to go around it? Otherwise, let me know if I am missing something.

Thank you very much!
Pedro

---------------------------------------------------------------------------------------------------

ERROR:   op2_reader.py:2982           finished table_name = b'MELM'
ERROR:   op2_reader.py:2987           There was a Nastran FATAL Error.  Check the F06.
last table=b'MELM'; post=-2 version='msc'
Error using op2_reader>_read_table_name
Python Error: FatalError: There was a Nastran FATAL Error.  Check the F06.
last table=b'MELM'; post=-2 version='msc'

Error in op2_scalar>_read_tables (line 2228)

Error in op2_scalar>read_op2 (line 1998)

Error in op2>read_op2 (line 600)

---------------------------------------------------------------------------------------------------

**Comment by SteveDoyle2** [comment]
Do you have an example? I don’t have optistruct.

**Comment by PedroMOMillan** [comment]
Hi again Steve,

Thanks for your prompt response. 

Attached are the ().op2, ().m.op2 and ().k.op2 files corresponding to an example structure. 

Also, I am sending the file ().full.mat that contains the mass and stiffness matrix in ASCII format (https://2021.help.altair.com/2021/hwsolvers/os/topics/solvers/os/full_mat_file_r.htm), which should contain similar information to that in the ().m.op2 and the ().k.op2 files -- note that I want to use the ().m.op2 / ().k.op2 instead of ().full.mat because I am working with large models that make it impractical to use the latter.

Let me know if you need other files.

Best,
Pedro

[EXAMPLE.zip](https://github.com/user-attachments/files/17394015/EXAMPLE.zip)

**Comment by SteveDoyle2** [comment]
KELM and MELM are not supported. They're individual mass/striffness matrices for each element. The format gets super messy. Full matrices are supported, so like KAAX.

**Comment by SteveDoyle2** [comment]
I would ask Altair/your reseller or read the documentation about how to get
only the data you want in those files.

**Comment by PedroMOMillan** [comment]
Ok. Thanks for the help Steve, and for the great tool you developed! 

Cheers
