### ISSUE TITLE
NX Nastran bulk checksum

### ISSUE THREAD

**Issue by mutricyl** [SteveDoyle2/pyNastran#804]
Hello,

NX nastran requires a checksum for the bulk section in dbf file to be able to run (this is one of the limitation of NX compared to MSC).

I was wondering if this checksum generation is supported by pyNastran ?

Regards
Laurent

**Comment by SteveDoyle2** [comment]
No. It’s impossible to create a checksum without knowing their secret key
or brute forcing it.

**Comment by mutricyl** [comment]
OK, i guess i can close this issue then.
