### ISSUE TITLE
LoadCase ids - keys in dictionary not same as keys of isubcase_name_map

### ISSUE THREAD

**Issue by Vybornak2** [SteveDoyle2/pyNastran#805]
Hello,
I do not know, if this is intentional or not, but in some of the models I am getting different keys in these objects:

```
op2.op2_results.stress.ctira3_stress
op2.isubcase_name_map
```

is this expected behavior? 

## Actual output

```
ctira3_stress keys:
dict_keys([
    (1, 1, 1, 0, 0, '', ''),
    (2, 1, 1, 0, 0, '', ''),
    (3, 1, 1, 0, 0, '', ''),
    (4, 1, 1, 0, 0, '', ''),
    (5, 1, 1, 0, 0, '', ''),
    (6, 1, 1, 0, 0, '', ''),
    (31, 1, 1, 0, 0, '', ''),
    (32, 1, 1, 0, 0, '', ''),
    (33, 1, 1, 0, 0, '', ''),
    (34, 1, 1, 0, 0, '', ''),
    (35, 1, 1, 0, 0, '', ''),
    (36, 1, 1, 0, 0, '', ''),
    (37, 1, 1, 0, 0, '', ''),
    101
])
```

```
isubcase_name_map keys:
dict_keys([1, 2, 3, 4, 5, 6, 31, 32, 33, 34, 35, 36, 37, 101, 0])
```

**Comment by SteveDoyle2** [comment]
The documentation describes it. The result can’t be squashed though you
results aren’t anything special…

**Comment by Vybornak2** [comment]
Thank you for explanation, could you please by any chance provide this piece of documentation? Unfortunately I do not understand what these values in dictionary keys stands for. And I did not find related documentation. Even some brief information would help of course :). 

Thank you kindly for your time and responses.

**Comment by SteveDoyle2** [comment]
Here you got. By default, everything is in this form. At the end of
processing, the code attempts to squish the keys, but fails if there are
multiple choices for a given subcase.

https://pynastran-git.readthedocs.io/en/latest/quick_start/op2_pandas_multi_case.html#

**Comment by Vybornak2** [comment]
Thank you :)
