### ISSUE TITLE
Are MPCs evaluated with model section cuts?

### ISSUE THREAD

**Issue by Czarified** [SteveDoyle2/pyNastran#808]
Looking at the set of elements returned from `get_element_centroids()` I don't see any id numbers from MPCs in the array. Is this because they don't have a "centroid?" You make a special exception for the spring elements, but nothing for MPCs.

https://github.com/SteveDoyle2/pyNastran/blob/6df023bd9d61934bd6ec558fd68c4b0c1a60c90b/pyNastran/bdf/mesh_utils/cut_model_by_plane.py#L40

If this is the case, is there a way to include MPC forces in section cuts, or will they always be neglected? I'm comparing some pyNastran cuts to FEMAP cuts.

**Comment by SteveDoyle2** [comment]
I believe MPCs are not classified as elements. I believe the BWB example
has one. Like springs though, MPCs should be dots, but they’re rigid, so I
think I’m confused on the issue.

The cutting plane plotter words the same as the section cut option on the
grid point forces object. It just does a single point, it’s the same as
what femap does.

**Comment by Czarified** [comment]
In the model I'm working with, there are many many MPC's to serve as load distribution from load application points. As such, I have very large RBE's that spider out. Of course, in the GPFORCE table, you can choose to include MPC contributions in the summation or not, and this is what FEMAP does when you check or uncheck that box in the section cut tool. I was wondering if such an option existed in pyNastran.

Typically, I don't think it makes a lot of sense to include MPC contributions, but FEMAP seems to have the option.

**Comment by Czarified** [comment]
Thanks for the information Steve! Closing this.
