### ISSUE TITLE
Can PyQt/PySide be removed or stubbed as non-required imports for the nastran_to_vtk converter?

### ISSUE THREAD

**Issue by gabrielhae** [SteveDoyle2/pyNastran#809]
Greetings, the nastran_to_vtk converter is currently connected up to the GUI through the testing path, and that pulls in PyQt/PySide would you kindly be able to advise on disconnecting them from being needed for the converter?

**Comment by SteveDoyle2** [comment]
I’d go through and comment out the imports, refactor it and submit a pull
request.

**Comment by SteveDoyle2** [comment]
Are you referring to the tests or the code? I don't think it's required. 

I uninstalled qtpy and was able to run all the nastran gui tests externally. I just couldn't run it from the root directory.
