### ISSUE TITLE
transform static loads from element faces to nodes?

### ISSUE THREAD

**Issue by jaredmagnusson** [SteveDoyle2/pyNastran#812]
Hello,
I'm looking to convert pressures known at element nodes and faces into forces at the nodes (FEA tool I'm using wants nodal values). Getting forces is straightforward at the face centroids (pressure*Area), but robustly getting a "nodal area" is more difficult across different element types and orders. Preferably, I'd like that interpolation to account for and conserve energy using something like weighted areas (shape functions?).

I saw this functionality in v1.1.0 in pyNastran/bdf/cards/loads/static_loads.py for the PLOAD4 card, a method called `transform_load`. It didn't take into account area weightings (simply divided the total load by number of nodes), but otherwise looked good. Somewhere in either v1.2.0 or 1.3.0 that functionality went away. 

What do you think the best approach would be to perform that kind of operation now? I see a more general `transform_load` now in the loads.py file, but it only works between 2 existing CID, so I don't think that'd work with an element face center. If there's a better way go about this let me know.

**Comment by SteveDoyle2** [comment]
There is a force to pressure code outside of the total loads summation. The
right way to do it is by using the shape functions, but I'm far from an
expert in fea theory. Even the loads summation tool ignores the moment
generated by pressure.

The transform_load method in pyNastran/bdf/utils, but it's used to
transform reduced forces/moments.into different coordinate frames.

**Comment by jaredmagnusson** [comment]
Ok thank you. Where's the force to pressure code located?

**Comment by SteveDoyle2** [comment]
pyNastran.bdf.mesh_utils.force_to_pressure

**Comment by jaredmagnusson** [comment]
Thank you
